### ISSUE TITLE
Unkown OS found 

### ISSUE THREAD

**Issue by 2O16O7** [CISOfy/lynis#1000]
**Describe the bug**
  Exception found!

  Function/test:  [OS Detection]
  Message:        Unknown OS found 
  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (./lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

  Thanks!

**Version**
 - Distribution [e.g. Kali Linux 2020.02]
 - Lynis version [e.g. 3.0.0]

**Expected behavior**
Unknown OS found

**Comment by mboelen** [comment]
What is the content of /etc/os-release?

**Comment by quantumpacket** [comment]
@mboelen I'm going to go ahead and follow-up for the original poster.

**Distro:** Kali Linux 2020.4
**Lynis:** 3.0.0

```
  Exception found!

  Function/test:  [OS Detection]
  Message:        Unknown OS found in /etc/os-release

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (/usr/sbin/lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

  Thanks!

=================================================================

  - Detecting OS...                                           [ DONE ]
  - Checking profiles...                                      [ DONE ]

  ---------------------------------------------------
  Program version:           3.0.0
  Operating system:          Linux
  Operating system name:     Debian
  Operating system version:  kali-rolling
```

The output of `/etc/os-release`:
```
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2020.4"
VERSION_ID="2020.4"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
```
