### ISSUE TITLE
iWatch not recognized as HIDS

### ISSUE THREAD

**Issue by damnms** [CISOfy/lynis#1001]
**Describe the bug**
I had an error, saying i have no HIDS or so, sorry, can not remember the exact error code.
But i had iwatch installed. Seems like iWatch is not recognized like tripwire, aide etc., but its much better because it reports in realtime.

**Version**
Debian 10
Lynis master

**Expected behavior**
No warning that i have no HIDS installed

**Output**
does not exist anymore, because i also have aide now running

**Additional context**

**Comment by mboelen** [comment]
Thanks for reporting. While it is pretty easy to add support for iWatch, I see the last release was in 2007. For that reason, we won't add it now.

**Comment by damnms** [comment]
@mboelen iwatch is part of the official debian repository.
So because a software is "finished" and gets no feature updates for years, it is not recognized as "being good enough for lynis" - serious?

**Comment by damnms** [comment]
btw. i use iwatch for more than 7 years on many of my productive servers - no problems

**Comment by mboelen** [comment]
Not sure if we should encourage people to use very old software. Sure, it might not even need new features, but it might lack the required performance, or have enough code reviews.

As said, it is not that hard to have it added to Lynis. Tell me its process name when it is running, and let's have it added for recognition purposes.

**Comment by damnms** [comment]
/usr/bin/perl -T /usr/bin/iwatch -f /etc/iwatch/iwatch.xml -p /var/run/iwatch.pid -d

i just wrote with the developer about the state of the software. he is currently migrating the project from sf.net to github
