### ISSUE TITLE
LINUX_VERSION incorrectly set on Debian or Ubuntu based distributions

### ISSUE THREAD

**Issue by Varbin** [CISOfy/lynis#1003]
**Describe the bug**
As the test PKGS-7388 (apt security repository) [tests agains LINUX_VERSION](https://github.com/CISOfy/lynis/blob/master/include/tests_ports_packages#L988), Lynis incorrectly complains about a missing security repository on Raspbian (the issue #835 isn't fixed).

The issue is at `osdetection`:
 - In [ll. 244](https://github.com/CISOfy/lynis/blob/master/include/osdetection#L244) Raspbian is correctly detected and LINUX_VERSION is set to Raspbian.
 - It is later overwritten in [ll. 312](https://github.com/CISOfy/lynis/blob/master/include/osdetection#L312) and not set to Raspbian again.

I would suggest to only "reset" LINUX_VERSION to Debian if not already set after parsing `os-release`, [you already implemented this for RedHat based distributions](https://github.com/CISOfy/lynis/blame/master/include/osdetection#L355). I will prepare a pull request which fixes this issue.

I suspect all Debian "relatives" (like Kali, ...) which are not based on Ubuntu are affected, though I did not verify it..

**Version**
 - Raspberry Pi OS / Raspbian Buster
 - Lynis Commit 7df0b8618b5cce39961b245a3c582af4294276d7

**Comment by stnert** [comment]
In Arch Linux it detects this path as well.
