### ISSUE TITLE
Exception Found! [OS Detection]

### ISSUE THREAD

**Issue by crashmaster18** [CISOfy/lynis#1018]
**Describe the bug**
SUSE Linux Enterprise / openSUSE Leap detection should be updated 

**Version**
 - Distribution SUSE Linux Enterprise / openSUSE Leap 15.x / 12.x
 - Lynis version 3.0.0

**Expected behavior**
/etc/os-release detection/parsing should now work in Lynis as it does for RHEL.

**Output**
"Message: Unknown OS found in /etc/os-release"

**Additional context**
SUSE Linux Enterprise (sle) and openSUSE Leap are near equivalents (similar to RHE and CentOS). Starting with version 12, /etc/os-release is used consistently (/etc/SuSE-release is depreciated since version 11). With this in mind, I'm admittedly not a programmer, but I believe the code required to produce the OS detection in Lynis for SUSE Linux Enterprise and openSUSE Leap [should be very similar what is used for detecting RedHat releases](https://github.com/CISOfy/lynis/blame/master/include/osdetection#L250). Two example /etc/os-release files;

SUSE Linux Enterprise (SuSE is now SUSE);

NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"

and

openSUSE Leap;

NAME="openSUSE Leap"
VERSION="15.2"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.2"
PRETTY_NAME="openSUSE Leap 15.2"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.2"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"

**Comment by konstruktoid** [comment]
Can you verify this is still the case?

```
[+] Initializing program
------------------------------------
  - Detecting OS...                                           [ DONE ]
  - Checking profiles...                                      [ DONE ]

  ---------------------------------------------------
  Program version:           3.0.2
  Operating system:          Linux
  Operating system name:     openSUSE
  Operating system version:  15.2
  Kernel version:            4.19.76
  Hardware platform:         x86_64
  Hostname:                  8e596a4d6439
  ---------------------------------------------------
  Profiles:                  /lynis/default.prf
  Log file:                  /var/log/lynis.log
  Report file:               /var/log/lynis-report.dat
  Report version:            1.0
  Plugin directory:          ./plugins
  ---------------------------------------------------
  Auditor:                   [Not Specified]
  Language:                  en
  Test category:             all
  Test group:                all
  ---------------------------------------------------
  - Program update status...                                  [ SKIPPED ]
```

**Comment by mboelen** [comment]
@konstruktoid thanks for assisting. Looks like openSUSE Leap should already be detected.
Just added SLES with commit https://github.com/CISOfy/lynis/commit/77b93ae73df0de716f7dd56f85a8c51406607a54

@crashmaster18 - Closing issue, let us know in case detection is not working properly.
