### ISSUE TITLE
[FILE-6344] hidepid value is not recognising in PROC

### ISSUE THREAD

**Issue by Me-Codifier** [CISOfy/lynis#1022]
**Describe the bug**
PROC mount value hidepid is not recognising

**Version**

- Distribution : Manjaro 20.0.1
- Lynis Version : 3.0.0

**Expected behavior**
should read  correct hidepid value form /usr/bin/mount.

**Output**
Proc with hidepid is not detecting.

**Additional context**
_Issue On Line_
https://github.com/CISOfy/lynis/blob/7df0b8618b5cce39961b245a3c582af4294276d7/include/tests_filesystems#L357

In my Manjaro Linux, proc is mounted with hidepid=2 and lynis is not recognizing it.
When I dig in, I found code is only finding for ` "hidepid=[0-9]" `
In  my Manjaro, hidepid is showing invisible.
``` proc on /proc type proc (rw,relatime,hidepid=invisible) ```

hidepid 0 = gives no output
hidepid 1 = noaccess
hidepid 2 = invisible

I have made some workaround in code locally, as :
``` FIND=$(${MOUNTBINARY} | ${EGREPBINARY} "${ROOTDIR}proc " | ${EGREPBINARY} -o "hidepid=[0-9,i,n]") ```
...
``` if [ "${FIND}" = "hidepid=2" -o "hidepid=i" ]; then ```
...
``` elif [ "${FIND}" = "hidepid=1" -o "hidepid=n" ]; then ```
bad at regex :smiley: 

Could you get this sorted in future commits.

**Comment by mboelen** [comment]
Fixed with https://github.com/CISOfy/lynis/pull/1173
