### ISSUE TITLE
ROSA Linux not detected

### ISSUE THREAD

**Issue by SergeyDjam** [CISOfy/lynis#1026]
lynis - 3.0.1
ROSA Linux Fresh R11.1 

>  Exception found!
> 
>   Function/test:  [OS Detection]
>   Message:        Unknown OS found in /etc/os-release - Please create issue on GitHub project page: https://github.com/CISOfy/lynis

> lsb_release -a
> LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:core-5.0-amd64:core-5.0-noarch:cxx-3.1-amd64:cxx-3.1-noarch:cxx-3.2-amd64:cxx-3.2-noarch:graphics-3.1-amd64:graphics-3.1-noarch:graphics-3.2-amd64:graphics-3.2-noarch:lsb-2.0-amd64:lsb-2.0-noarch:lsb-3.0-amd64:lsb-3.0-noarch:lsb-3.1-amd64:lsb-3.1-noarch:lsb-3.2-amd64:lsb-3.2-noarch:lsb-4.0-amd64:lsb-4.0-noarch:lsb-4.1-amd64:lsb-4.1-noarch:lsb-5.0-amd64:lsb-5.0-noarch
> Distributor ID: RosaDesktopFresh
> Description:    ROSA Desktop Fresh R11.1
> Release:        2016.1
> Codename:       Fresh

> cat /etc/os-release 
> NAME="ROSA Desktop Fresh R11.1"
> VERSION="EE 2016.1 Desktop"
> ID=rosa
> VERSION_ID=2016.1
> PRETTY_NAME="ROSA Desktop Fresh R11.1 EE 2016.1 Desktop"
> ANSI_COLOR="1;43"
> CPE_NAME="cpe:/o:rosa:rosalinux:2016.1"
> HOME_URL="http://www.rosalinux.com/"
> BUG_REPORT_URL="https://bugs.rosalinux.ru/"

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. How would it help you to make things easier? Ex. I'm always frustrated when [...]

**Describe the solution you'd like**

**Required changes**
What needs to be changed in Lynis?

**Additional context**
Add anything else that you consider to be relevant about the feature request here.

**Comment by SergeyDjam** [comment]
#1027

**Comment by mboelen** [comment]
Closed after added #1027
