### ISSUE TITLE
NETW-3200 is inverted

### ISSUE THREAD

**Issue by ogmueller** [CISOfy/lynis#1028]
**Describe the bug**
I believe that NETW-3200 is checked contrary to expectations. The check is looking for protocols usually not used, BUT activated anyway. Though the code is written as looking for blacklisting those modules. So the result is wrong. If modules are installed, which they shouldn't, the test is "OK".

**Version**
 - Distribution Ubuntu 20.04
 - Lynis version 3.0.1

**Expected behavior**
in `/include/tests_networking` (test NETW-3200) in line 744 the test is looking for a line `install ${P} /bin/true`. So it checks if the module has been installed/activated/loaded. In 745 though if this is the case and result is non-zero length `-n` (so someone has purposefully installed one of those protocols), the variable `UNCOMMON_PROTOCOL_DISABLED` is set to true. It should be reversed, if i am not mistaken.

So either the test should look for a blacklist in /etc/modules.d and set `UNCOMMON_PROTOCOL_DISABLED=1` or
look for "install ..." and than set `UNCOMMON_PROTOCOL_DISABLED=0`.

As far as I see, it has been implemented differently at the beginning (https://github.com/CISOfy/lynis/issues/702) with commit https://github.com/CISOfy/lynis/commit/d2deb63ebb416b957ba973a014ea6588103f3cfc. In it a variable `FOUND_UNCOMMON_PROTOCOL` has been set to true.

**Output**
```
2020-10-10 13:54:30 Test: checking the status of some network protocols that typically are not used
2020-10-10 13:54:30 Test: now checking module 'dccp'
2020-10-10 13:54:30 Suggestion: Determine if protocol 'dccp' is really needed on this system [test:NETW-3200] [details:-] [solution:-]
2020-10-10 13:54:30 Test: now checking module 'sctp'
2020-10-10 13:54:30 Suggestion: Determine if protocol 'sctp' is really needed on this system [test:NETW-3200] [details:-] [solution:-]
2020-10-10 13:54:30 Test: now checking module 'rds'
2020-10-10 13:54:30 Suggestion: Determine if protocol 'rds' is really needed on this system [test:NETW-3200] [details:-] [solution:-]
2020-10-10 13:54:30 Test: now checking module 'tipc'
2020-10-10 13:54:30 Suggestion: Determine if protocol 'tipc' is really needed on this system [test:NETW-3200] [details:-] [solution:-]
```

**Comment by ogmueller** [comment]
The test itself doesn't seem to be very fool proof. If there is any additional space in the conf, the test won't work anymore. E.g.
```
install     ${P}     /bin/true
```
instead of 
```
install ${P} /bin/true
```

Is there no better way to actually find out, if modules are available? E.g. with lsmod or so?

**Comment by silentcreek** [comment]
You seem to misunderstand what 'install {MODULE} /bin/true' does. This will not install {MODULE} but entirely disable it or prevent you from loading it. Check man modprobe.d(5) where it says:

> install modulename command...
>     This command instructs modprobe to run your command instead of inserting the module in the kernel as normal.

Thus, loading the module would just result in /bin/true being executed which does nothing but return with exit code 0.

So, the test logic itself is correct.

**Comment by ogmueller** [comment]
Yes, you are right. Sorry, but I am not very experienced with modules. But reading the man page, it says:

> The long term future of this command as a solution to the problem of providing additional module dependencies is not assured and it is intended to replace this command with a warning about its eventual removal or deprecation at some point in a future release.

Is it not better or possible to use `blacklist` instead? At least that is used in lynis `tests_filesystems` and `tests_storage`.

**Comment by silentcreek** [comment]
Well, blacklisting using the blacklist command in the modprobe configuration has the downside that it only prevents the kernel from automatically loading it. When a module is blacklisted, it's still possible, however, to load the module manually or that the module is loaded as a dependency of another module that is loaded automatically. The `install ... /bin/true' approach is a workaround that prevents the module from being loaded in any case.

Nevertheless, I'm not convinced either by this particular test. As you mentioned, it requires an exact match of the tested syntax (so, /usr/bin/true wouldn't be matched either, for instance). But more importantly, it dictates which approach you should use which is debatable. I'd be fine with just blacklisting the module. And Ubuntu, for example, uses yet another approach to "blacklist" rare and possibly unmaintained network protocols (not the 4 protocols tested here, though). They define an alias for the protocol family which also prevents the module from being autoloaded, but allows an administrator to explicitly load a module, if required. Their syntax is:
> # protocol family 3 equals protocol ax25
> alias net-pf-3 off

So, I'd prefer a test that allows more options than just the hardcoded `install ... /bin/true' approach.

And then there's the question, which protocols to look for. Why not extend the list of uncommon protocols to those disabled by Ubuntu, for example? These would be rds (already covered by this test), ax35, netrom, x25, rose, econet, af_802154 and decnet, if I'm not mistaken (last time I checked was quite a while ago already, though). On top of that, I personally also disable IPX (and some not so uncommon protocols that I happen to have no use for).

To complicate matters, distributions may disable protocols at the kernel configuration level, which makes it superfluous to disable them through the modprobe configuration. To my knowledge, Debian disables the protocols af_802154, rds and decnet in their kernel packages.

**Comment by mboelen** [comment]
Thanks @silentcreek for providing the details. And I agree, we currently test one approach with the goal to enforce that modules really can't be loaded. This is also the most used method in hardening guides.

So now that we confirmed that the test works as expected, I will close this issue, yet allow further discussing what can be done to improve the test itself.
