### ISSUE TITLE
DBS-1816 doesn't detect empty MySQL password

### ISSUE THREAD

**Issue by oliver** [CISOfy/lynis#1030]
**Describe the bug**
The DBS-1816 test ("Checking empty MySQL root password") does not actually detect if no (or an empty) root password is set for MySQL database.

**Version**
 - Distribution: Debian 10.6 "Buster"
 - Lynis version: 3.0.1

**Expected behavior**
I have a Debian server where MySQL (actually MariaDB now) is installed, but no database password is set for the root user. Any user can execute `mysql -u root` and get access to the database. However, when I run `lynis audit system` this is not detected, even though it should be detected by the DBS-1816 test.

I noticed this problem since I had an earlier version of Lynis installed before (from official Debian package, version 2.6.2-1), which did detect the missing MySQL root password. After upgrading Lynis, the warning did not appear any more, which was strange.

**Output**
From terminal output:
```
[+] Databases
------------------------------------
- MySQL process status [ GEFUNDEN ]

[+] LDAP Services
------------------------------------
- Checking OpenLDAP instance [ NICHT GEFUNDEN ]
```

From /var/log/lynis.log:
```
2020-10-11 23:02:57 ====
2020-10-11 23:02:57 Action: Performing tests from category: Databases
2020-10-11 23:02:57 ====
2020-10-11 23:02:57 Performing test ID DBS-1804 (Checking active MySQL process)
2020-10-11 23:02:57 Result: MySQL is active
2020-10-11 23:02:57 ====
2020-10-11 23:02:57 Performing test ID DBS-1816 (Checking MySQL root password)
2020-10-11 23:02:57 Test: Trying to login to local MySQL server without password
2020-10-11 23:02:57 Result: Login did not succeed, so a MySQL root password is set
2020-10-11 23:02:57 Hardening: assigned maximum number of hardening points for this item (2). Currently having 167 points (out of 247)
2020-10-11 23:02:57 ====
```

**Additional context**
The problem appears to be that in https://github.com/CISOfy/lynis/blob/master/include/tests_databases#L89 the check command returns `0 0` which is stored in `$FIND`. The first `0` is probably the result of `SELECT count(*) ...`; the second `0` is the result of `echo $?`.

As result, the test `if [ "${FIND}" = "0" ]` will never succeed, since it checks for `0` but gets `0 0`. Therefore it will always enter the `else` case and will display `Result: Login did not succeed, so a MySQL root password is set`.

**Comment by Varbin** [comment]
Seems it may have been introduced with 40d6a853d56cffc99cb95f18396db252cc7c3025 in version 2.6.4.

**Comment by mboelen** [comment]
Should be fixed with https://github.com/CISOfy/lynis/commit/8fb98cb25c80ad4655887af7aefc99db7c508f87

Can you test?
