### ISSUE TITLE
Unknown OS found in /etc/os-releases

### ISSUE THREAD

**Issue by C4pr1c0rn** [CISOfy/lynis#1031]
**Describe the bug**
Zorin OS (derives from Ubuntu) is not detected

output /etc/os-releases:
NAME="Zorin OS"
VERSION="15.3"
ID=zorin
ID_LIKE=ubuntu
PRETTY_NAME="Zorin OS 15.3"
VERSION_ID="15"
HOME_URL="https://www.zorinos.com"
SUPPORT_URL="https://www.zorinos.com/help"
BUG_REPORT_URL="https://bugs.launchpad.net/zorin-os"
PRIVACY_POLICY_URL="https://www.zorinos.com/legal/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
**Version**
 - Distribution Zorin OS 15.3
 - Lynis version 3.0.1

**Expected behavior**
It should detect the OS :-)

**Output**
[+] Initializing program
------------------------------------

=================================================================

  Exception found!

  Function/test:  [OS Detection]
  Message:        Unknown OS found in /etc/os-release - Please create issue on GitHub project page: https://github.com/CISOfy/lynis

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (/usr/sbin/lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

  Thanks!

**Additional context**

**Comment by KneadToKnow** [comment]
Also getting this with Linux Mint 18.2 (also derived from Ubuntu). Note that second part *does* appear to know what OS it is.

Output of /etc/os-release:
============================================
NAME="Linux Mint"
VERSION="18.2 (Sonya)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.2"
VERSION_ID="18.2"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sonya
UBUNTU_CODENAME=xenial

Lynis reports
============================================
 Exception found!

  Function/test:  [OS Detection]
  Message:        Unknown OS found in /etc/os-release - Please create issue on GitHub project page: https://github.com/CISOfy/lynis

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (./lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

  Thanks!

=================================================================

- Detecting OS...  [ DONE ]
- Checking profiles... [ DONE ]

  ---------------------------------------------------
  Program version:           3.0.1
  Operating system:          Linux
  Operating system name:     Linux Mint
  Operating system version:  18.2
  Kernel version:            4.15.0
  Hardware platform:         x86_64

**Comment by mboelen** [comment]
@C4pr1c0rn - Thanks for reporting, detection has been added!
@KneadToKnow - Please create a separate issue
