### ISSUE TITLE
Add 'Mageia' in osdetection module

### ISSUE THREAD

**Issue by rexy74** [CISOfy/lynis#1034]
**Describe the bug**
Unknown OS found in /etc/os-release

**Version**
 - Distribution : Mageia-7.1
 - Lynis version : 3.0.1

**Expected behavior**
mach the content of "/etc/os-release" file

**Output**
Unknown OS found in /etc/os-release

**Additional context**
This is the content of os-release :
NAME="Mageia"
VERSION="7"
ID=mageia
VERSION_ID=7
ID_LIKE="mandriva fedora"
PRETTY_NAME="Mageia 7"
ANSI_COLOR="1;36"
HOME_URL="http://www.mageia.org/"
SUPPORT_URL="http://www.mageia.org/support/"
BUG_REPORT_URL="https://bugs.mageia.org/"
PRIVACY_POLICY_URL="https://wiki.mageia.org/en/Privacy_policy"

**Comment by konstruktoid** [comment]
Hi @rexy74, Mageia was added a few years back (https://github.com/CISOfy/lynis/blame/master/include/osdetection#L399-L404) can you check if `grep "^Mageia" /etc/redhat-release | awk '{ if ($2=="release") { print $3 } }'` fails?

**Comment by konstruktoid** [comment]
Mageia got a `/etc/os-release` and will get caught at https://github.com/CISOfy/lynis/blob/master/include/osdetection#L142 and not at https://github.com/CISOfy/lynis/blob/master/include/osdetection#L373.
Can you test https://github.com/CISOfy/lynis/pull/1043?

**Comment by rexy74** [comment]
Hi @konstruktoid, this is all you need to know which file to take into account :
------
ls -l /etc/*-release
-rw-r--r-- 1 root root 104 sept. 20  2018 lsb-release
-rw-r--r-- 1 root root  39 juil. 12  2019 mageia-release
lrwxrwxrwx 1 root root  14 juil. 12  2019 mandrakelinux-release -> mageia-release
lrwxrwxrwx 1 root root  14 juil. 12  2019 mandrake-release -> mageia-release
lrwxrwxrwx 1 root root  14 juil. 12  2019 mandriva-release -> mageia-release
lrwxrwxrwx 1 root root  21 juil. 12  2019 os-release -> ../usr/lib/os-release
lrwxrwxrwx 1 root root  14 juil. 12  2019 redhat-release -> mageia-release
lrwxrwxrwx 1 root root  14 juil. 12  2019 system-release -> mageia-release
------
"os_release" is like in my first post
"mageia-release" is like that : Mageia release 7 (Official) for x86_64
"lsb-release" is like that : 
LSB_VERSION=
DISTRIB_ID="Mageia"
DISTRIB_RELEASE=7
DISTRIB_CODENAME=mga7
DISTRIB_DESCRIPTION="Mageia 7"

**Comment by konstruktoid** [comment]
Thanks @rexy74, I believe this is fix in https://github.com/CISOfy/lynis/pull/1043

**Comment by mboelen** [comment]
Closing issue, as the specific change to include this has already been merged. Will be part of upcoming release.
