### ISSUE TITLE
Export results tests in HTML / CSV

### ISSUE THREAD

**Issue by steph78630** [CISOfy/lynis#1037]
**Is your feature request related to a problem? Please describe.**
Unless I am not aware of it, I have not found a solution to export the test results displayed during execution...

**Describe the solution you'd like**
Allow export to an HTML file (with for eg. expanding and collapsing sections), or export to CSV file

> This would make it possible, via a cron job, to generate this file and thus be able to consult it easily without having to manually run the tests

**Required changes**
Add a switch / option when running tests (for eg. --exporthtml)

**Additional context**

**Comment by mboelen** [comment]
Creating a HTML/JSON/CSV file is something that we currently not have planned. The reason is that there is already a plaintext file (lynis-report.dat), that can be parsed.

**Comment by steph78630** [comment]
Ok, I understand, thanks !
