### ISSUE TITLE
Unknown OS found in /etc/os-releases on IPFire 2.25 (x86_64) - core150

### ISSUE THREAD

**Issue by steph78630** [CISOfy/lynis#1040]
**Describe the bug**
Exception found! [OS DETECTION]

**Version**
 - Distribution [IPFire 2.25 (x86_64)]
 - Lynis version [3.0.2]

**Expected behavior**

**Output**

**Additional context**
$ cat /etc/os-release

NAME="IPFire"
VERSION="2.25"
ID=ipfire
VERSION_ID=2
PRETTY_NAME="IPFire 2.25 (x86_64) - core150"
ANSI_COLOR="0:31"

_Note : IPFire (open firewall solution) supports the work of **lynis** - addon in IPFire > Pakfire addons list_

**Comment by steph78630** [comment]
Note : For IPFire, problem corrected by the #1073

**Comment by mboelen** [comment]
Closed after work done by @Varbin
