### ISSUE TITLE
Upgrading from version 3.0.0 to 3.0.1 fails

### ISSUE THREAD

**Issue by Haxx** [CISOfy/lynis#1053]
**Bug Description**
 I followed the installation steps as described in https://packages.cisofy.com/community/#debian-ubuntu
 
1.  Import key
2.  Add software repository
3.  Install Lynis via apt

**Version**
 - OS: 5.8.0-2parrot1-amd64
 - Lynis version: 3.0.0

**Expected behavior**
$lynis show version
3.0.1

**Output**
$lynis show version
3.0.0

**Additional context**
```
$lynis update check
status=outdated
```
```
$lynis update info

 == Lynis ==

  Version            : 3.0.0
  Status             : Outdated
  Installed version  : 300
  Latest version     : 301
  Release date       : 2020-06-18
  Project page       : https://cisofy.com/lynis/
  Source code        : https://github.com/CISOfy/lynis
  Latest package     : https://packages.cisofy.com/


2007-2020, CISOfy - https://cisofy.com/lynis/
```

`/etc/apt/preferences.d/lynis`
```
Package: lynis
Pin: origin packages.cisofy.com
Pin-Priority: 600

```
`$ sudo apt-cache policy lynis`

```
lynis:
  Installed: 3.0.0-2
  Candidate: 3.0.0-2
  Version table:
     3.0.1-100 600
     500 https://packages.cisofy.com/community/lynis/deb stable/main amd64 Packages 
 *** 3.0.0-2 1001
       1001 https://deb.parrot.sh/parrot rolling/main amd64 Packages
       1001 https://ftp.nluug.nl/os/Linux/distr/parrot rolling/main amd64 Packages
       1001 https://ftp.acc.umu.se/mirror/parrotsec.org/parrot rolling/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by mboelen** [comment]
Looks like the '1001' priority wins (has also the 3 stars). Why? Higher number is higher priority. So update your preferences.d/lynis file and increase the value, then see if that would make it win by running `apt-cache policy lynis` again. Is that the case?

**Comment by Haxx** [comment]
@mboelen 
I have increased the priority in `/etc/apt/preferences.d/lynis`

```
$cat /etc/apt/preferences.d/lynis
Package: lynis
Pin: origin packages.cisofy.com
Pin-Priority:1001
```
and it worked.

It would be useful to update the installation manual to reflect this specific use case.

**Comment by mboelen** [comment]
Documentation has been changed.
