### ISSUE TITLE
Missing constants

### ISSUE THREAD

**Issue by steph78630** [CISOfy/lynis#1056]
**Describe the bug**
Execution crash with display of an error message "unbound variable"

**Version**
 - Distribution [synology DSM 6.2.3]
 - Lynis version [3.0.2 from Github]

**Expected behavior**

**Output**

**Additional context**
./lynis/include/tests_hardening: line 57: CCBINARY: unbound variable
./lynis/include/tests_hardening: line 57: GCCBINARY: unbound variable

**Comment by mboelen** [comment]
Thanks for reporting. Added with https://github.com/CISOfy/lynis/commit/a2f4d524047b10cc5199ccde7831f22e62ccdfd7
