### ISSUE TITLE
Errors during profile check on OpenSolaris distributions

### ISSUE THREAD

**Issue by Varbin** [CISOfy/lynis#1065]
**Describe the bug**
On OpenSolaris derivates (e.g. Omnios and OpenIndiana), Lynis does not start and reports "unexpected characters in profile".

**Version**
 - OmniosCE r151034l / OpenIndiana 
 - Lynis version 3.0.2 (499cf1c or Rev 3182 if copied as SVN repository)

**Expected behavior**
Lynis starts.

**Output**

OpenIndiana (had to clone as svn repository):
<pre>
root@openindiana:~/lynis.git/trunk# ./lynis audit system

[ Lynis 3.0.2 ]

################################################################################
  Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
  welcome to redistribute it under the terms of the GNU General Public License.
  See the LICENSE file for details about using this software.

  2007-2020, CISOfy - https://cisofy.com/lynis/
  Enterprise support available (compliance, plugins, interface and tools)
################################################################################

[+] Initializing program
------------------------------------
  - Detecting OS...                                           [ DONE ]

 ==================================================================================================

  [WARNING]: Your profile contains old-style configuration entries. See log file for more details and how to convert these entries

  * ISSUE
  Your profile has one or more lines that are in an old format (key:value). They need to be converted into the new format (key=value) or disabled.

  * HOW TO RESOLVE
  Use grep to see the relevant matches (grep -E "^[a-z-]{1,}:" custom.prf)

 ==================================================================================================

  [WARNING]: Your profile '/root/lynis.git/trunk/default.prf' contains unexpected characters. See the log file for more information.

Fatal error: unexpected characters in profile. Stopping execution (security measure)
</pre>

OmniosCE:
<pre>
root@omniosce:~/lynis# ./lynis audit system

[ Lynis 3.0.2 ]

################################################################################
  Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
  welcome to redistribute it under the terms of the GNU General Public License.
  See the LICENSE file for details about using this software.

  2007-2020, CISOfy - https://cisofy.com/lynis/
  Enterprise support available (compliance, plugins, interface and tools)
################################################################################

[+] Initializing program
------------------------------------
awk: syntax error near line 1
awk: bailing out near line 1
  - Detecting OS...                                           [ DONE ]

 ==================================================================================================

  [WARNING]: Your profile contains old-style configuration entries. See log file for more details and how to convert these entries

  * ISSUE
  Your profile has one or more lines that are in an old format (key:value). They need to be converted into the new format (key=value) or disabled.

  * HOW TO RESOLVE
  Use grep to see the relevant matches (grep -E "^[a-z-]{1,}:" custom.prf)

 ==================================================================================================

  [WARNING]: Your profile '/root/lynis/default.prf' contains unexpected characters. See the log file for more information.

Fatal error: unexpected characters in profile. Stopping execution (security measure)
</pre>

In both cases, not a single profile file was touched.

**Additional context**

Executing `grep -E "^[a-z-]{1,}:" default.prf | od -An -ta | sed 's/ /!space!/g'` or `grep -E "^[a-z-]{1,}:" developer.prf | od -An -ta | sed 's/ /!space!/g'` (as written in `include/profiles`) returns this:

`!space!!space!!space!!space!!space!!space!!space!!space!`

On a side note: `grep` of both distributions supports `-E`.

**Comment by Varbin** [comment]
Addition:
I ran `echo -n "" | od -An -ta | sed 's/ /!space!/g'` on both (Oracle) Solaris and OmniosCE:

| OmniosCE | Solaris |
|-|-|
| `!space!!space!!space!!space!!space!!space!!space!!space!` | ` ` |

I don't know what od does on those platforms but it seems odd.

**Comment by mboelen** [comment]
Closed due to merging work by @Varbin
