### ISSUE TITLE
netstat command not found

### ISSUE THREAD

**Issue by XlllllllX** [CISOfy/lynis#1066]
**Describe the bug**
Lynis can't use `netstat` because of "command not found".

**Version**
 - openSUSE 15.2
 - Lynis 3.0.1

**Expected behavior**
Have a correct detection about network open ports

**Output**
[+] Networking
------------------------------------
  - Starting verifying open network ports (22 25 80 111 443)...
/usr/share/lynis/include/tests_network_allowed_ports: line 37: netstat : command not found
expr: syntax error: unexpected argument '0'
/usr/share/lynis/include/tests_network_allowed_ports: line 71 : [: -lt : unary operator expected

**Additional context**
`netstat` was replaced here by `/usr/sbin/ss`

**patch proposal**
(sorry, can't find the file in this github repo + certainly not POSIX + surely not the most elegant)
*in /usr/share/lynis/include/tests_network_allowed_ports at line 36 -> to add / modify*
```
if which netstat &> /dev/null
then
    NETCMD=$(which netstat)
elif which ss &> /dev/null
then
    NETCMD=$(which ss)
else
    echo -e "\`netstat\` nor \`ss\` don't seem to be present here so we can't test open ports. Please, install one of those before audit again."
fi
"$NETCMD" -an | grep -i listen > "$TMP"
```
*in /usr/share/lynis/include/tests_network_allowed_ports at line 71*
Maybe change the mindness of this test and check if `$HP` is set or not and ensure the type value before?

**Comment by Varbin** [comment]
@XlllllllX Do you mind telling me which package of [those](https://software.opensuse.org/package/lynis) you have installed? 

I believe this test might not be part of the lynis upstream sources, as I can't find the file `tests_network_allowed_ports` either, and not even find the string `Starting verifying open network ports` anywhere in the repository.

Usually Lynis already detects available tools in the file `include/binaries`.

**Comment by Varbin** [comment]
I found file in the lynis package of home:ecsos (have not chacked if it is included in the official package as well). The file header indicates it has been written by Thoma Biege (<thomas@suse.de>), so you might want try contacting him regarding this issue.

**Comment by Varbin** [comment]
I found the file in the `home:ecsos` package. The file header indicates that this file has been written by Thomas Biege from SUSE. His mail address is included in the file itself.

**Comment by XlllllllX** [comment]
@Varbin Thanks for answering.
Package info :
```
Name         : lynis
Version      : 3.0.1-lp152.83.1
Architecture : noarch
Location     : https://download.opensuse.org/repositories/security/openSUSE_Leap_15.2/noarch/lynis-3.0.1-lp152.83.1.noarch.rpm
```
It's the same maintainer, and you are surely right:
https://build.opensuse.org/package/view_file/security/lynis/tests_network_allowed_ports?expand=1
I'm going to contact him.
Many thanks!
