### ISSUE TITLE
Unknown OS found in /etc/os-releases on NixOS

### ISSUE THREAD

**Issue by ryneeverett** [CISOfy/lynis#1068]
**Describe the bug**
An exception message is printed complaining of an unknown OS.

**Version**
 - Distribution NixOS 20.03
 - Lynis version 3.0.1

**Expected behavior**
No such warning.

**Output**
Unknown OS found in /etc/os-release - Please create issue on GitHub project page: https://github.com/CISOfy/lynis

**Additional context**

```sh
$ cat /etc/os-release
NAME=NixOS
ID=nixos
VERSION="20.03.3158.7c2a362b58a (Markhor)"
VERSION_CODENAME=markhor
VERSION_ID="20.03.3158.7c2a362b58a"
PRETTY_NAME="NixOS 20.03 (Markhor)"
LOGO="nix-snowflake"
HOME_URL="https://nixos.org/"
DOCUMENTATION_URL="https://nixos.org/learn.html"
SUPPORT_URL="https://nixos.org/community.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
```

**Comment by mboelen** [comment]
Closed after work done by @Varbin
