### ISSUE TITLE
plugin pam

### ISSUE THREAD

**Issue by 0x25** [CISOfy/lynis#107]
I get this error when I run the audit system whith the plug-in pam

   [../lynis: 337: [: -eq: unexpected operator
./lynis: 349: [: -eq: unexpected operator
./lynis: 411: [: -eq: unexpected operator
./lynis: 417: [: -eq: unexpected operator
./lynis: 425: [: -eq: unexpected operator

**Comment by kboratynski** [comment]
What operating system did you run Lynis on?

**Comment by mboelen** [comment]
Seems like unitialized variables. Are you using this with the development version from GitHub?

**Comment by 0x25** [comment]
hello

I test in a simple debian. (Linux debian 3.2.0-4-486 #1 Debian 3.2.68-1+deb7u5 i686 GNU/Linux)
"Seems like unitialized variables" +1
I put some log https://ghostbin.com/paste/p4jho

**Comment by mboelen** [comment]
Thanks for sharing the log. To be 100% sure we are troubleshooting correctly: What Lynis version are you using?

**Comment by 0x25** [comment]
./lynis --version
2.1.1

**Comment by mboelen** [comment]
Thanks. In that case that explains it. The solution is to upgrade to the latest version of Lynis from GitHub. You can do this by performing a git clone of this project and run Lynis again.

Closing this issue.
