### ISSUE TITLE
Doesnt work in termux

### ISSUE THREAD

**Issue by ghost** [CISOfy/lynis#1072]
**Describe the bug**
Lynis fails after OS detection in termux

**Version**
 - Android 10, OneUI 2.5
 - Lynis 3.0.2

**Expected behavior**
Lynis works perfectly fine and tests the security of the OS

**Output**
`mktemp: failed to create file via template ‘/tmp/lynis.XXXXXXXXXX’: No such file or directory`

**Additional context**
My phone is the Samsung A71 and it is not rooted
also this will probably get denied because "oh its not supposed to work on android"

**Comment by quantumpacket** [comment]
@breadtard I'd like to try this out myself, but it doesn't seem to be available for me to install via `pkg` at least for me. Did you enable/add a repo other than the defaults? If not, what method did you use to get it installed? Manual download?

**Comment by breadtard** [comment]
> @breadtard I'd like to try this out myself, but it doesn't seem to be available for me to install via `pkg` at least for me. Did you enable/add a repo other than the defaults? If not, what method did you use to get it installed? Manual download?

I cloned the git repo and ran `./lynis audit system` yes

**Comment by quantumpacket** [comment]
The reason you are getting the error:

> `mktemp: failed to create file via template ‘/tmp/lynis.XXXXXXXXXX’: No such file or directory`

Is that `mktemp` is trying to create a directory in `/tmp`, which does not exist. I ran `sudo ls /` to get  listing of directories in the root directory and there is no `/tmp`. Even if Lynis were to create one it would need root permissions to do so.

**Comment by quantumpacket** [comment]
You got me interested in getting this to work on Termux. So I'm going to attempt to get it working, but waiting for a response to https://github.com/CISOfy/lynis/issues/374#issuecomment-732616280 before I execute the cloned repo on my device.
