### ISSUE TITLE
Unknown OS found in /etc/os-releases on EndeavourOS

### ISSUE THREAD

**Issue by ElviaSchoultz** [CISOfy/lynis#1077]
**Describe the bug**
An exception message is printed complaining of an unknown OS.

**Version**
Distribution EndeavourOS
Lynis version 3.0.1

**Expected behavior**
No such warning.

**Output**
Unknown OS found in /etc/os-release - Please create issue on GitHub project page: https://github.com/CISOfy/lynis

**Comment by quantumpacket** [comment]
Can you run the command `cat /etc/os-release` and paste us the output?

**Comment by ElviaSchoultz** [comment]
NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID=endeavouros
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://endeavouros.com/wiki/"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://github.com/endeavouros-team"
LOGO=endeavouros

**Comment by ElviaSchoultz** [comment]
fixed with #1080
