### ISSUE TITLE
tests_databases  execute  error

### ISSUE THREAD

**Issue by awanawana** [CISOfy/lynis#1081]
**Describe the bug**
![图片](https://user-images.githubusercontent.com/32409620/100822286-fc6d0100-348c-11eb-9f37-8d02bb0ae5b1.png)
The code is in ../include/databases line 89.

this code "FIND=$(${MYSQLCLIENTBINARY} --no-defaults -u root --password= --silent --batch --execute="SELECT count(*) FROM mysql.user WHERE user = 'root' AND plugin = 'mysql_native_password' AND authentication_string = ''" mysql 2>/dev/null; echo $?)" could return "0 0" that result next code can't execute rightly。

**Version**
 - Distribution [e.g. Ubuntu 18.04]
 - Lynis version [e.g. 2.7.0]

**Expected behavior**

**Output**
If applicable, add output that you get from the tool or the related section of lynis.log

**Additional context**

**Comment by Varbin** [comment]
Is this the same problem as #1030?

**Comment by mboelen** [comment]
Yes, looks the same as https://github.com/CISOfy/lynis/issues/1030

@awanawana can you check out that issue and see it is resolved?
Will close this issue.
