### ISSUE TITLE
Unknown OS found in /etc/os-releases [ElementaryOS]

### ISSUE THREAD

**Issue by raibtoffoletto** [CISOfy/lynis#1082]
**Describe the bug**
Exception found at OS Detection, program asks to report it but runs as Debian Buster/Sid

**Version**
 - Distribution: elementaryOS 5.1.7 (Hera)
 - Lynis version: 3.0.2

**Expected behavior**
Detect the ubuntu-based distro.

**Output**
Unknown OS found in /etc/os-release - Please create issue on GitHub project page
[...]
  Program version:           3.0.2
  Operating system:          Linux
  Operating system name:     Debian
  Operating system version:  buster/sid
  Kernel version:            5.4.0
  Hardware platform:         x86_64

** /etc/os-release **
NAME="elementary OS"
VERSION="5.1.7 Hera"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 5.1.7 Hera"
LOGO=distributor-logo
VERSION_ID="5.1.7"
HOME_URL="https://elementary.io/"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=hera
UBUNTU_CODENAME=bionic

--
Ps: Thanks for the great tool!

**Comment by mboelen** [comment]
Thanks for reporting. Added with commit https://github.com/CISOfy/lynis/commit/44201f02abac47cdfb7aaf118f00c742fea03583
