### ISSUE TITLE
Lynis doesn't detect ELILO boot loader

### ISSUE THREAD

**Issue by pyllyukko** [CISOfy/lynis#1086]
Lynis tries to detect various boot loaders but fails to detect [ELILO](https://en.wikipedia.org/wiki/LILO_(boot_loader)#ELILO).

```
[+] Boot and services
------------------------------------
    - Boot loader                                             [ NONE FOUND ]
```

**Describe the solution you'd like**
Lynis should be able to detect use of ELILO.

**Required changes**
* [ ] Assign `BOOT` ID for test
* [ ] Implement test

**Comment by quantumpacket** [comment]
@pyllyukko can you run `cat /etc/elilo.conf` and post the output? I'm going to presume the config will be similar to LILO's config, so creating a new test using BOOT-5139 as a template should be a good starting point. I'll see if I have time over the holidays to get a PR ready for you to test out.

**Comment by pyllyukko** [comment]
There is no such file. You can see what files are included from <ftp://ftp.slackware.com/pub/slackware/slackware64-current/slackware64/MANIFEST.bz2> (search for elilo).

**Comment by quantumpacket** [comment]
Did you run `eliloconfig` as root? From what I can gather from the docs it should create a default config in `/etc/elilo.conf` which is symbolically linked to from the EFI boot partition. I'll spin up a Slackware VM and see what's going on.

**Comment by quantumpacket** [comment]
Can you try `cat /boot/efi/EFI/Slackware/elilo.conf`?

**Comment by pyllyukko** [comment]
Here:

```
chooser=simple
#chooser=textmenu
prompt
delay=50
default=vmlinuz-generic
timeout=50
#
image=vmlinuz
        label=vmlinuz
        initrd=initrd-5.4.82.gz
        read-only
        append="root=/dev/cryptvg/root vga=normal ro"

image=vmlinuz-generic
        label=vmlinuz-generic
        initrd=initrd-5.4.82.gz
        read-only
        append="root=/dev/cryptvg/root vga=normal ro"
```

But the `Slackware` part of that path might not always be the case. I recall it's up to the user what to name it.

**Comment by teoberi** [comment]
I have the same problem for Slackware & ELILO.

**Comment by teoberi** [comment]
A possible solution, already tested.
```
    # Test        : BOOT-5140
    # Description : Check for ELILO boot loader
    Register --test-no BOOT-5140 --os "Linux" --weight L --network NO --root-only YES --category security --description "Check ELILO as bootloader"
    if [ ${SKIPTEST} -eq 0 ]; then
        BOOT_LOADER_SEARCHED=1
        FileExists ${ROOTDIR}boot/efi/EFI/Slackware/elilo.conf
        if [ ${FILE_FOUND} -eq 1 ]; then
            Display --indent 2 --text "- Checking boot loader ELILO" --result "${STATUS_FOUND}" --color GREEN
            LogText "Result: found ELILO boot loader"
            BOOT_LOADER="ELILO"
            BOOT_LOADER_FOUND=1
        else
            LogText "Result: ELILO configuration file not found"
        fi
    fi
```
**Additional context**
http://slackware.osuosl.org/slackware64-current/README_UEFI.TXT

**Comment by pyllyukko** [comment]
Looking at eliloconfig[1] (the script used in Slackware installer) the dir `/boot/efi/EFI/Slackware/` should indeed exist in all installations.

[1] ftp://ftp.slackware.com/pub/slackware/slackware64-current/source/a/elilo/eliloconfig>

**Comment by teoberi** [comment]
A more general solution.
```
    # Test        : BOOT-5140
    # Description : Check for ELILO boot loader
    Register --test-no BOOT-5140 --os "Linux" --weight L --network NO --root-only YES --category security --description "Check ELILO as bootloader"
    if [ ${SKIPTEST} -eq 0 ]; then
        BOOT_LOADER_SEARCHED=1
        CONF_FILES="${ROOTDIR}etc/elilo.conf ${ROOTDIR}boot/efi/EFI/Slackware/elilo.conf"
        for FILE in ${CONF_FILES}; do
            FileExists ${FILE}
            if [ ${FILE_FOUND} -eq 1 ]; then
                Display --indent 2 --text "- Checking boot loader ELILO" --result "${STATUS_FOUND}" --color GREEN
                LogText "Result: found ELILO boot loader"
                BOOT_LOADER="ELILO"
                BOOT_LOADER_FOUND=1
            fi
        done
    fi
```

**Comment by pyllyukko** [comment]
Are you aware of some distro having `/etc/elilo.conf`? So it's not just guessing.

**Comment by teoberi** [comment]
There are only older distributions that use elilo.
https://manpages.debian.org/jessie/elilo/elilo.8
http://manpages.ubuntu.com/manpages/trusty/man8/elilo.8.html
https://wiki.gentoo.org/wiki/Handbook:IA64/Installation/Bootloader
I only used ELILO in Slackware for servers, although I also have workstations with Ubuntu.
