### ISSUE TITLE
Seeing log error on scan

### ISSUE THREAD

**Issue by kalkir** [CISOfy/lynis#1089]
./lynis: /tmp/lynis/include/tests_logging: line 619: syntax error: unterminated quoted string

**Version**
 -  alphine container
 -  3.0.2

**Expected behavior**
Completed the scan with score

**Output**
[+] Software: firewalls
------------------------------------
  - Checking iptables kernel module                           [ FOUND ]
  - Checking host based firewall                              [ ACTIVE ]

[+] Software: webserver
------------------------------------
  - Checking Apache                                           [ NOT FOUND ]
  - Checking nginx                                            [ NOT FOUND ]

[+] SSH Support
------------------------------------
  - Checking running SSH daemon                               [ NOT FOUND ]

[+] SNMP Support
------------------------------------
  - Checking running SNMP daemon                              [ NOT FOUND ]

[+] Databases
------------------------------------
    No database engines found

[+] LDAP Services
------------------------------------
  - Checking OpenLDAP instance                                [ NOT FOUND ]

[+] PHP
------------------------------------
  - Checking PHP                                              [ NOT FOUND ]

[+] Squid Support
------------------------------------
  - Checking running Squid daemon                             [ NOT FOUND ]

[+] Logging and files
------------------------------------
  - Checking for a running log daemon                         [ WARNING ]
    - Checking Syslog-NG status                               [ NOT FOUND ]
    - Checking systemd journal status                         [ NOT FOUND ]
    - Checking Metalog status                                 [ NOT FOUND ]
    - Checking RSyslog status                                 [ NOT FOUND ]
    - Checking RFC 3195 daemon status                         [ NOT FOUND ]
    - Checking klogd                                          [ NOT FOUND ]
    - Checking minilogd instances                             [ NOT FOUND ]
  - Checking logrotate presence                               [ OK ]
./lynis: /tmp/lynis/include/tests_logging: line 619: syntax error: unterminated quoted string

**Additional context**

**Comment by Varbin** [comment]
Sorry, this is my fault :worried:

I introduced unbalanced braces. I introduced it here: https://github.com/CISOfy/lynis/commit/1f3d0956a75a8eaca5d2acda4af93f190e1b2527#diff-0d1f697a9d1d29c4d16623bbe0b1e817c6f91130fed7b57e3add3ce440c62edcL316-L317.

**Comment by mboelen** [comment]
Fixed with commit https://github.com/CISOfy/lynis/commit/a26ebd3004fc13cff5d15c5de86e09cb0baf2e13

**Comment by kalkir** [comment]
Thanks for the quick fix :+1:
