### ISSUE TITLE
Unknown OS found - Parrot linux

### ISSUE THREAD

**Issue by alembiq** [CISOfy/lynis#1090]
**Describe the bug**
runned Lynis 3.0.1 on [parrot linux](https://www.parrotsec.org/), was told to create a new issue for unknown OS 

**Version**
 - Distribution Parrot 4.10
 - Lynis version 3.0.1

**Expected behavior**

**Output**
```
Exception found!

  Function/test:  [OS Detection]
  Message:        Unknown OS found in /etc/os-release - Please create issue on GitHub project page: https://github.com/CISOfy/lynis

  Help improving the Lynis community with your feedback!

```

**Additional context**

**Comment by quantumpacket** [comment]
@alembiq can you post the output for `cat /etc/os-release`?

**Comment by alembiq** [comment]
sure, here it is

```
PRETTY_NAME="Parrot GNU/Linux 4.10"
NAME="Parrot GNU/Linux"
ID=parrot
ID_LIKE=debian
VERSION="4.10"
VERSION_ID="4.10"
HOME_URL="https://www.parrotsec.org/"
SUPPORT_URL="https://community.parrotsec.org/"
BUG_REPORT_URL="https://community.parrotsec.org/"

```

**Comment by mboelen** [comment]
Thanks, added with commit https://github.com/CISOfy/lynis/commit/fa69256f459ee55571c6ac2bb4f4e2ba3ec38665
