### ISSUE TITLE
Lynis with MariaDB > 10.4

### ISSUE THREAD

**Issue by teoberi** [CISOfy/lynis#1092]
**Describe the bug**
The root@localhost user account created by mysql_install_db is created with the ability to use two authentication plugins.
First, it is configured to try to use the unix_socket authentication plugin. This allows the root@localhost user to login without a password via the local Unix socket file defined by the socket system variable, as long as the login is attempted from a process owned by the operating system root user account.
Second, if authentication fails with the unix_socket authentication plugin, then it is configured to try to use the mysql_native_password authentication plugin.
However, just using the unix_socket authentication plugin may be fine for many users, and it is very secure. You may want to try going without password authentication to see how well it works for you. Remember, the best way to keep your password safe is not to have one!

**Version**
 - Distribution: Slackware64-current
 - Lynis version: 3.0.2
 - MariaDB version: 10.5.8

**Expected behavior**
The test should be re-evaluated in this case.

**Output**

>   Warnings (1):
>   ! No MySQL root password set [DBS-1816]
>       https://cisofy.com/lynis/controls/DBS-1816/

lynis.log

> Performing test ID DBS-1816 (Checking MySQL root password)
> Test: Trying to login to local MySQL server without password
> Result: Login succeeded, no MySQL root password set!
> Warning: No MySQL root password set [test:DBS-1816]

**Additional context**
https://mariadb.com/kb/en/authentication-from-mariadb-104/
https://mariadb.com/kb/en/authentication-plugin-unix-socket/

**Comment by teoberi** [comment]
/lynis/include/tests_databases
Test : DBS-1816
Line
`FIND=$(${MYSQLCLIENTBINARY} --no-defaults -u root --password= --silent --batch --execute="SELECT count(*) FROM mysql.user WHERE user = 'root' AND plugin = 'mysql_native_password' AND authentication_string = ''" mysql > /dev/null 2>&1; echo $?)`
replaced with
`FIND=$(${MYSQLCLIENTBINARY} --default-auth=mysql_native_password --no-defaults -u root --password= --silent --batch --execute="SELECT count(*) FROM mysql.user WHERE user = 'root' AND plugin = 'mysql_native_password' AND authentication_string = ''" mysql > /dev/null 2>&1; echo $?)`

**Output (after modifications)**

> Performing test ID DBS-1816 (Checking MySQL root password)
> Test: Trying to login to local MySQL server without password
> Result: Login did not succeed, so a MySQL root password is set
> Hardening: assigned maximum number of hardening points for this item (2). Currently having 2 points (out of 2)

**Comment by mboelen** [comment]
Thanks, that looks like a good suggestion. Can you turn this into a pull request? That way your efforts are linked to this project :)

**Comment by mboelen** [comment]
Closing after merging pull request #1100
