### ISSUE TITLE
Lynis with PostgreSQL 13.1 - test ID DBS-1826/DBS-1828

### ISSUE THREAD

**Issue by teoberi** [CISOfy/lynis#1095]
**Describe the bug**
/lynis/include/consts
Line
`POSTGRES_RUNNING=0`
replaced with
`POSTGRESQL_RUNNING=0`

/lynis/include/tests_databases
Test        : DBS-1826
Line
`if IsRunning "postgres:"; then`
replaced with
`if IsRunning "postgres"; then`
Test        : DBS-1828
Line
`FIND_PATHS="${ROOTDIR}etc/postgres ${ROOTDIR}var/lib/postgres/data"`
replaced with
`FIND_PATHS="${ROOTDIR}etc/postgres ${ROOTDIR}var/lib/postgres/data ${ROOTDIR}usr/local/pgsql/data"`
Line
`CONFIG_FILES=$(${FINDBINARY} ${FIND_PATHS} -type f -name "postgresql.conf" -print0 2> /dev/null | ${TRBINARY} -cd '[:print:]\0' | ${TRBINARY} -d '\n' | ${TRBINARY} '\0' '\n' | xargs -i sh -c 'test -r "{}" && echo "{}" | ${SEDBINARY} "s/ /:space:/g"')`
replaced with
`CONFIG_FILES=$(${FINDBINARY} ${FIND_PATHS} -type f -name "*.conf" -print0 2> /dev/null | ${TRBINARY} -cd '[:print:]\0' | ${TRBINARY} -d '\n' | ${TRBINARY} '\0' '\n' | xargs -i sh -c 'test -r "{}" && echo "{}"' | ${SEDBINARY} "s/ /:space:/g")`
The for loop
```
for CF in ${CONFIG_FILES}; do
       Report "postgresql_config_file[]=${CF}"
       LogText "Found configuration file (${CF})"`
done
```
replaced with

```
for CF in ${CONFIG_FILES}; do
        Report "postgresql_config_file[]=${CF}"
        LogText "Found configuration file (${CF})"
             if IsWorldReadable ${CF}; then
                 LogText "Result: configuration file ${CF} is world readable, this might leak sensitive information!"
                 ReportWarning "${TEST_NO}" "PostgreSQL configuration file ${CF} is world readable and might leak sensitive details" "${CF}" "Use chmod 600 to change file permissions"
             else
                 LogText "Result: great, configuration file ${CF} is not world readable"
             fi
done
```

**Version**
 - Distribution: Slackware64-current
 - Lynis version: 3.0.2
 - PostgreSQL version: 13.1 (compiled from sources with default options)

**Expected behavior**
DBS-1826/DBS-1828 tests run without errors.
The process and configuration files with their permissions for PostgreSQL to be detected.
**Output (after modifications)**
lynis.log

> Performing test ID DBS-1826 (Checking active PostgreSQL processes)
> Performing pgrep scan without uid
> IsRunning: process 'postgres' found (21875 21877 21878 21879 21880 21881 21882 )
> Result: PostgreSQL is active
> 
> Performing test ID DBS-1828 (Test PostgreSQL configuration)
> Found configuration file (/usr/local/pgsql/data/pg_ident.conf)
> Result: great, configuration file /usr/local/pgsql/data/pg_ident.conf is not world readable
> Found configuration file (/usr/local/pgsql/data/postgresql.conf)
> Result: great, configuration file /usr/local/pgsql/data/postgresql.conf is not world readable
> Found configuration file (/usr/local/pgsql/data/pg_hba.conf)
> Result: great, configuration file /usr/local/pgsql/data/pg_hba.conf is not world readable
> Found configuration file (/usr/local/pgsql/data/postgresql.auto.conf)
> Result: great, configuration file /usr/local/pgsql/data/postgresql.auto.conf is not world readable

**Additional context**
https://www.postgresql.org/docs/13/runtime-config-file-locations.html

**Comment by mboelen** [comment]
Looks like a good set of changes to me. Can you turn this one also into a pull request?

**Comment by teoberi** [comment]
A PR # 1101 is already posted.
https://github.com/CISOfy/lynis/pull/1101
