### ISSUE TITLE
Minor inconsistency between AUTH-9229 and AUTH-9230

### ISSUE THREAD

**Issue by schurzi** [CISOfy/lynis#1098]
**Describe the bug**
In AUTH-9229 you are checking for [`"${ROUNDS}" -le 5000`](https://github.com/CISOfy/lynis/blob/075d92e275b1984328b95ea8e5b4b1958cf5befd/include/tests_authentication#L301), in AUTH-9230 you are checking for [`${SHA_CRYPT_ROUNDS} -lt 5000`](https://github.com/CISOfy/lynis/blob/075d92e275b1984328b95ea8e5b4b1958cf5befd/include/tests_authentication#L390)

**Version**
current master

**Expected behavior**
both controls should check for the same `-lt` or `-le`

**Additional context**
I can open a PR for that, I just need to know, what it should be, `-lt` or `-le` :)

**Comment by mboelen** [comment]
Hi @schurzi - Good finding!

AUTH-9229 should be adjusted as the generic best practice is that it should be at least 5000. Under 5000 is a finding.

Pull request is welcome. Please note that the description within the text should also reflect that. An undefined set of rounds is probably also an issue, as it may be unclear what the value is. Or in other words, an explicitly defined value is preferred.

**Comment by schurzi** [comment]
Now there is another ambiguity. :)
The default for sha512crypt/sha256crypt is exactly 5000. and you say:
> Under 5000 is a finding.

The current implementation already reports, a missing value (default) is a finding.

The [man page](https://man.archlinux.org/man/crypt.5#sha512crypt) also states:
> The default CPU time cost parameter is 5000, which is too low for modern hardware.

Maybe the best approach is recommending a higher value? I have some internal reference documentation, which requires 640.000 rounds at least.

For now I created a PR, which preserves current behaviour. #1108

**Comment by schurzi** [comment]
In my search I also found, that only setting `SHA_CRYPT_MIN/MAX_ROUNDS` in login.defs is sometimes not enough. See man page https://man7.org/linux/man-pages/man5/login.defs.5.html

```
           Note: This only affect the generation of group passwords. The
           generation of user passwords is done by PAM and subject to
           the PAM configuration. It is recommended to set this variable
           consistently with the PAM configuration.```

I verified this on a CentOS 8 Docker Image. An extra config in `/etc/pam.d/system-auth` is needed:
`password    sufficient    pam_unix.so try_first_pass use_authtok nullok sha512 shadow rounds=6000`

Should I also create a test for this?
