### ISSUE TITLE
AUTH-9328 Default umask best practise

### ISSUE THREAD

**Issue by martinstefany** [CISOfy/lynis#110]
Lynis recommends to change umask in /etc/profile from 002/022 to something more strict like 027, but this is not recommended procedure, at least by RedHat:

    # It's NOT a good idea to change this file unless you know what you
    # are doing. It's much better to create a custom.sh shell script in
    # /etc/profile.d/ to make custom changes to your environment, as this
    # will prevent the need for merging in future updates.

Thus, it might be better to recommend and detect changes in /etc/profile.d/custom.sh, e.g.

    # /etc/profile.d/umask.sh
    
    # By default, we want umask to get set. This sets it for login shell
    # Current threshold for system reserved uid/gids is 200
    # You could check uidgid reservation validity in
    # /usr/share/doc/setup-*/uidgid file
    if [ $UID -gt 199 ] && [ "`id -gn`" = "`id -un`" ]; then
        umask 007
    else
        umask 027
    fi

For further reference (for RH subscribers) https://access.redhat.com/solutions/107683 .

**Comment by rhyven** [comment]
That looks great, @martinstefany.  Looks like something I could probably squeeze in over the next few days, if nobody else gets to it first.  Thanks!

**Comment by mboelen** [comment]
It has been a while. A patch has been applied in the meantime which does scanning of files in /etc/profile.d. This should fix your finding, therefore closing this issue. If it still gets triggered, feel free to reopen.

Thanks for reporting and contributing to Lynis.

**Comment by thelounge-zz** [comment]
/etc/profile.d/custom.sh is indeed dectedted correctly and the hint goes away but the yellow WEAK which is still present is misleading

    - Checking default umask in /etc/bashrc                   [ WEAK ]
    - Checking default umask in /etc/csh.cshrc                [ WEAK ]
    - Checking default umask in /etc/profile                  [ WEAK ]

[root@localhost:~]$ cat /etc/profile.d/custom.sh
# Make sure umask is sane
umask 027
