### ISSUE TITLE
BANN-7126 should check files under /etc/issue.d/*.issue files

### ISSUE THREAD

**Issue by aboe76** [CISOfy/lynis#1106]
**Is your feature request related to a problem? Please describe.**
BANN-7126  checks the file /etc/issue but not the files under /etc/issue.d/*.issue

**Describe the solution you'd like**
BANN-7126  should check the files under /etc/issue.d/*.issue 

**Required changes**
include/tests_banners should be ammended with a check for files/symlinks under /etc/issue.d/*.issue

**Additional context**
/etc/issue.d/*.issue is a new way to add data to /etc/issue.

https://users.suse.com/~kukuk/SUSE-CaaSP-Docu/issue.d.5.html#:~:text=d%20.-,Files%20in%20%2Fetc%2Fissue.,the%20directories%20they%20reside%20in.

**Comment by aboe76** [comment]
This is not An stalen issue

**Comment by mboelen** [comment]
Hi @aboe76 - I did some research into this. From what I could see is that the issue.d/* files are used to form/create the main /etc/issue file. Therefore checking only this file, seems to be enough. Maybe I'm wrong though. Do you (or someone else) have information shows otherwise?

**Comment by aboe76** [comment]
You're somewhat right, these files are appended to the issues output not
the file itself.

So checking only the issues file doesn't work that's why I created the
ticket(issue).

Op za 23 jan. 2021 09:32 schreef Michael Boelen <notifications@github.com>:

**Comment by mboelen** [comment]
That is not what the man page of [issue-generator](https://users.suse.com/~kukuk/SUSE-CaaSP-Docu/issue-generator.8.html) implies: 

> If invoked with no arguments, it applies all input files and creates a temporary issue file as /run/issue. /etc/issue should be symlink to this file.

I read that as: one or more files are merged into a temporary file (/run/issue). And although that is not /etc/issue directly, it is indirectly as there needs to be a symlink from /etc/issue to /run/issue. So parsing /etc/issue will parse the content of the contents of /etc/issue.d/*

Can you test on your system that what the man page describes here is wrong?

**Comment by aboe76** [comment]
@mboelen, you are correct, but strangely it has updated my /etc/issue.net instead of /etc/issue.
