### ISSUE TITLE
Unknown macOS version. Do you know what version it is?

### ISSUE THREAD

**Issue by chris-camm** [CISOfy/lynis#1107]
lynis audit system

[ Lynis 3.0.3 ]

################################################################################
  Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
  welcome to redistribute it under the terms of the GNU General Public License.
  See the LICENSE file for details about using this software.

  2007-2021, CISOfy - https://cisofy.com/lynis/
  Enterprise support available (compliance, plugins, interface and tools)
################################################################################

[+] Initializing program
------------------------------------

  ###################################################################
  #                                                                 #
  #   NON-PRIVILEGED SCAN MODE                                      #
  #                                                                 #
  ###################################################################

  NOTES:
  --------------
  * Some tests will be skipped (as they require root permissions)
  * Some tests might fail silently or give different results

Unknown macOS version. Do you know what version it is? Create an issue at https://github.com/CISOfy/lynis
  - Detecting OS...                                           [ DONE ]
  - Checking profiles...                                      [ DONE ]

  ---------------------------------------------------
  Program version:           3.0.3
  Operating system:          macOS
  Operating system name:     macOS
  Operating system version:  11.1
  Kernel version:            20.2.0
  Hardware platform:         x86_64
  Hostname:                  ***********

**Comment by benjivcodes** [comment]
```
  Operating system:          macOS
  Operating system name:     macOS
  Operating system version:  11.2
  Kernel version:            20.3.0
  Hardware platform:         x86_64
```

MacOS 11.x is branded as BigSur.
