### ISSUE TITLE
 Unknown OS found in /etc/os-release

### ISSUE THREAD

**Issue by Naik-NLZ** [CISOfy/lynis#1109]
**Describtion**
 Unknown OS found in /etc/os-release.
I was asked to state this here.

**Version**
 - Distribution: Bunsenlabs GNU/Linux 10.5 "Lithium" based on Debian Buster
 - Lynis version: 3.0.3

`$ cat /etc/os-release
ANSI_COLOR="0;34"
BUG_REPORT_URL="https://forums.bunsenlabs.org/viewforum.php?id=14"
HOME_URL="https://www.bunsenlabs.org"
ID="bunsenlabs"
ID_LIKE="debian"
NAME="BunsenLabs GNU/Linux"
PRETTY_NAME="BunsenLabs GNU/Linux 10.5 (Lithium)"
PRIVACY_POLICY_URL="https://www.bunsenlabs.org/legal.html"
SUPPORT_URL="https://forums.bunsenlabs.org"
VERSION="10.5 (Lithium)"
VERSION_ID="10.5"`

**Comment by mboelen** [comment]
Apologies for the delay. It has been implemented with commit https://github.com/CISOfy/lynis/commit/54f9281040c8cc82aa7f8e961dcb6d04af14dfe2

**Comment by Naik-NLZ** [comment]
Great, the people over at bunsenlabs.org will highly appreciate this.
