### ISSUE TITLE
aide 0.16 incorrectly being called out for missing database 

### ISSUE THREAD

**Issue by gcsgithub** [CISOfy/lynis#1115]
**Describe the bug**
aide database check is now wrong

**Version**
 - Distribution: Aide 0.16.2
 - Lynis version 3.0.3

**Output**
      AIDE database [ NOT FOUND ]

[root@orac] # grep database /etc/aide.conf | grep -v ^#
database_in=file:@@{DBDIR}/aide.db.gz
database_new=file:@@{DBDIR}/aide.db.new.gz
database_out=file:@@{DBDIR}/aide.db.new.gz

removing the _in to demonstrate the current state of aide

[root@orac ]# aide --config-check
WARNING: /etc/aide.conf:8: Using 'database' is DEPRECATED. Update your config and use 'database_in' instead (line: 'database=file:@@{DBDIR}/aide.db.gz')

I think the correct fix here is to check for database= for legacy but not declare it missing before checking for database_in=   ?

**Comment by whygee-dev** [comment]
Same issue

**Comment by HillGnur** [comment]
Same here with Lynis 3.0.2 and aide 0.17.3
