### ISSUE TITLE
Check MemoryOverwriteRequest-bit is set

### ISSUE THREAD

**Issue by NicolaiSoeborg** [CISOfy/lynis#1116]
**Is your feature request related to a problem? Please describe.**

If disk is encrypted then we want the MOR-bit set so if the computer is stolen it is harder to do a Cold Boot Attack.

**Describe the solution you'd like**

```
# Good:
$ xxd /sys/firmware/efi/efivars/MemoryOverwriteRequestControl-e20939be-32d4-41be-a150-897f85d49829
00000000: 0700 0000 01                             .....

# Bad:
$ xxd /sys/firmware/efi/efivars/MemoryOverwriteRequestControl-e20939be-32d4-41be-a150-897f85d49829
00000000: 0700 0000 00                             .....
```

**Required changes**

Add extra check in `tests_crypto` or `tests_boot_services`?

**Comment by mboelen** [comment]
Closed due to merge action. Thanks for the contribution!

**Comment by Magicrafter13** [comment]
No information at https://cisofy.com/lynis/controls/CRYP-8006/

And based on the description in this issue, should this test be considered a failure (bad result) if the system *isn't* using disk encryption (and the MOR-bit isn't set)?

**Comment by NicolaiSoeborg** [comment]
Is there any use-cases for wanting the MOR-bit _not_ set?

I wrote in the original PR that disk encryption is affected, but really any secrets in memory is 'at risk' if the MOR-bit isn't set, afaik
