### ISSUE TITLE
ARM Bootloader - Kernel Problems (Raspberry Pi 2)

### ISSUE THREAD

**Issue by Huskynarr** [CISOfy/lynis#112]
That's a very good question.
I do not use Lynis very often, but is one of the first things I do.
So now I have installed it on the Raspberry Pi.

Which reminds me, incidentally, was this here ..

```bash
[+] Boot and services
------------------------------------
  - Service Manager [UNKNOWN]
    - Bootloader [NONE FOUND]
```

He's probably a problem with the recognition of the bootloader.
Either because it is an ARM architecture or because the system no common memory has (SD card).

When he can not find the kernel configuration.
```bash
  - Checking Linux kernel configuration file [NOT FOUND]
  - Checking for available kernel update [UNKNOWN]
  - Checking core dumps Configuration [Disabled]
    - Checking setuid core dumps configuration [default]
./lynis: 516: [: /boot/kernel.img: Unexpected operator
  - Check if reboot is needed [UNKNOWN]
```

So I know that a reboot is recommended, since I have the Linux kernel and the firmware recently updated. Raspbian is quite fast update the Linux kernel when.

The complete kernel hardening could not be recognized.

**Comment by virtadpt** [comment]
The same thing happens when a Linux system is using syslinux as its bootloader instead of LILO or GRUB.

**Comment by mboelen** [comment]
Thanks @virtadpt. Do you have a specific file we can check for to detect syslinux?

**Comment by virtadpt** [comment]
Syslinux requires that its config file be found in /boot/syslinux/syslinux.cfg.  The bootblock file (syslinux.c32) is kept in the same directory.

**Comment by mboelen** [comment]
@virtadpt support for Syslinux has been added

**Comment by mboelen** [comment]
@Huskynarr can you test if the latest version still gives you error? On what line?

**Comment by virtadpt** [comment]
Thank you very much, @mboelen.

**Comment by mboelen** [comment]
@Huskynarr Do you still have this problem with the latest version?

**Comment by mboelen** [comment]
Closing this issue, as no feedback came and can't be reproduced in our environment.
