### ISSUE TITLE
Artix linux not detected in OS Detection

### ISSUE THREAD

**Issue by tzlils** [CISOfy/lynis#1120]
/etc/os-release:
```
NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
LOGO=artixlinux
```
lynis fails to detect artix

**Comment by mboelen** [comment]
Thanks for your discovery and reporting! Do you like to create a pull request for it, so it is recognized?

**Comment by mboelen** [comment]
Pull request #1188 has been applied to recognize Artix Linux.

**Comment by anonimou0** [comment]
This has a typo in "artix", missing a quote. Making `audit system` to fail.

**Comment by mboelen** [comment]
Fixed, thanks!
