### ISSUE TITLE
Devuan 3.1 Beowulf not detected in OS Detection

### ISSUE THREAD

**Issue by farmatito** [CISOfy/lynis#1121]
PRETTY_NAME="Devuan GNU/Linux 3 (beowulf)"
NAME="Devuan GNU/Linux"
VERSION_ID="3"
VERSION="3 (beowulf)"
VERSION_CODENAME=beowulf
ID=devuan
ID_LIKE=debian
HOME_URL="https://www.devuan.org/"
SUPPORT_URL="https://devuan.org/os/community"
BUG_REPORT_URL="https://bugs.devuan.org/"

---------------------------------------------------
  Program version:           3.0.3
  Operating system:          Linux
  Operating system name:     Debian
  Operating system version:  10.0
  Kernel version:            5.10.0
  Hardware platform:         x86_64
  Hostname:                  hostname
  ---------------------------------------------------

**Comment by mboelen** [comment]
Thanks for your discovery and reporting! Do you like to create a pull request to add the detection?

**Comment by farmatito** [comment]
Not really as i did not fix the bug. Can contribute info if needed.

**Comment by mboelen** [comment]
Ok, then I will create it. Fixed with commit https://github.com/CISOfy/lynis/commit/21219c91eb08ad224853dd60d3b95e0b8d344141
