### ISSUE TITLE
[TIME-TIME-3185] Debian 9 incorrect path

### ISSUE THREAD

**Issue by FabianBoernerCHECK24** [CISOfy/lynis#1125]
**Describe the bug**
As mentioned here in the pullrquest https://github.com/CISOfy/lynis/pull/1013

The syncfile was changed to /var/lib/systemd/timesync/clock but this file doesn exists in debian
currently the only file that comes near that is /var/lib/systemd/clock

**Version**
 - Debian GNU/Linux 9.13 (stretch)
 - 3.0.3

**Expected behavior**
No message about: "systemd-timesyncd did not synchronized the time recently. [TIME-3185]"

**Output**
[DEBUG] Performing test ID TIME-3104 (Check for running NTP daemon or client)
[DEBUG] Performing test ID TIME-3148 (Check TZ variable)
[DEBUG] Performing test ID TIME-3170 (Check configuration files)
[DEBUG] Performing test ID TIME-3185 (Check systemd-timesyncd synchronized time)
  ! systemd-timesyncd did not synchronized the time recently. [TIME-3185]
      https://cisofy.com/lynis/controls/TIME-3185/

**Additional context**
Clockfile /var/lib/systemd/clock

**Comment by konstruktoid** [comment]
Hi @FabianBoernerCHECK24, can you include your systemd version?
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=883605

**Comment by FabianBoernerCHECK24** [comment]
Seems debian stretch only has 232

**Comment by konstruktoid** [comment]
The file was moved in 235 and https://packages.debian.org/stretch/systemd is version 232 from 21 Jul 2019 as you said.
Using backports or upgrading to Buster would fix this.

https://github.com/systemd/systemd/commit/53d133ea1bb4c4ed44c4b6aae42f1feb33d9cb78

**Comment by FabianBoernerCHECK24** [comment]
Ok then its not on your side we have to upgrade to buster anyway. Ill close this issue and skip the time test for now.
