### ISSUE TITLE
Allow multiple .prf files or add configurable file include

### ISSUE THREAD

**Issue by mrplow87** [CISOfy/lynis#1129]
**Is your feature request related to a problem? Please describe.**
I'm handling my hosts with Ansible and I roll out `custom.prf` to all hosts. Some hosts need additional profile settings that I can't roll out with Ansible due to the way my company handles it's hosts, so I can't put them into the `custom.prf` file because those changes get overwritten once I run Ansible an all hosts again.

**Describe the solution you'd like**
Lynis could just include all `*.prf` files in `/etc/lynis` or let you specify an include in `custom.prf`.

**Required changes**
Change how Lynis loads the `custom.prf` file and change it to `*.prf` 
or 
Check if an include option is possible and add that to how Lynis handles it's profile files.

**Comment by mboelen** [comment]
Thanks for the suggestion. You can already specify additional profiles using the command line (`--profile`). So at this stage, implementing the suggested change has only a limited benefit.
