### ISSUE TITLE
macOS Big Sur (and releases) are not being correctly detected

### ISSUE THREAD

**Issue by cesarradtke** [CISOfy/lynis#1131]
There are an issue in include/osdetection file that return 'unknown' to new releases of macOS.

The correct version and new releases will be 11.x (and not 11.0.x).

**Comment by cesarradtke** [comment]
include/osdetection

`11.0 | 11.[0-9]*) OS_FULLNAME="macOS Big Sur `(${OS_VERSION})"` ;;`

db/software-eol.db
`os:macOS Catalina \(10.15.7\):2021-02-09:1612839600`
`os:macOS Big Sur \(11.0\):2020-12-14:1607914800`
`os:macOS Big Sur \(11.1\):2021-02-01:1612148400`
`os:macOS Big Sur \(11.2\)::-1`

**Comment by mboelen** [comment]
Thanks for reporting. Should now be working with linked pull request
