### ISSUE TITLE
BOOT-5104 fails to identify Service Manager on Alpine container

### ISSUE THREAD

**Issue by abangser** [CISOfy/lynis#1132]
**Describe the bug**

I am unable to run test `BOOT-5104` on an Alpine 3.9 build container due to the pid 1 is set to the entrypoint and not a system manager.

**Version**
 - Distribution
     <details>
       <summary>Alpine Linux v3.9</summary>
         # cat /etc/os-release
         NAME="Alpine Linux"
         ID=alpine
         VERSION_ID=3.9.6
         PRETTY_NAME="Alpine Linux v3.9"
         HOME_URL="https://alpinelinux.org/"
         BUG_REPORT_URL="https://bugs.alpinelinux.org/"
      </details>
 - Lynis version
      <details>
       <summary>3.0.3</summary>
         # /usr/local/lynis/lynis update check
         status=unknown
         # /usr/local/lynis/lynis --version
         3.0.3
      </details>

**Expected behavior**
Running Lynis on an Alpine container can successfully complete the `Boot and services` review of the `Service Manager`. In testing on an Ubuntu docker image I can see output that sets the Service Manager and validates the following:
- Checking UEFI boot
- Boot loader
- Check startup files (permissions)

**Output**
```
[+] Boot and services
------------------------------------
[DEBUG] Performing test ID BOOT-5104 (Determine service manager)

=================================================================

  Exception found!

  Function/test:  [BOOT-5104:001]
  Message:        Unknown service manager

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (/usr/local/lynis/lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

  Thanks!

=================================================================
```

**Additional context**
I saw the issue #547, however it does not appear that my docker container is using busybox so I think this is different.

I have run through the checks in the [`tests_boot_services` script](https://github.com/CISOfy/lynis/blob/master/include/tests_boot_services) and walked through by hand. It seems that the `SHORTNAME` ends up as `sh` which appears to be the output of the entry point for the docker container and is not in the list of available service managers.

Is this a limitation of running Lynis on a docker container or something else entirely?

<details>
  <summary>Steps to reproduce</summary>

  1. `docker run --rm -it alpine:3.9 /bin/sh`
  2. `mkdir -p /usr/local/lynis && wget -O /usr/local/lynis.tar.gz https://cisofy.com/files/lynis-3.0.3.tar.gz && tar xfvz /u
sr/local/lynis.tar.gz --directory /usr/local`
  3. [`awk '/(^\/|init)/ { print $1 }' /proc/1/cmdline | tr '\0' ' ' | sed 's/ $//'`](https://github.com/CISOfy/lynis/blob/master/include/tests_boot_services#L74)
  4. Verify output is `/bin/sh`
 
 </details>

<details>
  <summary>Manual output from tests</summary>

  ```
  # OUTPUT=$(awk '/(^\/|init)/ { print $1 }' /proc/1/cmdline | tr '\0' ' ' | sed 's/ $//')
  # echo $OUTPUT
  /bin/sh
  # FILENAME=$(echo "${OUTPUT}" | awk '{print $1}')
  # echo $FILENAME
  /bin/sh
  # ISFILE=$(echo ${FILENAME} | grep "^/")
  # echo $ISFILE
  /bin/sh
  # [ -n "${ISFILE}" ]
  # echo $?
  0
  # [ -L ${ISFILE} ]
  # echo $?
  1
  # [ -f ${ISFILE} ]
  # echo $?
  0
  # FILENAME="${ISFILE}"
  # echo $FILENAME
  /bin/sh
  # [ -n "${FILENAME}" ]
  # echo $?
  0
  # SHORTNAME=$(echo ${FILENAME} | awk -F/ '{ print $NF }')
  # echo $SHORTNAME
  sh
  ```

</details>

**Comment by mboelen** [comment]
Can you upgrade to 3.0.4 and see if this is resolved now with the recent changes?

**Comment by abangser** [comment]
Very nice! Looks good now 🙌 

```
[+] Boot and services
------------------------------------
  - Service Manager                                           [ busybox ]
    - Boot loader                                             [ NONE FOUND ]
```
