### ISSUE TITLE
Unknown OS under Oracle Linux Server

### ISSUE THREAD

**Issue by daplattla** [CISOfy/lynis#1133]
Exception found!

  Function/test:  [OS Detection]
  Message:        Unknown OS found in /etc/os-release - Please create an issue on GitHub and share the the contents (cat /etc/os-release): https://github.com/CISOfy/lynis

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (/usr/bin/lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

  Thanks!

=================================================================

  - Detecting OS...                                           [ DONE ]
  - Checking profiles...                                      [ DONE ]

  ---------------------------------------------------
  Program version:           3.0.3
  Operating system:          Linux
  Operating system name:     Oracle Enterprise Linux
  Operating system version:  Oracle Linux Server release 6.10
  Kernel version:            2.6.32
  Hardware platform:         x86_64
  Hostname:                  linucks-shared
  ---------------------------------------------------
  Profiles:                  /etc/lynis/default.prf
  Log file:                  /var/log/lynis.log
  Report file:               /var/log/lynis-report.dat
  Report version:            1.0
  Plugin directory:          /usr/share/lynis/plugins

[root]# cat /etc/oracle-release
Oracle Linux Server release 6.10

[root]# more /etc/os-release
NAME="Oracle Linux Server"
VERSION="6.10"
ID="ol"
VERSION_ID="6.10"
PRETTY_NAME="Oracle Linux Server 6.10"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:6:10:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 6"
ORACLE_BUGZILLA_PRODUCT_VERSION=6.10
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=6.10

**Comment by mboelen** [comment]
Working on cleaning up older issues. First of all, apologies you never got a timely answer and a "thank you" for reporting this. So, a little late, but thank you! :blush: 

The good part is that Oracle Linux should be detected (not just this version). So closing this issue.
