### ISSUE TITLE
BOOT-5104 does not detect runit init system on Void Linux (No data found in /proc/1/cmdline)

### ISSUE THREAD

**Issue by jhe2** [CISOfy/lynis#1134]
**Describe the bug**

I got this message, when running the latest version of lynis in default configuration:

```
=================================================================

  Exception found!

  Function/test:  [BOOT-5104:002]
  Message:        No data found in /proc/1/cmdline

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (./lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

  Thanks!

=================================================================
```

The problem appears to be caused by a regex in ``include/tests_boot_services``
that filters the content of ``/proc/1/cmdline`` for a slash at the beginning or "init" ( ``/(^\/|init)/`` ),
while ``/proc/1/cmdline`` contains just ``runit``, so the regex won't match anything.

**Version**
 - Void Linux
 - Lynis 3.0.3

**Expected behavior**

Detection of the runit service manager, no exception message.

**Output**
```
  - Service Manager                                           [ UNKNOWN ]
```

**Comment by mboelen** [comment]
Thanks for reporting and the pull request, it has been merged.
