### ISSUE TITLE
Broken Include Directory - When not run from /usr/local/lynis directory

### ISSUE THREAD

**Issue by riaano** [CISOfy/lynis#1144]
**Describe the bug**
An update to lynis broke the include lookup path. The code is missing a break when the file is already found thus it finds the last ./include that was added and overwrites the actual include directory. 

**Version**
 - Distribution [e.g. Centos 7]
 - Lynis version [e.g. 3.0.3]

**Expected behavior**
Expect to still find the include in the master directory /usr/local/lynis and not the directory that you are calling lynis from

**Output**
/usr/local/lynis/lynis --auditor "Auditor" --cronjob --profile /opt/lynis/server-centos.prf --plugindir /opt/lynis/plugins 2>&1
ls: cannot access /opt/lynis/include/consts: No such file or directory
ls: cannot access /opt/lynis/include/consts: No such file or directory
ls: cannot access /opt/lynis/include/consts: No such file or directory
ls: cannot access /opt/lynis/include/consts: No such file or directory
ls: cannot access /opt/lynis/include/consts: No such file or directory
ls: cannot access /opt/lynis/include/functions: No such file or directory
ls: cannot access /opt/lynis/include/functions: No such file or directory
ls: cannot access /opt/lynis/include/functions: No such file or directory
ls: cannot access /opt/lynis/include/functions: No such file or directory
ls: cannot access /opt/lynis/include/functions: No such file or directory

**Additional context**
The code needs a break on Line 92 before the fi close

     79     # Test from which directories we can use all functions and tests
     80     USE_CWD=0
     81     if case "$@" in *--usecwd*) true;; *) false;; esac; then
     82         USE_CWD=1
     83         INCLUDEDIR="./include"
     84     else
     85         INCLUDEDIR=""
     86         tINCLUDE_TARGETS="/usr/local/include/lynis /usr/local/lynis/include /usr/share/lynis/include ./include"  # Default paths to check (CWD as last option, in case we run from standalone)
     87         for I in ${tINCLUDE_TARGETS}; do
     88             if [ "${I}" = "./include" ]; then
     89                 if [ -d "${WORKDIR}/include" ]; then INCLUDEDIR="${WORKDIR}/include"; fi
     90             elif [ -d ${I} -a -z "${INCLUDEDIR}" ]; then
     91                 INCLUDEDIR=${I}
     92             fi
     93         done
     94     fi

**Comment by mboelen** [comment]
Closed due to merging #1145
