### ISSUE TITLE
Unknown OS found in /etc/os-release

### ISSUE THREAD

**Issue by mksipe** [CISOfy/lynis#1148]
`cat /etc/os-release`

> PRETTY_NAME="Parrot OS 4.11"
NAME="Parrot OS"
ID=parrot
ID_LIKE=debian
VERSION="4.11"
VERSION_ID="4.11"
HOME_URL="https://www.parrotsec.org/"
SUPPORT_URL="https://community.parrotsec.org/"
BUG_REPORT_URL="https://community.parrotsec.org/"

`uname -a` 

> Linux parrot 5.10.0-6parrot1-amd64 #1 SMP Debian 5.10.28-6parrot1 (2021-04-12) x86_64 GNU/Linux

**Comment by mksipe** [comment]
You are correct. The issue was the software was outdated. Parrot, by default, hasn't updated the lynis software from 3.0.2, so I manually imported it directly from the source, and it works fine. Sorry for the mishap.

**Comment by mboelen** [comment]
No problem, glad to see it works as expected now.
