### ISSUE TITLE
Unknown OS found - Arch Linux ARM

### ISSUE THREAD

**Issue by Grizaster** [CISOfy/lynis#1159]
**Describe the bug**
=================================================================

  Exception found!

  Function/test:  [OS Detection]
  Message:        Unknown OS found in /etc/os-release - Please create an issue on GitHub and share the the contents (cat /etc/os-release): https://github.com/CISOfy/lynis

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (/usr/local/lynis/lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

  Thanks!

=================================================================

  - Detecting OS...                                           [ DONE ]
  - Checking profiles...                                      [ DONE ]

  ---------------------------------------------------
  Program version:           3.0.5
  Operating system:          Linux
  Operating system name:     Linux
  Operating system version:  5.10.17-1-ARCH
  Kernel version:            5.10.17
  Hardware platform:         armv7l
  Hostname:                  no-hostname
  ---------------------------------------------------
  Profiles:                  /usr/local/lynis/default.prf
  Log file:                  /var/log/lynis.log
  Report file:               /var/log/lynis-report.dat
  Report version:            1.0
  Plugin directory:          /usr/local/lynis/plugins
  ---------------------------------------------------
  Auditor:                   [Not Specified]
  Language:                  en
  Test category:             all
  Test group:                all
  ---------------------------------------------------
...

**Version**
 - Distribution Arch Linux ARM (5.10.17-1-ARCH)
 - Lynis version 3.0.5

**Expected behavior**

**Output**
[cat /etc/os-release]
NAME="Arch Linux ARM"
PRETTY_NAME="Arch Linux ARM"
ID=archarm
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinuxarm.org/"
DOCUMENTATION_URL="https://archlinuxarm.org/wiki"
SUPPORT_URL="https://archlinuxarm.org/forum"
BUG_REPORT_URL="https://github.com/archlinuxarm/PKGBUILDs/issues"

**Additional context**

**Comment by mboelen** [comment]
Are you still running this OS?

Could you check out and see if the changes in pull request https://github.com/CISOfy/lynis/pull/1310 are working?

The pull request can't be merged, but if it works, we can implement it (or better: receive a new pull request).

Will close this issue, as I believe the pull request will resolve it (but needs confirmation) and that we are cleaning up the issue tracker.
