### ISSUE TITLE
AUTH-9308 failed when systemd is used

### ISSUE THREAD

**Issue by pcastellazzi** [CISOfy/lynis#116]
AUTH-9308 is not checking for systemd unit files, marking the test always as failed, even on centos 7 (i am guessing other systems too) when /sbin/sulogin is enabled by default.

Under systemd lynis need to check the presence of /sbin/sulogin on the following files:

* /usr/lib/systemd/system/console-shell.service
* /usr/lib/systemd/system/emergency.service
* /usr/lib/systemd/system/rescue.service

**Comment by mboelen** [comment]
Thanks for reporting. Initial set of changes have been applied to include support for this. Can you test if this works for you?

**Comment by pcastellazzi** [comment]
Thank you very much. I tested it against master and it works correctly on CentOS 7.

**Comment by mboelen** [comment]
Thanks for the confirmation, closing item.
