### ISSUE TITLE
OpenLightSpeed Checks For Webserver Software

### ISSUE THREAD

**Issue by MaximKing1** [CISOfy/lynis#1162]
OpenLightSpeed is a Open Source Webserver like Apache or Ngix, as i saw you do checks for both of them but not OpenLightSpeed which is used a lot now and become quite popular... Would be cool seeing it on here.

**Comment by mboelen** [comment]
Thanks for reporting this. At this moment it looks like there is not much traction on this issue. As we are cleaning up the issue tracker, I will close this issue for now, until there is renewed interest in adding it.
