### ISSUE TITLE
Unknown OS found - Redhat 6

### ISSUE THREAD

**Issue by daniejstriata** [CISOfy/lynis#1163]
Function/test:  [OS Detection]
  Message:        Unknown OS found in /etc/os-release - Please create an issue on GitHub and share the the contents (cat /etc/os-release): https://github.com/CISOfy/lynis
```
NAME="Red Hat Enterprise Linux"
VERSION="6.10"
ID="Redhat"
ID_LIKE="rhel fedora"
VERSION_ID="6"
PLATFORM_ID="platform:el7"
PRETTY_NAME="Red Hat Enterprise Linux 6"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:redhat:6"
HOME_URL="https://redhat.org/"
BUG_REPORT_URL="https://bugs.redhat.org/"
CENTOS_MANTISBT_PROJECT="Redhat-6"
CENTOS_MANTISBT_PROJECT_VERSION="6"
```

**Comment by daniejstriata** [comment]
I wonder why all the servers have this set:
`PLATFORM_ID="platform:el7"`

**Comment by mboelen** [comment]
Not sure about the `PLATFORM_ID`. Created an alias for `RedHat` besides the existing `RHEL`: https://github.com/CISOfy/lynis/commit/43054c0999f6e90f2dfef16228e6a2a147a36e6e
