### ISSUE TITLE
Passwords (no password set)

### ISSUE THREAD

**Issue by ocafebabe** [CISOfy/lynis#1172]
**Is your feature request related to a problem? Please describe.**
AUTH-9283 says that there are accounts without a password.

**Describe the solution you'd like**
A list of the affected user accounts.

**Required changes**
AUTH-9283

**Additional context**
![Screenshot from 2021-06-18 22-19-52](https://user-images.githubusercontent.com/3409735/122628402-d18e7700-d083-11eb-9b75-b1dab4de0b3d.png)

**Comment by mboelen** [comment]
Thanks for reporting. Change has been applied, so with the next release of the web interface this will be displayed.
