### ISSUE TITLE
invalid: EXPKEYSIG 3F873450D48C4F9C

### ISSUE THREAD

**Issue by moerkey** [CISOfy/lynis#1174]
**Describe the bug**
apt-get warns that the key is invalid.

**Version**
 - Ubuntu 18.04
 - Lynis version 3.0.4-100

**Expected behavior**
The key shouldn´t be invalid. apt-get update should run without errors.

**Output**
```
Err:15 https://packages.cisofy.com/community/lynis/deb stable InRelease       
  The following signatures were invalid: EXPKEYSIG 3F873450D48C4F9C CISOfy Software (signed software packages) <software@cisofy.com>
Reading package lists... Done 
W: GPG error: https://packages.cisofy.com/community/lynis/deb stable InRelease: The following signatures were invalid: EXPKEYSIG 3F873450D48C4F9C CISOfy Software (signed software packages) <software@cisofy.com>
E: The repository 'https://packages.cisofy.com/community/lynis/deb stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

```
pub   rsa4096 2016-06-22 [SC] [expires: 2026-06-20]
      C80E 383C 3DE9 F082 E013  91A0 366C 67DE 91CA 5D5F
uid           [ unknown] CISOfy Software (signed software packages) <software@cisofy.com>
sub   rsa4096 2016-06-22 [E] [expires: 2026-06-20]
```

**Additional context**
I already removed and readded the key.

**Comment by ocafebabe** [comment]
I'm experiencing the same issue here:

- Ubuntu 20.04
- Lynis Enterprise 3.0.4-100

**Comment by kecskemethy** [comment]
same here on debian 10, tried to re-download and get an updated key but did not work

```
apt-key adv --keyserver pgp.mit.edu --recv-keys C80E383C3DE9F082E01391A0366C67DE91CA5D5F
Executing: /tmp/apt-key-gpghome.qIMtZ1Sk7E/gpg.1.sh --keyserver pgp.mit.edu --recv-keys C80E383C3DE9F082E01391A0366C67DE91CA5D5F
gpg: key 366C67DE91CA5D5F: "CISOfy Software (signed software packages) <software@cisofy.com>" not changed
```

as well as checked [install docs](https://packages.cisofy.com/community/#debian-ubuntu) if we can get the new key info from there... 

but didn't help any of above...

**Comment by cb3inco** [comment]
Same - Ubuntu based systems.

**Comment by hsinanchen2007** [comment]
Same at MX Linux

**Comment by mboelen** [comment]
We are in the process of deprecating some signing keys and purging old distribution names from the software repository.

The roll-over to a new key has been performed and the repository has been signed with this new key.

- Old key: D48C4F9C
- New key: C2FDE6C4

The following steps are advised:

1. Check that your list file (/etc/apt/sources.listd/cisofy-lynis.list) contains no old distribution like 'xenial'
2. Import the new key `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 013baa07180c50a7101097ef9de922f1c2fde6c4`
3. Run `apt update`

The authoritative source is our [repo](https://packages.cisofy.com/), so consult that page for more details. Let us know if you still encounter issues, then we can add additions to the page if needed.

Apologies for the inconvenience,

Michael

**Comment by kecskemethy** [comment]
Everything is back to normal now. Thank you for the great GPL tool you provide Michael!

**Comment by quantumpacket** [comment]
@mboelen can the repo page and anywhere else be updated with the full fingerprint?

**Comment by mboelen** [comment]
The full fingerprint is displayed when going to "community" then look under Debian. Is that sufficient?
