### ISSUE TITLE
Repo public key unavailable, so Lynis cannot be installed or updated

### ISSUE THREAD

**Issue by jdrch** [CISOfy/lynis#1176]
**Describe the bug**
The Lynis community edition repo's public key is unavailable

**Version**
 - Debian Buster
 - All Lynis versions

**Expected behavior**
`# apt update` should result in no lynis repo errors

**Output**

```
# apt update
Err:17 https://packages.cisofy.com/community/lynis/deb stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9DE922F1C2FDE6C4
```

**Comment by quantumpacket** [comment]
@jdrch  see https://github.com/CISOfy/lynis/issues/1174#issuecomment-865683377 you need to verify and import the new signing key.

**Comment by mboelen** [comment]
The answer of @quantumpacket is correct.

**Comment by jdrch** [comment]
That fixed the problem, thanks!
