### ISSUE TITLE
Unknown OS - Artix Linux

### ISSUE THREAD

**Issue by digitalcheetah** [CISOfy/lynis#1179]
**Describe the bug**
An unknown OS exception is thrown when running on Artix Linux.

**Version**
 - Distribution: Artix Linux
 - Lynis version: 3.0.4

**Expected behavior**
It should be detected.

**Output**
2021-07-01 00:39:08 EOL check: 255
2021-07-01 00:39:08 Note: the end-of-life of 'Artix Linux' could not be checked. Entry missing in software-eol.db?

**Additional context**
From `/etc/os-release`:

NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
LOGO=artixlinux

Artix Linux, like Arch, is a rolling distribution.

**Comment by mboelen** [comment]
Thanks for reporting!

Do you have the chance to add an entry to include/os-detection and become a contributor? :)

**Comment by digitalcheetah** [comment]
Sure. Just made the PR a few minutes ago. :)

**Comment by mboelen** [comment]
Closing now pull request has been merged
