### ISSUE TITLE
Install a PAM module for password strength testing like pam_cracklib or pam_passwdqc [AUTH-9262]

### ISSUE THREAD

**Issue by azman0101** [CISOfy/lynis#118]
Hi,

I'm using pam module pwquality which is enable by default in Ubuntu Wily.

But I get the suggestion AUTH-9262.

Is this normal behavior ?

**Comment by mboelen** [comment]
Thanks for reporting @azman0101, that module seems to be a good alternative.

Can you show the lines used in your configuration (e.g. in your PAM itself) and the name of the pam module? Then we can add it to the test.

**Comment by azman0101** [comment]
this is the line present in the file /etc/pam.d/common-password

```bash
password        requisite                       pam_pwquality.so retry=3
```

**Comment by mboelen** [comment]
Hi @azman0101, can you test if recent change works for you correctly as well?

**Comment by azman0101** [comment]
Hi @mboelen, Perfect ! Thxs
