### ISSUE TITLE
Exception: test has an exceptional event (GetHostID)

### ISSUE THREAD

**Issue by jasonaleski** [CISOfy/lynis#1181]
**Describe the bug**
After upgrading to 3.0.5 on Ubuntu 20.04, the following error is generated  at the top of the display.

Exception found!
Function/test:  [GetHostID]
Message:        Can't create hostid (no MAC addresses found)

[+] Boot and services
------------------------------------
 [WARNING]: Test CORE-1000 had a long execution: 10.317846 seconds

**Version**
 - Distribution Ubuntu 20.04
 - Lynis version 3.0.5

**Expected behavior**
No error

**Output**
2021-07-02 16:12:54 Exception: test has an exceptional event (GetHostID) with text Can't create hostid (no MAC addresses found)
2021-07-02 16:12:59 Exception: test has an exceptional event (GetHostID) with text Can't create HOSTID, command ip not found
2021-07-02 16:13:04 Result: no HOSTID available, trying to use SSH key as unique source

**Additional context**
Have not looked at the code yet, just reporting the bug.

**Comment by jasonaleski** [comment]
This is a VM using VMWare Workstation 15.

**Comment by madindehead** [comment]
Seeing the exact same error on an Ubuntu Server 20.04 VM on Promox. Didn't have this issue with Lynis 3.0.4.

**Comment by mboelen** [comment]
Thanks for reporting.

Changes are already made to fix this. Please see https://github.com/CISOfy/lynis/issues/1183

If you have the chance, test the latest code. Will close this one, but feel free to reply in the other issue with any feedback.
