### ISSUE TITLE
Unknown OS: Nethserver 7.9.2009

### ISSUE THREAD

**Issue by just-some-tall-bloke** [CISOfy/lynis#1182]
**Describe` the bug**
Unknown OS found in /etc/os-release

**Version**
 - Nethserver
 - 7.9.2009

**Contents of /etc/os-release:**

NAME="NethServer"
VERSION="7.9.2009"
VERSION_ID="7"
PRETTY_NAME="NethServer 7.9.2009"
ID="nethserver"
HOME_URL="http://www.nethserver.org"

ID_LIKE="rhel fedora centos"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
BUG_REPORT_URL="https://community.nethserver.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"``

**Comment by mboelen** [comment]
Thanks for sharing!

Do you have the chance to create a pull request and add the OS to include/osdetection and become a contributor? :)

**Comment by just-some-tall-bloke** [comment]
Done :)

https://github.com/CISOfy/lynis/pull/1186

**Comment by mboelen** [comment]
Closing now the related pull request has been merged. Thanks @just-some-tall-bloke !
