### ISSUE TITLE
Rocky Linux - Function/test:  [GetHostID]

### ISSUE THREAD

**Issue by zabbix112** [CISOfy/lynis#1185]
Good day,

Issue is that Rocky running scans.

  ---------------------------------------------------
  Program version:           3.0.5
  Operating system:          Linux
  Operating system name:     Rocky Linux
  Operating system version:  8.4
  Kernel version:            4.18.0
  Hardware platform:         x86_64
  Hostname:                  rockylinux01
  ---------------------------------------------------
[root@rockylinux01 etc]# /bin/lynis update check
status=up-to-date

[root@rockylinux01 etc]# which ifconfig
/sbin/ifconfig

[root@rockylinux01 etc]# which ip
/sbin/ip

[root@rockylinux01 etc]# ip addr | grep ether
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff

net-tools-2.0-0.52.20160912git.el8.x86_64 : Basic networking tools

=================================================================

  Exception found!

  Function/test:  [GetHostID]
  Message:        Can't create hostid (no MAC addresses found)

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (/bin/lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

  Thanks!

=================================================================

=================================================================

  Exception found!

  Function/test:  [GetHostID]
  Message:        Can't create HOSTID, command ip not found

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (/bin/lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

  Thanks!

=================================================================

**Comment by wolfgoe** [comment]
Same error here:
  **Program version:           3.0.5
  Operating system:          Linux
  Operating system name:     Ubuntu
  Operating system version:  20.04
  Kernel version:            5.8.0
  Hardware platform:         x86_64**

=================================================================

  Exception found!

  Function/test:  [GetHostID]
  Message:        Can't create hostid (no MAC addresses found)

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (/usr/sbin/lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

  Thanks!

=================================================================


=================================================================

  Exception found!

  Function/test:  [GetHostID]
  Message:        Can't create HOSTID, command ip not found

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (/usr/sbin/lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

  Thanks!

=================================================================


=================================================================

  Exception found!

  Function/test:  [GetHostID]
  Message:        No unique host identifier could be created.

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (/usr/sbin/lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

  Thanks!

=================================================================

**Comment by mboelen** [comment]
Thanks for reporting. It is the same issue as https://github.com/CISOfy/lynis/issues/1183

Already resolved for the upcoming release.
