### ISSUE TITLE
Redis False Positive

### ISSUE THREAD

**Issue by yupthatguy** [CISOfy/lynis#1187]
**Describe the bug**
Lynis 3.0.5 gives the following warning:

  * Configure the 'requirepass' setting for Redis [DBS-1884] 
    - Details  : /etc/redis/redis.conf
    - Solution : configure 'requirepass' setting in /etc/redis/redis.conf
      https://cisofy.com/lynis/controls/DBS-1884/

When in reality "requirepass" hsa already been configured and is in use by another app 

**Version**
 - Distribution [Debian 10 (buster)]
 - Lynis version [3.0.5]

**Expected behavior**
No warning to appear

**Output**
If applicable, add output that you get from the tool or the related section of lynis.log

**Additional context**
bug present on both test and prod servers

**Comment by mboelen** [comment]
Can you show the lines that you have in your configuration file?

When you say it is in use by another app, what app do you refer to?

**Comment by yupthatguy** [comment]
Sorry, never saw this.. had to a complete new install...
