### ISSUE TITLE
Fatal error: Incorrect ownership or permissions of language file (/opt/lynis/db/languages/en): not found

### ISSUE THREAD

**Issue by Harrison-S1** [CISOfy/lynis#1190]
Hello,

 So downloading the tar.gz file from https://downloads.cisofy.com/lynis/lynis-3.0.5.tar.gz into /opt/
 mv into the lynis folder and run ./lynis --help or ./lynis audit system 
 Getting the following error:

```
root@server:~/lynis# ./lynis audit system
./lynis: 236: SafeFile: not found
./lynis: 661: : Permission denied
./lynis: 662: Fatal error: Incorrect ownership or permissions of language file (/root/lynis/db/languages/en): not found
./lynis: 663: : Permission denied
```
The error also happens on a ansible playbook as root or as a privileged user
Any ideas? 

**Version**
 - 20.04.2
 - Lynis version 3.0.5

**Comment by mboelen** [comment]
Are there by any chance multiple installations on this server?

If not, what do you get if you run `lynis audit system --use-cwd`?

**Comment by mboelen** [comment]
@Harrison-S1 Can you check if you have multiple installations?

**Comment by mboelen** [comment]
Closing issue, did not receive response.

Suggestions:
- Check if there is only one installation
- Check file permissions and ownership of directory and underlying files

**Comment by Harrison-S1** [comment]
Sorry @mboelen  I didn't get a notification you had replied. Yea the problem was lynis was install from the repo as well. Thanks for the reply.

**Comment by mboelen** [comment]
Tip: remove all installations and use the latest version from our [repository](https://packages.cisofy.com/).
