### ISSUE TITLE
Artix not working Calamares

### ISSUE THREAD

**Issue by xlwyx** [CISOfy/lynis#1200]
Hi, everyone..
Artix Linux drowned in the black hole....    We are pleased to see that Artix is reaching the peak of its end. 
I, as a user, advise to go for endeavourOS; at this moment it must be more polished than Arch Linux.
Everyone, Take care-off and good luck..!
Bye bye

**Comment by mboelen** [comment]
Noted, although I'm not sure how this is relevant to Lynis and therefore closing this issue.
