### ISSUE TITLE
Unsported Os - Funtoo

### ISSUE THREAD

**Issue by tczaude** [CISOfy/lynis#1201]
**Describe the bug**

  Exception found!

  Function/test:  [OS Detection]
  Message:        Unknown OS found in /etc/os-release - Please create an issue on GitHub and share the the contents (cat /etc/os-release): https://github.com/CISOfy/lynis

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (./lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

  Thanks!

**Version**
 - Distribution [e.g. Funtoo 1.4]
 - Lynis version [All]

`cat /etc/os-release`

```
ID="funtoo"
NAME="Funtoo"
PRETTY_NAME="Funtoo Linux"
ANSI_COLOR="0;34"
HOME_URL="https://www.funtoo.org"
BUG_REPORT_URL="https://bugs.funtoo.org"
```

**Comment by mboelen** [comment]
Thanks for reporting and thanks to @mrpjl for the pull request to implement this.
