### ISSUE TITLE
Gettting warning message on Parrot os 4.11

### ISSUE THREAD

**Issue by weu07** [CISOfy/lynis#1203]
Started using Parrot OS 4.11 and when running lynis audit system I am getting the following warning message;

Unknown OS found in /etc/os-release - Please create issue on GitHub project page: https://github.com/CISOfy/lynis

Can Parrot OS be added to the checks of operating systems?

**Comment by sebek88** [comment]
@weu07 I have the same issue in Parrot 4.11:
```bash
  Exception found!

  Function/test:  [OS Detection]
  Message:        Unknown OS found in /etc/os-release - Please create issue on GitHub project page: https://github.com/CISOfy/lynis
```
As mentioned above, the problem seems to be in the version that is offered by the OS vendor repos, which is  outdated as shown below:
```bash
#lynis update info

 == Lynis ==

  Version            : 3.0.2
  Status             : Outdated
  Installed version  : 302
  Latest version     : 306
```
Upgrading to [latest version](https://github.com/CISOfy/lynis/releases/tag/3.0.6) solves the problem.

**Comment by mboelen** [comment]
Closing this issue, as support for Parrot is available in newer versions.

```
                        "parrot")
                            LINUX_VERSION="Parrot"
                            OS_NAME="Parrot GNU/Linux"
                            OS_VERSION=$(grep "^VERSION_ID=" /etc/os-release | awk -F= '{print $2}' | tr -d '"')
                            OS_VERSION_FULL=$(grep "^PRETTY_NAME=" /etc/os-release | awk -F= '{print $2}' | tr -d '"')
                        ;;
```
