### ISSUE TITLE
3.0.6 tarball signature is missing

### ISSUE THREAD

**Issue by duck-rh** [CISOfy/lynis#1211]
Quack,

In https://downloads.cisofy.com/lynis/ `lynis-3.0.6.tar.gz.asc` cannot be found.

Regards.
\\_o<

**Comment by mboelen** [comment]
Hi @duck-rh!

Downloads are currently not signed, as we are in the process of migrating a few things, including the signatures.

**Comment by duck-rh** [comment]
@mboelen could you ping me when it's back please, so I can make the Debian package without compromising security?

**Comment by duck-rh** [comment]
@mboelen what's the status of the signing? I don't understand why you closed the ticket since it's not solved. I've been waiting for this to update the package in Debian.

**Comment by mboelen** [comment]
It is disabled for now, so it doesn't change. Most likely in 3.0.7 or 3.0.8 again and then we might sign 3.0.6 as well. It is work in progress in the background to improve the release flow (less steps between releases).

Is it possible to release a Debian package without it for the time being? Yes, I understand things are not signed, but you can check it against the hash for now as an alternative?

**Comment by duck-rh** [comment]
@mboelen thanks a lot.
