### ISSUE TITLE
Some tests incorrectly recognise access rights

### ISSUE THREAD

**Issue by fizista** [CISOfy/lynis#1214]
**Describe the bug**
Some tests incorrectly identify access rights when the target object is a symlink.

The problem is function: IsWorldWritable

**Version**
 - Distribution Ubuntu 20.04
 - Lynis version 3.0.6

**Expected behavior**
Correct recognition of the write right when the target object is a symlink.

**Output**

**Additional context**
We can test the problem in this way:
```
mv /etc/crontab /mnt/crontab
ln -s /mnt/crontab /etc/crontab
lynis audit system 2>&1 | grep SCHD-7704
```

**Comment by mboelen** [comment]
Closed due to merging changes in https://github.com/CISOfy/lynis/pull/1225 - Thanks to @konstruktoid
