### ISSUE TITLE
Determine available network protocols - false negative results

### ISSUE THREAD

**Issue by fizista** [CISOfy/lynis#1219]
**Describe the bug**
Lynis returns the suggestion:
"Determine if protocol 'rds' is really needed on this system [NETW-3200]"

There is an entry in the file:
`install rds    /bin/true`

The test returns a false negative because there are several "redundant" spaces between the word rds and /bin/true.

Correct command to search for entries:
`grep --files-with-matches --no-messages "^install \+rds \+/bin/true" /etc/modprobe.d/*`

**Version**
 - Distribution Ubuntu 20.04
 - Lynis version 3.0.6

**Expected behavior**
Search for entries with any number of spaces between words.

**Output**

**Additional context**

**Comment by mboelen** [comment]
Thanks for reporting and thanks to @konstruktoid for the fix. Change has been implemented and will be part of next release.
