### ISSUE TITLE
Apt-get not recognised as a package audit tool on minimal installs

### ISSUE THREAD

**Issue by rhyven** [CISOfy/lynis#122]
Hi guys, not sure if this is intentional but thought I'd check.

Running Debian 8.2 here, on a minimal installation.  I get a fail on PKGS-7398.

PKGS-7398 (Check for package audit tool) relies on PKGS-7392 to set `PACKAGE_AUDIT_TOOL="apt-get"` and `PACKAGE_AUDIT_TOOL_FOUND=1`

However, 7392 won't detect apt-get if:

1. update-notifier isn't installed (Line 885), AND
2. all apt-get packages are up-to-date (Line 914)

Specifically, the command `apt-get --dry-run --show-upgraded upgrade 2> /dev/null | grep '-security' | grep "^Inst"^C` will return null if all updates are already installed.

**Comment by mboelen** [comment]
With your patch it works correctly now, right?

**Comment by rhyven** [comment]
Sure does!  Thanks!  :)
