### ISSUE TITLE
HasCorrectFilePermissions - information on the difference in access rights should be clearer

### ISSUE THREAD

**Issue by fizista** [CISOfy/lynis#1220]
**Is your feature request related to a problem? Please describe.**
We currently have this message:

`Outcome: permissions of file /xxx are not matching expected value (640 != rw-------)`

It would be more readable if access rights were in one and the same form.

**Describe the solution you'd like**
It should look like this:

`Outcome: permissions of file /xxx are not matching expected value (rw-r----- != rw-------)`

**Required changes**
`lynis/include/functions ->  HasCorrectFilePermissions()`

**Additional context**

**Comment by mboelen** [comment]
Closed after implementing the pull request by @konstruktoid 

Thanks for reporting and the fix!
