### ISSUE TITLE
Suggestions for hardening system services

### ISSUE THREAD

**Issue by zaaurus** [CISOfy/lynis#1221]
I'd like Lynis to let me know what parameters to add/change in systemd services to harden them. It frustrates me that developers don't harden their services by default, so I need to spend a lot of time configuring and testing each service in the systemd.

Perhaps Lynis should scan each systemd service and suggest individual parameters to harden each service. Something like: Add `PrivateTmp=yes` to blabla.service etc.

**Comment by zaaurus** [comment]
No doubt it's a lot of work, but just imagine how much time was saved thanks to lynis.

**Comment by mboelen** [comment]
Great idea, but as @konstruktoid also shared it is an enormous amount of work. Also, consider the things that can break. Now with PrivateTmp that is typically having a low risk, but there are others that won't work on all systems or differ between Linux distributions. The best person to give advice about a systemd service file is the developer or the packager. They know what paths are typically used and what special permissions are needed.

Thanks again for the idea. For now, I will have to close this issue, as it is too hard to implement correctly.
