### ISSUE TITLE
Expand hardening features

### ISSUE THREAD

**Issue by zaaurus** [CISOfy/lynis#1224]
I came across this guide to hardening. It has some great tips on quenching, and I think we should add them to Lynis.

https://madaidans-insecurities.github.io/guides/linux-hardening.html

**Comment by konstruktoid** [comment]
Hi @zaaurus and thanks for sharing.
It's a good guide with a lot of interesting topics and suggestions.
Many of them are duplicates, but in order to prioritize, are there any specific suggestions you think are the most relevant for you point-of-view?

**Comment by zaaurus** [comment]
Hello @konstruktoid. Thank you for your response.

It's hard for me to prioritize because there's so much in the manual and it's all important.

**Comment by vk6xebec** [comment]
maybe include this in a future v4?
 +1 vote

**Comment by mboelen** [comment]
The document definitely has interesting items. However, this issue itself is (unfortunately) not actionable enough as @konstruktoid pointed out as well. We need to prioritize things and preferably have 1 item per issue or pull request.

If one is interested in any of the suggestions in this document, I suggest creating individual issues, or better, a pull request. Will close this issue for now.
