### ISSUE TITLE
debian/changelog is severly outdated, breaks our toolchain

### ISSUE THREAD

**Issue by lusitania** [CISOfy/lynis#123]
Top-most entry in tag 2.1.1 says

```
lynis (1.6.3-3) utopic; urgency=low
  * Release 1.6.3
 -- Michael Boelen <michael.boelen@cisofy.com>  Fri, 24 Oct 2014 10:58:23 +0200
```

whereas CHANGELOG correctly mentions `2.1.1 (2015-07-22)` to be the "current" version.

Implications: Automated Jenkins jobs relying on `dpkg-parsechangelog` fail. For Debian packages `CHANGELOG` is irrelevant. Only `debian/changelog` counts.

No idea how I can work around this for the current release without reinventing the wheel. Please take special care to not "break" debian/* files.

**Comment by mboelen** [comment]
The Debian part (debian/*) is currently not in use by the project, but will soon be updated for package building. As we want to learn about your integration (and determine how we will do package building), can you share how you rely on the project?

**Comment by lusitania** [comment]
We intend to build and use the most current release of Lynis to compare its recommendations against our workflow. dpkg is our primary release tool for which we've build an easy-to-use tool-chain.

**Comment by lusitania** [comment]
I suppose I have to rephrase my original text. I completely fail to build the package using git-buildpackage, even on master.

```
~ $ git clone https://github.com/CISOfy/lynis.git
~ $ cd lynis/
~/lynis $ git-buildpackage
dh_testdir
dh_testroot
rm -f build-stamp
dh_clean
gbp:info: lynis_1.6.3.orig.tar.gz does not exist, creating from 'upstream/1.6.3'
fatal: Not a valid object name upstream/1.6.3
```

https://cisofy.com/documentation/lynis mentions building rpm packages but says nothing about deb. What have you been using in the past to build your releases?

**Comment by mboelen** [comment]
Thanks for the clarification. The debian tree was never used to build Debian packages, as those are tilll now maintained by package builders (e.g. for Debian and Ubuntu). We are now making a shift with the project to fully control the package building process ourselves. No ETA for that yet though.

**Comment by mboelen** [comment]
Some initial changes have been made to the debian/* files. Work on this will be continued with the upcoming package building. Closing this issue, thanks for bringing it up and giving input.
