### ISSUE TITLE
Lynis does not detect/find arch-audit on Garuda Linux as an installed package audit tool

### ISSUE THREAD

**Issue by AkechiShiro** [CISOfy/lynis#1230]
**Describe the bug**
[`arch-audit`](https://gitlab.com/ilpianista/arch-audit) is a software used for package auditing under ArchLinux however Lynis does not detect it during scan.

**Version**
 - Distribution Garuda Linux (ArchLinux) 5.14.18-hardened kernel
 - Lynis version 3.0.7

**Expected behavior**
Checking package audit tool should be `[ FOUND ]` instead of `[ NONE ]`.

Should I try to make a PR fixing this bug if so what would be a good start point beside reading the Contributing Guidelines ?

**Comment by AkechiShiro** [comment]
I found that there is already a test that does exist, but it needs to be launched when the OS_FULLNAME contains probably `Garuda Linux`.

**Comment by AkechiShiro** [comment]
I have sent a PR in order to try and fix the problem #1231, if someone could review it and tell me if any change is needed in order to merge it with main.

**Comment by mboelen** [comment]
PR implemented, thanks for your contribution!
