### ISSUE TITLE
Missing PAM_FILES_LOCATIONS for aarch64

### ISSUE THREAD

**Issue by zwack-am** [CISOfy/lynis#1234]
**Describe the bug**
Even if cracklib is installed you are warned that it is missing

**Version**
 - Distribution Kali Rolling
 - Lynis version 3.0.7

**Expected behavior**
Correctly identify the existence of the pam_cracklib

**Output**
  * Install a PAM module for password strength testing like pam_cracklib or pam_passwdqc [AUTH-9262] 
      https://cisofy.com/lynis/controls/AUTH-9262

**Additional context**
The following entry in include/tests_authentication fixes this problem.

    PAM_FILE_LOCATIONS="${ROOTDIR}lib/arm-linux-gnueabihf/security ${ROOTDIR}lib/i386-linux-gnu/security ${ROOTDIR}lib/security ${ROOTDIR}lib/x86_64-linux-gnu/security ${ROOTDIR}lib64/security ${ROOTDIR}usr/lib /usr/lib/security ${ROOTDIR}usr/lib/aarch64-linux-gnu/security"

**Comment by mboelen** [comment]
Thanks to your code contribution, it will be fixed in the next release. Cheers!
