### ISSUE TITLE
LYNIS This release is more than 4 months old warning

### ISSUE THREAD

**Issue by mbtreetime** [CISOfy/lynis#1237]
**Version**
 - Ubuntu 18.04
 - Lynis version 3.0.6-100
 
**Expected behavior**
If packages are not going to be released more often than every 4 months then a warning about out of date version is a pain, since we are updating via package manager.

It would be nice to have either:
- a new package at least every 4 months
- a configuration option to ignore the update test

**Comment by mboelen** [comment]
Thanks for sharing. The new release is coming in the upcoming day(s).

**Comment by d4t4king** [comment]
This is untested, but presumably one could skip the check by adding `skip-test=LYNIS` to your custom.prf.  HOWEVER, you really shouldn't skip this check.

I totally agree with the OP that the check should be longer than 4 months if a newer version is not available in that time.

What the check _**should**_ do is alert when a new version is available and the local version is not the new version.  This should be adapted to how the tool is installed.  Gaps between source updates and distro package maintainers could potentially cause improper reporting. 

So if lynis is installed by apt (for example), there should be a way to: 
  a) demark apt as the install method, 
  b) periodically (or when run) check how old the installed package is and
  c) check if a new apt package is available that would update the version on the local filesystem.

At a minimum, I would expect the check to be compatible with apt, yum and git as install sources.

**Comment by stnert** [comment]
@d4t4king  I tried to put in "skip-test=" and it didn't work. Everything points to a fix for this in the next release.

**Comment by stnert** [comment]
Current OS: Fedora Workstation 35

**Comment by mboelen** [comment]
It took a bit longer, but the new version is available now. We are changing a few things in the build process and that delayed this release.

**Comment by mbtreetime** [comment]
> This is untested, but presumably one could skip the check by adding `skip-test=LYNIS` to your custom.prf. HOWEVER, you really shouldn't skip this check.

It's not actually a test it's just a hard coded value into the main lynis script file
https://github.com/CISOfy/lynis/commit/ad5dc53a5f01674bf2c89072dd65a33555c51ff1#diff-75b1644706ce4f6d34253ccc47cd3ac5860a2a1b7d9fa47e9aa31e0dad286615

https://github.com/CISOfy/lynis/blob/master/lynis#L799
