### ISSUE TITLE
No Online Documentation: AUTH-9229

### ISSUE THREAD

**Issue by d4t4king** [CISOfy/lynis#1242]
**Describe the bug**
The online documentation for AUTH-9229 ( https://cisofy.com/lynis/controls/AUTH-9229/) doesn't exist.  This i a pretty old check, IIRC.  It should have documentation.

**Version**
 - Distribution [e.g. Ubuntu 18.04]
 Raspian 10 (Buster)
 - Lynis version [e.g. 2.7.0]
 3.0.7

**Expected behavior**
Clarifying documentation should exist for this check online.

**Output**
If applicable, add output that you get from the tool or the related section of lynis.log
Clarifying documentation should exist for this check online.

**Additional context**

**Comment by mboelen** [comment]
Thanks for reporting. This is a known issue and will be resolved in a different way with upcoming Lynis releases. For that reason, I will close this issue without a related change.
