### ISSUE TITLE
No online documentation for BOOT-5264

### ISSUE THREAD

**Issue by d4t4king** [CISOfy/lynis#1243]
**Describe the bug**
Online documentation for BOOT-5624 does not exist.

**Version**
 - Distribution [e.g. Ubuntu 18.04]
 Raspobian 10 (Buster)
 - Lynis version [e.g. 2.7.0]
 3.0.7

**Expected behavior**
Clarifying online documentation for this check should exist.

**Output**
If applicable, add output that you get from the tool or the related section of lynis.log
Clarifying online documentation for this check should exist.

**Additional context**

**Comment by mboelen** [comment]
Thanks for reporting. This is a known issue and will be resolved in a different way with upcoming Lynis releases. For that reason, I will close this issue without a related change.
