### ISSUE TITLE
Improve symlink permission checks

### ISSUE THREAD

**Issue by incitem** [CISOfy/lynis#1245]
**Bug / behaviour / output**

For symlinks, the Lynis check `FILE-7524` should not test the permissions on the symlink itself, but the permissions of the target, because only the target's permission ultimately matters for access.

```
# Test: FILE-7524
2020-06-14 10:01:11 Test: checking file/directory /etc/motd
2020-06-14 10:01:11 Test: checking if file /etc/motd has the permissions set to 644 or more restrictive
2020-06-14 10:01:11 Outcome: permissions of file /etc/motd are not matching expected value (777 != rw-r--r--)

# why 777? because it's a symlink
$ ls -la /etc/motd
lrwxrwxrwx. 1 root root 25 Dec 17 23:21 /etc/motd -> /var/lib/update-motd/motd

# but it's actually 644!
$ ls -la /var/lib/update-motd/motd
-rw-r--r--. 1 root root 121 Jun 14 09:02 /var/lib/update-motd/motd
```

Mind though that this could be different for BSD-like systems. I think on those systems you can put actual permissions on symlinks (differing from the target) -- not sure though!

**Expected behavior**
Make the target's permissions count and not the symlink permissions.

**Comment by konstruktoid** [comment]
See https://github.com/CISOfy/lynis/pull/1225

**Comment by incitem** [comment]
Thanks @konstruktoid that looks good :-)

**Comment by mboelen** [comment]
Closed due to merging changes in https://github.com/CISOfy/lynis/pull/1225 - Thanks to @konstruktoid
