### ISSUE TITLE
signing key documentation for 3.0.7?

### ISSUE THREAD

**Issue by rfrohl** [CISOfy/lynis#1257]
The documentation for the signing key seems to be not up to date:

https://cisofy.com/documentation/lynis/ -> 4. Verification - Signature

talks about '0x429A566FD5B79251' the release for 3.0.7 is signed by '0x9DE922F1C2FDE6C4'.

 Maybe this is related to #1211

**Version**

 - Lynis  3.0.7 signature [0] and source [1]  

**Expected behavior**

documentation on which key to use and where to find it.

**Additional context**

```
$ wget https://downloads.cisofy.com/lynis/lynis-3.0.7.tar.gz.asc
[..]
$ wget  https://downloads.cisofy.com/lynis/lynis-3.0.7.tar.gz
[..]
$ gpg --verify lynis-3.0.7.tar.gz.asc lynis-3.0.7.tar.gz  
gpg: Signature made Di 18 Jan 2022 14:33:39 CET
gpg:                using RSA key 0x9DE922F1C2FDE6C4
gpg: Can't check signature: No public key
```

```
$ wget https://cisofy.com/files/cisofy-software.pub
[..]
$ gpg cisofy-software.pub                                                                                                                      
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa4096/0x429A566FD5B79251 2014-11-04 [SC] [expires: 2030-10-31]
      Key fingerprint = 73AC 9FC5 5848 E977 024D  1A61 429A 566F D5B7 9251
uid                             CISOfy (Software Signing Key) <security@cisofy.com>
sub   rsa4096/0x0F7E8B616E8847E1 2014-11-04 [E] [expires: 2030-10-31]
```

[0] https://downloads.cisofy.com/lynis/lynis-3.0.7.tar.gz.asc
[1] https://downloads.cisofy.com/lynis/lynis-3.0.7.tar.gz

**Comment by mboelen** [comment]
Yes, it is related. Please have a look at https://packages.cisofy.com/ for the public key. The documentation on the website is scheduled for updates.
