### ISSUE TITLE
DNS on Mac

### ISSUE THREAD

**Issue by cristianrz** [CISOfy/lynis#1258]
**Describe the bug**

Seems that Lynis examines `/etc/resolv.conf` for DNS hosts, but on Mac this file states the  following

```bash
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
```

**Version**
 - Distribution: Mac
 - Lynis version: 3.0.6

**Expected behavior**

For it to check `scutil --dns` when on Mac.

**Output**

Says it couldn't find two responsive DNS servers.

**Comment by mboelen** [comment]
Thanks for reporting. Can you show me some example output that you get to see? This way we can alter the test and properly test as well.

**Comment by cristianrz** [comment]
unfortunately I no longer own a Mac, hopefully somebody else that has one can test it :/

**Comment by mboelen** [comment]
Closing this issue for now, until the next person experiences the same and can share output or a pull request to improve upon this.
