### ISSUE TITLE
FILE-7524 test does not handle sym link target file permissions

### ISSUE THREAD

**Issue by bshamanov** [CISOfy/lynis#1266]
**Describe the bug**
I have my file etc/issue and etc/issue.net as sym links pointing to 
lrwxrwxrwx. 1 0 0 16 Nov 25 09:36 /etc/issue -> ../usr/lib/issue
lrwxrwxrwx. 1 0 0 20 Nov 25 09:36 /etc/issue.net -> ../usr/lib/issue.net

This triggers
    File: /etc/issue                                          [ SUGGESTION ]
    File: /etc/issue.net                                      [ SUGGESTION ]

Which cannot be fixed as symlinks don't have permissions. To make this worse, I cannot turn off specific file test, I have to turn of the entire FILE-7524 to avoid suggestions.

Looking at the logs we can see: 2022-02-06 22:20:01 Outcome: permissions of file /etc/issue are not matching expected value (777 != rw-r--r--)

While the actual file permissions are 644 as the test wants them to be:
-rw-r--r--. 1 0 0 377 Feb  2 23:30 /usr/lib/issue
-rw-r--r--. 1 0 0 377 Feb  2 23:28 /usr/lib/issue.net

**Version**
 - Distribution Fedora Linux 35 (Workstation Edition)
 - Lynis version 3.0.7

**Expected behavior**
I expect the target file of the sym link to be taken into account for permission checks

**Additional context**
I checked the source as well and according to my modest scripting knowledge there is not sym link handling to be seen

**Comment by mboelen** [comment]
Thanks for reporting. It is actually similar to issue https://github.com/CISOfy/lynis/issues/1245 and recently fixed. The next release will include this fix.
