### ISSUE TITLE
Unknown OS found - Koozali

### ISSUE THREAD

**Issue by mab974** [CISOfy/lynis#1274]
**Describe the bug**
'Koozali Sme Serve'r is unknown is lynis...

I have prepared a Pull request.

>>>>>>>>>> lynis result <<<<<<<<<<
  Exception found!
  Function/test:  [OS Detection]
  Message:        Unknown OS found in /etc/os-release - Please create an issue on GitHub and share the the contents (cat /etc/os-release): https://github.com/CISOfy/lynis
  Help improving the Lynis community with your feedback!

  Program version:           3.0.7
  Operating system:          Linux
  Operating system name:     Linux
  Operating system version:  3.10.0-1160.59.1.el7.x86_64
  Kernel version:            3.10.0
  Hardware platform:         x86_64

>>>>>>>> /etc/os-release <<<<<<<<<
NAME="Koozali SME Server"
VERSION="10.0"
ID="koozali"
ID_LIKE="rhel fedora centos"
VERSION_ID="10.0"
PRETTY_NAME="Koozali SME Server 10.0"
ANSI_COLOR="0;31"
HOME_URL="https://koozali.org"
BUG_REPORT_URL="https://bugs.koozali.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by mboelen** [comment]
Closing issue now that PR #1284 has been implemented.
