### ISSUE TITLE
Feature Request - More useful output with --cronjob

### ISSUE THREAD

**Issue by rhyven** [CISOfy/lynis#128]
I'm using a cron entry to run Lynis on my servers daily.

With `./lynis --cronjob`, the lack of formatting makes the output difficult to read in email:

> - debsums utility [ FOUND ]
> - Cron job for debsums [ FOUND ]
> - Checking security repository in sources.list file [ OK ]
> - Checking vulnerable packages [ WARNING ]

The WARNING above tends to get lost in the screed of text.

With `./lynis --cronjob -q`, the **only** output is:

> - Checking vulnerable packages [ WARNING ]

This isn't enough information for me.  In this current setup, I also get a red [ FOUND ] for a compiler, a [ NOT FOUND ] for SELinux/AppArmor/grsecurity, a [ NOT ACTIVE ] for host-based firewall... there's quite a lot that's missing.

I think there are a couple options here:
 - HTML emailing.  Probably high-effort with low returns, especially with the Lynis Enterprise Portal.
 - More granular output filtering.  Instead of just quiet mode, perhaps an option that will exclude all "[ OK ]" results.  (note I've tried to do this with grepz, but it returns strange results - see below) 
 - Perhaps the Lynis Portal could generate alerts for cronjob-executed uploads?

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

I'm trying to just use `./lynis -c -Q | grep -v '[ OK ]'`, but that doesn't respond with anything helpful:
```

root@xyz:/usr/local/lynis/lynis-master# ./lynis -c -Q | grep -v '\[ OK \]'


################################################################################

################################################################################

------------------------------------


------------------------------------

------------------------------------

```

**Comment by d4t4king** [comment]
FWIW, you're probably better off parsing/mailing one of the log files, rather than the output of the script itself.

Given the variability of the script's output, grepping for a simple string can be ambiguous, at best.  For example, grepping for `[ FOUND ]` would be good for the presence of a malware scanner; bad for the presence of a compiler.  

I also suspect (though I could be wrong) that your grep is seeing the color output as literal; meaning that it's seeing the code that causes the terminal to print in color.  Using the `--no-colors` options provides more sane (albeit still slightly ambiguous) results:  
`./lynis -c -Q --no-colors | grep -v "\[ OK \]"`

YMMV.

**Comment by rhyven** [comment]
The variability of the output was exactly why I decided to just exclude "OK", instead of any other option.  At least that increases the SNR.  :)

And you were right - Grep was choking on the colour codes.  That being the case, I wonder if I could tell grep to exclude any line including "green".

Thanks for your help

**Comment by mboelen** [comment]
The --cronjob option is programmed with the logic to display at less as possible. Only warnings will show up, as those could be a trigger to take an action (e.g. new vulnerable packages found).

Tips: if you would like to know the warnings/suggestions, it is better to parse the report file. When you still want the output in a cronjob, then run it in normal mode (lynis audit system -Q).

**Comment by rhyven** [comment]
Um... two things:

1)  PR #134 has actually resolved this for me -- I have a cronjob that greps for [*], and emails me the results.  All fine.

2)  This:

> The --cronjob option is programmed with the logic to display at less as possible. Only warnings will show up, as those could be a trigger to take an action (e.g. new vulnerable packages found).

That doesn't seem to be the case?  I still get heaps of output with --cronjob:

```
[+] Printers and Spools
------------------------------------
- Checking cups daemon [ NOT FOUND ]
- Checking lp daemon [ NOT RUNNING ]

[+] Software: e-mail and messaging
------------------------------------
- Checking Exim status [ NOT FOUND ]
- Checking Postfix status [ NOT FOUND ]
- Checking Dovecot status [ NOT FOUND ]
- Checking Qmail status [ NOT FOUND ]
- Checking Sendmail status [ NOT FOUND ]

[+] Software: firewalls
------------------------------------
- Checking iptables kernel module [ FOUND ]
- Checking host based firewall [ ACTIVE ]
```

I don't think *any* of those are warnings?  Is this working correctly?

**Comment by mboelen** [comment]
Sorry about that. Indeed, it does show normal output (without markup). Normally it is often used with the -q option to reduce this output, except the serious issues.

**Comment by rhyven** [comment]
Aha, that makes more sense.  :-D  Thanks!
