### ISSUE TITLE
Check if reboot is needed                                 [YES]  - Slackware Current 

### ISSUE THREAD

**Issue by stnert** [CISOfy/lynis#1281]
**Describe the bug**

**Version**
 Operating system name:  Slackware Linux
  Operating system version:  15.0+

 - Lynis version: 3.0.7

**Expected behavior**

**Output**
If applicable, add output that you get from the tool or the related section of lynis.log

**Additional context**

Check if reboot is needed                                 [YES]

**Comment by konstruktoid** [comment]
Hi @stnert, could you elaborate on this? What's the actual issue?
