### ISSUE TITLE
busybox support

### ISSUE THREAD

**Issue by vanhauser-thc** [CISOfy/lynis#1282]
**Is your feature request related to a problem? Please describe.**
most embedded systems are minimal installations that deploy busybox. as lynis expects standard gnu bash, ps, grep etc. this fails on all those targets.

**Describe the solution you'd like**
support busybox installations.

**Required changes**
detect if /bin/sh is busybox, and then switch to a different mode as bash features are mostly not supported, ps output is different (and is missing most command line parameters), grep is also missing several options that lynis is using

**Comment by alangonzalez** [comment]
Posted my current code to lynis fork on my personal github `alangonzalez/lynis`

It's working pretty good now, but going through tests one by one. Currently at the name services test and working through as I can. I use the testing.prf as my profile. It's got some plugins not enabled.

tests that have some level of verification - with modifications.  The others are running, just not clear on if it's truthful.
- Initialization
- Os detection
- System tools
- Boot and services
- Kernel
- Memory and Processes
- User, Groups, and Auth
- Shells
- File Systems
- USB Devices
- Storage - maybe
- SSH - sorta (didn't check SSHD, added dropbear)
- 

This version should run without obvious errors, behind the scenes it's a lot of line by line validation it's checking correctly. So I wouldn't use for report outs yet!

**Comment by mboelen** [comment]
Hi @alangonzalez - Thanks for your work in this area, much appreciated!

To prevent that we receive one big pull request later on (which is really hard to review and with the risk of introducing conflicts), can you split your changes up in small pull requests? In the upcoming days/week we will be reviewing, merging, and releasing a new version.

**Comment by agonzalez-plume** [comment]
@mboelen sure. Would this be too much for one commit? 

lynis, osdetection, binaries,functions? 

Could break it up more too.

After that I can do single tests or something.

**Comment by mboelen** [comment]
Normally it is better to break it up per file, so that the chance of conflicts is minimal. Feel free to submit and we review along the way. Thanks!

**Comment by mboelen** [comment]
Multiple changes have been merged, so things should be working better now in the next release. Thanks all for the suggestions and pull requests.

If some things still don't work in relation to busybox, let it know (preferably in a new issue).
