### ISSUE TITLE
Checks are missing manpage / expected/actual notes

### ISSUE THREAD

**Issue by stdedos** [CISOfy/lynis#1287]
**Describe the bug**

Some checks (e.g. https://cisofy.com/lynis/controls/FILE-7524/, https://cisofy.com/lynis/controls/HOME-9304/) do not have a solid manpage, or what does the software think that things should look like

**Version**
 - Distribution [e.g. Ubuntu 18.04] Ubuntu 20.04.4 LTS
 - Lynis version [e.g. 2.7.0] [ Lynis 3.0.8 ]

**Expected behavior**
All checks have a manpage and expected/actual notes

**Output**
If applicable, add output that you get from the tool or the related section of lynis.log

**Additional context**

**Comment by nodiscc** [comment]
- HOME-9306: Check if users own their home directories
- HOME-9304: Check if users' home directories permissions are 750 or more restrictive

**Comment by mboelen** [comment]
Thanks for reporting. Suggestions with (missing) links will be soon replaced by an alternative. As we are cleaning up the issues, I will close this one for now.
