### ISSUE TITLE
xargs -i is nonstandard

### ISSUE THREAD

**Issue by gwollman** [CISOfy/lynis#1300]
`include/tests_databases` invokes `xargs` with the nonstandard `-i`(lower-case `i`) flag, resulting in an error message to stderr. It should use the standard `-I` (upper-case `I`) flag, which requires an argument instead (but might need logic to deal with nonstandard `xargs` implementations). The GNU `xargs` manual page claims that `-I{}` does what the nonstandard `-i` flag did.  I can confirm that this eliminates the error message, but not that it is doing the expected thing.

**Version**
- 8d9cdb22f413f2b2c941ae4750ca40411ce8a194 (tagged 3.0.8)
- FreeBSD 12.3

**Expected behavior**
`xargs` should be invoked with valid command-line arguments so it does not write a diagnostic and exit with an error status.

**Output**
```
xargs: invalid option -- i
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements] [-S replsize]]
             [-J replstr] [-L number] [-n number [-x]] [-P maxprocs]
             [-s size] [utility [argument ...]]
```

**Additional context**

**Comment by xnoguer** [comment]
@gwollman Can you test pull request #1396  ?  I can't get my hands on a FreeBSD machine.
