### ISSUE TITLE
LOGG-2154 - Consider Wazuh to satisfy requirement

### ISSUE THREAD

**Issue by zbalkan** [CISOfy/lynis#1316]
**Is your feature request related to a problem? Please describe.**
[Wazuh](https://wazuh.com/) is a SIEM and XDR solution, that is a fork of OSSEC. It is actively developed and supported. It is agent based and the internals are based on central log collection, filtering, enrichment and processing of log data. Wazuh agent pushes [syslog](https://github.com/wazuh/wazuh/blob/master/etc/ossec-agent.conf#L139) by default. Therefore, `wazuh-agent` should be able to satisfy remote logging capabilities.

**Describe the solution you'd like**
Include wazuh-agent in the accepted remote logging utilities in test LOGG-2154

**Required changes**
[Logging tests need a new check](https://github.com/CISOfy/lynis/blob/master/include/tests_logging)

**Additional context**
Wazuh is an open source solution that helps PCI-DSS compliance with built-in capabilities. Logging is one of them.

**Comment by mboelen** [comment]
Thanks, related PR has been merged and will be available in the next release.
