### ISSUE TITLE
SSH-7408 Atomic Checks?

### ISSUE THREAD

**Issue by d4t4king** [CISOfy/lynis#132]
Would it not be better to break this out into atomic checks so that certain aspects of the config can be accepted (or not).  Maybe, implement a "sub-check" feature/capability, e.g. SSH-7408.1, SSH-7408.2, etc.?

**Comment by mboelen** [comment]
To reduce repetition, we are actually merging more tests. The benefit is shorter code, which becomes easier to extend. One possibility is that we allow these sub-checks, but then it would be better to this by name: SSH-7408.permitrootlogin

Will keep this item open and discuss it with others. Thanks for pointing out.

**Comment by mboelen** [comment]
Exactly, it should be possible to allow ignoring a partial piece of the test. That's why I consider this might be workable: if a test has sub-checks, each of the sub-checks can be individually disabled.

For example: If you do SSH-7408, the whole test is skipped. If you use SSH-7408.permitrootlogin, just the particular item will be skipped and the rest of the test is still performed.

**Comment by rhyven** [comment]
*cough*USB storage*cough*

I'm in exactly the same scenario with test STRG-1840.  I want to be reminded to disable the driver loading, but I don't much care about deauthorizing devices -- especially on a virtual machine.

@mboelen a name-type sub

**Comment by mboelen** [comment]
Initial steps have been made to allow this functionality. The function to allow skipping atomic tests is named SkipAtomicTest and has been applied to SSH-7408. For STRG-1840 it is no longer applicable, as that test was already been skipped.

You can test it by adding skip-test=SSH-7408:port to your custom profile. Please note that you no longer have to edit your default.prf, but can create a custom.prf in the same directory.

Would be great if both @d4t4king and @rhyven can test to see if it works for you.

**Comment by rhyven** [comment]
It works!  Beautiful  :)

**Comment by rhyven** [comment]
Added PR #169, to display when an atomic test is skipped.

Side-note, the atomic testing idea is excellent, but it will need more structure if we extend it to the rest of the codebase.  Otherwise we'll end up with spaghetti.  :)

**Comment by mboelen** [comment]
Closing issue, after confirmation that it works.
