### ISSUE TITLE
Exception found for nextcloud-snap redis.conf

### ISSUE THREAD

**Issue by keinhen** [CISOfy/lynis#1327]
**Describe the bug**

Ran lynis on a [nextcloud-snap](https://github.com/nextcloud-snap/nextcloud-snap) server, and got an exception after scanning the Databases portion that instructed me to post here.

>   Exception found!
>
>  Function/test:  [DBS-1882]
> Message:        Found Redis, but no configuration file. Report this if you know where it is located on your system.

I'm not super familiar with redis, but ran `locate` to see where `redis.conf` might be and got this:

`$ locate redis.conf`
`/snap/nextcloud/31033/config/redis/redis.conf`
`/snap/nextcloud/31222/config/redis/redis.conf`

I guess it's just a bit of a non-standard location for lynis where nextcloud-snap wants to store its configs. Hope it helps!

**Versions**
Ubuntu 20.04.4 LTS
Lynis 3.0.8
Nextcloud-snap 24.0.3snap1

**Comment by konstruktoid** [comment]
Hi @keinhen, can you please test https://github.com/CISOfy/lynis/pull/1328?

**Comment by keinhen** [comment]
> Hi @keinhen, can you please test #1328?

Hi, sure! 

Unfortunately the issue seems to persist even with these changes. 

I'll add my steps to test and my lynis.log if it helps, as I'm not 100% if I'm applying your fix correctly. I checked the file (include/tests_datahase) with the latest commit and it had the SNAP addition, so it should be good as far as I can tell.

**Steps to test**

> $ git clone https://github.com/konstruktoid/lynis.git
> $ cd lynis
> $ git checkout fc62b39f34b32f5d31502578f4f9a78b494b331d
> $ sudo chown -R root:root ../lynis
> $ sudo ./lynis audit syste

[lynis.log](https://github.com/CISOfy/lynis/files/9410748/lynis.log)

**Comment by konstruktoid** [comment]
It works, but I didn't remove the actual file name. Will fix.

```sh
2022-08-23 23:18:47 Action: scanning directory (/snap/nextcloud/31222/config/redis/redis.conf) for Redis configuration files
2022-08-23 23:18:47 Result: no configuration files found in this directory
2022-08-23 23:18:47 Action: scanning directory (/snap/nextcloud/31033/config/redis/redis.conf) for Redis configuration files
2022-08-23 23:18:47 Result: no configuration files found in this directory
```

**Comment by keinhen** [comment]
Ok, I was just going off of the terminal output having the same exception message as earlier. Happy to hear if it did the trick in the logs!

**Comment by konstruktoid** [comment]
Updated the PR to strip `redis.conf` from the path.

**Comment by keinhen** [comment]
Redid previous steps with the latest PR, seems to have fixed the issue! 

No exceptions reported, and it accurately reports warnings and suggestions on the currently used redis.conf file(s).

I'll mark this as closed, thanks a bunch!

**Comment by mboelen** [comment]
Change has been applied to the project as well now. Thanks both
