### ISSUE TITLE
 /sbin/lynis: 612: [: -lt: unexpected operator

### ISSUE THREAD

**Issue by fizista** [CISOfy/lynis#1329]
**Describe the bug**
When I run a command:
`lynis audit system --cronjob --profile /etc/lynis/custom.prf`

The following error occurs:
`/sbin/lynis: 612: [: -lt: unexpected operator`

**Version**
 - Distribution Ubuntu 22.04
 - Lynis version  3.0.8-100 from https://packages.cisofy.com/community/lynis/deb stable/main

**Comment by mboelen** [comment]
What if you just run `lynis audit system`? Does it then show the same error?

**Comment by fizista** [comment]
Yes, the problem still occurs when I launch:  `lynis audit system > /dev/null`

**Comment by mboelen** [comment]
I made a change with commit https://github.com/CISOfy/lynis/commit/73d43c25eb290e8879a590c8534202bcd400caeb

Can you check (using git) if that resolved it?

**Comment by fizista** [comment]
Bug fixed.

**Comment by mboelen** [comment]
Great, closing this issue then.
