### ISSUE TITLE
Nobara is unknown.

### ISSUE THREAD

**Issue by c0dezer019** [CISOfy/lynis#1334]
**Describe the bug**

**Version**
 - Distribution Nobara 36 (Fedora spinoff)
 - Lynis version 3.0.8

**Expected behavior**
Nobara to be recognized as a valid OS.

**Output**
From release-os:
NAME="Nobara Linux"
VERSION="36 (Thirty Six)"
ID=nobara
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Nobara Linux 36 (Thirty Six)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=nobara-logo-icon
CPE_NAME="cpe:/o:nobaraproject:nobara:36"
HOME_URL="https://www.nobaraproject.org/"
DOCUMENTATION_URL="https://www.nobaraproject.org/"
SUPPORT_URL="https://www.nobaraproject.org/"
BUG_REPORT_URL=""
REDHAT_BUGZILLA_PRODUCT="Nobara"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Nobara"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL=""
VARIANT_ID=workstation

**Additional context**

**Comment by NL-TCH** [comment]
i gotchu man, better late then never
