### ISSUE TITLE
Cannot open the latest release of Lynis on Ubuntu 18.04

### ISSUE THREAD

**Issue by StewAlexander-com** [CISOfy/lynis#1339]
Cannot open  Lynis on my Ubuntu 18.04 kvm on ProxMox

Getting this error:
----
```
support@ntopng ~/lynis> ./lynis                                                                                
./lynis: 206: .: Can't open /usr/share/lynis/include/consts
```

I installed it previously via apt, could this be interfering?

**Yeah that is the problem**, please add language to the readme if not already there (and somehow I missed it) that if you have the previous lynis installed by apt to remove it before installing the latest version from Git --- as the projects step on eachother, thanks

**Comment by mboelen** [comment]
Yes, it is. The best way is to use one source.

Tip: If your Lynis package from the default repository is too old, consider switching to the [offical software repository](https://packages.cisofy.com/) and pull in the package from there.
