### ISSUE TITLE
RHEL Community Repository GPG Check Failed

### ISSUE THREAD

**Issue by PhilG** [CISOfy/lynis#1342]
**Describe the bug**
Attempting to install Lynis on a fresh installation of Almalinux 9 according to the instructions on the page of the community repository fails with `Error: GPG check FAILED`.

**Version**
 - Distribution Almalinux 9 (RHEL)
 - Lynis version 3.0.8

**Expected behavior**
Installation should succeed, I've verified that the key at the repo URL is indeed the one in the RPM database.

**Output**
Running `rpm -Kv lynis-3.0.8-100.noarch.rpm` on the now locally cached package produces this output
```
lynis-3.0.8-100.noarch.rpm:
    Header V3 RSA/SHA1 Signature, key ID 0acf951b: BAD
    Header SHA1 digest: OK
    V3 RSA/SHA1 Signature, key ID 0acf951b: BAD
    MD5 digest: OK
```

**Comment by slauger** [comment]
It seems that EL9 removed the support for SHA1 signatures of RPM packages.

```
Error: Execution of '/bin/dnf -d 0 -e 1 -y install lynis' returned 1: warning: Signature not supported. Hash algorithm SHA1 not available.
warning: Signature not supported. Hash algorithm SHA1 not available.
Problem opening package lynis-3.0.8-100.noarch.rpm
Error: GPG check FAILED
Error: /Stage[main]/Lynis/Package[lynis]/ensure: change from 'purged' to 'present' failed: Execution of '/bin/dnf -d 0 -e 1 -y install lynis' returned 1: warning: Signature not supported. Hash algorithm SHA1 not available.
warning: Signature not supported. Hash algorithm SHA1 not available.
Problem opening package lynis-3.0.8-100.noarch.rpm
Error: GPG check FAILED
```

The package signing should be updated to a newer and supported mechanism.

**Comment by BeatBastic** [comment]
> "Per the warning/error above, DNF on RHEL 9 refuses to install the package. DNF is told to check signatures (DNF configuration gpgcheck=1) but the package signature hash algorithm is SHA-1. RPM is forbidden to even check it on the system-level crypto layer." ([Source redhat.com](https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9))

The official packages for RHEL & Fedora are signed with SHA-256 which could be used for Lynis as well. According to the NIST the SHA-1 algorithm should be migrated asap because there are security concerns & vulnerabilities. ([Source nist.gov](https://www.nist.gov/news-events/news/2022/12/nist-retires-sha-1-cryptographic-algorithm))

The problem should affect other RHEL versions with FIPS enabled ([Source redhat.com](https://access.redhat.com/solutions/473613)) or RHEL 8 with crypto policy `FUTURE` as well.

### Workarounds

For evaluation and testing you could use the following workarounds which will decrease security level:

```bash
# W1: Disable GPG check for install
sudo dnf --nogpgcheck install lynis

# W2: Allow SHA-1 in crypto policy for install
sudo update-crypto-policies --set DEFAULT:SHA1
sudo dnf install lynis
sudo update-crypto-policies --set DEFAULT
```

**Comment by lisenet** [comment]
+1, as I've just hit this issue after migrating to Rocky Linux 9.

```
[root@rocky9 ~]# yum install lynis
Last metadata expiration check: 0:00:08 ago on Wed 12 Jul 2023 15:12:23 BST.
Dependencies resolved.
==============================================================================================================================================================================================================================================
 Package                                                 Architecture                                             Version                                                       Repository                                               Size
==============================================================================================================================================================================================================================================
Installing:
 lynis                                                   noarch                                                   3.0.8-100                                                     lynis                                                   330 k

Transaction Summary
==============================================================================================================================================================================================================================================
Install  1 Package

Total download size: 330 k
Installed size: 1.7 M
Is this ok [y/N]: y
Downloading Packages:
lynis-3.0.8-100.noarch.rpm                                                                                                                                                                                    1.3 MB/s | 330 kB     00:00    
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                                         1.3 MB/s | 330 kB     00:00     
CISOfy Software - Lynis package                                                                                                                                                                               8.1 kB/s | 1.0 kB     00:00    
Importing GPG key 0x0ACF951B:
 Userid     : "CISOfy Software RPMs (signed software packages) <software-rpms@cisofy.com>"
 Fingerprint: 9146 CE61 DD17 4FB3 02C9 90A9 8246 12E2 0ACF 951B
 From       : https://packages.cisofy.com/keys/cisofy-software-rpms-public.key
Is this ok [y/N]: y
Key imported successfully
warning: Signature not supported. Hash algorithm SHA1 not available.
warning: Signature not supported. Hash algorithm SHA1 not available.
Import of key(s) didn't help, wrong key(s)?
Problem opening package lynis-3.0.8-100.noarch.rpm. Failing package is: lynis-3.0.8-100.noarch
 GPG Keys are configured as: https://packages.cisofy.com/keys/cisofy-software-rpms-public.key
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Error: GPG check FAILED
```

**Comment by RZR7332** [comment]
I have also just hit this, can the repository signing be updated from SHA-1 as a proper fix?

According to Red Hat, this will also become the default from Fedora 39: https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9

**Comment by mboelen** [comment]
Today we released a new version, including a switch of the key and switch to SHA512 (Header V3 RSA/SHA512 Signature).

It was signed with SHA1 (and a different key) because of backward compatibility with older RHEL systems. As of today, older systems may not be able to use the repository.

Can one of you confirm that the repository is working correctly (again)?

**Comment by RZR7332** [comment]
Hi Michael,

In my case, this was a fresh installation on RHEL (Lynis had never been present as far as I can tell). Is the key still https://packages.cisofy.com/keys/cisofy-software-rpms-public.key as per the setup documentation? 

It is not working for me, but perhaps I am not the best use case here.

**Comment by mboelen** [comment]
A few minutes ago we updated that part. See the [main page]([https://packages.cisofy.com/) for the details. Although we will keep that URL for backward compatibility, it is advised to use the updated path.

Can you check and see if it works now?

**Comment by RZR7332** [comment]
I removed the key from my system, and ran through the process again:

CISOfy Software - Lynis package                                                                                                                                                                                                 6.8 kB/s | 5.2 kB     00:00    
Importing GPG key 0x12576482:
 Userid     : "CISOfy software signing <software@cisofy.com>"
 Fingerprint: 84FA A998 3B24 AEF2 4D6C 87F1 FEBB 7D18 1257 6482
 From       : https://packages.cisofy.com/keys/cisofy-software-rpms-public.key
Is this ok [y/N]: y
warning: Signature not supported. Hash algorithm SHA1 not available.
Key import failed (code 2). Failing package is: lynis-3.0.9-100.noarch
 GPG Keys are configured as: https://packages.cisofy.com/keys/cisofy-software-rpms-public.key
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED

It is entirely possible that I am doing something wrong, or missing something here.

**Comment by mboelen** [comment]
Please show me your configuration (the repo file that you created). It looks like the path to the key is still old.

**Comment by RZR7332** [comment]
Working off the documentation on site:

[lynis]
name=CISOfy Software - Lynis package
baseurl=https://packages.cisofy.com/community/lynis/rpm/
enabled=1
gpgkey=https://packages.cisofy.com/keys/cisofy-software-public.key
gpgcheck=1
priority=2

**Comment by mboelen** [comment]
Change the 'gpgkey' line: `gpgkey=https://packages.cisofy.com/keys/cisofy-software-public.key` ([source](https://packages.cisofy.com/community/#centos-rhel))

Then run the `dnf clean packages`

Then do another update.

What output does that give you?

**Comment by RZR7332** [comment]
Apologies Michael, at this point I don't know if it's just me being stupid. The line in my original file and the line in the documentation you linked to are identical (https://packages.cisofy.com/community/#centos-rhel). I removed the file for the repository completely, recreated it using the text in the block from your source, cleaned the packages, ran again - same result, same output:

CISOfy Software - Lynis package                                                                                                                                                                                                 6.4 kB/s | 5.2 kB     00:00    
Importing GPG key 0x12576482:
 Userid     : "CISOfy software signing <software@cisofy.com>"
 Fingerprint: 84FA A998 3B24 AEF2 4D6C 87F1 FEBB 7D18 1257 6482
 From       : https://packages.cisofy.com/keys/cisofy-software-public.key
Is this ok [y/N]: y
warning: Signature not supported. Hash algorithm SHA1 not available.
Key import failed (code 2). Failing package is: lynis-3.0.9-100.noarch
 GPG Keys are configured as: https://packages.cisofy.com/keys/cisofy-software-public.key
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED

There are currently only three keys on the system: two Red Hat, one Fedora.

**Comment by mboelen** [comment]
The URL to the public key is good now.

And no you aren't stupid. I was... For some reason a part of the repository was still signed with the old key. Apparently the software to maintain the repository isn't the smartest either, so it did not give any warning at all.

A few updates have been made. It seems to work now. So the real question: is it now working for you as well?

Thanks for your patience

**Comment by RZR7332** [comment]
Not at all, thank you for your patience with me - its not easy troubleshooting with a random person somewhere in the world.

Assuming no changes to the repository file were needed... I ran into a new issue temporarily (complaining about checksum mismatches etc.). After removing the repository again and recreating - it throws the same error.

Maybe it takes a bit of time for updates to propagate?

**Comment by mboelen** [comment]
Did you also perform the clean action?

`dnf clean packages`

`dnf update`

Then `dnf install lynis`

**Comment by RZR7332** [comment]
I did yes, just ran through those steps again with the same result.

Will leave it for now and give it another shot in the morning; if there is anything else I should try, or anything specific you would like me to test, pop it here and I shall provide some feedback in a few hours.

Thank you for your patience, I appreciate it.

**Comment by mboelen** [comment]
Not sure if it is caching or something, as it is working here correctly after the changes made to the repository.

What I did for testing: I removed the package, disabled repo, dnf update, dnf clean all, enable repo, dnf search lynis, dnf install lynis. Only the question regarding the GPG acceptance was not there, most likely as it was stored in the local keyring.

What you also can try:
Display all keys available to rpm: `rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'`
Remove the key for CISOfy repository: `rpm --erase --allmatches gpg-pubkey-XYZ` (replace XYZ with the relevant ID)

Then install again and it should pull in the right key.

**Comment by mboelen** [comment]
Might be good to include the latest output after the steps above. Maybe it gives an additional hint.

**Comment by RZR7332** [comment]
[lynis-rhel.txt](https://github.com/CISOfy/lynis/files/12259087/lynis-rhel.txt)

I have attached terminal output of the process, I followed your steps accordingly. Key is not present on the system, nor will the system accept it. I'm out of ideas at this point, cannot understand why it is not working for me.

It might be best to get input from someone else as well, it might be a user/system issue in all honesty.

**Comment by mboelen** [comment]
I can reproduce it now on another system. So I will do some more troubleshooting on my end.

FYI, GPG in combination with RPM has a wonderful array of options that you can set. And some of the settings are as cryptic as the software itself ;-)

**Comment by RZR7332** [comment]
I am more used to Debia/Ubuntu GPG keyrings rather than the RPM way, so I did some reading last night to see if it wasn't maybe getting stuck somewhere... and I did in fact find the key when I first started. After removing it, no joy.

I don't want to say that I am happy that you can reproduce it - but that does make me feel a little less like I am the problem ;) happy to assist with testing where I can, almost anything is on the cards as long as I don't brick the server.

Thanks again for taking the time and making the effort to look at this.

**Comment by mboelen** [comment]
It looks like I found the cause. Even after adjusting several flags/options, things changed in the signature, but not in the digest. The part where it is complaining about.

We will be doing a migration to a new build system and then additional testing. At least we know now what to look at and most likely the underlying cause. To be continued...

**Comment by RZR7332** [comment]
Thanks again Michael - will leave system as is for now. Let me know if you need any further testing from my side, happy to help where I can.

**Comment by mboelen** [comment]
So in the last few days, we did the following:

- Install new build system
- Migrate everything
- Replaced software components for building the repositories
- Migrated keys
- Switched back the key for RPM-based systems, due to several bugs within rpm (e.g. issues with subkeys)
- Build the RPM for Lynis 3.0.9 again to resolve the hash issue (SHA1)
- Sign the package
- Test all scripts
- Updated the page to reflect the switch back to the previous key (0ACF951B, with public key linked)

So please update your repo file, so that the right public key is used: https://packages.cisofy.com/keys/cisofy-software-rpms-public.key), then test again to see if the update comes in.

Thanks for your patience.

**Comment by RZR7332** [comment]
I can confirm after the changes - installation succeeds after updating the repo file to point to the new key. Thank you for your time and effort on this, much appreciated!
