### ISSUE TITLE
Ubuntu - pam_cracklib; pam_passwdqc no longer available

### ISSUE THREAD

**Issue by vk6xebec** [CISOfy/lynis#1354]
**Describe the bug**
pam_cracklib; pam_passwdqc and apt-listbugs are no longer available on Ubuntu. 

**Version**
 - Distribution: Ubuntu 22.10
 - Lynis version: 3.0.7+

**Expected behavior**
The check does not throw up an suggestion or error

**Output**
Please disable this check on Ubuntu, or maybe suggest an alternative if there is one

**Context**
  * Install a PAM module for password strength testing like pam_cracklib or pam_passwdqc [AUTH-9262] 
      https://cisofy.com/lynis/controls/AUTH-9262/

Note that this is also applicable for
  * Install apt-listbugs to display a list of critical bugs prior to each APT installation. [DEB-0810] 
      https://cisofy.com/lynis/controls/DEB-0810/

**Comment by vk6xebec** [comment]
Found the package. Please change the script to refer to the following package instead: libpam-passwdqc

**Comment by xnoguer** [comment]
@vk6xebec Can you try this pull request ?
https://github.com/CISOfy/lynis/pull/1389

**Comment by mboelen** [comment]
Merged PR by @xnoguer , will be part of next release.
