### ISSUE TITLE
include/tests_php does not work with latest PHP versions v8x

### ISSUE THREAD

**Issue by vk6xebec** [CISOfy/lynis#1360]
**Describe the bug**
tests_php does not check for the presence of PHP v8x. Current version is 8.2

**Version**
 - Distribution: Ubuntu 22.10
 - Lynis version: 3.0.8

**Expected behavior**
PHP tests to search for and run version 8x of PHP

Works only up to 7.4 which is EOL and a security risk.

**Comment by xnoguer** [comment]
I proposed a pull request to fix this issue. Comments welcomed.
#1381

**Comment by Elnadrion** [comment]
@mboelen hello, could you please have a look on this PR?

**Comment by xnoguer** [comment]
@mboelen This was fixed by #1381 . Can you close this issue?

**Comment by mboelen** [comment]
Thanks, will close.
