### ISSUE TITLE
[FILE-6344] Invalid check on the kernel version

### ISSUE THREAD

**Issue by pyllyukko** [CISOfy/lynis#1367]
**Describe the bug**
There's a bug in the check for prerequirements where the kernel version is checked:

```bash
        LINUX_KERNEL_MAJOR=$(echo $OS_KERNELVERSION | ${AWKBINARY} -F. '{print $1}')
        LINUX_KERNEL_MINOR=$(echo $OS_KERNELVERSION | ${AWKBINARY} -F. '{print $2}')
        if [ -n "${LINUX_KERNEL_MAJOR}" -a -n "${LINUX_KERNEL_MINOR}" ]; then
            if [ ${LINUX_KERNEL_MAJOR} -ge 3 -a ${LINUX_KERNEL_MINOR} -ge 3 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
```

It should check that the kernel is newer than 3.3, but the test is written as such, that all minor versions below 3 will fail this test, even though the major version would be > 3. E.g. 4.[012], 5.[012] etc.

**Version**
 - Lynis version 3.0.8

**Expected behavior**
E.g. Linux kernel version 6.0.0 would fulfil the prerequirements.

**Output**
Prerequirements are not met if kernel's minor version is below 3.

**Comment by xnoguer** [comment]
@pyllyukko Could you please try this pull request?
https://github.com/CISOfy/lynis/pull/1388

**Comment by pyllyukko** [comment]
> @pyllyukko Could you please try this pull request?

Yes, it fixes this issue. Thanks.
