### ISSUE TITLE
Appimage format file :)

### ISSUE THREAD

**Issue by newyorkthink** [CISOfy/lynis#1369]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. How would it help you to make things easier? Ex. I'm always frustrated when [...]

**Describe the solution you'd like**

**Required changes**
What needs to be changed in Lynis?

**Additional context**
Add anything else that you consider to be relevant about the feature request here.

**Comment by mboelen** [comment]
Right now Lynis is offered in DEB, RPM, tar, and can be cloned via Git. Adding a new format is therefore currently not a high-priority thing.

Closing this issue as it contains no additional context or rationale to add AppImage format.
