### ISSUE TITLE
AUTH-9308 (and maybe others) in Arch

### ISSUE THREAD

**Issue by pfabreu** [CISOfy/lynis#1380]
**Describe the bug**
AUTH-9308 checks for systemd in /lib/systemd/system and in Arch they are in /usr/lib/systemd/system. Notice that I have only caught it for this specific rule it may happen in other systemd related rules, which is the reason I am starting this as an issue and not just doing a PR.

**Version**
 - Archlinux 6.1.19
 - Lynis version 3.0.8

**Expected behavior**
The rule should pass, my rescue.service is correct and contains:
```
ExecStart=-/usr/lib/systemd/systemd-sulogin-shell rescue
```

**Output**
No password set for single mode [AUTH-9308]

**Comment by xnoguer** [comment]
@pedro-abreu 
By looking at the code this issue appears to be related to 1338. Could you please try pull request 1386?
https://github.com/CISOfy/lynis/pull/1386
