### ISSUE TITLE
broken root detection

### ISSUE THREAD

**Issue by XenGi** [CISOfy/lynis#1383]
**Describe the bug**

When I run lynis without root privileges, instead of giving an informative error message it just gives out this a permission denied error.

**Version**

 - Distribution: Arch Linux
 - Lynis version: 3.0.8

**Expected behavior**

A clear and concise error message, telling the user to run the program as root.

**Output**

```
$ lynis
/usr/bin/lynis: line 206: /usr/share/lynis/include/consts: Permission denied
```

**Comment by xnoguer** [comment]
@XenGi ¿Can you post here the permissions and ownership for your /usr/share/lynis/include/consts file ?

**Comment by XenGi** [comment]
```
$ ls -la /usr/share/lynis/include/consts                                                                             
-rw-r----- 1 root root 11029 2022-05-21 22:13:01 /usr/share/lynis/include/consts
```

**Comment by xnoguer** [comment]
@XenGi I added a pull request that fixes the problem with the message:
https://github.com/CISOfy/lynis/pull/1385

About the file permissions in the Archlinux package, it seems to be a problem with file permissions in the tarball that is downloaded from the CISOfy site:
https://downloads.cisofy.com/lynis/lynis-3.0.8.tar.gz
Up to version 3.0.6 the file permissions seem to be ok, but something seems to have happened with versions 3.0.7 and 3.0.8 that left those files with 640 permissions. I assume that only Michael Boelen or someone else at CISOfy can change that.

**Comment by mboelen** [comment]
Are the file permissions still wrong in the tarball with recent changes?

**Comment by xnoguer** [comment]
> Are the file permissions still wrong in the tarball with recent changes?

No. Permissions now look fine in the last versions, 3.1.0 and 3.1.1.
Thanks!

**Comment by mboelen** [comment]
Closing this issue then. No other change at the moment, besides that we did before (updating it in our build process) :+1:
