### ISSUE TITLE
FreeBSD has changed PostgreSQL `data` directory

### ISSUE THREAD

**Issue by gwollman** [CISOfy/lynis#1397]
**Describe the bug**
The FreeBSD packaging now installs PostgreSQL with versioned `data` directories, so `/usr/local/pgsql/data` (in `include/tests_databases`) no longer matches where the cluster configuration files are actually located. Furthermore, FreeBSD has long allowed the administrator to override the default directory using the `postgresql_data` rc variable.

**Version**
 - FreeBSD 12.4 with `postgresql14-server` 14.6_1 installed
 - Lynis 3.0.8 with #1396 applied

**Expected behavior**
Lynis should look for the configuration files in `/usr/local/pgsql/data14` (or appropriate other versioned directory, `data12`, `data13`, `data15`, ...

**Output**

**Additional context**
Lynis should use `sysrc` to find whether a different data directory is configured. Something like
```sh
sysrc -nq postgresql_data || echo /usr/local/pgsql/data[[:digit:]][[:digit:]]
```
works on my system, at the cost of potential confusion if old data directories have been left on the server after a binary upgrade. To actually determine the specific active data directory would require not only checking `postgresql_data` but also identifying the version of the server package that is installed (if a packaged server is installed) and then looking for just that version's data directory -- but this seems like a waste of effort.

**Comment by xnoguer** [comment]
@gwollman Can you try pull request #1398 ?
I didn't use sysrc though, because it seems to work only for FreeBSD.

**Comment by gwollman** [comment]
After merging the two patches it does at least find the default data directory now, although at the cost of potentially not finding the data directory if the system administrator has configured it to be in a different location. Certainly an improvement on the previous condition.

**Comment by gwollman** [comment]
If you always use `sysrc -nq foobar || echo default` like in my example above, you can safely do something like the following:
```sh
if HasData "${SYSRCBINARY}"; then
  SYSRC="${SYSRCBINARY} -nq"
else
  SYSRC="false"
fi
```

**Comment by xnoguer** [comment]
@gwollman I can't merge that change into master, I don't know whether Michael Boelen will accept to define a binary that only exists for FreeBSD. But if this PR gets merged into master I'll be sure to mention this to Michael.

**Comment by mboelen** [comment]
Thanks for the comments and @xnoguer for the pull request.

If it can be implemented and tested properly, I am OK with a more reliable detection by using sysrc.
