### ISSUE TITLE
SC3028 (warning): In POSIX sh, _ is undefined.

### ISSUE THREAD

**Issue by wileyhy** [CISOfy/lynis#1412]
**Describe the bug**
Hi, I ran shellcheck on lynis; here is one of the warnings:

** # `shellcheck -S warning "$(command -v lynis)" | head | cat -n`

>      2	In /usr/bin/lynis line 28:
>      3	        test "$_" != "/usr/xpg4/bin/sh" && test -f /usr/xpg4/bin/sh && exec /usr/xpg4/bin/sh "$0" "$@"
>      4	              ^-- SC3028 (warning): In POSIX sh, _ is undefined.
> 

** # `vim "$(command -v lynis)"`

>   25     # In Solaris /bin/sh is not POSIX, but /usr/xpg4/bin/sh is.
>   26     # Switch to /usr/xpg4/bin/sh if it exists and we are not already running it.
>   27     if [ "$(uname)" = "SunOS" ]; then
>   28         test "$_" != "/usr/xpg4/bin/sh" && test -f /usr/xpg4/bin/sh && exec /usr/xpg4/bin/sh "$0" "$@"
>   29     fi
> 

**Expected behavior**
No warnings.

**Output**
An altered version, for debugging purposes, otherwise on Fedora the affected code doesn't execute:

>   25     # In Solaris /bin/sh is not POSIX, but /usr/xpg4/bin/sh is.
>   26     # Switch to /usr/xpg4/bin/sh if it exists and we are not already running it.
>   27     set -Cuxfav # <>
>   28       # <>
>   29     if [ "$(echo "SunOS")" = "SunOS" ]; then
>   30         test "$_" != "/usr/xpg4/bin/sh" && test -f /usr/xpg4/bin/sh && exec /usr/xpg4/bin/sh "$0" "$@"
>   31     fi
>   32       # <>
>   33     exit 101 # <>
> 

Xtrace output:

** # `/usr/bin/lynis_debug`

>       # <>
>     if [ "$(echo "SunOS")" = "SunOS" ]; then
>         test "$_" != "/usr/xpg4/bin/sh" && test -f /usr/xpg4/bin/sh && exec /usr/xpg4/bin/sh "$0" "$@"
>     fi
> ++ echo SunOS
> + '[' SunOS = SunOS ']'
> + test ']' '!=' /usr/xpg4/bin/sh
> + test -f /usr/xpg4/bin/sh
>       # <>
>     exit 101 # <>
> + exit 101
> 

**Version**
 - Fedora 38
 - Lynis version 3.0.8

**Additional context**
Perhaps I've missed a reference, but I don't see underscore as having been defined in POSIX-2017, Solaris 9 sh or in SunOS sh. 
  https://pubs.opengroup.org/onlinepubs/9699919799/
  https://www.shrubbery.net/solaris9ab/SUNWaman/hman1/sh.1.html
  https://www.unix.com/man-page/sunos/1/sh/

Sven Mascheck's `whatshell.sh` could be useful here, although it doesn't catch the cases of fish and csh. ...or `rc` the Plan 9 shell, if anybody still uses that in production environments.
  https://www.in-ulm.de/~mascheck/various/whatshell/

It appears that "$_" expands in an unexpected way also on...

1.   zsh 5.9 from zsh-5.9-5.fc38.x86_64.rpm
2.   csh & tcsh from tcsh-6.24.10-1.fc38.x86_64.rpm
3.   ksh93 Version AJM 93u+m/1.0.4 2022-10-22 

** # `ksh --version`

>     version         sh (AT&T Research) 93u+m/1.0.4 2022-10-22
> 

  

Cheers

**Comment by mboelen** [comment]
Thanks for reporting. This is a known issue or edge case. For that reason, the code is limited to just SunOS. For now we won't make changes to it. As the usage of SunOS is going down, I believe the support for SunOS will be removed one day.
