### ISSUE TITLE
tests_file_integrity: line 304: SKIPREASON: unbound variable

### ISSUE THREAD

**Issue by wileyhy** [CISOfy/lynis#1415]
**Describe the bug**
When executing `lynis audit system --profile /home/liveuser/OTHERSPROJECTS/lynis/developer.prf` as suggested in 'CONTRIBUTING.md,' this bug halts the program. `set -u` in enabled automatically in  "Strict mode."

** # `vim /usr/bin/lynis`
>  587     ParseProfiles
>  588 
>  589     # Define if we keep working in strict mode (development)
>  590     if [ ${SET_STRICT} -eq 0 ]; then
>  591         set +u  # Allow uninitialized variables
>  592     else
>  593         set -u  # Do not allow uninitialized variables
>  594     fi
> 

**Version**
 - Distribution: Fedora 38

 - Lynis version:
** # `lynis --version`

> egrep: warning: egrep is obsolescent; using grep -E
> egrep: warning: egrep is obsolescent; using grep -E
> 3.0.8
> 

**Expected behavior**
I expected for 'developer mode' to function minimally by the program completing its execution process as usual.

**Output**

> [DEBUG] Performing test ID FINT-4338 (osqueryd syscheck daemon running)
>     - osquery daemon (syscheck)                               [ NOT FOUND ]
> /usr/share/lynis/include/tests_file_integrity: line 304: SKIPREASON: unbound variable
> 

**Additional context**
Similar bugs: #1413 , #1414  and #1333 .

**Comment by wileyhy** [comment]
[lynis-bug-1415-unified-diff.txt](https://github.com/CISOfy/lynis/files/11850185/lynis-bug-1415-unified-diff.txt)

**Comment by mboelen** [comment]
Should be fixed (next release) with recent changes.
