### ISSUE TITLE
MALW-3280 producing a "pgrep" error

### ISSUE THREAD

**Issue by elatov** [CISOfy/lynis#1420]
**Describe the bug**
I was getting the following error thrown when I ran `lynis audit system`:

```
[+] Software: Malware
------------------------------------
- Checking Rootkit Hunter [ FOUND ]
pgrep: pattern that searches for process name longer than 15 characters will result in zero matches
Try `pgrep -f' option to match against the complete command line.
- Checking ClamAV scanner [ FOUND ]
- Checking ClamAV daemon [ FOUND ]
- Checking freshclam [ FOUND ]
- Malware software components [ FOUND ]
- Active agent [ FOUND ]
- Rootkit scanner [ FOUND ]
```

I tracked it down to the `MALW-3280` test when it searches for `avast`:

```
# pgrep com.avast.daemon
pgrep: pattern that searches for process name longer than 15 characters will result in zero matches
Try `pgrep -f' option to match against the complete command line.
```

Passing in `-f` helped out:

```
# pgrep -f com.avast.daemon
# echo $?
1
```

**Version**
 - Distribution: Debian 12
 - Lynis version: 3.0.8

**Expected behavior**
No errors are shown during execution

**Output**
If applicable, add output that you get from the tool or the related section of lynis.log

**Additional context**
passing `--full` to the `IsRunning` function fixed the issue:

```
 # Avast (macOS)
        LogText "Test: checking process com.avast.daemon"
        if IsRunning "com.avast.daemon" "--full"; then
            FOUND=1
            AVAST_DAEMON_RUNNING=1
```

**Comment by mboelen** [comment]
Thanks for reporting.

Fixed with commit https://github.com/CISOfy/lynis/commit/0d77a367c59a0b5f1bdcb46380a518519160503b
