### ISSUE TITLE
Amazon Linux 2 EOL checks failing

### ISSUE THREAD

**Issue by dinesh** [CISOfy/lynis#1421]
**Describe the bug**

It seems lynis has marked AL2 EOL as June 06, 2023, but according to AWS [Faqs](https://aws.amazon.com/amazon-linux-2/faqs/) it's extended till 2025.  Can we adjust the EOL date accordingly ?

> Q. When will support for Amazon Linux 2 end?

> Amazon Linux 2 end of support date (End of Life, or EOL) has been extended by two years from 2023-06-30 to 2025-06-30 to provide customers with ample time to migrate to the next version.

Also on https://endoflife.date/amazon-linux, the EOL is marked till 2025.

**Version**
 - Distribution [e.g. Ubuntu 18.04]
```
 Program version:           3.0.8[0m
[0;32m    amazon-ebs:   Operating system:          Linux[0m
[0;32m    amazon-ebs:   Operating system name:     Amazon Linux[0m
[0;32m    amazon-ebs:   Operating system version:  2[0m
[0;32m    amazon-ebs:   End-of-life:               [1;31mYES[0m[0m
[0;32m    amazon-ebs:   Kernel version:            5.10.184[0m
[0;32m    amazon-ebs:   Hardware platform:         x86_64[0m
```
 - Lynis version [e.g. 3.0.8]

**Expected behavior**

**Output**
If applicable, add output that you get from the tool or the related section of lynis.log

**Additional context**

**Comment by samueloph** [comment]
Fix at https://github.com/CISOfy/lynis/pull/1425

I'm from the Amazon Linux team and we're also fixing this in the lynis package provided by the official repos.

**Comment by mboelen** [comment]
Change implemented. Will be part of next release.
