### ISSUE TITLE
yum fails to install lynis from repo due to key change

### ISSUE THREAD

**Issue by afunix** [CISOfy/lynis#1427]
**Describe the bug**
After a recent key rotation for RPM , Yum on CentOS 7 fails to install lynis.

**Version**
 - Distribution CentOS 7.9
 - Lynis version 3.0.9-100

**Expected behavior**
Yum succeeds to install or upgrade the package

**Output**
```
# yum upgrade
<...>
Downloading packages:
warning: /var/cache/yum/x86_64/7/lynis/packages/lynis-3.0.9-100.noarch.rpm: Header V4 RSA/SHA512 Signature, key ID c2fde6c4: NOKEY
Retrieving key from https://packages.cisofy.com/keys/cisofy-software-public.key


The GPG keys listed for the "CISOfy Software - Lynis package" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.


 Failing package is: lynis-3.0.9-100.noarch
 GPG Keys are configured as: https://packages.cisofy.com/keys/cisofy-software-public.key
```

**Additional context**
https://packages.cisofy.com says 
```
2023-08-03: Systems using RPM-based package are advised to import the new key and adjust their repo configuration as the path of the public key changed. For backward compatibility we are keeping the old location active for a while.
```
However no location for the new key is specified.

https://packages.cisofy.com/community/#centos-rhel instructs to use `gpgkey=https://packages.cisofy.com/keys/cisofy-software-public.key`

Yum fails with the key mentioned in the installation guide.

**Comment by ssmithpthin** [comment]
I am experiencing the exact same issue with the same error messages on my older Amazon Linux 1 instance.

**Comment by mboelen** [comment]
Thanks for letting us know. We will look into it.

**Comment by mboelen** [comment]
We performed a big migration, rebuild the package, and signed the package again with the key we used before. We discovered that rpm has different bugs, including one that looks to be related to subkeys.

**Important**: as we reversed the key, ensure that you use the right key (so adjust your repo file and use https://packages.cisofy.com/keys/cisofy-software-rpms-public.key).

Can you test and let me know if it works?

**Comment by afunix** [comment]
Thank you.
I'm able to install lynis 3.0.9 with the new key.

**Comment by mboelen** [comment]
Thanks for confirmation, closing issue.
