### ISSUE TITLE
PLGN-3814 (Verify journal integrity) hangs up

### ISSUE THREAD

**Issue by boop5** [CISOfy/lynis#1428]
**Describe the bug**
I clone the repository and run `./lynis audit system` and then it hangs up at the _systemd_ plugin 3814. ctrl+c'd it after like 20minutes

**Version**
 - Distribution x64 Ubuntu 22.04 (kernel 5.15.0)
 - Lynis version 3.09

**Expected behavior**
It should not freeze

**Output**

> ./lynis audit system --debug --verbose
> 
> ....
>
>   - Plugin: systemd
>     [.[DEBUG] Performing test ID PLGN-3800 (Gather systemctl exit code)
> .[DEBUG] Performing test ID PLGN-3802 (Query systemd version and options)
> .[DEBUG] Performing test ID PLGN-3804 (Gather systemd unit files and their status)
> .[DEBUG] Performing test ID PLGN-3806 (Gather failed systemd units)
> .[DEBUG] Performing test ID PLGN-3808 (Gather systemd machine ID)
> .[DEBUG] Performing test ID PLGN-3810 (Query main systemd binaries)
> .[DEBUG] Performing test ID PLGN-3812 (Query journal for boot related information)
> .[DEBUG] Performing test ID PLGN-3814 (Verify journal integrity)
> ^C
> Interrupt detected.
>  Cleaning up...  [ DONE ]

I've stripped the logs to the important part down because it was bloating the issue. If you need the complete log you can find it [here](https://gist.github.com/boop5/a4ad885f3f9ca80fbc9cfbb07a4f6881#file-lynis-log)

**Additional Context**
I just have upgraded (`do-release-upgrade`) from ubuntu 18 to ubuntu 22.

**Comment by amkorb** [comment]
I have to wait for 2 minutes, but that's the time that the command 
`$ journalctl --verify`takes (within Performing test ID PLGN-3814)

What do you obtain when executing this command ?

**Comment by boop5** [comment]
My bad. `$ journalctl --verify` took forever. Thanks for your help
