### ISSUE TITLE
SentinelOne detection not working

### ISSUE THREAD

**Issue by sbaumgartner75** [CISOfy/lynis#1437]
**Describe the bug**
SentinelOne is not detected correctly because "IsRunning" is called wrongly in tests_malware lines 237ff

**Version**
 - Debian 11 "Bookworm"
 - Most current - pulled from github

**Expected behavior**
SentinelOne is detected correctly

**Output**
```
./lynis: 237: /opt/Lynis/include/tests_malware: isRunning: not found
./lynis: 238: /opt/Lynis/include/tests_malware: isRunning: not found
./lynis: 239: /opt/Lynis/include/tests_malware: isRunning: not found
```

**Additional context**
Pull Request #1436 created

**Comment by mboelen** [comment]
Fixed with #1436
