### ISSUE TITLE
Lynis is not updating

### ISSUE THREAD

**Issue by poinT1501** [CISOfy/lynis#1439]
Lynis is not updating at all, I already have installed the community repository. I'm not a client yet, I'm only using it for my personal linux system. 
I have version 3.0.2 installed at the moment and when I try to install it, it says I already have the latest version.

"Version            : 3.0.2
  Status             : Outdated
  Installed version  : 302
  Latest version     : 309
  Release date       : 2020-12-24
  Project page       : https://cisofy.com/lynis/
  Source code        : https://github.com/CISOfy/lynis
  Latest package     : https://packages.cisofy.com/"

**Comment by mboelen** [comment]
That version is indeed old. It looks like your apt/yum/dnf configuration is not up-to-date. But troubleshooting will be impossible without the details (the OS, the related file of your repo, the output of relevant package manager commands).

Can you provide a bit more details?

**Comment by poinT1501** [comment]
The OS is Parrot OS, debian-based.
 
sudo apt install lynis, output:
"Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
lynis is already the newest version (3.0.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded." 

Can you be a bit more specific with the details you need? I'm quite a rookie ..

**Comment by mboelen** [comment]
Show us what you have configured (as you stated your configured the software repository). You should have a list/repo file that contains the details as listed at the [software repository](https://packages.cisofy.com/).

The output of `apt policy lynis` is also useful.

**Comment by poinT1501** [comment]
sudo grep -rhE ^deb /etc/apt/sources.list*, output:
"deb https://deb.parrot.sh/parrot lts main contrib non-free
deb-src https://deb.parrot.sh/parrot lts main contrib non-free
deb https://deb.parrot.sh/parrot parrot main contrib non-free
deb https://deb.parrot.sh/direct/parrot parrot-security main contrib non-free
deb https://deb.parrot.sh/parrot parrot-backports main contrib non-free
deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main
deb https://packages.cisofy.com/community/lynis/deb/ stable main"

sudo apt policy lynis, output:
"lynis:
  Installed: 3.0.2-1
  Candidate: 3.0.2-1
  Version table:
     3.0.9-100 500
        500 https://packages.cisofy.com/community/lynis/deb stable/main amd64 Packages
 *** 3.0.2-1 600
        600 https://deb.parrot.sh/parrot lts/main amd64 Packages
        600 https://deb.parrot.sh/parrot parrot/main amd64 Packages
        100 /var/lib/dpkg/status".

**Comment by mboelen** [comment]
The one from Parrot "wins" due to the higher priority within the apt configuration (600 > 500). The solution is to set a higher priority for the Lynis package from our repository. The configuration to do that is also listed on our [repository](https://packages.cisofy.com/community/) (bottom).

With this solution, I will close the issue (no changes to Lynis).

**Comment by poinT1501** [comment]
Thanks a lot for your help, man!

**Comment by mboelen** [comment]
You are welcome. Happy hardening!
