### ISSUE TITLE
Lynis & Ansible

### ISSUE THREAD

**Issue by kboratynski** [CISOfy/lynis#144]
Dear community; how about creating an Ansible role for Lynis, that would:
- install it automatically on the server,
- perform security updates,
- configure cronjobs for security audits,
- checking is Lynis is up-to-date
- ...

**Comment by mboelen** [comment]
More live cases on how people deploy would be useful, also for the documentation.

We already have a section for it in the Upgrading guide: https://cisofy.com/documentation/lynis/upgrading/#ansible

**Comment by kboratynski** [comment]
@mboelen Be so kind and create a separate repository for `ansible-lynis` role so we will be able to add this one to https://galaxy.ansible.com ;-)

**Comment by mboelen** [comment]
Repository is available now: https://github.com/CISOfy/lynis-ansible

No integration with Galaxy at this moment, as they require write permissions to GitHub account. GitHub authentication is the only way to create an account currently.

**Comment by mboelen** [comment]
Open item:
- Create a cronjob for non-packaged installations (manual deployment). For DEB/RPM packages we will integrate cronjob in th package itself.

**Comment by lpirl** [comment]
Alternatively, consider using tasks [like those](https://github.com/lpirl/ansible-roles/blob/master/roles/managed_host/tasks/hardening-report.yml#L10-21) to run Lynis from a git checkout since malicious software will probably damage/modify/… a system-wide installation of Lynis.

**Comment by mboelen** [comment]
Closing this issue, as no actions will be performed at this moment. Any improvements or pull requests can be added directly to that repository/project.
