### ISSUE TITLE
  Exception found!    Function/test:  [SSH-7404:1]   

### ISSUE THREAD

**Issue by roelandjansen** [CISOfy/lynis#1446]
- Tumbleweed any current version. and lynis v3.0.9

exception:

 Function/test:  [SSH-7404:1]
  Message:        SSH daemon is running, but no readable configuration file found

Now, the searched config file is not in /etc/ssh anymore but here:

/usr/etc/ssh/sshd_config

and   symlinking /etc/ssh/sshd_config.d/sshd_config -> /usr/etc/ssh/sshd_config

fixed it for now.

**Comment by mboelen** [comment]
Thanks for reporting.

Looks like an additional path might need to be added to SSH_DAEMON_CONFIG_LOCS variable in include/tests_ssh

Can you test (if you remove the symlink) that if you add the /usr/etc/ssh directory to this variable, that it then works? If so, a pull request would be very welcome.

**Comment by mboelen** [comment]
Closing after PR made by @roelandjansen
