### ISSUE TITLE
Amazon Linux 2023 is marked as EOL

### ISSUE THREAD

**Issue by lisenet** [CISOfy/lynis#1448]
**Describe the bug**
Amazon Linux 2023 is marked as EOL.

**Version**
 - Distribution [Amazon Linux 2023]
 - Lynis version [3.0.9]

**Expected behavior**
Amazon Linux 2023 is not marked as EOL.

**Output**
```
EOL check: 1
Warning: This version 2023 is marked end-of-life as of 2023-06-26 [test:GEN-0010] [details:-] [solution:-]
Program version:           3.0.9
Operating system:          Linux
Operating system name:     Amazon Linux
Operating system version:  2023
Kernel version:            6.1.61
Kernel version (full):     6.1.61-85.141.amzn2023.aarch64
Hardware platform:         aarch64
```

**Additional context**
```bash
# cat /etc/amazon-linux-release-cpe 
cpe:2.3:o:amazon:amazon_linux:2023
```

https://docs.aws.amazon.com/linux/al2023/ug/release-cadence.html

**Comment by mboelen** [comment]
Thanks for reporting. Not sure why it was marked as such before, maybe the date changed. Can you create a pull request with the right date, then we merge it.

**Comment by samueloph** [comment]
This was fixed already at https://github.com/CISOfy/lynis/commit/e797d2d3bf59e9ab5bbdcd5cc7a5c1668500370f
You just need to install the latest version, or install lynis from the distro's official repos (it contains that change too).

**Comment by mboelen** [comment]
Thanks @samueloph for being sharper than I was. Closing this issue.
