### ISSUE TITLE
SSH-7408: Issue for items with multiple values

### ISSUE THREAD

**Issue by mboelen** [CISOfy/lynis#145]
MaxStartups shows up properly in the log. In screen output it shows an error, due to finding a string "4:30:8" instead of a number.

[11:49:25] Test: Checking MaxStartups in /etc/ssh/sshd_config
[11:49:25] Result: Option MaxStartups found in /etc/ssh/sshd_config
[11:49:25] Result: Option MaxStartups value is  4:30:8

Screen output:

    - SSH option: LogLevel                                    [ MEDIUM ]
    - SSH option: MaxAuthTries                                [ NOT FOUND ]
./lynis: 156: [: Illegal number: 4:30:8
./lynis: 158: [: Illegal number: 4:30:8
./lynis: 160: [: Illegal number: 4:30:8

**Comment by kboratynski** [comment]
This is not a _multiple value_. This is an another format for `MaxStartups`.
I will handle it.

**Comment by kboratynski** [comment]
The main question is: what is the expected value for such parameter?
I was thinking of `4:30:8`, but on the other hand, having `2:*:4` is acceptable too.
What do you think?

**Comment by mboelen** [comment]
Temporary workaround is ignoring this key. It has a hash sign now to comment it out, until there is a better fix.

**Comment by mboelen** [comment]
As no action has been taken for a while, this item will be ignored for now, until there is a need to use it again. The workaround will be sufficient for the time being.
