### ISSUE TITLE
Function required: CommandExists

### ISSUE THREAD

**Issue by mboelen** [CISOfy/lynis#146]
Right now there is not a clear function which can be used to see if a particular command exists.

Preference is to use `type -p command`, but it might not work on all systems. Use `which command 2> /dev/null` as a backup.

Possible solution: http://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script
Another good read: http://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then

This subject is not easy to solve, due to the many differences between the operating systems.

**Comment by kboratynski** [comment]
@mboelen I will handle it.

**Comment by mboelen** [comment]
Closing this issue for now, due to limited benefit yet high complexity to get it right. Nice to have for later.
