### ISSUE TITLE
unexpected operator

### ISSUE THREAD

**Issue by andrerferreira** [CISOfy/lynis#1462]
**Describe the bug**
A error message as part of the output of audit system

**Version**
 - Distribution [e.g. Ubuntu 18.04]
 - Lynis version 3.0.8
 - 
**Expected behavior**
No error message

**Output**
~# lynis audit system

[ Lynis 3.0.8 ]

################################################################################
  Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
  welcome to redistribute it under the terms of the GNU General Public License.
  See the LICENSE file for details about using this software.

  2007-2021, CISOfy - https://cisofy.com/lynis/
  Enterprise support available (compliance, plugins, interface and tools)
################################################################################

[+] Initializing program
------------------------------------
  - Detecting OS...                                           [ DONE ]
  - Checking profiles...                                      [ DONE ]
  - Detecting language and localization                       [ pt ]
/usr/sbin/lynis: 612: [: -lt: unexpected operator

  ---------------------------------------------------
  Program version:           3.0.8
  Operating system:          Linux
  Operating system name:     Debian
  Operating system version:  12
  Kernel version:            6.1.0

**Additional context**
Fresh install of the tool

**Comment by mboelen** [comment]
Please upgrade to the latest version. If the issue is still there, then please open a new issue.
