### ISSUE TITLE
Translation warning message.

### ISSUE THREAD

**Issue by Achaean** [CISOfy/lynis#1463]
**Hi!** :-)

I just downloaded and installed the latest Lynis version (3.1.0).
Everything went smooth. Just one warning message: "Translation file (db/languages/gr) needs an update        [ OUTDATED ]"

I also went to the proposed page (meant for the translators), but I got the message:
"You need to fork this repository to propose changes.
Sorry, you’re not able to edit this repository directly—you need to fork it and propose your changes from there instead.".

**Comment by mboelen** [comment]
Yes, the message is correct as you are not authorized to edit files directly, only project owners can.

To make a proposal (=pull request), fork the project first (=clone to your own account). Then edit the file and create the Pull Request. Then it shows up in the list and we will merge it so it becomes part of the project (and into a next release).

Thanks in advance!
