### ISSUE TITLE
Duplicated file "software-eol.db"

### ISSUE THREAD

**Issue by samueloph** [CISOfy/lynis#1464]
Looks like this is not intentional, the file is present both at https://github.com/CISOfy/lynis/blob/990a590f3c6120f639b696a40add5cb4a8037cb8/software-eol.db and https://github.com/CISOfy/lynis/blob/990a590f3c6120f639b696a40add5cb4a8037cb8/db/software-eol.db, the first one being an outdated version of the file.

**Comment by mboelen** [comment]
Thanks, this was indeed not intentional. Corrected it now.
