### ISSUE TITLE
Add Alt Linux to a list of a checkable versions of linux

### ISSUE THREAD

**Issue by Constacalm** [CISOfy/lynis#1465]
**Is your feature request related to a problem? Please describe.**

OS Detection function report an error, see below:

Exception found!

  Function/test:  [OS Detection]
  Message:        Unknown OS found in /etc/os-release - Please create an issue on GitHub and share the the contents (cat /etc/os-release): https://github.com/CISOfy/lynis

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (/usr/bin/lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

  Thanks!

**Describe the solution you'd like**

Here is a output from system under lynis checking:

$ cat /etc/os-release 
NAME="ALT"
VERSION="10.3"
ID=altlinux
LOGO="basealt"
VERSION_ID=10.3
PRETTY_NAME="ALT Workstation K 10.3 (Sorbaronia Mitschurinii)"
ANSI_COLOR="1;33"
CPE_NAME="cpe:/o:alt:kworkstation:10"
BUILD_ID="ALT 10.2"
ALT_BRANCH_ID="p10"
HOME_URL="https://www.basealt.ru/"
BUG_REPORT_URL="https://bugs.altlinux.org/"
DOCUMENTATION_URL="https://docs.altlinux.org/"
SUPPORT_URL="https://support.basealt.ru/"

**Required changes**

Add Alt Linux to a list of a checkable versions of linux (https://en.altlinux.org/Main_Page)

**Additional context**

No additional context yet.

**Comment by mboelen** [comment]
Thanks for the suggestion. Do you want to create a pull request for it?

**Comment by mboelen** [comment]
Would be great if you have the time. This way you can directly test that it works and then it becomes part of the next release (after merge).

**Comment by Constacalm** [comment]
https://github.com/CISOfy/lynis/pull/1475

**Comment by mboelen** [comment]
Thanks, merged and will be available in next release.
