### ISSUE TITLE
Unknown OS: OSMC

### ISSUE THREAD

**Issue by Erasure5959** [CISOfy/lynis#1466]
As suggested by Lynis:

  Function/test:  [OS Detection]
  Message:        Unknown OS found in /etc/os-release - Please create an issue on GitHub and share the the contents (cat /etc/os-release): https://github.com/CISOfy/lynis

Below is the output of os-release for OSMC:

PRETTY_NAME="Open Source Media Center"
NAME="OSMC"
VERSION="February 2024"
VERSION_ID="2024.02-1"
ID=osmc
ID_LIKE=debian

ANSI_COLOR="1;31"
HOME_URL="https://osmc.tv"
SUPPORT_URL="https://osmc.tv"
BUG_REPORT_URL="https://osmc.tv"

This has been tested with the current version of Lynis (3.1.1) with the above results.

Happy to provide any further information if required, thank you.

**Comment by mboelen** [comment]
Thanks for letting us know. Want to create a pull request for it?

**Comment by Erasure5959** [comment]
Sure, done - https://[github.com/CISOfy/lynis/pull/1467](https://github.com/CISOfy/lynis/pull/1467

Hopefully I have done this correctly, please let me know if I have missed anything, or if anything else is required.

**Comment by mboelen** [comment]
Thanks, merged the changes
