### ISSUE TITLE
Missing Color on Error Message

### ISSUE THREAD

**Issue by JohnTroony** [CISOfy/lynis#148]
I'm testing the current final release of `lynis` on Arch Linux... For most parts, it seems to work fine for me. I intentionally triggered an error and escape characters are printed along with the error messages. 
Check PR https://github.com/CISOfy/lynis/pull/147

**Comment by mboelen** [comment]
Is this solved for you with the related changes?

**Comment by mboelen** [comment]
Closing issue, as it seems to work properly now.
