### ISSUE TITLE
Unknown OS found - Neon KDE

### ISSUE THREAD

**Issue by riccardv** [CISOfy/lynis#1490]
**Describe the bug**
Unknown OS found in /etc/os-release

**Version**
 - Distribution:
cat /etc/os-release
PRETTY_NAME="KDE neon 6.0"
NAME="KDE neon"
VERSION_ID="22.04"
VERSION="6.0"
VERSION_CODENAME=jammy
ID=neon
ID_LIKE="ubuntu debian"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
PRIVACY_POLICY_URL="https://kde.org/privacypolicy/"
UBUNTU_CODENAME=jammy
LOGO=start-here-kde-neon

 - Lynis version 3.1.2

**Expected behavior**
NA

**Output**
 Exception found!

  Function/test:  [OS Detection]
  Message:        Unknown OS found in /etc/os-release - Please create an issue on GitHub and share the the contents (cat /etc/os-release): https://github.com/CISOfy/lynis

  Help improving the Lynis community with your feedback!

**Additional context**

**Comment by mboelen** [comment]
Should be resolved with commit https://github.com/CISOfy/lynis/commit/ba4cd63bdac6a3c613d27ef887c6950954d8ac65

Can you test the version from GitHub to see if that is the case?

**Comment by mboelen** [comment]
Closing this issue, as it should be resolved and a new version is available since last week.
