### ISSUE TITLE
Lynis on OpenBSD

### ISSUE THREAD

**Issue by gonzalo-** [CISOfy/lynis#1491]
**Describe the bug**
Something wrong (probably a nonexisting flag in our version) on grep somewhere, I quickly grep some greps but I didn't find anything, probably you know better :D

**Version**
 - Distribution OpenBSD 7.5 / -current
 - Lynis version 3.1.1

**Expected behavior**
Show something? :D

**Output**
```
[+] System tools
------------------------------------
  - Scanning available tools...
  - Checking system binaries...
    Warning: suspicious location (.) in PATH
usage: grep [-abcEFGHhIiLlnoqRsUVvwxZ] [-A num] [-B num] [-C[num]] [-e pattern]
        [-f file] [-m num] [--binary-files=value] [--context[=num]]
        [--label=name] [--line-buffered] [--null] [pattern] [file ...]
```

**Additional context**
I really don't remember in which version changed, but it worked before.

**Comment by mboelen** [comment]
Try running it with `sh -x ` so it shows you the commands as well. Then probably we can find it very easily.

**Comment by gonzalo-** [comment]
Yes, I tried but the output is huge, I will give it a try with more time later.

**Comment by mboelen** [comment]
In include/binaries there is a check to see if the 'extended-grep' can be used. It extracts this from the output (--help), which does not exist on OpenBSD. Looks like the error handling does not go correctly.

Can you check on your system: `grep --help 2> /dev/null | grep -e "extended-regexp" > /dev/null` and see if that is giving clean output (read: empty line)?

If you run the command and add `; echo $?`, do you then get a '1' as response?

**Comment by mboelen** [comment]
Great. Do you want to turn it into a pull request and check if things work as expected (again)?

**Comment by gonzalo-** [comment]
No need, it was your fix, but I can confirm with this:

```
diff --git include/binaries include/binaries
index b495013..a2b4895 100644
--- include/binaries
+++ include/binaries
@@ -338,7 +338,7 @@
 
        # If grep is capable of extended regexp, use that instead of egrep to avoid annoying warning
        if [ "${GREPBINARY:-}" ] ; then
-               ${GREPBINARY} --help | ${GREPBINARY} -e "extended-regexp" > /dev/null
+               ${GREPBINARY} --help 2> /dev/null | ${GREPBINARY} -e "extended-regexp" > /dev/null
                if [ $? -eq 0 ] ; then
                        EGREPBINARY="${GREPBINARY} -E"
                fi
```

I don't see the help anymore. Thanks for the quick response! ;)

**Comment by gonzalo-** [comment]
Here it is https://github.com/CISOfy/lynis/pull/1492

thanks!
