### ISSUE TITLE
PKGS-7392 - Found one or more vulnerable package right after dist-upgrade

### ISSUE THREAD

**Issue by abenoit-reeliant** [CISOfy/lynis#1500]
**Describe the bug**
On a fresh Ubuntu 24.04 installation, just after running `apt update` and `apt dist-upgrade -y`, running `lynis audit system --quick` provides the warning `PKGS-7392|Found one or more vulnerable packages.`

**Version**
 - Distribution: Ubuntu 24.04 LTS
 - Lynis version: 3.1.1-100

**Expected behavior**
No warning as all packages are up-to-date. Or if there really is a vulnerable package, the name of the package in the logs.

**Output**
Section of /var/log/lynis.log for this test:
```
2024-05-16 10:21:52 ====
2024-05-16 10:21:52 Performing test ID PKGS-7392 (Check for Debian/Ubuntu security updates)
2024-05-16 10:21:52 Action: updating package repository with apt-get
2024-05-16 10:21:54 Result: apt-get finished
2024-05-16 10:21:54 Test: Checking if /usr/lib/update-notifier/apt-check exists
2024-05-16 10:21:54 Result: found /usr/lib/update-notifier/apt-check
2024-05-16 10:21:54 Test: checking if any of the updates contain security updates
2024-05-16 10:21:55 Result: found 



0 security updates via apt-check
2024-05-16 10:21:55 Hardening: assigned partial number of hardening points (0 of 25). Currently having 106 points (out of 181)
2024-05-16 10:21:55 Warning: Found one or more vulnerable packages. [test:PKGS-7392] [details:-] [solution:-]
2024-05-16 10:21:55 Suggestion: Update your system with apt-get update, apt-get upgrade, apt-get dist-upgrade and/or unattended-upgrades [test:PKGS-7392] [details:-] [solution:-]
2024-05-16 10:21:55 ====
```

**Additional context**
I have 2 machines with fresh Ubuntu 24.04 installations, and both have this issue. I have several Ubuntu 20.04 and 22.04 installations, and none of them havec this issue, so it seems to happen only on 24.04.

**Comment by mboelen** [comment]
So the log file has a few empty lines?

Looks like the output of the command might be changed.

**Comment by abenoit-reeliant** [comment]
Hello. Thanks for the reply. Yes the log has thos empty lines, that seem to come from the apt-check output:
```
# /usr/lib/update-notifier/apt-check 2>&1 | awk -F\; '{ print $2 }'




0
```

**Comment by abenoit-reeliant** [comment]
The raw output of this apt-check is as follow. Maybe the warnings interfere ?
```
# /usr/lib/update-notifier/apt-check
/usr/lib/update-notifier/apt-check:351: Warning: W:Unable to read /var/lib/ubuntu-advantage/apt-esm/etc/apt/apt.conf.d/ - DirectoryExists (2: No such file or directory)
  apt_pkg.init()
/usr/lib/update-notifier/apt-check:359: Warning: W:Unable to read /var/lib/ubuntu-advantage/apt-esm/etc/apt/preferences.d/ - DirectoryExists (2: No such file or directory)
  apt_pkg.init()
0;0
```

**Comment by abenoit-reeliant** [comment]
If I manually create both directories, the output becomes:
```
# /usr/lib/update-notifier/apt-check 2>&1 | awk -F\; '{ print $2 }'
0
```
And the warning goes away.

**Comment by mboelen** [comment]
Thanks, looks like warnings are not properly filtered by stderr.

I have added commit https://github.com/CISOfy/lynis/commit/f8e2da3087204ab7b0e60dd8c0b5d7e03d1d0c73

Can you test this change:
- Remove one of the directories, then run apt-check to confirm it shows the error again
- Run Lynis from git and see if detection works correctly

**Comment by abenoit-reeliant** [comment]
I removed both directories to go back to the original state.

Warnings in the output are back, as expected:
```
# /usr/lib/update-notifier/apt-check
/usr/lib/update-notifier/apt-check:351: Warning: W:Unable to read /var/lib/ubuntu-advantage/apt-esm/etc/apt/apt.conf.d/ - DirectoryExists (2: No such file or directory)
  apt_pkg.init()
/usr/lib/update-notifier/apt-check:359: Warning: W:Unable to read /var/lib/ubuntu-advantage/apt-esm/etc/apt/preferences.d/ - DirectoryExists (2: No such file or directory)
  apt_pkg.init()
0;0
```

To make sure, I re-launched the release version of lynis and warning is back, as expected:
```
  -[ Lynis 3.1.1 Results ]-
                                                                                                                         
  Warnings (1):                                                                                                          
  ----------------------------
  ! Found one or more vulnerable packages. [PKGS-7392]                                                                   
      https://cisofy.com/lynis/controls/PKGS-7392/
```

Then clone master from git and launched this command in the cloned directory:
```
./lynis audit system --quick
```
But I also got the warning:
```
  -[ Lynis 3.1.2 Results ]-
                                                                                                                         
  Warnings (1):                                                                                                          
  ----------------------------
  ! Found one or more vulnerable packages. [PKGS-7392]                                                                   
      https://cisofy.com/lynis/controls/PKGS-7392/
```

Tried the output from the command in the commit, but the output looks fine (no empty lines), si I'm not sure why I still get the warning.
```
# /usr/lib/update-notifier/apt-check 2>&1 | grep '^[0-9]' | awk -F\; '{ print $2 }'
0
```

**Comment by abenoit-reeliant** [comment]
I didn't remove the lynis version installed by apt before the second test. I'll just try that to make sure.

**Comment by abenoit-reeliant** [comment]
OK. It seems that was the issue. After removing the original 3.1.1 version from APT, running the command from the git clone repository works:
```
  -[ Lynis 3.1.2 Results ]-                                                                                              

  Great, no warnings                                                                                                     
```

**Comment by mboelen** [comment]
Perfect, thanks. In the upcoming release, it will be fixed then. Thanks again for reporting.
