### ISSUE TITLE
NETW-3200 and FILE-6430 do no longer detect blacklisted modules

### ISSUE THREAD

**Issue by sbaumgartner75** [CISOfy/lynis#1502]
**Describe the bug**
Both tests NETW-3200 and FILE-6430 do no longer detect blacklisted modules

**Version**
 - Debian 12.5
 - Lynis version 3.1.2

**Expected behavior**
Both tests NETW-3200 and FILE-6430 detect blacklisted modules

**Output**
```
  * Determine if protocol 'dccp' is really needed on this system [NETW-3200] 
      https://cisofy.com/lynis/controls/NETW-3200/

  * Determine if protocol 'sctp' is really needed on this system [NETW-3200] 
      https://cisofy.com/lynis/controls/NETW-3200/

  * Determine if protocol 'rds' is really needed on this system [NETW-3200] 
      https://cisofy.com/lynis/controls/NETW-3200/

  * Determine if protocol 'tipc' is really needed on this system [NETW-3200] 
      https://cisofy.com/lynis/controls/NETW-3200/

```

**Additional context**
Since commit "9819ac4" the REGEX for detecting the blacklist entries is broken.

`DATA=$(${GREPBINARY} "^install \+${P} \+/bin/true$" ${ROOTDIR}etc/modprobe.conf)`
and
`DATA=$(${GREPBINARY} -l -s "^install \+${P} \+/bin/true$" ${ROOTDIR}etc/modprobe.d/*)`
respectively, because the "\" escapes the "+" and thus the "+" is expected in the output.

I fixed this to read

`DATA=$(${GREPBINARY} "^install +${P} +/bin/true$" ${ROOTDIR}etc/modprobe.conf)`
and
`DATA=$(${GREPBINARY} -l -s "^install +${P} +/bin/true$" ${ROOTDIR}etc/modprobe.d/*)`

which fulfills the original intention of allowing any number of blanks.

**Comment by SchwarzerA** [comment]
That's due to an error in **include/consts**, _**GREPBINARY="grep"**_. It should read **GREPBINARY="grep -E"** because in **NETW-3200** and other tests I assume extended regular expressions are used.

**Comment by sbaumgartner75** [comment]
I have amended my PR to include your very valid remark.

**Comment by konstruktoid** [comment]
to achieve the expected behaviour in https://github.com/CISOfy/lynis/commit/9819ac4023f2499231f07e93b40ed1cef49f0b19:
`/usr/bin/grep -E -l -s '^install\s+dccp\s+/bin/(true|false)$' /etc/modprobe.d/*`

**Comment by leonbeckert** [comment]
Would be great if this PR could get merged so we don't get this bug anymore.

**Comment by RZR7332** [comment]
Should be resolved in 3.1.2 (just released), can you double check?

**Comment by sbaumgartner75** [comment]
Yes, it works now again. Thanks for the merge.

**Comment by mboelen** [comment]
Thanks for the confirmation
