### ISSUE TITLE
Unknown OS found - gardenlinux

### ISSUE THREAD

**Issue by vassap2022** [CISOfy/lynis#1507]
**Describe the bug**
Unknown OS found in /etc/os-release

**Version**
 - Distribution
```
cat /etc/os-release
ID=gardenlinux
NAME="Garden Linux"
PRETTY_NAME="Garden Linux 1443.3"
HOME_URL="https://gardenlinux.io"
SUPPORT_URL="https://github.com/gardenlinux/gardenlinux"
BUG_REPORT_URL="https://github.com/gardenlinux/gardenlinux/issues"
GARDENLINUX_VERSION=1443.3
GARDENLINUX_COMMIT_ID=c261f887
GARDENLINUX_COMMIT_ID_LONG=c261f8879008bcc481ba49570524cfd9734c4d54
```
 - Lynis version: [3.1.1](https://github.com/CISOfy/lynis/releases/tag/3.1.1)

**Expected behavior**
the following error should not appear.

**Output**
Exception found!

Function/test: [OS Detection]
Message: Unknown OS found in /etc/os-release - Please create an issue on GitHub and share the the contents (cat /etc/os-release): https://github.com/CISOfy/lynis

Help improving the Lynis community with your feedback!

**Additional context**
This issue is similar to https://github.com/CISOfy/lynis/issues/1490. However, this request is about https://github.com/gardenlinux/gardenlinux. I assume that a change similar to [this](https://github.com/CISOfy/lynis/commit/ba4cd63bdac6a3c613d27ef887c6950954d8ac65) should be fine:
```
                        "gardenlinux")
                            LINUX_VERSION="Garden Linux"
                            LINUX_VERSION_LIKE="Debian"
                            OS_NAME=$(grep "^NAME=" /etc/os-release | awk -F= '{print $2}' | tr -d '"')
                            OS_VERSION=$(grep "^GARDENLINUX_VERSION=" /etc/os-release | awk -F= '{print $2}' | tr -d '"')
                            OS_VERSION_FULL=$(grep "^GARDENLINUX_VERSION=" /etc/os-release | awk -F= '{print $2}' | tr -d '"')

```

**Comment by mboelen** [comment]
Thanks for sharing. Can you turn this into a pull request?

**Comment by vassap2022** [comment]
Thanks for the comment. I opened https://github.com/CISOfy/lynis/pull/1556.

**Comment by mboelen** [comment]
Thanks for the pull request. It has been merged.

**Comment by vassap2022** [comment]
Thank you very much.
