### ISSUE TITLE
Determine if we want to replace old-style backticks

### ISSUE THREAD

**Issue by mboelen** [CISOfy/lynis#151]
All modern shells support command execution with $(...). It is stated as a preferred way over `...` (backticks) notation, and both POSIX-compliant. Before rewriting tests, we should ensure that it does work correctly for systems like AIX, Solaris and the *BSDs.

**Comment by mboelen** [comment]
Decision has been made to keep things as they are for now.

**Comment by rhyven** [comment]
Good call - sounded like a lot of work, with little benefit  :+1:
