### ISSUE TITLE
Unknown OS found: Buildroot

### ISSUE THREAD

**Issue by fperrad** [CISOfy/lynis#1520]
**Describe the bug**
Unknown OS found in /etc/os-release

**Version**
 - Distribution [Buildroot](https://buildroot.org)
 - Lynis version **3.1.1**

**Output**
```
  Exception found!

  Function/test:  [OS Detection]
  Message:        Unknown OS found in /etc/os-release - Please create an issue on GitHub and share the the contents (cat /etc/os-release)
```

**Additional context**

```
$ cat /etc/os-release
NAME=Buildroot
VERSION=2024.05.1-g2af647f4b
ID=buildroot
VERSION_ID=2024.05.1
PRETTY_NAME="Buildroot 2024.05.1"
```

Buildroot is a tool to generate embedded Linux systems, that usually use [Busybox](https://www.busybox.net/).

**Comment by mboelen** [comment]
Thanks for reporting this. Want create a pull request for it (as you probably have access to a test system)?
