### ISSUE TITLE
Unknown OS found: Peppermint

### ISSUE THREAD

**Issue by Aera23** [CISOfy/lynis#1521]
**Describe the bug**
Unknown OS found in /etc/os-release

**Version**
 - Distribution [[PeppermintOS](https://peppermintos.com/)]
 - Lynis version 3.1.2

**Output**
```
  Exception found!

  Function/test:  [OS Detection]
  Message:        Unknown OS found in /etc/os-release - Please create an issue on GitHub and share the the contents (cat /etc/os-release): https://github.com/CISOfy/lynis
```

**Additional context**
The results from ```cat /etc/os-release```:

```
PRETTY_NAME="PeppermintOS"
NAME="Peppermint"
ID=peppermint
VERSION_CODENAME="bookworm"
HOME_URL="https://peppermintos.com"
SUPPORT_URL="https://sourceforge.net/p/peppermintos/pepos/"
BUG_REPORT_URL="https://sourceforge.net/p/peppermintos/pepos/"
```

**Comment by mboelen** [comment]
Thanks for reporting. Want to create a pull request for it?

**Comment by mboelen** [comment]
Closing issue with your pull request being merged: https://github.com/CISOfy/lynis/pull/1550
