### ISSUE TITLE
fedora 40 bug on detecting systemd-analyze version

### ISSUE THREAD

**Issue by garberw** [CISOfy/lynis#1525]
The question is why does awk fail in the command below.  It gives an error message.
I already posted this.  It seems someone has deleted it so I will post it again.

I run this script from /etc/cron.daily

```
#!/bin/sh                                                                                           

set -u
DATE=$(date +%Y%m%d)
HOST=$(hostname)
LOG_DIR="/var/log/lynis"
REPORT="$LOG_DIR/report-${HOST}.${DATE}"
DATA="$LOG_DIR/report-data-${HOST}.${DATE}.txt"

#cd /usr/local/lynis                                                                                
cd /var/log/lynis

# Run Lynis                                                                                         
#./lynis audit system --cronjob > ${REPORT}                                                         
/usr/bin/lynis audit system --cronjob > ${REPORT}

# Optional step: Move report file if it exists                                                      
if [ -f /var/log/lynis-report.dat ]; then
    mv /var/log/lynis-report.dat ${DATA}
fi
# The End                                                                                           
```

The cron job gives the error:
```
/etc/cron.daily/lynis.garberw:
/usr/bin/grep: warning: stray \ before -
```

ANSWER / SOLUTION / FIX

in /usr/share/lynis/include there is a file tests_boot_services which does not detect SYSTEMD_VERSION on my system correctly.  So I fixed it by brute force:
```
(line 1086)
        # garberw                                                                                   
        # echo "garberw SYSTEMDANALYZEBINARY=${SYSTEMDANALYZEBINARY}"                               
        # echo "garberw AWKBINARY           =${AWKBINARY}"                                          
        # SYSTEMD_VERSION=$("${SYSTEMDANALYZEBINARY}" --version | ${AWKBINARY} '/^systemd/ {print $2}')                                                                                                
        # echo "garberw SYSTEMD_VERSION     =${SYSTEMD_VERSION}"                                    
        # garberw added next line                                                                   
        SYSTEMD_VERSION=251
        if [ "${SYSTEMD_VERSION}" -ge 240 ]; then PREQS_MET="YES"; else SKIPREASON="systemd-analyze too old (v${SYSTEMD_VERSION}), need at least v240"; PREQS_MET="NO"; fi
    fi
```
using the rpm version the awk command fails so I just manually overrided SYSTEMD_VERSION.

**Comment by Felipe-53** [comment]
Issue opened with no description? Can you elaborate a bit?

**Comment by jwadodson** [comment]
try this,
grep -E "GREP.*\\\-"  /usr/share/lynis/include/*

you will see 9 places where a slosh (backslash) preceeds a - (minus)
the fedora grep complains about them. vis.

        /usr/bin/grep: warning: stray \ before -

previously a number of these "errors" occured, but on FC40 it's down to one.
It's hard to know exactly which one of the 9 examples left.

I guess that if there is still a version of grep out there that requires "-" escaped by "\"
then a fix might be problematic - hopefully not!

**Comment by jwadodson** [comment]
Sorry that should have been,
grep -E "GREP.\-" /usr/share/lynis/include/*

**Comment by jwadodson** [comment]
Version in fedora40 is,
lynis.noarch                        3.1.1-1.fc40                         @fedora

**Comment by jwadodson** [comment]
Once fixed we have to try to persuade the packager to include it in the next release or
hopefully FC40!

**Comment by mboelen** [comment]
Is this still an issue or resolved?

**Comment by jwadodson** [comment]
So when will V312 get into the fedora repos?
Any idea?

**Comment by mboelen** [comment]
That is out of our control, as most likely you receive the package from the official Fedora repository. For quick testing you could uninstall the package, then download or close Lynis to your system and test it. Then remove the temporary directory and reinstall the package.

**Comment by jwadodson** [comment]
OK thanks. I realise it's a fedora packager problem.

**Comment by jwadodson** [comment]
Actually a big thanks for all the fixes & efforts! It's greatly appreciated (especially as I'm retired
for 10 years ;-)

**Comment by jwadodson** [comment]
Um the new (V312) lynis on FC40 now outputs a "spurious" message,

kadmin.local: unable to get default realm

I'm not using kerberos on a "private" desktop.

**Comment by mboelen** [comment]
Thanks, considering the initial issue fixed then.

@jwadodson - Can you create a separate (new) issue for the Kerberos output above?

**Comment by jwadodson** [comment]
OK here or via the Fedora Bugzilla?
