### ISSUE TITLE
Update errors after install

### ISSUE THREAD

**Issue by Opfour** [CISOfy/lynis#153]
1) I received the following error when I try to update Lynis from 2.1.1 to 2.2.0:

“Error: Unknown protocol, please specify (http, https) in profile (update_server_protocol)[-30C”vim /etc/lynis/default.prf
vim'd - vim /etc/lynis/default.prf

and uncommented lines:

331 config:update_server_protocol:http:

337 config:update_latest_version_download:/files/lynis-latest.tar.gz:

2. Tried updating again and got the following error:

Error: Unknown download address, please specify in profile (update_server_address)[-23C

modified lines:

333 # Address of update server
334 config:update_server_address:149.210.134.182/files/:

re-ran update: lynis update release

Got Error: No URL has been specified to know the latest version on the server, please specify in profile (update_latest_version_info)[-70C

vim'd - vim /etc/lynis/default.prf
339 # Last part of URL (file to gather)
340 #config:update_latest_version_info:/files/lynis-latest-version:

uncommented line 340

re-ran update: lynis update release

Error: No local directory has been specified to store Lynis files. Please specify in profile (update_local_directory)[-58C

uncommented line 324 config:update_local_directory:/usr/local:

uncommented line 326 config:update_local_version_info:/usr/local/lynis/client-version:

re-ran update: lynis update release: Update process got to...

[+] Helper: update
------------------------------------
  Note: local data file /usr/local/lynis/client-version does not exist. It will be created after updating. (update_local_version_info)[-73C
  [Phase 1] Downloading details
  Version found on server: <html>
<head>
<meta http-equiv="refresh" content="2; url=https://cisofy.com/">
</head>
<body>
Redirecting to the website
</body>
</html>[-102C
  Local version found: -
   
  [Phase 2] Compare results
  Different version available, moving to upgrade phase
   
  [Phase 3] Downloading latest release
  Download location: http://149.210.134.182/files/149.210.134.182/files/lynis-latest.tar.gz[-30C
  Download successful
  Extracting latest version to path /usr/local
  Creating 'lynis' directory in /usr/local
  Extracting files to /usr/local

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
  Error: File extraction failed
root@host [/etc/lynis]# 

(corrected Download location, still getting same error...)

**Comment by mboelen** [comment]
That download location seems to be incorrect. Instead of downloading directly from the cisofy.com domain, download the latest release to a HTTP server of your own. Then point your client(s) to that local directory.

**Comment by Opfour** [comment]
I'll try that today. TY for the reply :)

**Comment by mboelen** [comment]
Did it work @Opfour ?

**Comment by mboelen** [comment]
Closing issue, as we consider this to be a support request.
