### ISSUE TITLE
Make use of ID_LIKE from /etc/os-release for wider OS derivatives coverage

### ISSUE THREAD

**Issue by hiddenman** [CISOfy/lynis#1530]
**Is your feature request related to a problem? Please describe.**
Lynis does not detect derivative OS automatically

**Describe the solution you'd like**
I'd like Lynis to detect OS as much as possible using common ways to do this

**Required changes**
osdetection script

**Additional context**
include/osdetection script relies on "ID=" parameter from /etc/os-release
However, there is a special "ID_LIKE=" option which shows what was the original OS for this derivative.

For example:
```
ID=neon
ID_LIKE="ubuntu debian"
```
As far as i understand, version detection is only used for choosing the correct package manager, may be something more (like config paths)
Using ID_LIKE in addition to ID will prevent posting tens of "bugs" here with the error "Unknown OS found in /etc/os-release"

**Comment by mboelen** [comment]
Thanks for the suggestion and I understand your reasoning.

The reason that we don't use ID_LIKE (yet) is that we like to show the actual Linux distribution name and allow for flexibility in the future. For example, customizing tests. With more and more Linux distributions now being detected, the number of new ones is slowing down.

So for now we will not make a change in the detection, but we might give this a fresh thought if needed. Thanks again for sharing your feedback.
