### ISSUE TITLE
Unknown macOS version (Sequoia 15.0.1)

### ISSUE THREAD

**Issue by CholtonATX** [CISOfy/lynis#1565]
**Describe the bug**
First time I ran Lynis v3.1.2 (installed from Homebrew), it did not recognize my OS version and instructed me to open an issue here. Reported "Unkown macOS version".

**Version**
 - Distribution: macOS Sequoia 15.0.1
 - Lynis version 3.1.2

**Expected behavior**
I ran the command "lynis show" to get a list of available commands. I did get the list of additional arguments that could be appended to `lynis show`.

**Output**
"Unknown macOS version. Do you know what version it is? Create an issue at https://github.com/CISOfy/lynis"

> cat ~/lynis.log
2024-10-21 12:32:29 ====
2024-10-21 12:32:29 Action: Performing tests from category: Initializing program
2024-10-21 12:32:29 PID file removed (/Users/christian.holton/lynis.pid)

**Additional context**

**Comment by mvgfr** [comment]
also under macOS 15.2, build 24C101 (Lynis version 3.1.2, via homebrew)

**Comment by mboelen** [comment]
Fixed by @al-lac with pull request #1586 

Will available in Lynis 3.1.4.
