### ISSUE TITLE
Prepare functions for tests

### ISSUE THREAD

**Issue by kboratynski** [CISOfy/lynis#157]
To remove duplication of the code, write and implement the following functions for tests:
- `ValueEqual` (eq)
- `ValueGreaterThan` (gt)
- `ValueGreaterEqual` (ge)
- `ValueNotEqual` (ne)
- `ValueLessThan` (lt)
- `ValueLessEqual` (le)

**Comment by mboelen** [comment]
Changed some names to match them with the shell equivalents (and added their short version)

**Comment by mboelen** [comment]
A while ago an initial container was already created, named TestValue. Using the -- flags might greatly improve readability and forward/backward support, as this function might change. So suggesting that.

CheckValue --id "01" --description "SSH permit root login" --service "ssh" --field <etc>

**Comment by mboelen** [comment]
Closing, most of this functionality is implemented. New tests will be created later when required.
