### ISSUE TITLE
argument processing is not allowing file path eg --report-file /var/audit/lynis-report.txt

### ISSUE THREAD

**Issue by gcsgithub** [CISOfy/lynis#1588]
**Describe the bug**
argument processing is not allowing file path eg --report-file /var/audit/lynis-report.txt the / char has been blocked by the change https://github.com/CISOfy/lynis/commit/2a540ddf759e1ea677b433710336f57c88a97711  made in include/functions:SafeInput()

**Version**
 - Distribution [Any]
 - Lynis version [3.1.3]

**Expected behavior**
File paths are once again available on command line inputs 
eg. lynis --report-file /var/audit/lynis-report.txt

**Additional context**
```
mark@orac> cat ../fixcmdargs.patch 
*** CISOfy-lynis/include/functions	2024-12-18 10:28:43.957013359 +1100
--- fix/include/functions	2024-12-17 21:14:24.938442633 +1100
***************
*** 3056,3062 ****
          if [ $# -eq 1 ]; then
              input="$1"
              # Allow only a common set of characters in first parameter
!             cleaned=$(echo "$input" | sed 's/[^a-zA-Z0-9\._:=-]//g')
          # If know what to test against, then see if input matches the specified class
          elif [ $# -eq 2 ]; then
              input="$1"
--- 3056,3063 ----
          if [ $# -eq 1 ]; then
              input="$1"
              # Allow only a common set of characters in first parameter
!             #cleaned=$(echo "$input" | sed 's/[^a-zA-Z0-9\._:=-]//g')
!             cleaned=$(echo "$input" | sed 's/[^a-zA-Z0-9\/\._:=-]//g')
          # If know what to test against, then see if input matches the specified class
          elif [ $# -eq 2 ]; then
              input="$1"
 ```

**Comment by mboelen** [comment]
Thanks for reporting.

Should be fixed with commit https://github.com/CISOfy/lynis/commit/f2ac59a1303f397e263404d10f1315977372b58e

Can you test if it works?

**Comment by kepi** [comment]
Tested and working. Thanks for quick fix.

**Comment by kepi** [comment]
Btw. I didn't check your release policy, but it would be great to make some hotfix release.

I'll probably patch it on our servers from Ansible, but I suppose this might be affecting many systems (in our case problem was with `--profile /etc/lynis/custom.prf`).

**Comment by mboelen** [comment]
We will be releasing a new version soon, so that this is fixed.

For your situation there is an easier fix: leave the `--profile` away, as default.prf and custom.prf are picked up by default if they are in a common location like `/etc/lynis`.

**Comment by mboelen** [comment]
Closing issue after confirmation about @kepi that this issue is resolved.
