### ISSUE TITLE
SSH-7408: Parse SSH settings via daemon instead of file

### ISSUE THREAD

**Issue by mboelen** [CISOfy/lynis#159]
Due to the default settings changing sometimes in SSH, it would be better to parse the output of sshd -T, instead of the configuration file.

Benefits: This way we audit the actual live configuration. Also, the defaults are accounted for. So we don't have to statically build them into the tooling.

Command: sshd -T --> ${SSHDBINARY} -T
Note: The output of this command is lowercase.

Agree?

**Comment by kboratynski** [comment]
@mboelen: Yeah, sure. I totally agree.
I will try to handle this feature with: #157 .

**Comment by rhyven** [comment]
Yep totally agree here, too.  Great point.

**Comment by mboelen** [comment]
Sorry for hijacking this one. Changes to parsing the output is implemented, as this test needed some details. Next step is adding atomic support, so individual keys can be ignored via the profile.
