### ISSUE TITLE
FINT-4316 never work

### ISSUE THREAD

**Issue by cnrat** [CISOfy/lynis#160]
I see FINT-4316 check as following:

FIND=`${GREPBINARY} "^Checksums" ${AIDECONFIG}`
FIND2=`${GREPBINARY} "^Checksums" ${AIDECONFIG} | ${EGREPBINARY} "sha256|sha512"`

witch try to find 'Checksums=sha256' or 'Checksums=sha512' in aide.conf

But I can not find a word about that configuration line in [http://aide.sourceforge.net/stable/manual.html](http://aide.sourceforge.net/stable/manual.html) .

So why is FINT-4316 exists?

**Comment by mboelen** [comment]
Thanks for reporting. Seems to be a specific configuration, and looks like you are right. We are investigating it, to see if we can improve it.

**Comment by mboelen** [comment]
This test was changed and renamed to FINT-4402. Feel free to have a look if detection works for you now. Closing this issue, as it was related to the old test.
