### ISSUE TITLE
TOOL-5004 should check for existence of iptables binary

### ISSUE THREAD

**Issue by rhyven** [CISOfy/lynis#166]
Need to insert an if clause in include/tests_tooling at line 251:

```
if [ -f $IPTABLESBINARY ] ; then

...

else
    LogText "asdfjasdlasflfs"
    ReportWarning "alkhasdljhas"
fi
```

@mboelen I'll do this when I have a sec  :)

**Comment by mboelen** [comment]
Thanks. It has been merged and slightly changed (check if IPTABLESBINARY variable has a value).
