### ISSUE TITLE
[HTTP-6710]  SSL nginx checks don't follow includes

### ISSUE THREAD

**Issue by tuxayo** [CISOfy/lynis#168]
Leading to false positives

**Comment by mboelen** [comment]
Can you show more details? (OS, related directories)

When possible, we appreciate any patch to improve the test.

**Comment by tuxayo** [comment]
OS: Arch Linux

File and directories:
/etc/nginx/nginx.conf

If the ssl conf extracted to another file and then included using `include ssl-example-domain-1.conf;`

In my case there are even two inclusion level:

`/etc/nginx/nginx.conf` includes `example-domain-1.conf` and `example-domain-2.conf`
`example-domain-1.conf` includes `ssl-example-domain-1.conf`
`example-domain-2.conf` includes `ssl-example-domain-2.conf`

**Comment by vivianspencer** [comment]
I just ran into this issue also.

If I include all of my configuration in the host file (/etc/nginx/sites-available/domain.conf) there are no issues. If I separate my SSL parameters into a separate file (/etc/nginx/snippets/ssl-params.conf) I receive a false positive on [HTTP-6710](https://cisofy.com/controls/HTTP-6710/)

OS: Debian 8.5

**Comment by mboelen** [comment]
Hi @tuxayo and @vivianspencer. A rewrite of nginx has been done, to allow parsing of nginx files more extensively. Also included is a second level of file includes. Does it work properly now for you both? The configuration files parsed are displayed on screen (except mime.types).

**Comment by mboelen** [comment]
Any of you two who has a few minutes to test if things are working now? Then we can finish it up for next release.

**Comment by vivianspencer** [comment]
Sorry this is still not working for me, I've checked the log and it's finding the includes but I get the "Result: this include does not point to a file"

**Comment by mboelen** [comment]
Can you share the related include line?

**Comment by vivianspencer** [comment]
Yes sorry, I have several config files in the folder /etc/nginx/snippets,  so the includes come up as "snippets/ssl-params.conf" for instance.

In my log this is what I get:

>
2016-08-19 07:46:49 Result: found option include with parameters snippets/cache.conf
2016-08-19 07:46:49 Found unknown option include in nginx configuration
2016-08-19 07:46:49 Result: found option include with parameters snippets/drupal.conf
2016-08-19 07:46:49 Found unknown option include in nginx configuration
2016-08-19 07:46:49 Result: found option include with parameters snippets/restrictions.conf
2016-08-19 07:46:49 Found unknown option include in nginx configuration
2016-08-19 07:46:49 Result: found option include with parameters snippets/ssl-params.conf
2016-08-19 07:46:49 Found unknown option include in nginx configuration

**Comment by tuxayo** [comment]
I tried on version 2.3.3 and still get that SSL is not configured.

Here are my config files

```
# cat nginx.conf 
user http;
worker_processes  4;

error_log stderr;

events {
    worker_connections  1024;
}

http {
    upstream php-handler {
      server unix:/run/php-fpm/php-fpm.sock;
    }
[...]other includes
    include tuxayo.conf;
[...]other includes
}

```

```
# cat tuxayo.conf
server {
    listen       80;
    listen       [::]:80;
    server_name  example.net;
    server_name  *.example.net;
    return       301 https://$server_name$request_uri;
}

server {
    include ssl-tuxayo.conf;
    server_name  example.net;
    server_name  *.example.net;
    client_max_body_size 1024M;

    root   /srv/http-tuxayo;
[...] headers
    location / {
    }
[...] other includes


}

```

```
# cat ssl-tuxayo.conf
listen 443 ssl http2;
listen [::]:443 ssl http2;

add_header Strict-Transport-Security "max-age=15768000";

ssl_session_cache    shared:SSL:10m;
ssl_session_timeout  10m;
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
ssl_dhparam dhparams.pem;

```

**Comment by mboelen** [comment]
Closing this issue for now to do a cleanup. If this is still an issue, please reopen.

**Comment by vishalg** [comment]
I have the same issue on ubuntu 16.04 with lynis 2.6.3

```
server {
...
  include snippets/ssl-params.conf;
...
}
```
snippets/ssl-params.conf:

```
ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
```
lynis.log has the following

```
...
2018-04-14 12:01:30 Result: found option include in /etc/nginx/sites-enabled/default with value 'snippets/ssl-params.conf'
2018-04-14 12:01:30 Result: this include does not point to a file
...
2018-04-14 12:01:31 Suggestion: Change the HTTPS and SSL settings for enhanced protection of sensitive data and privacy [test:HTTP-6710] [details:-] [solution:-]
```
In addition the output of audit system has

```
     - SSL configured                                        [ YES ]
        - Ciphers configured                                  [ NO ]
```

If I move the ssl_ciphers out of the included file into main server block it works fine.
