### ISSUE TITLE
SkipAtomicTest is case sensitive

### ISSUE THREAD

**Issue by rhyven** [CISOfy/lynis#170]
When the profiles are read, the atomic tests are stored in case-sensitive form, as typed by the auditor.

When the SkipAtomicTest function is called later, the atomic test is converted to lower case, but the skip-test value was not.  Therefore, the atomic test name may not match the skipped test in custom.prf.

I suggest modifying /include/profiles:173 to convert the atomic part of $VALUE to lowercase before appending it to $SKIP_TESTS.

Thoughts?

**Comment by mboelen** [comment]
sure, let's do the comparison of values all with lowercase values. Then people can decide themselves if they use lowercase, uppercase, or a combination. In all cases it will still match.

**Comment by mboelen** [comment]
Change committed. @rhyven, can you validate if it works for you?

**Comment by rhyven** [comment]
Confirmed working here!  Nice :)
