### ISSUE TITLE
KERN-5788 gives misleading error message when /vmlinuz is missing

### ISSUE THREAD

**Issue by rhyven** [CISOfy/lynis#176]
On systems where /vmlinuz doesn't exist, KERN-5788 gives a misleading error message:

`ReportSuggestion ${TEST_NO} "Check the output of apt-cache policy manually to determine why output is empty"`

I suggest checking the existence of /vmlinuz first, and throwing the following if it's missing:

`ReportSuggestion ${TEST_NO} "Unable to check for availability of a new kernel, because /vmlinuz is missing on this system."`

... Or something similar.  Either way, apt-cache isn't causing the problem, so shouldn't be part of the suggestion.  :)

**Comment by mboelen** [comment]
Agree. Will you do the patch for this?

**Comment by rhyven** [comment]
Fixed with PR #178

**Comment by mboelen** [comment]
Thanks, PR looks good. Made a few small changes to enhance the check (elif).
