### ISSUE TITLE
Regression caused by custom exit 78

### ISSUE THREAD

**Issue by jsilverman-blispay** [CISOfy/lynis#177]
Hi. We've been using Lynis pretty successfully as a hardening tool. We run it on a schedule, in cron, inside a wrapper script.

Our wrapper is using bash, and we set errexit to true (i.e. "set -e" or "set -o errexit")

This causes the wrapper to exit before some reporting tasks can run, because of the custom exit code 78 added in commit 04b2a900c174d95e0e8144a6b96d7602230395e3 . We want to still exit cleanly on warnings, and deal with them ourselves.

https://github.com/CISOfy/lynis/commit/04b2a900c174d95e0e8144a6b96d7602230395e3

I recommend setting this as a configurable value, e.g.

```
WARNING_THRESHOLD=20
if [ ${TOTAL_WARNINGS} -gt ${WARNING_THRESHOLD} ]; then
    ExitCustom 78
else
    ExitClean
fi
```
Thanks,
JDS

**Comment by mboelen** [comment]
Thanks for reporting @jsilverman-blispay. We have made a different change, to make things even easier for you.

By default now: exit with code 0, even when warnings have been found. If Lynis found a fatal issue, then it will raise an exit code higher than 0, like before.

If you want to know if warnings have been found, Lynis can still exit with the previous code 78. This can be defined with "error-on-warnings" in custom.prf. Of course, you can also use the report file to determine if there are warnings.
