### ISSUE TITLE
ssh-options are not case sensitive

### ISSUE THREAD

**Issue by kboratynski** [CISOfy/lynis#183]
While implementing some playbook for SSHD server and configuring its values, I discovered SSHD tests in Lynis are case sensitive, while ssh_config is not.

@mboelen mark this as a bug, please.

**Comment by mboelen** [comment]
That recently was already changed (everything lowercase) to match with lowercase of sshd -T.

Is this still an issue?

**Comment by mboelen** [comment]
Recently changed to have all test comparisons uppercased. So closing this issue.
