### ISSUE TITLE
Database support: Redis

### ISSUE THREAD

**Issue by rugk** [CISOfy/lynis#198]
It would be nice if you could also support [Redis](http://redis.io/) in the database section.

**Comment by mboelen** [comment]
Sure :) Care to create a test for it and send it in a pull request?

If you like, you can battle test our fresh documentation: https://github.com/CISOfy/lynis-sdk/tree/master/documentation

**Comment by rugk** [comment]
I rather leave this to someone else...
But the documentation looks good.

**Comment by mboelen** [comment]
Sure, will mark it with an up-for-grabs, so others from the community can see if they like to pick it up.

**Comment by rugk** [comment]
Well.. I'd imagine:
* `bind` only to localhost (think it is the usual situation, but may be not of course)
* `requirepass` for authentication enabled
* `rename-command CONFIG` and other potentially dangerous commands

That's also what is basically listed here: http://redis.io/topics/security

**Comment by mboelen** [comment]
Initial detection is added for Redis. @rugk can you check if it detects your instance as well?

**Comment by rugk** [comment]
It says:
```
Redis (server) status                                     [ FOUND ]
```

This looks okay to me.

**Comment by mboelen** [comment]
Requirepass test implemented. Can you test to confirm it works for you as well?

https://github.com/CISOfy/lynis/commit/30cb17cbc48f4579b5fc0bfb7c0e290ffea2dd53

**Comment by rugk** [comment]
I got this message:
> * Configure the 'secureauth' setting for Redis [DBS-1884]  
     Details: /etc/redis/redis.conf  
      https://cisofy.com/controls/DBS-1884/

and this in the overview:
> [DEBUG] Performing test ID DBS-1880 (Check for active Redis server)
   Redis (server) status                                     [ FOUND ]
[DEBUG] Performing test ID DBS-1882 (Redis configuration file)
[DEBUG] Performing test ID DBS-1884 (Redis: secureauth option configured)
     Redis (secureauth configured)                           [ NOT FOUND ]


However there is [no such setting](https://raw.githubusercontent.com/antirez/redis/3.0/redis.conf).

**Comment by mboelen** [comment]
Mixed up the setting, which has now been corrected. The `bind` and `rename-command CONFIG` has been added.

Would be great if you can run another test and confirm that these settings now work all correctly for you as well.

**Comment by rugk** [comment]
Yes, it's working:

```
[DEBUG] Performing test ID DBS-1880 (Check for active Redis server)
  - Redis (server) status                                     [ FOUND ]
[DEBUG] Performing test ID DBS-1882 (Redis configuration file)
[DEBUG] Performing test ID DBS-1884 (Redis: requirepass option configured)
    - Redis (requirepass configured)                          [ FOUND ]
[DEBUG] Performing test ID DBS-1886 (Redis: rename-command CONFIG used)
    - Redis (rename of CONFIG command)                        [ FOUND ]
[DEBUG] Performing test ID DBS-1888 (Redis: bind on localhost)
    - Redis (bind on localhost)                               [ FOUND ]
```

It does not scan my custom redis config files, but I think this is expected.
Just when you run multiple redis servers, you usually have multiple config files.

The bad thing is this config files can be anywhere, but usually they are copies of the `/etc/redis/redis.conf`

Another thing you may want to add: Whether the redis file has this ownership and permission set: `-rw-r-----  1 redis redis`. Otherwise the password required by `requirepass` can be read by any application as the file is world-readable by default.

**Comment by mboelen** [comment]
Can you show your `lsof -n | grep redis` output? It might give a good clue if that is suitable for detecting which conf files are used.

**Comment by rugk** [comment]
No, not really. There is no `conf` in the output, but only TCO connection, and the files saved in `/var/lib/redis/`. Personally I would just check everry `.conf`file in `/etc/redis/`.

**Comment by mboelen** [comment]
Had a look at /proc structure, but it seems like Redis changes its cmdline property, so can't see with what configuration file it was started. When using the client, you can see the configuration file (in /var/lib/redis), but that is not an actual file on disk. LSOF output doesn't reveal anything either.

So now scanning the /etc/redis directory, with permission check.

How does it look in your setup? Does it detect all the right configuration files?

**Comment by rugk** [comment]
> How does it look in your setup? Does it detect all the right configuration files?

Yes, it seems. (It shows the output messages multiple times now in the verbose & debug view. There are no file paths shown however.)

**Comment by mboelen** [comment]
And in the logfile?

**Comment by rugk** [comment]
Yes, there they are shown.

However all - except of the files except of the usual `redis.conf` file are detected as "Sentinel configuration file". I think this is not correct. They are basically just copies of the main `redis.conf` file, with a few modifications.

```
2016-08-13 22:08:51 Performing test ID DBS-1882 (Redis configuration file)
2016-08-13 22:08:51 Action: scanning directory (/etc/redis) for Redis configuration files
2016-08-13 22:08:51 Test: check if we can access /etc/redis/redis.conf
2016-08-13 22:08:51 Result: file is not owned by current user ID (0), but UID <SomeOtherUID>
2016-08-13 22:08:51 Result: file /etc/redis/redis.conf is readable (or directory accessible).
2016-08-13 22:08:51 Action: checking if /etc/redis/redis.conf this is a Sentinel configuration file
2016-08-13 22:08:51 Result: not a Sentinel configuration file. Now scanning if it is a Redis configuration file
2016-08-13 22:08:51 Result: found a Redis configuration file (/etc/redis/redis.conf)
2016-08-13 22:08:51 Test: check if we can access /etc/redis/redis_FILE1.conf
2016-08-13 22:08:51 Result: file is not owned by current user ID (0), but UID <SomeOtherUID>
2016-08-13 22:08:51 Result: file /etc/redis/redis_FILE1.conf is readable (or directory accessible).
2016-08-13 22:08:51 Action: checking if /etc/redis/redis_FILE1.conf this is a Sentinel configuration file
2016-08-13 22:08:51 Result: not a Sentinel configuration file. Now scanning if it is a Redis configuration file
2016-08-13 22:08:51 Result: found a Redis configuration file (/etc/redis/redis_FILE2.conf)
2016-08-13 22:08:51 Test: check if we can access /etc/redis/redis_FILE2.conf
2016-08-13 22:08:51 Result: file is not owned by current user ID (0), but UID <SomeOtherUID>
2016-08-13 22:08:51 Result: file /etc/redis/redis_FILE2.conf is readable (or directory accessible).
```

**Comment by rugk** [comment]
However only the correct Sentinel file is skipped:
```
2016-08-13 22:08:51 Result: file /etc/redis/sentinel.conf is readable (or directory accessible).
2016-08-13 22:08:51 Action: checking if /etc/redis/sentinel.conf this is a Sentinel configuration file
2016-08-13 22:08:51 Result: file is a Sentinel configuration file, skipping
```

**Comment by rugk** [comment]
Ah, now I just saw what I got wrong: `checking if /etc/redis/redis_FILE1.conf this is a Sentinel configuration file` (I though, "No it is not!").
But I overlooked this: `Result: not a Sentinel configuration file. Now scanning if it is a Redis configuration file`

So you maybe just want to remove the "this", so that it states `checking if /etc/redis/redis_FILE1.conf is a Sentinel configuration file`.

**Comment by mboelen** [comment]
Text is updated. Better?

**Comment by rugk** [comment]
I think already the old text was okay. :smiley: 
So I think this issue can be closed, can't it? Everything I could imagine about redis has been implemented.
Maybe only block some more dangerous commands with "rename-command" such as [these listed here](https://www.digitalocean.com/community/tutorials/how-to-secure-your-redis-installation-on-ubuntu-14-04#step-5-%E2%80%94-renaming-dangerous-commands).
I'd propose to at least block `DEBUG` and maybe `SHUTDOWN` as no productive server application should use this.

BTW do you also allow commands to be renamed (instead of blocked totally), so is using `rename-command CONFIG "MySecretString2354209"` okay?

**Comment by mboelen** [comment]
Yes, a rename should be caught by that as well. So closing this issue. Thanks for thinking along. Hope you will bring in more ideas (or even pull requests) :+1:
