### ISSUE TITLE
systemd-timesyncd status isn't checked when checking for NTP implementations

### ISSUE THREAD

**Issue by Pyrohh** [CISOfy/lynis#2]
I see ntpd and a few other NTP daemons being scanned by Lynis, so it's seems reasonable to scan for systemd's variant as well.

systemd-timecyncd's status can be retrieved via `systemctl is-enabled systemd-timesyncd` and `systemctl is-active systemd-timesyncd`, which both return 0 on a service being enabled and active respectively.

**Comment by mboelen** [comment]
Support has been implemented for systemd-timesyncd and Chrony. Will be available in next release. Thanks again for sharing!
