### ISSUE TITLE
Fail2ban enable jail test and  iptables test

### ISSUE THREAD

**Issue by Heretic-q2** [CISOfy/lynis#206]
In Centos in the program Fail2ban recommend create rule in another file in special folder /etc/fail2ban/jail.d/.
And include rules in that file.

>  # Changes:  in most of the cases you should not modify this
>  #           file, but provide customizations in jail.local file,
>  #           or separate .conf files under jail.d/ directory, e.g.:
>  #
>  # HOW TO ACTIVATE JAILS:
>  #
>  # YOU SHOULD NOT MODIFY THIS FILE.

EXAMPLE:/etc/fail2ban/jail.d/custom.conf.
```
[sshd]
enabled = true
```

In Fedora/Centos/RHEL in the program fail2ban uses chain f2b-\<name\>, but  Debian/Ubuntu fail2ban-\<name\>

[0001-Fail2ban-tool.patch.zip](https://github.com/CISOfy/lynis/files/281965/0001-Fail2ban-tool.patch.zip)

**Comment by mboelen** [comment]
Thanks for reporting this. Can you turn this into a pull request? Then you are properly linked as a contributor and we can merge it in a logged way.

**Comment by mboelen** [comment]
Changed to the logic of fail2ban test were implemented, so closing this issue as well. Thanks for the insights and help.
