### ISSUE TITLE
could `find` in /tmp use -xdev?

### ISSUE THREAD

**Issue by lpirl** [CISOfy/lynis#207]
First, thanks for this valuable tool everyone – thumbs up!

I just discovered a `find /tmp -type f -atime +90` running for ages on a machine since that has a (huge) file system temporarily mounted to a directory in `/tmp` for backup purposes.

Without knowing what this command is used for, maybe it's an option to add `-xdev` to `find` commands targeting `/tmp`.

**Comment by mboelen** [comment]
Hi Lukas. Thanks for reporting this. Can you run it again with the latest version and see if it is better now?

**Comment by lpirl** [comment]
It is. Thanks a lot for the instant fix!
