### ISSUE TITLE
LOGG-2190 always throws a warning with MySQL <5.6 installed

### ISSUE THREAD

**Issue by rhyven** [CISOfy/lynis#209]
MySQL 5.5 and previous versions have a bug that leaves dozens of deleted-but-held files in /tmp.

It's been recognised since 2005 (ref http://bugs.mysql.com/bug.php?id=15089), and has been fixed in 5.6+ (ref http://bugs.mysql.com/bug.php?id=66237), but hasn't been fixed in 5.5 and it looks like it won't be.

What do you guys think about adding an exclusion for mysql files in LOGG-2190?

**Comment by mboelen** [comment]
We did some research and found indeed the same cause, after it was reported by Lynis on many systems. Sure, an exclusion for this is fine. Want to create the pull request?
