### ISSUE TITLE
SSH warnings not showing in 'Warnings' summary?

### ISSUE THREAD

**Issue by pr0letariat** [CISOfy/lynis#211]
Recently running `lynis`, I had a couple of SSH warnings:

```
- SSH option: X11Forwarding                               [ WARNING ]
- SSH option: Port                                        [ WARNING ]
```

But these did not show in the 'Warnings' summary under '-[ Lynis 2.2.0 Results ]-'.

Why is this?

**Comment by mboelen** [comment]
Are they listed in Suggestions overview?

**Comment by pr0letariat** [comment]
Yes.

**Comment by mboelen** [comment]
Thanks, we have changed the screen output, to reflect that better.
