### ISSUE TITLE
[TOOL-5002] detect Ansible as system management tool

### ISSUE THREAD

**Issue by lpirl** [CISOfy/lynis#212]
One approach could be to read the syslog. Ansible produces lines like:

```
 Jun  4 17:03:00 MyHost ansible-git: …
 Jun  4 17:03:04 MyHost ansible-file: …
 Jun  4 17:03:06 MyHost ansible-apt: …
```

Not sure how platform dependent that is, thought…

**Comment by mboelen** [comment]
Thanks for sharing. This is definitely a brain challenger ;-)

Although your proposal is possible, parsing log files is not preferred as it may take a long while. If you know you have a management tool in place (like Ansible), then we suggest disabling the test in your custom.prf.

**Comment by ad-m** [comment]
In TOOL-5002 there is no test about Ansible. Ansible is agent-less, but create directory ~/.ansible when used. Can we display a hint with the question about Ansible when traces of Ansible found?

```
  * Determine if automation tools are present for system management [TOOL-5002] 
    - Solution : Is it Ansible?
      https://cisofy.com/controls/TOOL-5002/
```
