### ISSUE TITLE
Whats wrong with SSHd's AllowTcpForwarding?

### ISSUE THREAD

**Issue by lpirl** [CISOfy/lynis#220]
In analogy to #217, I miss some explanation/references regarding the suggestion to turn off TCP forwarding in `sshd`.
I do see the generic reason to "generally reduce the attack surface" but even `man sshd_config` states:

> Note that disabling TCP forwarding does not improve security unless users are also denied shell access, as they can always install their own forwarders.

So again, it would be very beneficial to provide some pointers [on the corresponding Web site](https://cisofy.com/controls/SSH-7408/) regarding the specific suggestions.

**Comment by kboratynski** [comment]
@mboelen: I will handle it.

@lpirl: Simple question; do you *really* need TCP port forwarding? If no - disable it.  Well, enabling TCP-forwarding might be a simple way to omit active, passive and application firewalls.

References: 
[V-22464]: https://www.stigviewer.com/stig/unix_srg/2013-03-26/finding/V-22464
[STACK]: http://security.stackexchange.com/questions/22782/security-concerns-with-tcp-forwarding

**Comment by lpirl** [comment]
@kboratynski thanks for your reply.
As I said earlier, I see the point in turning off what is not needed (yes, I do need forwarding for jump hosts to connect to hosts that are completely hidden/proxied).

As with the other issue mentioned in the OP, it'd probably be useful for future users to include your last sentence and the references on the Web site linked in the OP.

**Comment by kboratynski** [comment]
@lpirl Did I explain everything clearly enough?
Can we close it?

**Comment by lpirl** [comment]
Well… is there any motivation for improving [those pages](https://cisofy.com/controls/SSH-7408/)?
As mentioned here and in #217, I guess it would help users searching for references and as well to increase Lynis' plausibility.

**Comment by kboratynski** [comment]
@lpirl: I agree. I think this topic can be closed as my explaination was good enough for you. (I hope so.)
@mboelen: Would you be so kind and add my references and explainations (including these from #217) to Lynis controls page? You can close this topic as well.

**Comment by lpirl** [comment]
Correct. I'll leave it open as well for @mboelen to remember.
Thanks!

**Comment by mboelen** [comment]
Closing issue, related note has been added to website. Sorry for delay in implementing, we had a lot of invisible work internally.

**Comment by lpirl** [comment]
No worries and thanks for taking user suggestions serious.
