### ISSUE TITLE
AUTH-9288 can have false positive if there's no maximum age set

### ISSUE THREAD

**Issue by pyllyukko** [CISOfy/lynis#221]
Hi.

Found out a false positive with AUTH-9288 in [tests_authentication](https://github.com/CISOfy/lynis/blob/master/include/tests_authentication) when there's no password maximum age set.

The test tests for ```last day changed + maximum change time```, but it is possible to have the ```maximum password age``` field in ```/etc/shadow``` completely empty. This is also documented in the [man page](http://linux.die.net/man/5/shadow): "```An empty field means that there are no maximum password age, no password warning period, and no password inactivity period```".

If this is the case, the test effectively calculates ```last day changed + 0```, which usually is lower than ```DAYS_SINCE_EPOCH```.

**Comment by mboelen** [comment]
Thanks for sharing. Made a related change in commit https://github.com/CISOfy/lynis/commit/c181a5745f9cf31e5c667393eb35255b86357887

Does it work correctly for you as well?

**Comment by pyllyukko** [comment]
> Does it work correctly for you as well?

Yes it does. Thanks!
