### ISSUE TITLE
Doesn't currently recognize Avira AV on Mac

### ISSUE THREAD

**Issue by Pavornoc** [CISOfy/lynis#226]
During a normal system audit, Lynis shows no malware scanner installed.  Avira is installed on the system tested.

I thought maybe a discrepancy with Antivirus vs Malware, but test ID HRDN-7230 cites: "Use ClamAV or a commercial alternative".  Surely Avira AV would qualify under this condition?

Tested on Mac OS v10.11.5, Lynis v2.3.0, Avira Free Antivirus v3.3.0

```
2016-07-13 11:00:07 Performing test ID HRDN-7230 (Check for malware scanner)

2016-07-13 11:00:07 Test: Check if a malware scanner is installed

2016-07-13 11:00:07 Result: no malware scanner found

2016-07-13 11:00:07 Suggestion: Harden the system by installing at least one malware scanner, to perform periodic file system scans [test:HRDN-7230] [details:-] [solution:-]

2016-07-13 11:00:07 Hardening: assigned partial number of hardening points (1 of 3). Currently having 72 points (out of 104)
```

**Comment by mboelen** [comment]
Sure, that will qualify as a scanner to be detected. Can you add a process listing with the related processes on your system? Then we can add Avira as well.

**Comment by mboelen** [comment]
Hi @Pavornoc, do you have the process listing, so we can add it?

**Comment by mboelen** [comment]
Any update?

**Comment by marcus-cr** [comment]
Working on adding support for this manually, since no further information was provided.

**Comment by marcus-cr** [comment]
@Pavornoc there actually is a difference with lynis' tests. The hardening test you referenced (HRDN-7230) checks for specific malware scanners, like chkrootkit or rkhunter, to be installed. Your Avira antivirus isn't a part of the hardening or malware tests, however I'm adding support to the malware tests to recognize it running.

**Comment by marcus-cr** [comment]
@mboelen: here's the list of process that run with Avira (free)
- AV_Systray
- avbackendproxy
- avguard-ondemand-mgmt
- avguard-scanner (ten individual processes)
- avguard.bin
- avlogwriter
- avqmd (two instances)
- avsavapi-super
- AVStats
- avwatchdox.bin
- savapi

Golden ticket could be avguard-ondemand-mgmt, avguard-scanner or avqmd

**Comment by marcus-cr** [comment]
Process of elimination brought the list down the the following candidates:
- AV_Systray
- avguard-ondemand-mgmt
- avqmd
- avguard.bin
Termination of these processes seem to stop protection until some other process(s) re-launches it. I'm betting on avqmd, or avguard.bin, being the daemon needed to support recognition that Avira AV is installed. @mboelen, your thoughts on this?

**Comment by Pavornoc** [comment]
I apologize profusely for completely dropping the ball on this ticket.  It's been a while since I've used a Mac, but from what I recall, the explanation and changes @marcus-cr made cleared up my issue.  Again, I am so sorry.  I'll close this ticket now.

**Comment by mboelen** [comment]
Reopening it to see if it is fully implemented. In the upcoming weeks we will check all issues and process them.

**Comment by marcus-cr** [comment]
I have switched AV software since, will investigate further in macOS 10.12 VM about Avira processes.

**Comment by mboelen** [comment]
Implemented initial detection with https://github.com/CISOfy/lynis/commit/4be6b958e4a3fa79125bca49fc569dd3a9e5335e
