### ISSUE TITLE
lynis-report.dat bug(?)

### ISSUE THREAD

**Issue by d4t4king** [CISOfy/lynis#230]
In some of my reports, I get the line:
```Result: allow_url_fopen option is turned on, which can be used for riskful downloads via PHP```
...in the `/var/log/lynis-report.dat` output file.  This breaks the "key=value" symmetry of the file.

(It also looks like this line should probably be related to something else, but is just "dangling" in the report.

**Comment by mboelen** [comment]
Fixed with commit https://github.com/CISOfy/lynis/commit/d02cb095da5851e20f55a6bba715715a03f93eb7

Thanks for reporting!
