### ISSUE TITLE
Suggestion: Install debsums...[PKGS-7370]

### ISSUE THREAD

**Issue by d4t4king** [CISOfy/lynis#231]
The `debsums` utility doesn't exist on Gentoo linux.  Not exactly sure what an equivalent might be.  File/package checksumming is built into portage (in theory -- AFAIK), but isn't used or supported.

Recommend dropping the suggestion if OS is detected as Gentoo linux -- at least until an appropriate alternative can be identified.

**Comment by mboelen** [comment]
This check normally only runs on systems which have dpkg. Do you have this utility installed?

**Comment by d4t4king** [comment]
Interestingly, `dpkg` is available in the portage system but is not installed on the test system.  It seems I did, however, create a wrapper script (called `/usr/bin/oops`, symlinked as `/usr/bin/dpkg`) to remind me that I was on a Gentoo system and not a Debian one (I use a lot of both).

I removed the link and reran lynis, and debsums is no longer reported as a suggestion.

Put this as a feature request/enhancement, if you like, but the tool should probably do some more checking to verify the authenticity of dpkg.  Maybe something simple like a MIME magic check with `file`.  Which on a Debian system reports:
```/usr/bin/dpkg: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=62403fbc06d8a47d0d857498d32f68b8009db8e5, stripped```
....but on the test Gentoo system reports....
```/usr/bin/dpkg: symbolic link to oops```

Also interesting to note, while `dpkg` is listed in portage and can, therefore, be installed on a Gentoo system (who known why -- perhaps to install Debian packages(???)), `debsums` is not in portage.

**Comment by rhyven** [comment]
Haha @d4t4king I've experienced almost exactly the same thing.

**Comment by mboelen** [comment]
Checking all binaries in-depth (at every run) would be slowing down the scan a lot. Checking if a file is an ELF binary or symlink, does not give guarantees. Several "binaries" are typically symlinks, like `python`.

In this case, an edge-case looks better to me than slowing down all audits. For now leaving things as-is, but will monitor if this happens more often.

Thanks @d4t4king for the interesting case and reporting it :)
