### ISSUE TITLE
Subtests still reporting when disabled

### ISSUE THREAD

**Issue by d4t4king** [CISOfy/lynis#232]
The best (only?) example is the SSH hardening check (SSH-7408).  When disabling sub-checks in the default.prf (relocated and designated by `--profile`), they are still reported as suggestions.

**Comment by mboelen** [comment]
Can you show an example what you put in your profile?

Tip: don't change default.prf when not strictly needed. Put your changes in /etc/lynis/custom.prf (See the changelog for all details)

**Comment by d4t4king** [comment]
Moved configs to `/etc/lynis/custom.prf`, per your instruction..... test are still tested/reported.

custom.prf sample below:
```
# Skip a particular option within a test (when applicable)
#skip-test=SSH-7408:loglevel
#skip-test=SSH-7408:permitrootlogin
skip-test=SSH-7408:permitrootlogin
skip-test=SSH-7408:loglevel
skip-test=SSH-7408:compression
```

**Comment by mboelen** [comment]
Cause has been found and related function altered. Thanks for reporting!

Commit: https://github.com/CISOfy/lynis/commit/f9a4348f107ba0e8fa98d319cfa39ba410475844

**Comment by d4t4king** [comment]
Confirmed!  Working as expected.  Thanks!
