### ISSUE TITLE
mod_evasive not found

### ISSUE THREAD

**Issue by ben29** [CISOfy/lynis#238]
hi.
i'm using centos 7.
i get this:

> - Install Apache mod_evasive to guard webserver against DoS/brute force attempts [HTTP-6640] 
>     https://cisofy.com/controls/HTTP-6640/

but the module is loaded and working:

```
httpd -M | grep evasive
 evasive20_module (shared)
```

also modsecurity:

> - Install Apache modsecurity to guard webserver against web application attacks [HTTP-6643] 
>     https://cisofy.com/controls/HTTP-6643/

```
 httpd -M | grep sec
 security2_module (shared)
```

**Comment by Roennie** [comment]
How did you install mod_evasive, from a repository, compiled from source, or...?

**Comment by ben29** [comment]
i'm using directadmin compiler. so the confgiure for modules will not be in 
> /usr/lib64/httpd/modules
all the modules is here:
> /usr/lib/apache/

**Comment by ben29** [comment]
any update?

**Comment by mboelen** [comment]
Marked as a bug, we will investigate it. Thanks for reporting.

**Comment by strangelittlemonkey** [comment]
Does your apache config mention the path as being /usr/lib/apache?

**Comment by mboelen** [comment]
@ben29 please provide output of the following command:

`grep apache /var/log/lynis-report.dat`

**Comment by mboelen** [comment]
With the latest change it will most likely be fixed. If not, please reopen.

**Comment by mohammedkra** [comment]
any updates?
