### ISSUE TITLE
Strange characters in report log

### ISSUE THREAD

**Issue by tjancz** [CISOfy/lynis#244]
Hi 

I'm starting lynis by command  ./lynis audit system -Q > my_report.log

and have some strange characters in the output log like below:
^[[1;37m[ Lynis 2.3.2 ]^[[0;39m

################################################################################
  Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
  welcome to redistribute it under the terms of the GNU General Public License.
  See the LICENSE file for details about using this software.

  2007-2016, CISOfy - https://cisofy.com/lynis/
  Enterprise support available (compliance, plugins, interface and tools)
################################################################################

[+] ^[[1;33mInitializing program^[[0;39m
------------------------------------
^[[2C- Detecting OS... ^[[41C [ ^[[1;32mDONE^[[0;39m ]
^[[2C- Checking profiles...^[[37C [ ^[[1;32mDONE^[[0;39m ]
^[[2C- Detecting language and localization^[[22C [ ^[[1;37mpl^[[0;39m ]
^[[4C^[[1;33mNotice:^[[0;39m no language file found for 'pl' (tried: /home/tomasz/lynis/db/languages/pl)^[[0C
^[[4CSee https://github.com/CISOfy/lynis-sdk/documentation/10-translations.md for more details to help translating Lynis^[[0C

  ---------------------------------------------------
  Program version:           2.3.2
  Operating system:          Linux
  Operating system name:     Debian
  Operating system version:  8.5
  Kernel version:            3.16.0
  Hardware platform:         x86_64
  Hostname:                  tj
  ---------------------------------------------------
  Profiles:                  /home/tomasz/lynis/default.prf
  Log file:                  /var/log/lynis.log
  Report file:               /var/log/lynis-report.dat
  Report version:            1.0
  Plugin directory:          ./plugins
  ---------------------------------------------------
  Auditor:                   [Not Specified]
  Test category:             all
  Test group:                all
  ---------------------------------------------------
^[[2C- Program update status... ^[[32C [ ^[[1;32mNO UPDATE^[[0;39m ]

[+] ^[[1;33mSystem Tools^[[0;39m
------------------------------------
^[[2C- Scanning available tools...^[[30C
^[[2C- Checking system binaries...^[[30C

[+] ^[[1;35mPlugins (phase 1)^[[0;39m

Best regards
TJ

**Comment by kboratynski** [comment]
Thank you for this report. These characters are color sequences [1]; I think `less` should handle these chars. If you would like to have plain-text --  use ``no-color`` option, please.

[1]: http://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/x329.html

**Comment by beelsr** [comment]
1.  `--no-colors`
2.  `--cronjob` also strips color from output.

**Comment by mboelen** [comment]
Just to be sure: What language setting do you have? Can you share output of: `lynis show settings`

**Comment by tjancz** [comment]
Sure
# Compressed uploads
compressed-uploads=0

# Use non-zero exit code if one or more warnings were found
error-on-warnings=0

# Language
language=pl

# License key
license-key=[not configured]

# Machine role (server or desktop)
machine-role=server

# Pause between tests (in seconds)
pause-between-tests=0

# Quick mode (non-interactive)
quick=0

# Show tool tips
show-tool-tips=1

# Skip plugins
skip-plugins=0

# Paths for SSL certificates
ssl-certificate-paths=/etc/letsencrypt:/etc/pki:/etc/ssl:/usr/local/share/ca-certificates:/var/www:/srv/www

# Scan mode
test-scan-mode=full

# Upload options
upload-options=[not configured]

# Upload server (ip or hostname)
upload-server=[not configured]

# Verbose output
verbose=0

# Add --brief to hide descriptions, --configured-only to show configured items only, or --nocolors to remove colors

**Comment by tjancz** [comment]
If You want I could provide You english <-> polish translation for output info

**Comment by mboelen** [comment]
One thing you can try is setting the language to English (language=en) in custom.prf and then see if this solves the output.

Otherwise, I suspect your shell. What does `file /bin/sh` show? If it is a symlink, to what?

Yes, we would love a translation for Polish. The "pl" file has been added. You can fork it, change the translations, then remove the # sign for each line you have translated. And put it into a pull request.

Thanks

**Comment by mboelen** [comment]
Hi @tjancz, Did you have a look at what `file /bin/sh` shows?

**Comment by mboelen** [comment]
Any update @tjancz ?

**Comment by tjancz** [comment]
Now it is working as expected just added cron job as parameter. 
Thank You!

**Comment by mboelen** [comment]
Thanks for the quick reply. If you have the chance, the Polish translation would be appreciated. Closing this issue to keep the list tidy.
