### ISSUE TITLE
bug in yum gpgcheck detection

### ISSUE THREAD

**Issue by beelsr** [CISOfy/lynis#245]
this snippet, while valid and `working,` is not recognized by lynis:
`gpgcheck          = 1
`

and here's a diff to fix. 

```
diff -U0 tests_ports_packages~ tests_ports_packages
--- tests_ports_packages~       2016-07-14 14:19:10.000000000 -0400
+++ tests_ports_packages        2016-07-29 12:50:52.647929289 -0400
@@ -826,2 +826,2 @@
-           SearchItem "^gpgenabled=1$" "/etc/yum.conf"; if [ ${ITEM_FOUND} -eq 1 ]; then FOUND=1; fi
-           SearchItem "^gpgcheck=1$" "/etc/yum.conf"; if [ ${ITEM_FOUND} -eq 1 ]; then FOUND=1; fi
+           SearchItem "^gpgenabled\s*=\s*1$" "/etc/yum.conf"; if [ ${ITEM_FOUND} -eq 1 ]; then FOUND=1; fi
+           SearchItem   "^gpgcheck\s*=\s*1$" "/etc/yum.conf"; if [ ${ITEM_FOUND} -eq 1 ]; then FOUND=1; fi
```

**Comment by kboratynski** [comment]
@beelsr Thank you for this report.
Would you be so kind and write a pull request?
We would appreciate your contribution.

_Postscriptum_: I am not fairly sure, yum-repo-file accepts only *one* space between parameter and `=` mark. Would you be so kind and check it? If so, I would suggest to modify your regexp to handle *only* proper yum-repos. What do you think?

**Comment by beelsr** [comment]
so, I deleted my MariaDB key from my rpmdb via `rpm -e gpg-pubkey-1bb943db-511147a9`.

I then:
edited yum.conf to say `gpgcheck = 1`
verified no gpgcheck entry existed in `yum.repos.d/mariadb.repo`
issued a `yum  --disablerepo="*" --enablerepo="mariadb" install mariadb-test` command and was rewarded with the output of:
```
Downloading packages:
warning: /var/cache/yum/x86_64/7/mariadb/packages/MariaDB-10.1.16-centos7-x86_64-test.rpm: Header V4 DSA/SHA1 Signature, key ID 1bb943db: NOKEY
Retrieving key from https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
Importing GPG key 0x1BB943DB:
 Userid     : "MariaDB Package Signing Key <package-signing-key@mariadb.org>"
 Fingerprint: 1993 69e5 404b d5fc 7d2f e43b cbcb 082a 1bb9 43db
 From       : https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
Is this ok [y/N]: n
```

I then edited yum.conf to say `gpgcheck         = 1` and also `gpgcheck =         1`.  The result was the same for all three runs.  I think this proves that spaces are ignored by the parser.  A cursory "grep gpgcheck yum*" found `/usr/lib/python2.7/site-packages/yum/config.py` but I don't do python.

**Comment by beelsr** [comment]
and I just noticed reading my post that markdown is eating the extra spaces... :(  I thought code tags preserved the entered text exactly?  
Let's try this:
first run was gpgkey oneSpace = oneSpace 1
second run was gpgkey oneSpace = manySpaces 1
third run was gpgkey manySpaces = oneSpace 1

I hope that's more clear.

**Comment by mboelen** [comment]
Thanks for the pull request @beelsr. Can you add it to our repository (instead of yours), so we can merge it? :)

**Comment by beelsr** [comment]
ah yeah, just figuring out this guthub stuff...  :)

**Comment by mboelen** [comment]
No problem :) We appreciate any help to make the software better. Pull request merged.
