### ISSUE TITLE
Deprecated use of sed?

### ISSUE THREAD

**Issue by timreeves** [CISOfy/lynis#249]
Hi,
I installed from current packages on Ubuntu 14.04 (no problem) and on Debian 8.5, where most calls give me this message as the first message (but then seem to work):
sed: -e expression #1, char 53: unknown option to `s'
I got the latest version from GitHub and copied the files into place, but it does not change.
Hope this helps, thx for all the good work!
Cheers,
Tim

**Comment by mboelen** [comment]
Hi Tim. Just to be sure: remove all installed artifacts from Lynis on the Debian system.

Then run `git clone https://github.com/CISOfy/lynis`. Go into the Lynis directory (`cd lynis`) and run `./lynis audit system`.

Do you still get the same output then?

**Comment by timreeves** [comment]
Hi Michael,
did that - purged the installed package and autoremoved 'menu'. Then cloned and tested as you suggested.

1)
./lynis show profiles
sed: -e expression #1, char 53: unknown option to `s'

2)
./lynis audit system
...
[+] Initializing program
------------------------------------
  - Detecting OS...                                           [ DONE ]
sed: -e expression #1, char 53: unknown option to `s'
  - Checking profiles...                                      [ DONE ]
...

That should help you to locate it.
Thanks for your very prompt reply!
Tim

**Comment by mboelen** [comment]
I just gave it a try on a Debian 8.5 myself, but no errors here. So it looks like it might have to be a specific profile option. 

Can you run: `sh -x ./lynis show profiles`

A few lines around the sed error, there should be a clue what it was doing when it triggered the error. Then we can use this to improve the test.

Thanks!

**Comment by timreeves** [comment]
+ egrep ^ssl-certificate-paths; /tmp/lynis.OQHKXT1txo
+ FIND=ssl-certificate-paths;/etc/letsencrypt:/etc/pki:/etc/ssl:/usr/local/share/ca-certificat...
+ [ -z ssl-certificate-paths;/etc/letsencrypt:/etc/pki:/etc/ssl:/usr/local/share/ca-certificat...
+ Debug Option ssl-certificate-paths was already configured, overwriting previous value in /tm...
+ [ 0 -eq 1 -a 1 -gt 0 ].
+ sed -i -e s/ssl-certificate-paths;.*$/ssl-certificate-paths;/etc/letsencrypt:/etc/pki:/etc/s...
sed: -e expression #1, char 53: unknown option to `s'.
+ ContainsString config: config:compliance_standards:cis,hipaa,iso27001,pci-dss:.
+ RETVAL=1.

BTW "man grep" says: Direct invocation as either egrep or fgrep is deprecated

Cheers, Tim

**Comment by mboelen** [comment]
Alright, after a serious session of troubleshooting a change has been made which should now work.

Use `git pull` to update your version and then use `./lynis show settings` to see if your settings are correct (set by custom.prf).

**Comment by timreeves** [comment]
Hi Michael,
YES, I can confirm that the "sed" message has gone away.
When approx will you package and release 2.3.2?
Thanks so much for your Sunday-Session!
Cheers, Tim

root@HIDDEN # ./lynis show profiles
/root/lynis/default.prf
/etc/lynis/custom.prf
~/lynis
root@HIDDEN # ./lynis show settings
# Compressed uploads
compressed-uploads=0

# Use non-zero exit code if one or more warnings were found
error-on-warnings=0

# Language
language=en

# License key
license-key=[not configured]

# Machine role (server or desktop)
machine-role=server

# Pause between tests (in seconds)
pause-between-tests=0

# Quick mode (non-interactive)
quick=0

# Show tool tips
show-tool-tips=1

# Skip plugins
skip-plugins=0

# Paths for SSL certificates
ssl-certificate-paths=/etc/letsencrypt:/etc/pki:/etc/ssl:/usr/local/share/ca-certificates:/var/www:/srv/www

# Scan mode
test-scan-mode=full

# Upload options
upload-options=[not configured]

# Upload server (ip or hostname)
upload-server=[not configured]

# Verbose output
verbose=0

# Add --brief to hide descriptions, --configured-only to show configured items only, or --nocolors to remove colors
~/lynis

**Comment by mboelen** [comment]
You checked that the settings are OK as well?

Package will be released soon (maybe upcoming week), as it contains enough improvements to ship it out.

**Comment by timreeves** [comment]
> You checked that the settings are OK as well?
Not quite sure how you mean that... I had not personalised the settings at all, my tests were with full default settings. Am personalising right now - and have a quick question:

Lynis says: "Purge old/removed packages (40 found)" - but when I call "apt purge" it finds 0 to purge.
Am I doing something wrong?
Thanks!

**Comment by mboelen** [comment]
Closing this one again, to avoid confusion with original bug (sed issue).

Regarding the purged packages: have a look at lynis.log, as that should list some more details.
