### ISSUE TITLE
Software: webserver = too many arguments errors at line 772

### ISSUE THREAD

**Issue by centminmod** [CISOfy/lynis#25]
manually installed lynis 2.0 tarball on CentOS 7 system which has my own centminmod.com LEMP web stack installed.

running command

    lynis --auditor "centminmod.com initial run" -c -Q --profile /usr/local/lynis/default.prf

gives me errors at

    [+] Software: webserver
    ------------------------------------
      - Checking Apache                                           [ NOT FOUND ]
      - Checking nginx                                            [ FOUND ]
        - Searching nginx configuration file                      [ FOUND ]
          - Found nginx includes                                  [ 7 FOUND ]
        - Parsing configuration options
    ./include/functions: line 772: [: too many arguments
    ./include/functions: line 772: [: too many arguments
    ./include/functions: line 772: [: too many arguments
          - SSL configured                                        [ NO ]
          - Checking log file configuration
            - Missing log files (access_log)                      [ NO ]
            - Disabled access logging                             [ NO ]
            - Missing log files (error_log)                       [ NO ]
            - Debugging mode on error_log                         [ NO ]

my Nginx stack is source compiled with following options

    nginx -V
    nginx version: nginx/1.7.10
    built by gcc 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) 
    TLS SNI support enabled
    configure arguments: --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --with-http_ssl_module --with-http_gzip_static_module --with-http_stub_status_module --with-http_sub_module --with-http_addition_module --with-http_image_filter_module --with-http_secure_link_module --with-http_flv_module --with-http_realip_module --with-openssl-opt=enable-tlsext --add-module=../ngx-fancyindex-ngx-fancyindex --add-module=../ngx_cache_purge-2.3 --add-module=../headers-more-nginx-module-0.25 --add-module=../nginx-accesskey-2.0.3 --add-module=../nginx-http-concat-master --with-http_dav_module --add-module=../nginx-dav-ext-module-0.0.3 --add-module=../openresty-memc-nginx-module-1518da4 --add-module=../openresty-srcache-nginx-module-ffa9ab7 --add-module=../nginx-sticky-module-1.2.5 --add-module=../nginx_upstream_check_module-0.3.0 --with-openssl=../openssl-1.0.2 --with-libatomic --with-pcre=../pcre-8.36 --with-pcre-jit --with-http_spdy_module --add-module=../ngx_pagespeed-release-1.9.32.3-beta

**Comment by mboelen** [comment]
Patch submitted. Can you check if this removes the warning message?

**Comment by mboelen** [comment]
@centminmod does it work for you correctly with the latest changes?

**Comment by mboelen** [comment]
Timed out, considering issue resolved.

**Comment by centminmod** [comment]
sorry for late reply been sick with the flu :(

just tested and same error

    [+] Software: webserver
    ------------------------------------
      - Checking Apache                                           [ NOT FOUND ]
      - Checking nginx                                            [ FOUND ]
        - Searching nginx configuration file                      [ FOUND ]
          - Found nginx includes                                  [ 6 FOUND ]
        - Parsing configuration options
    ./include/functions: line 781: [: too many arguments
          - Checking log file configuration
            - Missing log files (access_log)                      [ NO ]
            - Disabled access logging                             [ NO ]
            - Missing log files (error_log)                       [ NO ]
            - Debugging mode on error_log                         [ NO ]

version

     == Lynis ==
    
      Version         : 2.1.0
      Status          : Up-to-date
      Release date    : 16 April 2015
      Update location : https://cisofy.com

**Comment by mboelen** [comment]
No worries, glad that you do confirm now.

In that case you have something behind your access_log statement, right? Can you share the lines from your configuration?

**Comment by centminmod** [comment]
here's my access_log lines

    access_log  logs/access.log combined buffer=128k flush=15m;
    error_log   logs/error.log warn;

**Comment by mboelen** [comment]
Does it work with the latest patch? (I edited by previous comment, due to this patch)

**Comment by centminmod** [comment]
doh sorry i install Lynix via a shell script and it was set to latest tag via github not the master branch

      cd /usr/local
      git clone https://github.com/CISOfy/Lynis.git lynis
      cd lynis
      LATEST_TAG=$(git tag | sort -V | tail -1)
      git branch -a
      git branch -D lynis-local
      git checkout -b lynis-local $LATEST_TAG

**Comment by centminmod** [comment]
latest master branch Lynis works without the too many arguments error :+1: 

    [+] Software: webserver
    ------------------------------------
      - Checking Apache                                           [ NOT FOUND ]
      - Checking nginx                                            [ FOUND ]
        - Searching nginx configuration file                      [ FOUND ]
          - Found nginx includes                                  [ 6 FOUND ]
        - Parsing configuration options
          - Checking log file configuration
            - Missing log files (access_log)                      [ NO ]
            - Disabled access logging                             [ NO ]
            - Missing log files (error_log)                       [ NO ]
            - Debugging mode on error_log                         [ NO ]

**Comment by mboelen** [comment]
Great, in that case closing the issue. Thanks again for reporting it.
