### ISSUE TITLE
PHP5.6 detection?

### ISSUE THREAD

**Issue by erialor** [CISOfy/lynis#257]
I see Lynis is searching for /etc/php/cli-5.6/php.ini but not /etc/php/apache-5.6/php.ini (which I'm using)? only 5, 5.4 and 5.5

**Comment by mboelen** [comment]
The required change is adding the path in include/tests_php. Dare to make the change and create a pull request?

**Comment by erialor** [comment]
Mistyped - should be apache2 and not apache.
Not sure I'm up for making the change - not using Git/not installed....

**Comment by mboelen** [comment]
You can create pull request without Git client. All from GitHub and do an inline edit. We appreciate more contributors, and a great way to show attribution on who contributed ;-) Would that make a difference?

**Comment by erialor** [comment]
I *think/hope* I've done it now :)

**Comment by mboelen** [comment]
Thanks, you did it. Closing this issue with pull request https://github.com/CISOfy/lynis/pull/261
