### ISSUE TITLE
lynis --profile options available ?

### ISSUE THREAD

**Issue by centminmod** [CISOfy/Lynis#26]
I did tarball lynis 2.0 install but confused as to whether there is a profile specifically for CentOS  ?

what is correct syntax for --profile and what are all available options for linux distrubutions available ?

    lynis --auditor "centminmod.com initial run" -c -Q --profile CentOS

    [ Lynis 2.0.0 ]
    
    ################################################################################
     Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
     welcome to redistribute it under the terms of the GNU General Public License.
     See the LICENSE file for details about using this software.
    
     Copyright 2007-2015 - CISOfy, https://cisofy.com
     Enterprise support and plugins available via CISOfy
    ################################################################################
    
    [+] Initializing program
    ------------------------------------
    Fatal error: Can't open profile file (CentOS)

thanks

**Comment by mboelen** [comment]
Profiles are meant to define a scan should be done. There is a default profile, named default.prf, which you optionally can copy and alter. This is useful to avoid the file being overwritten, or using different profiles for different types of scans. No need to specify the OS, as Lynis will detect that and adjust tests to what it discovered.

**Comment by centminmod** [comment]
thank @mboelen for the clarification :)
