### ISSUE TITLE
System Warnings no longer showing Low, Medium or High (L,M,H) rating - version 2.3.3

### ISSUE THREAD

**Issue by mdearlove** [CISOfy/lynis#271]
lynis-report.dat no longer contains L,M or H ratings.  

e.g. High rated item
Version 2.3.3
KRNL-5830|Reboot of system is most likely needed|-|-|

full line looks like:
_warning[]=KRNL-5830|Reboot of system is most likely needed|-|-|_

Version 2.2.0
KRNL-5830|Reboot of system is most likely needed|**H**|-|

Is this a bug or intended behaviour? I was using the rating to "Find All" from a summary report I wrote that aggregated the results from many servers into one log but can no longer quickly skip results of scans :-(  

Is this a setting I need to enable to bring these values back or is it simply a bug?

All Warnings and suggestions appear to be "**|-|-|**"

I am running the command with only --cronjob parameter

**Comment by mboelen** [comment]
Hi. It is intended behavior, as part of an ongoing rewrite. The rating was never really used, so as part of our simplicity principle, we stripped it from the output. Another reason is that a warning for one system could be high priority, while the same warning for another system could be fine.

Tip: Have a look in the ReportWarning and ReportSuggestion functions for the details regarding the fields if you like to know more about the last fields.
