### ISSUE TITLE
Bug in FILE-6344 on CentOS 7

### ISSUE THREAD

**Issue by marrrt** [CISOfy/lynis#275]
Pull request for #263 breaks test on CentOS 7.

Output from mount is formatted as follows:

```proc on /proc type proc (rw,relatime,hidepid=2)```

Release is ```CentOS Linux release 7.2.1511 (Core)```

**Comment by mboelen** [comment]
Change has been applied, can you test if it solved for you now?

https://github.com/CISOfy/lynis/commit/0a0453e1bc1683861880f09529ad8a44c12566fc

**Comment by marrrt** [comment]
Works for me on the same machine as above.

Thanks for the quick turnaround.

**Comment by mboelen** [comment]
Thanks for confirmation.
