### ISSUE TITLE
Check for CSF Firewall

### ISSUE THREAD

**Issue by centminmod** [CISOfy/Lynis#28]
Firewall check in lynis 2.0 doesn't check for CSF Firewall http://configserver.com/cp/csf.html which is commonly used in cpanel.net based control panel installs as well as standalone on CentOS servers.

I use CSF Firewall for CentminMod.com LEMP stack by default which interfaces with iptables http://centminmod.com/csf_firewall.html

    [+] Software: firewalls
    ------------------------------------
      - Checking iptables kernel module                           [ NOT FOUND ]
      - Checking pf                                               [ NOT FOUND ]
      - Checking host based firewall                              [ NOT ACTIVE ]

**Comment by mboelen** [comment]
Initial CSF detection has been added. Thanks for submitting this request.

**Comment by centminmod** [comment]
cheers you have a typo in line 245 missing csf directory name https://github.com/CISOfy/Lynis/commit/a12876e472b0a75a95a13d2d1f295ca6fbcc51ee#diff-5bf84564ef65aeccb19174001a2c1adbR245

**Comment by mboelen** [comment]
Thanks, changed full path into variable.
