### ISSUE TITLE
running lynis via ansible breaks web page

### ISSUE THREAD

**Issue by edgarmaloverian** [CISOfy/lynis#282]
I spotted interesting behaviour, while running lynis from shell
`$ ssh ansible@somehost sudo /usr/sbin/lynis audit system --quick --upload --profile custom`
works okay, running via ansible with become:
`command: sudo /usr/sbin/lynis audit system --quick --upload --profile custom`
kinda works, but breaks layout on hosted enterprise version (hardening sections gets missing)
that's probably has something to do with lot of exra environment ansible supplies when connecting to host.
if this issue is not easily repeatable I can dump exact execution environment. @mboelen

**Comment by mboelen** [comment]
Might be better indeed to share the output via email, so we can have a look at the additional data added. Possibly it can be scrubbed before uploading.

**Comment by edgarmaloverian** [comment]
may be you can sport what environment makes a difference to script?
local report looks very similar. 

	ansible: 

	lynis audit system --quick --upload --profile custom 
SUDO_GID=1000 
MAIL=/var/mail/root 
LANGUAGE=en_US: 
USER=root 
HOME=/root 
SUDO_UID=1000 
LOGNAME=root 
TERM=xterm 
USERNAME=root 
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin 
LANG=en_GB.UTF-8 
SUDO_COMMAND=/bin/sh -c echo BECOME-SUCCESS-rnowjsdtubtzafxzbpqekocwmiwsjdqu; LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1474372967.97-84314713069140/command; 
rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1474372967.97-84314713069140/" > /dev/null 2>&1 
LC_MESSAGES=en_GB.UTF-8 
SHELL=/bin/bash 
SUDO_USER=ansible 
PWD=/home/ansible 
LC_ALL=en_GB.UTF-8

shell:

lynis audit system --quick --upload --profile custom 
SHELL=/bin/bash 
TERM=xterm 
USER=root 
MAIL=/var/mail/root 
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin 
PWD=/root LANG=en_US SHLVL=1 
HOME=/root LANGUAGE=en_US: 
LOGNAME=root 
LESSOPEN=| /usr/bin/lesspipe %s 
LESSCLOSE=/usr/bin/lesspipe %s %s 
_=/usr/sbin/lynis

September 21, 2016 9:18 AM, "Michael Boelen"  wrote: 
	Might be better indeed to share the output via email, so we can have a look at the additional data added. Possibly it can be scrubbed before uploading.

**Comment by mboelen** [comment]
I don't think any shell variables have a direct impact. You could run a diff on the reports (one via Ansible, one directly as root).

**Comment by mboelen** [comment]
This problem has been solved. The underlying cause was a plugin.
