### ISSUE TITLE
MaxAuthTries with value 1 is too strict

### ISSUE THREAD

**Issue by mboelen** [CISOfy/lynis#283]
Due to publickey authentication this value might be too strict.

**Comment by rhyven** [comment]
Really?  With Pubkeys, I'd think that any failures at all means they're connecting with an incorrect key anyway.  I think MaxAuthTries = 1 is quite a reasonable configuration.

**Comment by kboratynski** [comment]
@mboelen : `$HOME/.ssh/config`.

**Comment by edgarmaloverian** [comment]
not sure, having two keys I saw this on MaxAuthTries1
```
debug1: SSH2_MSG_NEWKEYS received
debug2: key: /home/ets/.ssh/id_rsa (0x5574f63c0530)
debug2: key: /home/ets/.ssh/id_dsa (0x5574f63c1860)
debug2: key: /home/ets/.ssh/id_ecdsa ((nil))
debug2: key: /home/ets/.ssh/id_ed25519 ((nil))
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/ets/.ssh/id_rsa
debug2: we sent a publickey packet, wait for reply
Received disconnect from 127.0.0.1 port 22:2: Too many authentication failures
```

**Comment by rhyven** [comment]
@edgarmaloverian -- That's interesting, I didn't realise that presenting an unrecognised key counted as an authentication attempt.  Presumably your DSA key has been added to the authorized_keys file then, but your RSA key is being offered first.

Does it successfully authenticate with MaxAuthTries 2, then?

**Comment by strangelittlemonkey** [comment]
I can confirm that if you specify a key this will still fail. I.e., ssh -i keyfile user@host, MaxAuthTries 1 will cause your connection to not go through.

**Comment by kamilboratynski** [comment]
@strangelittlemonkey: Would you be so kind and provide your config for `ssh` client and verbose log for connection?

**Comment by mboelen** [comment]
For now changed MaxAuthTries to 2, closing this issue.
