### ISSUE TITLE
Lynis is broken on Freebsd

### ISSUE THREAD

**Issue by vr** [CISOfy/lynis#286]
because of this commit : https://github.com/CISOfy/lynis/commit/eded02cfde6a48270b975d8390dac44b3ad22f35

error is : 
`lynis/include/tests_kernel_hardening: arithmetic expression: variable conversion error: "HPTOTAL + HPADDMAX"`

**Comment by vr** [comment]
Well `/bin/sh` is not bash on freebsd, and you use bashism since this commit.

If i do a `bash lynis audit system` it works, but i get this : `/lynis/include/functions: line 118: 1Do: value too great for base (error token is "1Do")`

**Comment by mboelen** [comment]
Thanks for reporting.

What FreeBSD version is this? On my 10.2 test system this does not result in an error.

Our project avoids bashism and the $((x+y)) is [POSIX compliant](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_04). So I don't think that's the cause.

What does your lynis.log show. How far did it get before it showed the error?

**Comment by mboelen** [comment]
Hi @vr, can you share additional details?

**Comment by edgarmaloverian** [comment]
getting same error on FreeBSD fbsd11 11.0-CURRENT FreeBSD 11.0-CURRENT #0 r285616
exact place is:
```
    - kern.sugid_coredump (exp: 0)                            [ OK ]
    - net.inet.icmp.bmcastecho (exp: 0)                       [ OK ]
    - net.inet.icmp.drop_redirect (exp: 1)                    [ DIFFERENT ]
/usr/local/lynis-master/include/tests_kernel_hardening: arithmetic expression: variable conversion error: "HPTOTAL + HPADDMAX"

```

**Comment by mboelen** [comment]
Thanks @edgarmaloverian for the confirmation. The problem was in the default.prf and is now fixed.

**Comment by manasb** [comment]
I had been running Lynis with bash. though that could be a security issue itself, comments?

**Comment by mboelen** [comment]
@manasb You are welcome. But this is not the right place discussion. Feel free to send an email to the lynis-dev@cisofy.com. Maybe we can make a nice blog post for it.
