### ISSUE TITLE
atomic skip for php tests

### ISSUE THREAD

**Issue by ogmueller** [CISOfy/lynis#287]
This is a feature request.

It would be really nice to be able to skip atomic tests within the php tests.
So something like:

```
skip-test=PHP-2372:expose_php
```

would not skip the whole PHP-2372 tests, but only the expose_php option test within it.

The ssh tests do allow that. E.g. with:

```
skip-test=SSH-7408:TCPKeepAlive
```

The php tests are a little bit of guess work, because it won't check other INI files, which are listed with e.g. "php --ini" and also included with the main php.ini. Because of this fact, it would be very helpful to overcome this problem.

**Comment by mboelen** [comment]
Sounds like a good plan. Want to help getting it implemented?

**Comment by ogmueller** [comment]
I was just about to help and implement it, but when I was looking into the source code more closely, I discovered, that the atomic tests are not needed, because the php tests are done separately. So each of the config value tests have a different test number.

The ssh tests are really nice and I like the idea of having those tests combined as one "lynis number", because they are testing the configuration file (one item). I don't know if atomic tests are better or not, but I assume that changing this for the php tests is not a good idea because it would break the configuration compatibility.

so you might want to close this issue?

**Comment by mboelen** [comment]
Right now we will leave things as-is. In the future, we will address PHP to improve its scanning capabilities for that language. Especially dealing with default and the varies locations and configuration.
