### ISSUE TITLE
DBS-1816: mysql root user with empty password check not working correctly

### ISSUE THREAD

**Issue by ogmueller** [CISOfy/lynis#288]
The test DBS-1816 checks whether the root user has set a password or not. Depending on the mysql-server and setting, this test or detection is not sufficient anymore. Since mysql has more authentication methods/plugins now.

A mysql installation may use the authentication plugin [auth_socket](https://dev.mysql.com/doc/mysql-security-excerpt/5.5/en/socket-authentication-plugin.html) for user root. So a user table might look like this:

```
# select user, host, plugin, authentication_string from mysql.user;
+------------------+---------------------------+-----------------------+-----------------------+
| user             | host                      | plugin                | authentication_string |
+------------------+---------------------------+-----------------------+-----------------------+
| root             | localhost                 | auth_socket           |                       |
| mysql.sys        | localhost                 | mysql_native_password | *...                  |
| debian-sys-maint | localhost                 | mysql_native_password | *...                  |
| root             | 127.0.0.1                 | mysql_native_password | *...                  |
| root             | ::1                       | mysql_native_password | *...                  |
```

So when testing mysql access being user root and using no password will always work, even though a password has been set, but in this case the auth_socket "wins". I am not sure how to test this in an easy way. I assume you have to be a different user to circumvent it. Or maybe doing a select on the user table helps?

**Comment by mboelen** [comment]
Thanks for letting us know. We know that some things can't checked easily. Looks like this test is now one of them.

**Comment by ogmueller** [comment]
Currently the test is trying to access mysql as root without password. This is an indicator, that there is no password set for root, but there might be two common alternative explanations to it: .my.cnf in home dir or a plugin mentioned above.

Testing the case above is actually easy, because you already know how to get access to mysql.

After you successfully accessed mysql with
```
FIND=$(${MYSQLCLIENTBINARY} -u root --password= --silent --batch --execute="" 2> /dev/null; echo $?)
if [ "${FIND}" = "0" ]; then
```
you could try to find these entries in user table:
```
FIND=$(${MYSQLCLIENTBINARY}  -u root --password= --silent --batch --execute="SELECT count(*) FROM mysql.user WHERE user = 'root' AND plugin = 'mysql_native_password' AND authentication_string = ''" >/dev/null)
if [ "${FIND}" > "0" ]; then
```

Maybe this makes it a bit more accurate?

A patch could look like this (more or less):
```
--- tests_databases.org	2017-02-28 09:38:50.542993191 +0100
+++ tests_databases	2017-02-28 09:41:26.755063719 +0100
@@ -77,10 +77,17 @@
         LogText "Test: Trying to login to local MySQL server without password"
         FIND=$(${MYSQLCLIENTBINARY} -u root --password= --silent --batch --execute="" 2> /dev/null; echo $?)
         if [ "${FIND}" = "0" ]; then
-            LogText "Result: Login succeeded, no MySQL root password set!"
-            ReportWarning ${TEST_NO} "No MySQL root password set"
-            Display --indent 4 --text "- Checking empty MySQL root password" --result "${STATUS_WARNING}" --color RED
-            AddHP 0 5
+			FIND=$(${MYSQLCLIENTBINARY}  -u root --password= --silent --batch --execute="SELECT count(*) FROM mysql.user WHERE user = 'root' AND plugin = 'mysql_native_password' AND authentication_string = ''" >/dev/null)
+			if [ "${FIND}" > "0" ]; then
+	            LogText "Result: Login succeeded, no MySQL root password set!"
+	            ReportWarning ${TEST_NO} "No MySQL root password set"
+	            Display --indent 4 --text "- Checking empty MySQL root password" --result "${STATUS_WARNING}" --color RED
+	            AddHP 0 5
+        	else
+        	    LogText "Result: Login did not succeed, so a MySQL root password is set"
+        	    if IsVerbose; then Display --indent 4 --text "- Checking MySQL root password" --result "${STATUS_OK}" --color GREEN; fi
+        	    AddHP 2 2
+			fi
         else
             LogText "Result: Login did not succeed, so a MySQL root password is set"
             if IsVerbose; then Display --indent 4 --text "- Checking MySQL root password" --result "${STATUS_OK}" --color GREEN; fi
```

**Comment by ad-m** [comment]
IMO there is false positive when ``~/.my.cnf`` contains authentication data too.

**Comment by ad-m** [comment]
IMO there is false positive when ``/root/.my.cnf`` contains authentication data too.

When ``/root/.my.cnf`` present and ```mysql -u root --password= --silent --batch --execute="SELECT count(*) FROM mysql.user"``` executed as root there is success. As any other user this command fail.

**Comment by mboelen** [comment]
@ogmueller thanks for your patience regarding this issue. Your suggested option seems like an improvement. Although it may not be 100% reliable, it is still better. Can you create a pull request for it?

**Comment by mboelen** [comment]
@ogmueller Oliver, do you have time to create the pull request?

**Comment by ogmueller** [comment]
just created it...

**Comment by mboelen** [comment]
Closing
