### ISSUE TITLE
Little Snitch (FW) Support - MacOS (Sierra)

### ISSUE THREAD

**Issue by marcus-cr** [CISOfy/lynis#289]
Hello,

I have the firewall Little Snitch installed on MacOS Sierra however Lynis doesn't seem to support this application. Since it monitors incoming and outgoing communications (unlike the built-in firewall), I left MacOS' firewall disabled and use Little Snitch instead. Lynis only recognizes that pf isn't active. Hopefully this is an easy remedy!

**Comment by mboelen** [comment]
Thanks. We are are updating Lynis to support Sierra. Will link this to the project.

**Comment by mboelen** [comment]
It does now. Run a git pull and run Lynis. Does it get detected now?

**Comment by marcus-cr** [comment]
Perfect, it passed for Little Snitch. Cheers!

**Comment by mboelen** [comment]
Thanks, closing this issue.
