### ISSUE TITLE
TIME-3104 does not find chrony.conf on Debian

### ISSUE THREAD

**Issue by PCarlsson** [CISOfy/lynis#292]
On Debian 8.6 chrony.conf is located in /etc/chrony/

Change include/test_time from:
`        if [ -f /etc/chrony.conf ]; then
            IsRunning chronyd
            if [ ${RUNNING} -eq 1 ]; then
                FOUND=1; NTP_DAEMON_RUNNING=1; NTP_CONFIG_TYPE_DAEMON=1; NTP_DAEMON="chronyd"
                Display --indent 2 --text "- NTP daemon found: chronyd" --result "${STATUS_FOUND}" --color GREEN
            fi
        fi
`

to:
`        if [ -f /etc/chrony.conf -o -f /etc/chrony/chrony.conf ]; then
            IsRunning chronyd
            if [ ${RUNNING} -eq 1 ]; then
                FOUND=1; NTP_DAEMON_RUNNING=1; NTP_CONFIG_TYPE_DAEMON=1; NTP_DAEMON="chronyd"
                Display --indent 2 --text "- NTP daemon found: chronyd" --result "${STATUS_FOUND}" --color GREEN
            fi
        fi
`

**Comment by mboelen** [comment]
Thanks for reporting. A slightly different change has been applied. Can you check if it is properly detected for you now as well?

https://github.com/CISOfy/lynis/commit/f18ef5c21029ba47773ad604a1c15ef26a3859c5

**Comment by PCarlsson** [comment]
Hello! Seems to work properly! Thanks! /Peter
