### ISSUE TITLE
Accounting auditd - not for OpenVZ virtualized containers

### ISSUE THREAD

**Issue by centminmod** [CISOfy/lynis#30]
In virtualized containers for OpenVZ or Parallels Virtuozzo, auditd kernel doesn't work by design. So when you report auditd is not found in Accounting section, maybe also do a check for see if Lynis is being run within an OpenVZ like container and make a note as such ?

i.e. 

NOT FOUND (Not supported in OpenVZ kernels) ?

    [+] Accounting
    ------------------------------------
      - Checking accounting information                           [ NOT FOUND ]
      - Checking sysstat accounting data                          [ ENABLED ]
      - Checking auditd                                           [ NOT FOUND ]

for CentOS at least there's yum package to check for it virt-what

    yum list virt-what -q
    Installed Packages
    virt-what.x86_64                                                   1.13-5.el7

running check

    virt-what
    openvz

also you can check for openvz virtualization via file /proc/user_beancounters 

    ls -lah /proc/user_beancounters 
    -r-------- 1 root root 0 Mar  9 21:52 /proc/user_beancounters

**Comment by centminmod** [comment]
seems same applies to psacct for process accounting not supported in OpenVZ kernels so a note for auditd and psacct is needed when OpenVZ virtualized containers are detected

    -- Subject: Unit psacct.service has begun with start-up
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit psacct.service has begun starting up.
    Mar 10 15:48:53 host accton[13734]: accton: Operation not permitted
    Mar 10 15:48:53 host accton[13734]: Turning on process accounting, file set to '/var/account/pacct'.
    Mar 10 15:48:53 host systemd[1]: psacct.service: main process exited, code=exited, status=1/FAILURE
    Mar 10 15:48:53 host systemd[1]: Failed to start Kernel process accounting.
    -- Subject: Unit psacct.service has failed

**Comment by mboelen** [comment]
Hi, initial patch has been implemented. Can you test latest version from Git and see if it works for you?

**Comment by mboelen** [comment]
Closing this issue to keep the list clean. If the patch does not work as expected, please reopen this isssue.

Thanks for reporting it!
