### ISSUE TITLE
Test group "nameservices" continues without /etc/resolv.conf

### ISSUE THREAD

**Issue by marcus-cr** [CISOfy/lynis#305]
After installing fresh copy of macOS Sierra in virtual machine without internet connection Lynis will continue the nameservices test group and provides incorrect results:

> 2016-10-19 03:00:16 Performing test ID NAME-4018 (Check /etc/resolv.conf search domains)
> 2016-10-19 03:00:16 Test: check /etc/resolv.conf for search domains
> 2016-10-19 03:00:16 Result: /etc/resolv.conf does not exist, skipping test
> 2016-10-19 03:00:16 Result: found <null> line(s) with a search statement (expecting less than 2 lines)
> 2016-10-19 03:00:16 Warning: Found more than 1 search lines in /etc/resolv.conf, which is probably a misconfiguration [test:NAME-4018] [details:-] [solution:-]
> 2016-10-19 03:00:16 ===---------------------------------------------------------------===

Log shows it found " " line(s) with search statement while expecting less than 2 lines. The log above shows <null> whereas the actual log showed a blank space.

Test results displayed at end of testing also shows incorrect results from the other tests in the test-group "nameservices" as warnings instead of skipping the applicable unnecessary tests (resulting in false positives).

**Comment by mboelen** [comment]
Good catch. Are you running Sierra in a VM on Sierra? Trying to simulate the issue, but can't get that to work.

**Comment by marcus-cr** [comment]
Yes, I was running Sierra in a VM on Sierra. Prior to installing macOS Sierra in the virtual machine I made sure all of the VM's network adapters were disconnected. Naturally macOS didn't generate the /etc/resolv.conf file because of this, that would be the best way to replicate the issue.

**Comment by mboelen** [comment]
Related test has been changed to fix this: https://github.com/CISOfy/lynis/commit/814f2355ca14bca1cdad04a923950d4168e5b7bd
