### ISSUE TITLE
Suggestions - How To Solve

### ISSUE THREAD

**Issue by Geyup** [CISOfy/lynis#306]
I noticed on the website for the URLs you can look up for the ```Suggestions``` and noticed that the ```How to solve``` sections do not really show you how to slove these issues, rather it's just explaining the situation instead...

It would be really great if all the Suggestions - How to Solve sections were updated with actual examples of how to really solve many of these situations.

Here's a perfect example for the USB Storage;

https://cisofy.com/controls/STRG-1840/

How to solve should read;

On most distros you add in a config file for /etc/modprobe.d

```install usb-storage /bin/true```

Now I've just shown a real solution and this is what people need!

THANKS

**Comment by mboelen** [comment]
Thanks for bringing this up.

We currently don't provide scripts on our website. Lynis evolved over the last years, and previously only showed the warnings. Now we do link to the website, to provide more details, and when possible link to a blog post. So although I do agree more information on the "solving" part, it remains a work in progress. Our first priority is to keep enhancing the Lynis tooling itself.
