### ISSUE TITLE
macOS 10.12.1 comes up Undetectable

### ISSUE THREAD

**Issue by jpartain89** [CISOfy/lynis#307]
It looks like its specifically due to the calling of `/usr/bin/sw_vers -productVersion` and its response being `10.12.1` rather than `10.12`, and the `include/osdetection` only parsing for 10.12 rather than 10.12.1, or allowing the 10.12.x compatibility.

**Comment by mboelen** [comment]
Thanks, the routine has been extended to detect both now.
