### ISSUE TITLE
Add /usr/local/lynis/default.prf path to tPROFILE_TARGETS array

### ISSUE THREAD

**Issue by centminmod** [CISOfy/Lynis#31]
Official README https://github.com/CISOfy/Lynis/blob/master/README suggests to create directory at /usr/local/lynis for installation but this path is not checked for in lynis itself ?

I symlinked lynis to /usr/bin/lynis so if you run lynis by itself it hangs as it can't find default.prf

so maybe add /usr/local/lynis/default.prf path to tPROFILE_TARGETS array ?

    # Try to find a default profile file, if none is specified
    if [ "${PROFILE}" = "" ]; then
        tPROFILE_TARGETS="/usr/local/etc/lynis/default.prf /etc/lynis/default.prf ./default.prf"
        for I in ${tPROFILE_TARGETS}; do
            if [ -f ${I} ]; then PROFILE=${I}; fi
        done
    fi

**Comment by mboelen** [comment]
Thanks, path has added.
