### ISSUE TITLE
Tool fails with lynis/include/osdetection: line 458: READLINKBINARY: parameter not set

### ISSUE THREAD

**Issue by alienpussy** [CISOfy/lynis#315]
I can not use this tool. It fails on every attempt to execute it with this error:
```
lynis/include/osdetection: line 458: READLINKBINARY: parameter not set
```

I am using a small custom linux with busybox.

**Comment by novaksam** [comment]
I worked around this by removing the check for it in the if statement, which works for me since I'm not trying to deploy this to production.

**Comment by mboelen** [comment]
Thanks for reporting. The variable has been added in commit https://github.com/CISOfy/lynis/commit/b5a1deae47247589167c8ea37d1f25c760e8922d, so you don't get the error anymore.
