### ISSUE TITLE
/root/.ssh not found on MacOS

### ISSUE THREAD

**Issue by FreshXOpenSource** [CISOfy/lynis#317]
The root home on OSX by default resides in /var/root, hence the .ssh folder can be found there but is not detected by lynis (yet)

**Comment by mboelen** [comment]
Thanks for creating this issue. To ensure we focus on the right test, can you share the specific test to which this applies?

**Comment by FreshXOpenSource** [comment]
```
[+] File Permissions
------------------------------------
  - Starting file permissions check
    /etc/lilo.conf                                            [ NOT FOUND ]
    /root/.ssh                                                [ NOT FOUND ]
```

**Comment by marcus-cr** [comment]
The root directory `/var/root` in macOS doesn't have a file or directory `.ssh`. Typically this is found in the user's home directory, such as `/Users/marcus/.ssh`. It isn't created until the non-privileged user actually uses SSH for the first time, so it seems.

**Comment by FreshXOpenSource** [comment]
/var/root/.ssh is  used only if you work / use SSH as root (which is not the case on default macOS systems). The question in the end is if lynis 
- runs regularly as root in a cron job etc to monitor systems -> then its a good test still or if it 
- runs occasionally as a user -> then a proper usage of sudo is the better way

**Comment by marcus-cr** [comment]
Yes, the root account is disabled by default. You have the ability to run lynis as a privileged user or non-privileged user with the `--pentest` option. Normally I run lynis manually instead of as a cron job. @mboelen may be able to assist with your new question.

**Comment by mboelen** [comment]
The file permissions check is receiving its input from the profiles. In this case you can manually override the files and paths to be checked via the profile. So this is just an innocent message actually. We made a change to hide "not found" entries with a recent update: https://github.com/CISOfy/lynis/commit/cd63e2389ef9aef5b8d2e12f472243d243c6ce1e
