### ISSUE TITLE
Error in boot_services test BOOT-5104

### ISSUE THREAD

**Issue by caderobinson** [CISOfy/lynis#321]
Get a null byte warning in the boot services test on Arch.
[+] Boot and services
------------------------------------
/usr/share/lynis/include/tests_boot_services: line 74: warning: command substitution: ignored null byte in input
  - Service Manager                                           [ systemd ]

The log it seems to be working:
2016-11-08 10:50:57 Performing test ID BOOT-5104 (Determine service manager)
2016-11-08 10:50:57 Result: cmdline found = /sbin/init
2016-11-08 10:50:57 Action: checking symlink for file /sbin/init
2016-11-08 10:50:57 Note: Using real readlink binary to determine symlink on /sbin/init
2016-11-08 10:50:57 Result: readlink shows /usr/lib/systemd/systemd as output
2016-11-08 10:50:57 Result: symlink found, pointing to file /usr/lib/systemd/systemd
2016-11-08 10:50:57 Found: systemd
2016-11-08 10:50:57 Result: service manager found = systemd

**Comment by mboelen** [comment]
Thanks for reporting. Looks like a "\0" that might be in the output. What does this command below show for you:
tr -d '\0' < /proc/1/cmdline | awk '/(^\/|init)/ { print $1 }' | hexdump -c

**Comment by caderobinson** [comment]
I think the null byte is related to readline 7.
I had a bunch of Arch "testing" packages installed and reverted readline from 7 to 6.3 and the null byte goes away. Might be a heads up that it is coming thought.

**Comment by caderobinson** [comment]
This is the output:
$ tr -d '\0' < /proc/1/cmdline | awk '/(^\/|init)/ { print $1 }' | hexdump -c
0000000   /   s   b   i   n   /   i   n   i   t  \n                    
000000b

vs without the "tr"
$ awk '/(^\/|init)/ { print $1 }' /proc/1/cmdline | hexdump -c
0000000   /   s   b   i   n   /   i   n   i   t  \0  \n                
000000c

**Comment by mboelen** [comment]
Good to know about readline 7. I had a quick peek in their change log, but can't make up if it is intended behavior or a bug on their side. So before we start stripping things, I propose we leave things in Lynis as-is. If the warning shows up, this ticket will act as a reference.

Thanks again for providing this feedback.
