### ISSUE TITLE
SSH Required to Clone

### ISSUE THREAD

**Issue by nstr10** [CISOfy/lynis#326]
The documentation states that one should run `git clone git@github.com:CISOfy/lynis.git` to get started.

Outbound SSH is disabled on many organization's networks (mine included) so you may want to make a note of that in the documentation and offer an alternate solution.

**Comment by mboelen** [comment]
Thanks for letting us know. It has been altered in the README.me to git clone https://github.com/CISOfy/lynis, which is a more firewall-friendly way :)
