### ISSUE TITLE
./lynis audit Dockerfile says " Error: Invalid option 'Dockerfile'"

### ISSUE THREAD

**Issue by aschmidt75** [CISOfy/Lynis#33]
```
# ./lynis audit Dockerfile ../Dockerfile

[ Lynis 2.1.0 ]
....

  Error: Invalid option '../Dockerfile'
  See man page and documentation for all available options.
```

both in a vm (Linux vagrant-ubuntu-trusty-64 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux) and OSX.

Do i use this in a wrong way? According to docs
``` 
 Mode:

    audit
        audit system                  : Perform security scan
        audit Dockerfile <file>       : Analyze Dockerfile
```

**Comment by mboelen** [comment]
Typo in the help. It should be "audit dockerfile".
Files have been corrected, thanks for reporting.

**Comment by aschmidt75** [comment]
That was easy :) It's working now!
Thank you!
