### ISSUE TITLE
Script fails: /usr/share/lynis/include/tests_kernel

### ISSUE THREAD

**Issue by noci2012** [CISOfy/lynis#330]
V2.1.1
[+] Kernel
------------------------------------
  - Checking default run level                                [ 3 ]
  - Checking CPU support (NX/PAE)
    CPU support: PAE and/or NoeXecute supported               [ FOUND ]
  - Checking kernel version and release                       [ DONE ]
  - Checking kernel type                                      [ DONE ]
  - Checking loaded kernel modules                            [ DONE ]
      Found 252 active modules
  - Checking Linux kernel configuration file                  [ FOUND ]
  - Checking core dumps configuration                         [ DISABLED ]
    - Checking setuid core dumps configuration                [ DEFAULT ]
/usr/share/lynis/include/tests_kernel: line 516: [: too many arguments
  - Check if reboot is needed                                 [ UNKNOWN ]

failure is due to returning more then one result from ls... 

after changing:

 [ ! `ls /boot/kernel* 2> /dev/null` != "" ]

(on line 516 in /usr/share/lynis/include/tests_kernel) to: 

 [ ! "$(ls /boot/kernel* 2> /dev/null)" != "" ]

it works as intended.

**Comment by mboelen** [comment]
Thanks for this catch. Would like to contribute by turning this into a pull request? This way you become history in the shared efforts of the project. If this is your first pull request: https://help.github.com/articles/creating-a-pull-request/

**Comment by noci2012** [comment]
I cannot fix it in 2.1.1.. After forking 2.1.1 is not editable.
in Master (2.4.0+) is has been fixed. (probably before that one).

line 537:         elif [ ! "$(ls ${ROOTDIR}boot/kernel* 2> /dev/null)" = "" ]; then

**Comment by mboelen** [comment]
Ok, if I understand correctly is already has been fixed and this issue can be closed. Thanks for reporting.
