### ISSUE TITLE
Feature request - json output

### ISSUE THREAD

**Issue by hyperized** [CISOfy/lynis#331]
We'd love to receive the output of the results to be optionally given in `json` format so we can automatically parse the output and compile reports for our machines.

This could be given in the shape of the `--report-json` parameter. This can be combined with the `--quiet` parameter to skip the 'checking' results.

Thanks!

**Comment by mboelen** [comment]
Thanks for your request. As we use shell script for this project, outputting in json is not that easy. Did you see the lynis-report.dat file?

**Comment by hyperized** [comment]
I did not see the .dat file (will check it out), we were looking into doing this runtime, to compile a list of all unique issues / warnings to feed right into our ticket system.

But I understand that JSON is not a native shell experience and will likely include unwanted dependencies.

Having the .dat files will probably solve our need for now.

**Comment by mboelen** [comment]
Sounds good and yes, we rather don't add any dependencies. Most likely it will be what you are looking for, as it is the raw data.

Will close this ticket. And please leave a star if you like Lynis :)

**Comment by d4t4king** [comment]
It's not JSON, but I could probably add that as a feature.....

https://github.com/d4t4king/lynis_report

**Comment by mboelen** [comment]
Thanks @d4t4king for the addition and being part of the Lynis ecosystem.

One suggestion from my side: your existing tool name collides with the generic name "lynis report" and might confuse people. A better name could be Lynis Report Export or Lynis Report Converter. This way you might get more hits when people search for the outcome they want to achieve, and also the purpose of your tool.

**Comment by d4t4king** [comment]
Thanks for the feedback, @mboelen.  I'll take it into consideration.

@hyperized I've added JSON output (pipe to `/usr/bin/json_pp` for pretty print), and am working on XML.
