### ISSUE TITLE
Error: Invalid option system!

### ISSUE THREAD

**Issue by mclucario** [CISOfy/lynis#332]
**OS:** Debian 8.6
**Lynis Version:** Lynis 1.6.3 (APT-GET)

Hey, when I try to use "lynis audit system" I just get the error "Error: Invalid option system!". I took the stuff from the getting started page and im kind of confused.

**Comment by mboelen** [comment]
I see you got an old version of Lynis. Update to the latest one by using the version from GitHub, our website, or the software repository: https://packages.cisofy.com

That should solve it. If so, please leave a star :)
