### ISSUE TITLE
False positive MAIL-8818 when postfix is not listening on any socket

### ISSUE THREAD

**Issue by opoplawski** [CISOfy/lynis#334]
We configure postfix for outgoing only messaging - so it is not listening on any socket and so check MAIL-8818 is not relevant.

Unfortunately, it does not look like postconf reports this.  But perhaps you could test for the presence of running smtpd processes.

**Comment by mboelen** [comment]
Thanks for reporting this. Do you get a specific message?

**Comment by opoplawski** [comment]
yeah, the MAIL-8818 one:
```
[+] Software: e-mail and messaging
------------------------------------
  - Checking Exim status                                      [ NOT FOUND ]
  - Checking Postfix status                                   [ RUNNING ]
  - Checking Postfix configuration                            [ FOUND ]
    - Postfix banner                                          [ OK ]

  Warnings (2):
  ----------------------------
  ! Found mail_name in SMTP banner, and/or mail_name contains 'Postfix' [MAIL-8818] 
      https://cisofy.com/controls/MAIL-8818/

  Suggestions (31):
  ----------------------------
  * You are advised to hide the mail_name (option: smtpd_banner) from your postfix configuration. Use postconf -e or change your main.cf file (/etc/postfix/main.cf) [MAIL-8818] 
      https://cisofy.com/controls/MAIL-8818/
```

**Comment by mboelen** [comment]
If you feel this is an accepted configuration for your situation (which I can agree with), then you can disable the particular test via your custom.prf file on those machines. Another option is simply to change the banner, that will remove it as well.

Sorry for the delay in answering. Filtering in GitHub on responses is not perfect yet.
