### ISSUE TITLE
Inconsistent key name: localhost-mapped-to

### ISSUE THREAD

**Issue by d4t4king** [CISOfy/lynis#335]
More (if not all, except this one) key names in the lynis-report.dat are named using the underscore.  The subject key name uses hyphens, which inconsistent with the rest of the tool.

**Comment by mboelen** [comment]
That is a good observation. We started years ago with underscores. Slowly we will migrate everything to hyphens, starting with the profiles.

**Comment by mboelen** [comment]
Closing this item, as this is work in progress (for longer period of time).
