### ISSUE TITLE
Invalid key in lynis-report.dat

### ISSUE THREAD

**Issue by d4t4king** [CISOfy/lynis#336]
```Result: expose_php option is turned on, which can expose useful information for an attacker```

The above bare line was found in lynis-report.dat and not associated with any key; i.e. did not match the "key=value" format for the file.

**Comment by mboelen** [comment]
What do you mean it is not associated with any key? Do you mean it is listed as a suggestion, but no other lines related to that issue where stored?

**Comment by d4t4king** [comment]
Here is a snippet from `lynis-report.dat`:
```
mysql_running=1
postgresql_running=1
warning[]=PHP-2372|PHP option expose_php is possibly turned on, which can reveal useful information for attackers.|-|-|
suggestion[]=PHP-2372|Change the expose_php line to: expose_php = Off|-|-|
Result: expose_php option is turned on, which can expose useful information for an attacker
suggestion[]=PHP-2376|Change the allow_url_fopen line to: allow_url_fopen = Off, to disable downloads via PHP|-|-|
syslog_daemon_present=1
syslog_daemon[]=systemd-journal
```

**Comment by mboelen** [comment]
Some keys are not stored, it depends on the test. Any specifics you were looking for to parse?

**Comment by d4t4king** [comment]
Not storing a key in the "report" breaks the rule of "key=value" pair, established by the majority of the output, forcing the parser (whether human or programmatic) to toss out the errant value(s) as anomalous.

**Comment by mboelen** [comment]
Discussed this subject internally. Right now such data is not used by our solution, so to keep the report file "lean", we don't store everything. So currently we don't see this as an issue, but that might change over time. Thanks for sharing, appreciated as always :)
