### ISSUE TITLE
Report for files that are not from a package management system

### ISSUE THREAD

**Issue by rkubik** [CISOfy/lynis#337]
Even better, report for files that are not from a signed RPM package or trusted APT repository. If this is something you would accept as a PR I don't mind starting the work.

**Comment by mboelen** [comment]
Thanks for the suggestion and the proposal to create a PR.

We actually had such test in our plugins, but it takes a long time to complete as you need to check each individual binary. I would suggest running a check like this in a separate cron job (e.g. weekly) as an independent check.

**Comment by mboelen** [comment]
Closing this issue, as the idea is good, but would make a scan very slow.
