### ISSUE TITLE
'cat' Binary Not Being Found?

### ISSUE THREAD

**Issue by quantumpacket** [CISOfy/lynis#338]
I was having issues with the AppArmor tests and narrowed it down to it not being able to pass the file check on this line [tests_mac_frameworks#L56](https://github.com/CISOfy/lynis/blob/master/include/tests_mac_frameworks#L56). The file does exist and can be read, and I am able to use `cat` on it just fine. So I edited the tests file and echoed `${CAT_BINARY}` right before the point of failure, only to have it output an empty string. Which explains why the statement kept producing the wrong status code. Yes, this is all being done as root.

I checked my log file, and **did not** find the following as I would expect:
> Found known binary: cat (generic file handling)

It appears `cat` is not being detected and the path is defaulting to empty. The system this is being tested on is *Ubuntu Server 16.04* and I'm using *Lynis 2.4.0* and the path to my binary is `/bin/cat`. Which after examining the Lynis code is already a path that is searched, in fact it's the first directory. I'm not sure why the binary detection is failing in this case.

This works fine for me.
```sh
/bin/cat /sys/kernel/security/apparmor/profiles
```

Let me know if there is anything else I need to provide to figure out what is going wrong.

**Comment by rhyven** [comment]
Could you please post the output of `sudo apparmor_status | grep cat`?

I've had issues with apparmor doing funny stuff and leaving behind no trace, particularly with logrotate and man.  Since you're using it, that's the first thing I'd look into.

**Comment by quantumpacket** [comment]
Nothing is returned when I run that command.

I don't think this is an issue with AppArmor I had just mentioned it as it was that test file that the issue was found in. The problem as far as I can tell is this line [binaries#L104](https://github.com/CISOfy/lynis/blob/master/include/binaries#L104) is not being triggered so `${CAT_BINARY}` is not being populated from its [default value of empty](https://github.com/CISOfy/lynis/blob/master/include/consts#L62). 

So when this snippet is ran, the empty value is used instead of the path to `cat`. 
```sh
FIND=$(${CAT_BINARY} ${FILE} 2> /dev/null)
if [ $? -eq 0 ]; then CAN_READ_FILE=1; fi
```
So the command ends up as:
```sh
 /sys/kernel/security/apparmor/profiles 2> /dev/null
```
Since part of the command is missing, it fails. This causes the status to not equal 0 and `CAN_READ_FILE=1` is never reached. So the tests are never done for AppArmor.

**Comment by rhyven** [comment]
Yep if that grep command doesn't return anything, it's a good indication that AppArmor isn't causing the failure.  I do realise your comments weren't about the tests for AppArmor, it's just that some of the profiles are a bit broken, and I've been bitten by them in the past -- resulting in similar weird behaviour  ;-)

**Comment by quantumpacket** [comment]
I found the problem. Support for `cat` was added in this commit https://github.com/CISOfy/lynis/commit/1cb1fc40ca5188dd3eef37c853fe3a76b22a37f7 which was 1 day after the 2.4.0 release. However, the broken code in this issue, which is part of 2.4.0 is dependent on that later commit. The test should not have been enabled in a release half completed. :confused:

**Comment by mboelen** [comment]
Yes, that one is fixed and sorry it gave you troubles. We will be releasing a new version soon.
