### ISSUE TITLE
Unclear wording in suggestion

### ISSUE THREAD

**Issue by marios-zindilis** [CISOfy/lynis#34]
In the file `include/tests_hardening` line 105 reads: `ReportSuggestion ${TEST_NO} "Harden the system by installing one or malware scanners to perform periodic file system scans"`.

This is not clear. Did you mean "one or **more** malware scanners"? Did you mean "one **of** malware scanners"?

**Comment by mboelen** [comment]
Thanks for reporting this. The related description has been improved.
