### ISSUE TITLE
DBS-1882 - misses redis config file:

### ISSUE THREAD

**Issue by noci2012** [CISOfy/lynis#344]
It doesn't check for /etc/redis.conf   ( gentoo based system)

**Comment by mboelen** [comment]
Thanks for reporting. Do you want to create a pull request for that?

**Comment by noci2012** [comment]
I didn't lookinto the code yet, but that will be later.

**Comment by noci2012** [comment]
https://github.com/noci2012/lynis/pull/1 ??

**Comment by mboelen** [comment]
Hi @noci2012, This is fixed now, right?

**Comment by noci2012** [comment]
Didn;t check yet. Was busy elsewhere in RL.  Will looktoday

**Comment by noci2012** [comment]
Yes fixed.
