### ISSUE TITLE
hostid2 is not properly filled in

### ISSUE THREAD

**Issue by mattkinsey** [CISOfy/lynis#349]
It appears there is a bug in GetHostID that I had crop up on a fresh ubuntu 16.04 install.

It appears that GetHostID attempts to fill in hostid2 based on the public ssh keys present in /etc/ssh (https://github.com/CISOfy/lynis/blob/master/include/functions#L1029). In the event that these keys don't exist it instead puts the value of /etc/machine-id into STRING_TO_HASH. However it then goes on to not use STRING_TO_HASH and simply hashes the (in this case empty) value in DATA_SSH. This results in an empty hostid2.

**Comment by mboelen** [comment]
Great catch, it has been solved with commit https://github.com/CISOfy/lynis/commit/ed45fe7b293860e7c2bf55fc903e242d39532486
