### ISSUE TITLE
I'm confused: lynis-2.0.0.tar.gz contains lynis 1.6.4

### ISSUE THREAD

**Issue by msx** [CISOfy/lynis#35]
Hello,
I downloaded the package mentioned in the subject from the website but when running Lynis it says it is version 1.6.4; furthermore, issuing --check-update effectively tag it as outdated.

/me scratches his head trying to figure out what's happening here...

**Comment by msx** [comment]
Forgive me, I'm asleep and was running the version installed through the packet manager :clap:

**Comment by mboelen** [comment]
No problem :)
