### ISSUE TITLE
HTTP-6641 - should use mod_reqtimeout instead of mod_qos

### ISSUE THREAD

**Issue by kforner** [CISOfy/lynis#350]
According to wikipedia (https://en.wikipedia.org/wiki/Slowloris_(computer_security)) : 

> Since Apache 2.2.15, Apache ships the module **mod_reqtimeout** as the official solution supported by the developers.[6]

so, maybe the suggestion should be mod_reqtimeout ?

**Comment by mboelen** [comment]
Hi @kforner, thanks for your suggestion. It has been implemented with commit https://github.com/CISOfy/lynis/commit/57770fe332d31124ed4dc44a0329885ac226ea36

**Comment by kforner** [comment]
nice, thank.
