### ISSUE TITLE
Lynis doesnt update (Phase 1 Downloading Details)

### ISSUE THREAD

**Issue by playtime999** [CISOfy/lynis#351]
===============================================================================
        Lynis update available
      ===============================================================================

        Current version is more than 4 months old

        Current version : 232   Latest version : 240

        Please update to the latest version.
        New releases include additional features, bug fixes, tests and baselines.

        Download the latest version:
        Packages (DEB/RPM) -  https://packages.cisofy.com
        Website            -  https://cisofy.com/downloads/
        GitHub             -  https://github.com/CISOfy/lynis

      ===============================================================================

Note: local data file /usr/local/lynis/client-version does not exist. It will be created after updating. (update_local_version_info)
[Phase 1] Downloading details

**Comment by mboelen** [comment]
The update command is rarely used and will be deprecated. Better option is to use the software repository of https://packages.cisofy.com to update. Does that help?

**Comment by playtime999** [comment]
I have solved this issue yesterday Thanks you for the tool :+1:
