### ISSUE TITLE
AUTH-9283 - Possible False Positive - User Without Password - SLES 11

### ISSUE THREAD

**Issue by H8to** [CISOfy/lynis#352]
There is the following warning:
`- Accounts without password                                 [ WARNING ]`
when users do not have a password set but bash etc. enabled.

```
! Found accounts without password [AUTH-9283] 
      https://cisofy.com/controls/AUTH-9283/
```
I think this is a false positive or further validation on pam settings should be done.
Default setting is that it is not allowed to switch user to account with no password set as described [here](http://unix.stackexchange.com/questions/316657/why-cant-su-be-used-to-switch-to-users-with-empty-password).

> nullok
> 
> The default action of this module is to not permit the user access to a service if their official password is blank. The nullok argument overrides this default and allows any user with a blank password to access the service.
> 
> nullok_secure
> 
> The default action of this module is to not permit the user access to a service if their official password is blank. The nullok_secure argument overrides this default and allows any user with a blank password to access the service as long as the value of PAM_TTY is set to one of the values found in /etc/securetty.

Maybe this is a special case for SLES. However, I'm not able to switch user to one of the accounts with bash enabled but blank password.

Regards,
Sebastian

**Comment by mboelen** [comment]
Hi Sebastian. Thanks for reporting this.


Looks like Lynis is "right" in the way that the user has no password, but at the same time it can't be used as you have a second level of defense in the form of the PAM configuration. As you can imagine things can become very complicated if a full trail is to be checked (especially with PAM in the mix). I suggest that you skip the test on that system (skip-test=AUTH-9283 in custom.prf).
