### ISSUE TITLE
When checking "logrotates" properties, subdirectories are not well took into acccount.

### ISSUE THREAD

**Issue by sklerder** [CISOfy/lynis#36]
Actually, at line 277 of "~lynis/include/tests_logging", the check is made against :
sed 's/\/[a-zA-Z_.-]$//g' | sort | uniq
It should be done against :
sed 's//[^/]$//g'
But because we are checking against a string that should contain a "/", it's better to chack with :
sed 's@/[^/]$@@g'

Pull request #37 available including this correction.

**Comment by sklerder** [comment]
Actually, at line 277 of "~lynis/include/tests_logging", the check is made against :
sed 's/\/*[a-zA-Z_.-]*$//g' | sort | uniq
It should be done against :
sed 's//[^/]*$//g'
But because we are checking against a string that should contain a "/", it's better to chack with :
sed 's@/[^/]*$@@g'

**Comment by mboelen** [comment]
Change has been applied. Thanks for reporting.
