### ISSUE TITLE
Setting Apache, nginx, php paths in profile file

### ISSUE THREAD

**Issue by medfx** [CISOfy/lynis#361]
Hi,
Is it possible to set the right paths for Apache, nginx and php in the profile file via options, or do i need to change the test file in the include folder?

Thanks!

**Comment by mboelen** [comment]
Right now this can not be set yet. Step by step we are changing the tests to allow them to be customized via the profile(s).

What paths do you have/use currently?

**Comment by medfx** [comment]
I want to audit the default configuration of the serverpilot.io web stack.

> ServerPilot is an automated service for managing your WordPress sites and other PHP apps hosted with cloud servers on DigitalOcean, Linode, Vultr, and more. (Running on Ubuntu)

To enable automatic updates they install their own versions of apache, php and nginx with an `-sp` suffix.
So `/etc/apache-sp`, `/etc/php7.1-sp` and `/etc/nginx-sp`.


I know here is not the right place to ask this, but do you think it will someday be possible to purchase the Cisofy SaaS Premium package for fewer than minimum 5 servers? Maybe even for only one server?

**Comment by mboelen** [comment]
My apologies that this did not get the right follow-up. Other work including a rewrite and preparations for major 3.x release got priority.

At this stage, we try to clean out as many issues, so we can push out the 3.x release. I will close this one, but that does not mean this work will be ignored. After the release we will continue adding options to make the profile more flexible for needs like this.
