### ISSUE TITLE
AUTH-9288 can have false positive when password is locked

### ISSUE THREAD

**Issue by pyllyukko** [CISOfy/lynis#362]
Hello.

I'm experiencing a FP with AUTH-9288 with an account that has it's password locked.

The thing is, that (for some reason), the particular system account has an entry in ```Password expires``` field and the regex does not match ```:!!:```.

So the [tests_authentication](https://github.com/CISOfy/lynis/blob/master/include/tests_authentication) has:
```
# Skip fields with a !, *, or x, or !* (field $3 is last changed, $5 is maximum changed)
FIND=$(${EGREPBINARY} -v ":[\!\*x](\*)?:" /etc/shadow | ${AWKBINARY} -v today=${DAYS_SINCE_EPOCH} -F: '{ if (($5!="") && (today>$3+$5)) { print $1 }}')
```
I guess the regex could be something like ```":[\!\*x]([\*\!])?:"``` to match also ```:!!:```? Then again, maybe it should be written even more specific, so it wouldn't match e.g. ```x*```. Something like ```":(x|\*|\!(\*|\!)?):"```, which would match **exactly** ```x```, ```*```, ```!```, ```!*``` and ```!!```?

Also the test matches locked accounts with password hash, e.g. ```:!!$6...```. I think if the password is locked, it shouldn't be a problem.

**Comment by mboelen** [comment]
Thanks @pyllyukko 
I would go for the second more specific regex. Want to make a pull request?

**Comment by pyllyukko** [comment]
> Want to make a pull request?

I'll do that.
