### ISSUE TITLE
Puppet not detected when installed from PuppetLabs packages

### ISSUE THREAD

**Issue by crispygoth** [CISOfy/lynis#365]
I have Puppet installed on my servers using the packages provided by Puppetlabs at apt.puppetlabs.com. These packages install Puppet into ``/opt/puppetlabs`` rather than under ``/usr``. However when I run Lynis on one of these servers I get:

  * Determine if automation tools are present for system management [TOOL-5002] 
      https://cisofy.com/controls/TOOL-5002/

It seems like Lynis is unable to detect puppet when it's installed under ``/opt/puppetlabs`` -- full path to puppet binary is ``/opt/puppetlabs/puppet/bin/puppet`` (also symlinked from ``/opt/puppetlabs/bin/puppet``). I think it would make sense for Lynis to check this location in addition to the standard bin directories.

**Comment by mboelen** [comment]
Commit https://github.com/CISOfy/lynis/commit/b306ab891f8710dc99069e3c2116ddc2c885c90c has been implemented to detect this. Can you see if it works for you?

**Comment by crispygoth** [comment]
Yes, that seems to work. The latest master detects Puppet fine on my system now.

**Comment by mboelen** [comment]
Thanks for the quick response, closing this issue.
