### ISSUE TITLE
Package database - false positive?

### ISSUE THREAD

**Issue by fusionneur** [CISOfy/lynis#368]
I get the following warning:

 ! Found one or more problems in the package database [PKGS-7384]
      https://cisofy.com/controls/PKGS-7384/

Let me know if you need further info. Thank you.

Versions below:
[root@host~]# lynis -V
2.4.5

[root@host]# rpm -qa | egrep 'rpm|yum|dnf'
rpm-python-4.11.3-21.el7.x86_64
yum-3.4.3-150.el7.centos.noarch
rpm-4.11.3-21.el7.x86_64
rpm-build-4.11.3-21.el7.x86_64
perl-srpm-macros-1-8.el7.noarch
rpm-sign-4.11.3-21.el7.x86_64
PackageKit-yum-1.0.7-6.el7.centos.x86_64
yum-plugin-fastestmirror-1.1.31-40.el7.noarch
yum-langpacks-0.4.2-7.el7.noarch
redhat-rpm-config-9.1.0-72.el7.centos.noarch
yum-metadata-parser-1.1.4-10.el7.x86_64
deltarpm-3.6-3.el7.x86_64
yum-utils-1.1.31-40.el7.noarch
rpm-libs-4.11.3-21.el7.x86_64
rpmdevtools-8.3-5.el7.noarch
rpm-build-libs-4.11.3-21.el7.x86_64

[root@host~]# uname -a
Linux host 4.10.1-1.el7.elrepo.x86_64 #1 SMP Sun Feb 26 19:47:48 EST 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mboelen** [comment]
You can see the specific details from that test by using `lynis show details PKGS-7384`. That might reveal what problems it found. As there is no specific bug mentioned, closing the ticket.
