### ISSUE TITLE
who are your fingerprint public key ?

### ISSUE THREAD

**Issue by sissisi** [CISOfy/lynis#374]
Hi,

Since twenty minutes, I search fingerprint of your public key, and i can not find fingerprint:

 CISOfy Software (signed software packages) <software@cisofy.com>

 In my OS, I get the fingerprint:

C80E 383C 3DE9 F082 E013  91A0 366C 67DE 91CA 5D5F

Can you confirm ?

I think you should add the fingerprint for your public key.

Thanks.

Bests regards

**Comment by quantumpacket** [comment]
I'd like to point out that the GPG key used in the [verification examples](https://cisofy.com/documentation/lynis/#faq) and what is uploaded to the website, do not match what is currently being used to sign the releases.

What is in my keyring, and what is located at https://cisofy.com/files/cisofy-software.pub
```
pub   rsa4096/0x429A566FD5B79251 2014-11-04 [SC] [expires: 2030-10-31]
      Key fingerprint = 73AC 9FC5 5848 E977 024D  1A61 429A 566F D5B7 9251
uid                   [ unknown] CISOfy (Software Signing Key) <security@cisofy.com>
sub   rsa4096/0x0F7E8B616E8847E1 2014-11-04 [E] [expires: 2030-10-31]
      Key fingerprint = DB79 ADB9 A432 0D08 5DC2  81FC 0F7E 8B61 6E88 47E1
```

However, the key ID used for signing the Git releases is: `26141F77A09D7F04`

```
git tag --verify 2.4.8
object 5ef342037f82287e193ba7feec0b359ff083143a
type commit
tag 2.4.8
tagger Michael Boelen <michael.boelen@cisofy.com> 1490800168 +0200

Lynis 2.4.8
gpg: Signature made Wed 29 Mar 2017 11:09:28 AM EDT
gpg:                using RSA key 0x26141F77A09D7F04
gpg: Can't check signature: No public key
error: could not verify the tag '2.4.8'
```

**Comment by mboelen** [comment]
The release on GitHub is tagged and signed with my developer key. That is different from the signed releases on the website itself. We are changing things on the background to get them all in line, so they can be used on the website, GitHub, and software repository.

To confirm, this is my key:

```
pub   4096R/26141F77A09D7F04 2014-09-11 [expires: 2019-09-10]
uid                          Michael Boelen <michael.boelen@cisofy.com>
```

**Comment by quantumpacket** [comment]
@mboelen 

On this page https://packages.cisofy.com/community/#debian-ubuntu the `wget` example uses `http://packages.cisofy.com/keys/cisofy-software-public.key` to fetch the key to import. The key is served over HTTP, so you can't trust it's integrity to be imported *as much* as if it were sent over HTTPS.

I was expecting it to redirect me to HTTPS, but it doesn't. Since the server isn't enforcing a secure connection, the key and any file can potentially be tampered with if someone uses HTTP by accident like in the above example. Just a heads up in case this is a server mis-configuration.

**Comment by sissisi** [comment]
Thanks for the replies.

Thanks at @quantumpacket quantumpacket, I found keyring.
https://cisofy.com/files/cisofy-software.pub

also thanks at @mboelen .
All works,  At the time who I wrote the issue, some links in Website does not work.

This issue is resolved.

Thanks

**Comment by quantumpacket** [comment]
@mboelen I can't verify tagged releases via Git.

```
git tag -v 3.0.1
object 21b5493a1cb679d68e3da15ffdfc4f0a46a76776
type commit
tag 3.0.1
tagger Michael Boelen <michael.boelen@cisofy.com> 1601897096 +0200

Lynis 3.0.1
gpg: Signature made Mon 05 Oct 2020 07:24:56 AM EDT
gpg:                using RSA key 26141F77A09D7F04
gpg: Can't check signature: No public key
```

I imported the latest key per the Lynis [docs](https://cisofy.com/documentation/lynis/):

```
pub   rsa4096 2014-11-04 [SC] [expires: 2030-10-31]
      73AC 9FC5 5848 E977 024D  1A61 429A 566F D5B7 9251
uid           [ unknown] CISOfy (Software Signing Key) <security@cisofy.com>
sub   rsa4096 2014-11-04 [E] [expires: 2030-10-31]
```

I thought according to your comment above that the same key would be used for all areas. What key(s) should I be using? Thanks.
