### ISSUE TITLE
CRYP-7902 Test is Marking None SSL PEM Certificate files as expired

### ISSUE THREAD

**Issue by elatov** [CISOfy/lynis#376]
I have noticed that when running **lynis** from **cron**, it throws the following errors:

    unable to load certificate
    139902189282960:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:696:Expecting: 
    TRUSTED CERTIFICATE
    unable to load certificate

Looking over the report, I see that's it's marking some files that are not certificates as expired:

    <> grep 'has been expired' lynis.log
    2017-04-11 21:59:55 Result: certificate /etc/apache2/nssdb/cert8.db has been expired
    2017-04-11 21:59:55 Result: certificate /var/www/project/certificate.js has been expired

Looking at the actual test, it's using the following command to first locate potential certs:

    sFINDCRTS=$(${FINDBINARY} ${DIR} -name "*.crt" -or -name "*.pem" -or -name "cert*" -and -type f -print 2> /dev/null)

And then it runs **openssl** on the each file

    EXIT_CODE=$(${OPENSSLBINARY} x509 -noout -checkend 0 -in ${FILE} -enddate > /dev/null ; echo $?)

I don't think we should assume that if a file starts with the name **cert** then it's a certificate file. In the **find** command maybe we can add **and** logic rather than **or** logic. Also if we are only checking for PEM files (x509 base64 certs), we can maybe do a simple check like this:

    <> grep 'BEGIN CERT' -q /usr/share/gnupg2/com-certs.pem
    <> echo $?
    0
    <> grep 'BEGIN CERT' -q /var/www/project/certificate.js
    <> echo $?
    1

But if you guys are checking for other file types, it might get trickier :)

**Comment by mboelen** [comment]
Thanks for reporting. We will look into this and see if we can come up with a good way to filter out this. Looks like your suggestion at the end might already be a winner :)

**Comment by AlainG80** [comment]
```
if $(${OPENSSLBINARY} x509 -in ${FILE} -text -noout)
unable to load certificate
12626:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:647:Expecting: 
elif $(${OPENSSLBINARY}  x509 -in ${FILE} -inform der -text -noout)
unable to load certificate
13978:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1306:
13978:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:tasn_dec.c:380:Type=X509
fi
```
https://stackoverflow.com/questions/5215771/how-can-i-check-if-the-certificate-file-i-have-is-in-pem-format

**Comment by mboelen** [comment]
Implemented with commit https://github.com/CISOfy/lynis/commit/211fb9117ce379cea5d040cb4dd9a392acaf5831
