### ISSUE TITLE
Granular sysctl "excludes"

### ISSUE THREAD

**Issue by d4t4king** [CISOfy/lynis#378]
One should have the option of granularly excluding sysctl checks, similar to how SSHD check are atomized.

For example: in certain environments, I want to disable ```log_martians``` to prevent excessive logging.  However, I would like to continue to adhere to the other recommended settings.  As is, one can only exclude the entire sysctl check.

**Comment by mboelen** [comment]
Sounds like a good addition. Want to give it a shot with a pull requests? It can be made similar to what the SSH test has.

**Comment by d4t4king** [comment]
For me to submit a pull request would require reading/reversing what was done with the SSH checks, then imitating for sysctl.  It might be some time before I have anything to submit, since any contribution to this project is done on my personal time and is uncompensated.  ;-)

**Comment by d4t4king** [comment]
Finally got a little time to dig into this a little....

It looks like if I add the `config-data:...` lines for the values that I want to change to `/etc/lynis/custom.prf`, I get the desired outcome, i.e. `lynis` accepts the values I specify in custom.prf as valid.

So to delineate the steps for the example:
```
# filter and copy the desired lines from the default profile to the custom profile:
grep -h "^config-data=sysctl;" .../lynis/default.prf | grep "log_martians >> /etc/lynis/custom.prf
# modify the custom profile config data to the values desired, also
# reduce the hardening points since this might not be considered "hardened" by some.
sed -i -e 's/log_martians;1;1;Log/log_martians;0;0;Log/' /etc/lynis/custom.prf
# rerun lynis audit, and now lynis thinks o is the desired value for log_martians
./lynis audit system
# outputs:
#    - net.ipv4.conf.all.forwarding (exp: 0)                   [ OK ]
#    - net.ipv4.conf.all.log_martians (exp: 0)                 [ OK ]
#    - net.ipv4.conf.all.mc_forwarding (exp: 0)                [ OK ]
#    .....
#    - net.ipv4.conf.default.accept_source_route (exp: 0)      [ OK ]
#    - net.ipv4.conf.default.log_martians (exp: 0)             [ OK ]
#    - net.ipv4.icmp_echo_ignore_broadcasts (exp: 1)           [ OK ]
```
I'm not sure if that's the desired behavior, but it works for me and is definitely easier than trying to paste in test elimination logic.  ;-)

**Comment by mboelen** [comment]
So in other words: no change is needed, right?

If so, let's close this one :)

**Comment by d4t4king** [comment]
Correct.  As stated, this works for me.  

Concur on close.
