### ISSUE TITLE
Mark OSSEC as a malware scanner

### ISSUE THREAD

**Issue by mboelen** [CISOfy/lynis#379]
Perform detection of OSSEC (already part of integrity tests). When found, mark availability of malware scanner.

**Comment by superpoussin22** [comment]
perhaps you should also add wazuh :) which is a variant with oscap support ...

**Comment by d9705996** [comment]
Please add [wazuh-agent](https://wazuh.com/) as a valid malware scanner.  OSSEC but with PCI-DSS compliance

```
rpm -qa | grep wazuh
wazuh-agent-2.0-1.el7.x86_64

```

**Comment by mboelen** [comment]
After reviewing: the state of rootkit checking on OSSEC is very outdated (most code untouched in 3 years). Therefore not considering this a malware scanning solution. Users are suggested to use tools like chkrootkit, rkhunter, ClamAV, or other tools that are updated more often or use signatures.
