### ISSUE TITLE
Lynis needs to drop privilleges to support homebrew on MacOSX

### ISSUE THREAD

**Issue by AlainG80** [CISOfy/lynis#382]
Given I run the version of today + mac ports patch:
When scanning I need to login as root.
Then I get the following error in my report:
> 
> [+] Ports and packages
> ------------------------------------
>   - Searching package managers
>     - Searching brew                                          [ FOUND ]
>     - Querying brew for installed packages
> Error: Running Homebrew as root is extremely dangerous and no longer supported.
> As Homebrew does not drop privileges on installation you would be giving all
> build scripts full access to your system.
>   - Checking ports for updates                                [ FOUND ]

Logfile /var/log/lynis.log doesn't give any more details.
Expected behavior: the program should drop privileges.

**Comment by mboelen** [comment]
Thanks for reporting this. Lynis doesn't drop privileges as it is a shell script and it does not have a default user to use (like nginx would use www-data on Ubuntu). If you would run Lynis as a non-privileged user, this error does not show up, right?

Not sure if there is a right fix here. If you run Lynis as root user (or indirectly via sudo), then you would also run Brew as root user. Unless there is a default user for Brew. Any suggestion from your side?

**Comment by AlainG80** [comment]
If the unprivileged user is still logged in, we can do something like this:
sudo -u $(who | cut -d' ' -f1 | uniq) brew update
I strongly recommend that the long term solution is that the program makes an unprivileged deamon account, for security purposes under any OS.
To get a free uid under MacOSX:
uid=$(($(sudo dscl . list /Users uid | grep -o '5..' | sort -u | tail -1)+1))
dscl . -create /Users/$username UniqueID $uid
dscl . -create /Users/$USERNAME UserShell /usr/bin/false

https://serverfault.com/questions/182347/add-daemon-account-on-os-x

**Comment by AlainG80** [comment]
With homebrew I can still run old mac versions:
```
--- ./include/osdetection.bak	2017-04-30 11:23:40.000000000 +0100
+++ ./include/osdetection	2017-04-30 11:25:37.000000000 +0100
@@ -46,6 +46,8 @@
                 OS_VERSION_NAME="unknown"
                 OS_FULLNAME="macOS (unknown version)"
                 case ${OS_VERSION} in
+                    10.7 | 10.7.[0-9]*) OS_FULLNAME="Mac OS X 10.7 (Lion)" ;;
+                    10.8 | 10.8.[0-9]*) OS_FULLNAME="Mac OS X 10.8 (Mountain Lion)" ;;
                     10.9 | 10.9.[0-9]*) OS_FULLNAME="Mac OS X 10.9 (Mavericks)" ;;
                     10.10 | 10.10.[0-9]*) OS_FULLNAME="Mac OS X 10.10 (Yosemite)" ;;
                     10.11 | 10.11.[0-9]*) OS_FULLNAME="Mac OS X 10.11 (El Capitan)" ;;
```

**Comment by mboelen** [comment]
Thanks for suggestions. This is an interesting case and has to be researched more in depth from our side, to see if this is in line with the goals of Lynis.

As Lynis is not a daemon process, we rather not switch back to a normal user. That is up to the user to do, especially as there could be multiple users on a single system that have Brew installed. Lynis does not have to be executed as root. So if Brew is discovered for the root user, and Brew gives a warning, it might be something to "accept" from an auditing point of view.

Just to be sure: on your system, do you have Brew installed as a root user, or only as a normal user?

**Comment by AlainG80** [comment]
Homebrew is installed under my normal user account. Only the make install step could require elevated privileges. That applies to all package auditing tools.
Using the $SUDO_USER variable should not conflict with multiple users accounts.
If a daemon is not an option for the GPL version, than at least all executables should have a full path to prevent privilege escalation.

**Comment by jpartain89** [comment]
Well, since errors are already displayed when running as NOT sudo, saying not every test would run without it, for the time being the same could be displayed when running AS sudo, that HomeBrew tests will NOT run when using Sudo.... Seeing as that is what happens... Therefore stopping HomeBrew tests on Sudo.

**Comment by mboelen** [comment]
Closing this issue at this moment, as there is not enough support for this item. We monitored the item to see if more macOS users feel the same. We rather prevent the usage of sudo or having the hard requirement of a dedicated user.

**Comment by jpartain89** [comment]
Well, it doesn't exactly seem that there is a large macOS user base that is active here on this page. Seeing as I just reported the issue about Lynis not identifying Mojave, of which any number of beta testers who would have been using Lynis would've reported such an issue months ago... 

The better reasoning could've been "the means of circumventing this issue is much too difficult and doesn't work with the rest of our code" instead of "our already tiny macOS user base just didn't respond with the same furor as any of the larger user base... 

Apologies if the above opinion came off as overly rude, but I don't care to sugarcoat things.
