### ISSUE TITLE
Add Protected Links Checks

### ISSUE THREAD

**Issue by quantumpacket** [CISOfy/lynis#386]
Add support for hardlink and symlink file protections per kernel filesystem docs:
https://www.kernel.org/doc/Documentation/sysctl/fs.txt

Safe:
> fs.protected_hardlinks=1
fs.protected_symlinks=1

Unsafe:
> fs.protected_hardlinks=0
fs.protected_symlinks=0

**Comment by mboelen** [comment]
Sounds like a good addition to check and can be added to the default.prf. Want to create a pull request?

**Comment by quantumpacket** [comment]
@mboelen I'll submit a PR shortly. I have two questions though. In `default.prf` we have:

> config-data=sysctl;kernel.suid_dumpable;0;1;Restrict core dumps;sysctl -a;url:https;//kernel.org/doc/Documentation/sysctl/kernel.txt;category:security;

From my understanding it should be `fs.suid_dumpable` as per https://www.kernel.org/doc/Documentation/sysctl/fs.txt unless these are both functionally equivalent?

RedHat shows the other `fs` options as such https://access.redhat.com/solutions/800023 too.

Should I correct that entry, and make a separate options block for all `fs` options?

**Comment by mboelen** [comment]
Thanks.

You are right, but they are the same. The existing one is for older kernels. So instead of replacing it, just add a new line. If a sysctl key can't be found, it is ignored.

**Comment by quantumpacket** [comment]
@mboelen Btw, we check for `fs.suid_dumpable` in https://github.com/CISOfy/lynis/blob/master/include/tests_kernel#L445-L466 but do not check for the older `kernel.suid_dumpable`. Does the older config lack granular options?
