### ISSUE TITLE
Function for parsing commandline options.

### ISSUE THREAD

**Issue by AlainG80** [CISOfy/lynis#387]
After the [commit](https://github.com/CISOfy/lynis/commit/4ecb9d4d05124b813cd4d7ddcaf5671c2f4c4765#commitcomment-21966803) of how to find the snort log file and snort config file, I realised that certain options can be chained or switch order. 
Therefore the awk third field will fail:

Ideally we should add a function that parses command line arguments from ps | grep -om1 process | awk -F-.. '/c/ {print $3}'
In awk this would be messing around with an array of arguments and a for loop, which is too complex for a one liner.
 
From the latest snort man page, we have the following options:
>        Snort - open source network intrusion detection system
> 
> SYNOPSIS
>        snort  [-bCdDeEfHIMNOpqQsTUvVwWxXy?] [-A alert-mode ] [-B address-conversion-mask ] [-c rules-file ] [-F bpf-file ] [-g group-name ] [-G id ] [-h home-net ] [-i interface ] [-k
>        checksum-mode ] [-K logging-mode ] [-l log-dir ] [-L bin-log-file ] [-m umask ] [-n packet-count ] [-P snap-length ] [-r tcpdump-file ] [-R name  ]  [-S  variable=value  ]  [-t
>        chroot_directory  ]  [-u  user-name ] [-Z pathname ] [--logid id ] [--perfmon-file pathname ] [--pid-path pathname ] [--snaplen snap-length ] [--help ] [--version ] [--dynamic-
>        engine-lib file ] [--dynamic-engine-lib-dir directory ] [--dynamic-detection-lib file ] [--dynamic-detection-lib-dir directory ] [--dump-dynamic-rules directory  ]  [--dynamic-
>        preprocessor-lib  file ] [--dynamic-preprocessor-lib-dir directory ] [--dynamic-output-lib file ] [--dynamic-output-lib-dir directory ] [--alert-before-pass ] [--treat-drop-as-
>        alert ] [--treat-drop-as-ignore ] [--process-all-events ] [--enable-inline-test ] [--create-pidfile ] [--nolock-pidfile ] [--no-interface-pidfile ] [--disable-attribute-reload-
>        thread ] [--pcap-single= tcpdump-file ] [--pcap-filter= filter ] [--pcap-list= list ] [--pcap-dir= directory ] [--pcap-file= file ] [--pcap-no-filter ] [--pcap-reset ] [--pcap-
>        reload ] [--pcap-show ] [--exit-check count ] [--conf-error-out ] [--enable-mpls-multicast ] [--enable-mpls-overlapping-ip ] [--max-mpls-labelchain-len ] [--mpls-payload-type ]
>        [--require-rule-sid ] [--daq type ] [--daq-mode mode ] [--daq-var name=value ] [--daq-dir dir ] [--daq-list [dir] ] [--dirty-pig ] [--cs-dir dir ] [--ha-peer ] [--ha-out file ]
>        [--ha-in file ] expression
> 

If snort is deamonised we can read its configuration file instead on linux. Although on MacOSX ps output is more accurate and the command line option parsing is a similar problem that probably extends to malware scanners as well.

Since ruleset and config errors are checked by:
snort -T -c $SNORT_CONFIG
The only tests that is useful is to see if the ruleset covers all open ports:
```
dscacheutil -q user | grep -A5 'name: snort'
name: snort
password: *
uid: 50x
gid: 50x
dir: /opt/local/var/snort
shell: /sbin/nologin
```
I will not make any contribution anytime soon, I'll probably uphrade to the 3.x brach to make use of the merging threats rulesets.
FIY: A NIDS/NIPS is impossible to detect for lynis. The suggestion should be updated to acknowledge that use case.
From:
             ReportSuggestion ${TEST_NO} "Install and configure automated intrusion detection/prevention tools"
To:
            ReportSuggestion ${TEST_NO} "Install and configure host based automated intrusion detection/prevention tools or ensure you have network based NIPS/NIDS in the same subnet"

**Comment by mboelen** [comment]
At this moment, the extensive parsing of Snort parameters will be skipped. As part of a regular cleanup, I will close this issue for now.
