### ISSUE TITLE
Check For kernel.yama.ptrace_scope

### ISSUE THREAD

**Issue by quantumpacket** [CISOfy/lynis#390]
There is an article on your site about it https://linux-audit.com/protect-ptrace-processes-kernel-yama-ptrace_scope/ but I checked the source and did not see any checks for `ptrace_scope`. So wondering if there was a reason for that. Let me know if you want a PR sent for it. I presume you'd want the check to be done in `tests_kernel` and in a similar fashion to [this](https://github.com/CISOfy/lynis/blob/master/include/tests_kernel#L445-L466) code block.

Docs: https://www.kernel.org/doc/Documentation/security/Yama.txt
```
# classic ptrace permissions
kernel.yama.ptrace_scope=0

# restricted ptrace
kernel.yama.ptrace_scope=1

# admin-only attach
kernel.yama.ptrace_scope=2

# no attach
kernel.yama.ptrace_scope=3
```

**Comment by quantumpacket** [comment]
@mboelen is this something that should be added?

**Comment by quantumpacket** [comment]
@mboelen any input on this?

**Comment by mboelen** [comment]
Sounds like a good change. It would be even better if it can be done as the [SSH test](https://github.com/CISOfy/lynis/blob/76b4afb14d441fb3e1d2c6b616cea263df1faf48/include/tests_ssh#L110) where "bad, average, good" values are stored.

Then we can reuse this for other sysctl settings, as there are a few more that have a similar structure.

**Comment by mboelen** [comment]
Resolved with https://github.com/CISOfy/lynis/commit/35e8c0ab3aed8970f684efdd8953dba5b44186aa
