### ISSUE TITLE
Contribution to fix description

### ISSUE THREAD

**Issue by ad-m** [CISOfy/lynis#391]
Hello,

Where and how report fix to content on https://cisofy.com/controls/KRNL-5788/ ? There is some repo for that? It should also be an exhaustive source of knowledge and concrete guidance on how to eliminate the problems presented, and what change might have consequences.

**Comment by mboelen** [comment]
There is no repository for that part of the website. Opening an issue here is fine, so we can look into it and get the text extended. Do you have a specific proposal for the text?

**Comment by mboelen** [comment]
Hi @ad-m, do you have a specific proposal?

**Comment by mboelen** [comment]
Closing ticket. Please reopen if you have a suggestion.
