### ISSUE TITLE
'show changelog' not working

### ISSUE THREAD

**Issue by 83problems** [CISOfy/lynis#395]
I am using Fedora 26 and Lynis version 2.5.0.

I am running this command and without the version string:

`lynis show changelog 2.5.0`

And the error is:

> Error: Could not find the changelog file (searched in /usr/share/doc/Lynis /usr/share/doc/Lynis-2.5.0 .)

The CHANGELOG_PATHS variable in /usr/share/lynis/include/helper_show is using PROGRAM_NAME which is set to "Lynis".  The directory in /usr/share/doc/ is lowercase.

If I am in /usr/share/doc/lynis/ the command works.

**Comment by mboelen** [comment]
Did you install it as a package?

**Comment by 83problems** [comment]
Yes, I did install it as a package.  I was testing the newest version and noticed it.

I just noticed that when pulled from git the CHANGELOG.md is in the same directory.  It may be a problem for the package maintainer.

**Comment by mboelen** [comment]
We received a pull request that might solve it: https://github.com/CISOfy/lynis/pull/408

Agree to close this one for now? If the issue returns after next release, feel freel to reopen.

**Comment by 83problems** [comment]
Agreed.  Thank you.
