### ISSUE TITLE
Arpwatch not detected

### ISSUE THREAD

**Issue by Organic-Marble** [CISOfy/lynis#396]
"systemctl is-active arpwatch.service" returns "active"

but I get 

  * Consider running ARP monitoring software (arpwatch,arpon) [NETW-3032] 
      https://cisofy.com/controls/NETW-3032/

**Comment by mboelen** [comment]
Can you share also your ps output?

**Comment by Organic-Marble** [comment]
I believe systemctl was not providing a complete status. I restarted arpwatch and the warning went away.  Please close this as not reproducible.
