### ISSUE TITLE
How to / permit except particular KRNL-6000 tests?

### ISSUE THREAD

**Issue by swizca** [CISOfy/lynis#405]
It seems that KRNL-6000 tests are a block / can not be individually excepted?

I am running Lynis on an OpenVZ VPS (thank you for having Lynis!).

I get, including:

> [+] Kernel Hardening
> [DEBUG] Performing test ID KRNL-6000 (Check sysctl key pairs in scan profile)
> \- Comparing sysctl key pairs with scan profile
> \- kernel.kptr_restrict (exp: 2) [ DIFFERENT ]
> \- kernel.sysrq (exp: 0) [ DIFFERENT ]
> \- net.ipv4.tcp_timestamps (exp: 0) [ DIFFERENT ]

These are items I have no control over / changing /etc/sysctl.conf has no effect. (permission denied)

Is there a way to except these particular values so I, or other / future / less experienced with the history of this installation, don't keep seeing these discrepancies that we can do nothing about in the Lynis report?

Thanks for any thoughts.

**Comment by mboelen** [comment]
You can override the keys in your custom.prf (see default.prf for the specifics), or exclude the full test if you feel the values are an acceptable risk.

**Comment by swizca** [comment]
Ah! Don't except the tests, override the acceptable value. e.g.:

> config-data=sysctl;kernel.kptr_restrict;1;1;Restrict access to kernel symbols;sysctl -a;url:https;//kernel.org/doc/Documentation/sysctl/kernel.txt;category:security;
> config-data=sysctl;kernel.sysrq;1;1;Disable magic SysRQ;sysctl -a;url:https;//kernel.org/doc/Documentation/sysctl/kernel.txt;category:security;
> config-data=sysctl;net.ipv4.tcp_timestamps;1;1;Do not use TCP time stamps;-;category:security;

Thank you!

I suppose, for a subsequent maintainer, just as they should ask 'why is this test excepted', their equivalent ask would be 'why is this value overridden'. (And ask if the conditions that required it are still true.)

**Comment by mboelen** [comment]
Yup, overriding makes more sense then. I suggest commenting the related lines on why you accepted or performed a specific override :)

Will close this one. If you like Lynis, please do share with others and add a star :)
