### ISSUE TITLE
/home/dacr/lynis/include/parameters: line 62: $1: unbound variable

### ISSUE THREAD

**Issue by dacrhu** [CISOfy/lynis#407]
Hi,

I tried a remote audit but I get error:

[dacr@berci lynis]$ ./lynis audit system remote example.com
/home/dacr/lynis/include/parameters: line 62: $1: unbound variable

Thank you,
David

**Comment by mboelen** [comment]
A change has been made to the code to properly show the usage. If you like to test, do a `git clone`.
