### ISSUE TITLE
OS X Application firewall not detected

### ISSUE THREAD

**Issue by tas50** [CISOfy/lynis#41]
Apple ships OS X with pf, but also with their application level firewall.  Lynis should also check the status of that firewall.  /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate shows you the status of the firewall.  It could be added if that binary was detected.  I'm not sure if you want to keep adding more and more paths to the binary search path list or if you have a more ideal way of detecting the CTL command.

**Comment by mboelen** [comment]
Hi Tim,

In that case the best option is to make it a prereq for the test, like many tests have. Adding the path to binary search is not preferred in this case :)
So if file /usr/libexec/ApplicationFirewall/socketfilterfw exists, prereq is met and test will be executed.

Currently don't have a Mac running here. So if you can share the output, we can create the test very easily.

**Comment by mboelen** [comment]
Hi Tim, can you share your output?

**Comment by tas50** [comment]
what output exactly do you want?

**Comment by mboelen** [comment]
Output of the command you suggested: /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate
(or any parameter that might be useful)

Thanks!

**Comment by tas50** [comment]
bash-3.2# /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate
Firewall is enabled. (State = 1)

**Comment by mboelen** [comment]
First patch is applied to detect this. If you have the chance, please test and let us know the status of FIRE-4532.

**Comment by tas50** [comment]
Application firewall is now supported.  I'll open another ticket for pf not showing up though.  Thanks for getting this fixed.

**Comment by tas50** [comment]
Scratch that part about PF.  It's doing the right thing after all.
