### ISSUE TITLE
Do not suggest debsums on Ubuntu (and derivates) PKGS-7370

### ISSUE THREAD

**Issue by tomreyn** [CISOfy/lynis#413]
On Ubuntu 16.04, Lynis 2.5.1 may suggest this:

>   * Install debsums utility for the verification of packages with known good database. [PKGS-7370] 
>       https://cisofy.com/controls/PKGS-7370/

debsums, while available as a package on Ubuntu, does not actually work there because it uses the Debian GNU/Linux vulnerability feed (downloaded from the hardcoded default Debian security tracker URLs - which could be overridden by the SOURCE option in its configuration file), and no such feed is available for Ubuntu (or I was unable to find it by trying some URLs on Ubuntu's security tracker).

**Comment by mboelen** [comment]
Solved in new release. Thanks for reporting!
