### ISSUE TITLE
Apache module search path for DirectAdmin based servers

### ISSUE THREAD

**Issue by jamesmacwhite** [CISOfy/lynis#415]
Currently running `lynis` on a server running DirectAdmin Control Panel which uses its own program custombuild to compile and build components like apache, the mod_security2.so (and possibly others) module searches fail. For example, I have mod_security2.so installed but `lynis` cannot "see" it.

Example of a live CentOS 7 linux box, here's some info:

Apache version:

```
Server version: Apache/2.4.26 (Unix)
Server built:   Jun 20 2017 07:29:47
```

Module paths for mod_security2.so:

```
/usr/lib/apache/mod_security2.so
/usr/local/modsecurity/lib/mod_security2.so
```

Would it be acceptable to add `/usr/lib/apache` to `APACHE_MODULES_LOCS` in this case? It appears only `/usr/lib/apache2` is present currently.

**Comment by mboelen** [comment]
Thanks for pull request, closing this one.
