### ISSUE TITLE
PHP-2379 should not suggest suhosin for php 7

### ISSUE THREAD

**Issue by optyfr** [CISOfy/lynis#420]
PHP-2379 tries to detect suhosin extension on PHP, and suggest it if not available, the problem is that suhosin for php 7.x (suhosin7) is not available and won't be available for months since it is pre-alpha release (and not actively developed)
I suggest to exclude PHP-2379 when there is only php 7.x installed and running, since It may be more harmful to use suhosin7 than being vanilla

**Comment by compermisos** [comment]
sektioneins/suhosin7 is in pre-apha stage

**Comment by mostafahussein** [comment]
Why would you think that it may be more harmful to use suhosin7 than being vanilla ? My thought that using suhosin to block dangerous functions is useful regardless being pre-alpha release

**Comment by quantumpacket** [comment]
Why would anyone deploy a pre-alpha in their development environment, let alone their production environment? The last commit to sektioneins/suhosin7 was 8 months ago. I think we can assume development of it is dead for now, and recommending that an unstable extension be installed can itself introduce security and stability problems.

**Comment by icasimpan** [comment]
Hi, newbie on lynis here. I agree to what @optyfr  and @quantumpacket said. From my perspective, blindly trusting a project (suhosin in this case) is analogous to driving a trustworthy car but without the needed periodic maintenance and trusting that it won't lead you to accidents. Surely, statistics wise, you'll have higher chance of accidents/troubles than with something that undergoes periodic maintenance.

**Comment by noone-silentrunner** [comment]
From the README.md of sektioneins/suhosin7

WARNING: THIS SOFTWARE IS PRE-ALPHA SOFTWARE. DO NOT ATTEMPT TO RUN IN PRODUCTION

I think nobody is using lynis on dev machines, so I totaly agree with @optyfr and the others

**Comment by quantumpacket** [comment]
@noone-silentrunner  so you think suggesting that a pre-alpha software be installed on production is a good idea?
