### ISSUE TITLE
Make output easy to consume

### ISSUE THREAD

**Issue by thesp0nge** [CISOfy/lynis#421]
Hi there, we're trying to consume lynis output in Splunk. We're facing tons of problems because there is no an output that is easy to consume with other tools.

It could be a good idea to have a JSON, CSV or whatever format that can be parsed by other infosec tools.

**Comment by mboelen** [comment]
Did you see the report file (lynis-report.dat)? That has a key/value based structure.

**Comment by thesp0nge** [comment]
No, I don't. I will do.

Thanks

**Comment by mboelen** [comment]
Sure, happy to help. Will close this one then.
