### ISSUE TITLE
missing "Origin" and "Suite" in repository Release file

### ISSUE THREAD

**Issue by shpokas** [CISOfy/lynis#422]
I tried to set up unattended, automatic update of lynis package on Ubuntu Xenial (16.04). For that "Origin" and "Suite" fields are needed, but it looks like Cisofy repository Release file does not have them.

In more detail, to get lynis package updated automagically, besides some other stuff file **/etc/apt/apt.conf.d/50unattended-upgrades** needs 
Unattended-Upgrade::Allowed-Origins { ... }; entries in format “Origin:Suite”;

Please check below that **_apt policy_** output and see that Cisofy repository does not have "o=" and "a=" entries.
Same can be seen in repository Release file.

# apt policy 
Package files:
 100 /var/lib/dpkg/status
     release a=now
 500 https://packagecloud.io/varnishcache/varnish5/ubuntu xenial/main amd64 Packages
     release v=1,**o=packagecloud.io/varnishcache/varnish5**,**a=xenial**,n=xenial,l=varnish5,c=main,b=amd64
     origin packagecloud.io
 500 http://dl.google.com/linux/mod-pagespeed/deb stable/main i386 Packages
     release v=1.0,**o=Google, Inc.**,**a=stable**,n=stable,l=Google,c=main,b=i386
     origin dl.google.com
 500 http://dl.google.com/linux/mod-pagespeed/deb stable/main amd64 Packages
     release v=1.0,**o=Google, Inc.,a=stable**,n=stable,l=Google,c=main,b=amd64
     origin dl.google.com
 500 https://packages.cisofy.com/community/lynis/deb xenial/main i386 Packages
     _release n=xenial,c=main,b=i386
     origin packages.cisofy.com_
 500 https://packages.cisofy.com/community/lynis/deb xenial/main amd64 Packages
     _release n=xenial,c=main,b=amd64
     origin packages.cisofy.com_
 500 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial/main i386 Packages
     release v=16.04,**o=LP-PPA-certbot-certbot**,**a=xenial**,n=xenial,l=Certbot PPA,c=main,b=i386
     origin ppa.launchpad.net
...

**Comment by mboelen** [comment]
Changes have been made in the meantime. When next release becomes available, these changes should be visible. Leaving this open for tracking.

**Comment by mboelen** [comment]
Hi @shpokas - Is it correct for you now?

**Comment by shpokas** [comment]
Yes, now upgrade works unattended. thank you.
