### ISSUE TITLE
FILE-6310 incorrectly detect separated mount points

### ISSUE THREAD

**Issue by optyfr** [CISOfy/lynis#424]
This test is currently looking for /home /tmp and /var separated mount points
For each mount points _mounpoint_ it is testing output from command "mount | grep _mounpoint_", and if there is no output, then there is no separated mount point, otherwise it is a separated mount point...

Now in my mount list I have this entry :
rpc_pipefs on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)

and this is detected as a /var separated mount point which it is totally wrong

Please consider to enhance grep pattern or simply use the "mountpoint" command from util-linux, it has been made for this! example : "mountpoint -q /var" will have exit code 0 if /var is a mountpoint, non zero otherwise...

**Comment by mboelen** [comment]
Thanks, that is a good observation. While the mountpoint tool is perfect for that, it is not available on the other Unix flavors. So with commit https://github.com/CISOfy/lynis/commit/dbec83566b6add3d38e5d95a502b7079bce3b93e this has been implemented in a slightly different way.
