### ISSUE TITLE
isVirtualMachine() is unable to detect lxc container inside vm (over-virtualization use case)

### ISSUE THREAD

**Issue by optyfr** [CISOfy/lynis#425]
whatever the method used (facter, lshw, ...), I got a detection of vmware instead of lxc (the VM is a VMWare guest)

one early test to include for lxc detection could be : 
grep -qa 'container=lxc' /proc/1/environ

furthermore lscpu is returning "Hypervisor vendor" instead of "Hypervisor Vendor" so you should add "-i" for grep (but this would also detect vmware)

**Comment by mboelen** [comment]
Sounds reasonable. Do you want to create a pull request for that?

**Comment by optyfr** [comment]
https://github.com/CISOfy/lynis/pull/426

**Comment by mboelen** [comment]
Closed with #426
