### ISSUE TITLE
Improve check empty NTP step-tickers file

### ISSUE THREAD

**Issue by CarstenGrohmann** [CISOfy/lynis#427]
The check TIME-3160 will fail with the suggestion "Some time servers missing in step-tickers file" if the step-tickers file exists and only contains empty lines / comments.

Maybe you can exclude comments / empty lines before you check for an empty file.

**Affected Versions**

- Current Lynis version from Github
- at least RHEL7

**Example**

```
$ cat /etc/ntp/step-tickers
# empty file to use servers in /etc/ntp.conf
```

results in 

```
  * Some time servers missing in step-tickers file [TIME-3160]
      https://cisofy.com/controls/TIME-3160/
```

Regards,
Carsten

**Comment by mboelen** [comment]
Hi @CarstenGrohmann - several improvements have been made to that test with commit https://github.com/CISOfy/lynis/commit/40282cde497f4b3e74f3dfc5c2116b83bca19889

**Comment by CarstenGrohmann** [comment]
Hi Michael,

I've successfully tested the change and it works fine.

Thank you,
Carsten
