### ISSUE TITLE
Suggestion: added Lynis tests when "Cockpit" is installed

### ISSUE THREAD

**Issue by karlisk** [CISOfy/lynis#429]
Fedora 26 comes with pre-installed and pre-enabled web dashboard/control panel for the OS, it is also available on other Linux distros, like Debian, Ubuntu, RHEL or CentOS (more info available at the dedicated website: http://cockpit-project.org ).

While, a very useful tool with nifty ability to review logs, however, poses a potential security risk - by default it's accessible from anywhere and is available at https://-server-ip-:9090/ to anyone, it also permits log-in with root account. Not only that but the web dashboard provides a built-in terminal, which, with root access, is on par with having SSH allow RootLogin. There for consider this a feature request for any update release in the future ...  or perhaps just a plug-in is in order.

I mean, granted - for production servers people would most likely use CentOS, RHEL, SUSE/OpenSUSE or any other sturdier/more tested OS, but who knows... since the software is available on other Linux Distros, it's worth a shout to consider.

**Comment by mboelen** [comment]
Hi @karlisk - Great insight and thanks for sharing. Do you have a specific proposal on what you like to see?

**Comment by karlisk** [comment]
The way I see it - if the said software is present, it's probably needed/used. In case if it isn't - the multiple suggestions notices/warnings in a Lynis audit printout or log should be sufficient to attract the attention of the auditor or system admin to review the situation and to either disable/remove the software or secure it to avoid any incidents.

Admittedly, I'm no expert and haven't yet really inspected the software/technology stack used in Cockpit but a quick look at the documentation shows a few tips on how to secure it - http://cockpit-project.org/guide/latest/guide.html . I also haven't dug into the config of it. I wasn't really even aware of it until I noticed a promo mentioning it during setup for a Fedora VM that I was setting up for tests.

My suggestions for Lynis tests: 
- similarly to SSH hardening practices - suggest limiting public access to whitelisted IPs through firewalld (or the equivalent of it on other distros if firewalld isn't used) and changing the default port '9090' to something else (a quick look into the documentation suggests it's doable - http://cockpit-project.org/guide/latest/listen.html ). This also coincides with the ability to centrally manage & monitor multiple different servers all running Cockpit, useful, however, potentially dangerous if the software is running on default config.
- in it's standard configuration, while HTTPS is used, Cockpit uses self-signed certificates - suggest using more secure certificates (doesn't have to be a costly certificate thanks to https://letsencrypt.org ).
- it also seems that Cockpit allows just about any normal user account (that you could normally use to log into the system) to log in and access various sections, including the users list (possibly depends on user groups and user account-specific settings) - suggest limiting users that are permitted to log in (needs more info on this tho, for example - users will be denied access to logs if they don't have the appropriate permissions).

**Comment by mboelen** [comment]
Sounds like a reasonable set of changes. Are you up for creating a pull request with an initial test for these items?

**Comment by karlisk** [comment]
Sure, I'll look into this - I have some ideas. Already had a look at Lynis plugin development info materials too, this shouldn't be too complex.

**Comment by karlisk** [comment]
Started looking into this, I might have missed it but is there a way to let the plugin check the installed packages against the Lynis standard built-in test results? I figure that way there is no need to do a new package look-up to check if the packages have been downloaded and/or installed.

**Comment by mboelen** [comment]
If you look for a specific package, then you could do a single call to the package manager. Or what we typically do is look for the presence of a binary.
