### ISSUE TITLE
sshd option UsePrivilegeSeparation is/will be deprecated

### ISSUE THREAD

**Issue by lpirl** [CISOfy/lynis#430]
Lynis suggests to set ``UsePrivilegeSeparation`` to ``SANDBOX``. However, this [option deprecated since release 7.5](https://www.openssh.com/txt/release-7.5).

**Comment by mboelen** [comment]
Thanks. Let's remove it. Want to make a pull request for it?

**Comment by lpirl** [comment]
continuing as #432
