### ISSUE TITLE
lynis on HP-UX

### ISSUE THREAD

**Issue by 1nsecure** [CISOfy/lynis#431]
HP-UX don't have /var/log by-default, so there are a lot of errors, while running lynis.
I think we need to:
1. Don't use hardcoded paths in lynis (e.g. set it to $log_dir or something) + use different ones for different OSes (for example, /var/adm/syslog/ on HP-UX)
2. Check if directory exists and create it before running everything else - it is easier to implement, but not as good as previous solution

**Comment by mboelen** [comment]
Hi @1nsecure, thanks for reporting this. We just made a commit to set a default and override it for HP-UX: https://github.com/CISOfy/lynis/commit/a547953d99d09ec8e3daa6ae593b615506a565a9

Can you test if it works correctly for you?

**Comment by 1nsecure** [comment]
Currently I don't have access to HP-UX boxes, but looks fine.

**Comment by mboelen** [comment]
Thanks, closing in that case.
