### ISSUE TITLE
Suppress `[TIP]: Enhance Lynis audits...` with `--warnings-only`, `--quiet` or `--cronjob`

### ISSUE THREAD

**Issue by jimbobmcgee** [CISOfy/lynis#434]
`[TIP]: Enhance Lynis audits by adding your settings to custom.prf (see /etc/lynis/default.prf for all settings)`

Lynix seems to want emit the above tip, regardless of whether `--quiet`, `--cronjob` or `--warnings-only` are set.  This means my cronjob wants to mail me all the time with this tip.

Now, I could just put a custom.prf file in, but I don't know that I need anything there, yet.
I could redirect all output from Lynis to /dev/null, but I do actually *want* to be emailed with warnings.

Maybe I'm missing something obvious...

I'm running Lynis 2.5.1-2 on Centos 7.2, as deployed from EPEL.

**Comment by mboelen** [comment]
Thanks for reporting. The easiest way is to actually tell Lynis to skip sharing tips with you:
show-tools-tips=0 (put that in your custom.prf)

**Comment by mboelen** [comment]
Closing this issue.

**Comment by jimbobmcgee** [comment]
Sorry, but the proposed resolution is circular, and amounts to *'create a custom.prf file so Lynis stops telling you that you can create a custom.prf file'*.

Tips should not be displayed when `--warnings-only` is specified, because a tip is not a warning, nor is it of higher importance than a warning.

I don't want to be forced to create a custom.prf.  Not having a custom.prf is not a *real* problem.  I just want the output to only contain *real* problems, and I *feel* like I've told Lynis this with `--warnings-only`.

I guess I'll just have to `| grep -Ev '^[[:space:]]*\[TIP\]\:'` it away in my cron job.
(Oh good, another dependency...)

**Comment by nickanderson** [comment]
I almost filed an issue for this, but found this and figured it would be better to comment on the existing issue.

I also did not expect any output when running with `--quiet`. I expected that would suppress all output as detailed in the help output.

From the --help output in 2.7.4:

```
    --quiet (-q)                      : No output
```

**Comment by nickanderson** [comment]
Ah, this seems to have been changed for 2.7.5:

https://github.com/CISOfy/lynis/commit/8a7f8038b5e4e4c674ae8924a0c551dd53ce8559
