### ISSUE TITLE
[NETW-2705] Be resolvconf aware

### ISSUE THREAD

**Issue by majormoses** [CISOfy/lynis#437]
If a system is managed by resolvconf it does not seem like a reasonable requirement to have 2 resolvable DNS servers in it. I think we could avoid this with a couple different methods:
check if `/etc/resolv.conf` is a symlink:
```
if [[ -L /etc/resolv.conf ]]; then
  echo 'managed by resolvconf'
  # skip test or new logic that might make sense here
else
  echo 'not managed by resolvconf'
  # do existing tests
fi
```
check for verbiage about resolvconf:
```
resolvconf=`grep -c 'generated by resolvconf' /etc/resolv.conf`
if [[ "$resolvconf" -ge 1 ]]; then
  echo 'managed by resolvconf'
else
  echo 'not managed by resolvconf'
fi
```
check if nameserver is local loopback:
```
resolvconf=`grep -c 'nameserver 127.0.1.1' /etc/resolv.conf`
if [[ "$resolvconf" -ge 1 ]]; then
  echo 'uses self as a nameserver'
else
  echo 'nothing to see here'
fi
```

I am willing to take a crack at adding this but wanted some guidance first on which of the 3 or any combination you would like to accept and if there was some reason you still think this is an area of concern.

**Comment by mboelen** [comment]
Hi! Looks like a good addition and we would welcome it as a pull request.

Before you make the change, a few tips to make the merge as easy as possible:

- Only use single brackets: [ x -eq y ], as Lynis uses /bin/sh, which is not always bash
- grep -c looks to be safe on at least AIX, which typically means all platforms support it (maybe not dash)
- Check for both 127.0.0.1 and 127.0.1.1
- Make the patch as small as possible, it might be even an idea to do it in multiple patches, and for the first one to be merged, then add the second one.

Thanks for the proposal, and let me know if there are questions.

**Comment by mboelen** [comment]
Ping @majormoses

**Comment by majormoses** [comment]
Yup I plan on doing this sorry I got side tracked. I might have something this weekend.

**Comment by majormoses** [comment]
@mboelen I will do them each as their own PR as requested #459 is the first one. Let me know if I am adding this in the wrong place but it seemed right to me and when I tested it I no longer had any warnings.

**Comment by mboelen** [comment]
After merging, I noticed that NETW-2704 already prevents NETW-2705 from running if '127.0.0.1' was available. I've changed a few things. Can you test if you still get the warning of NETW-2705, or that it is gone now?

**Comment by majormoses** [comment]
It is still warning, it was not with my change.
latest commit:
```
$ git log -1 --stat
commit 6aecde7e140753cbdfcdc476a693ba0b015efb61
Author: Michael Boelen <michael.boelen@cisofy.com>
Date:   Sat Sep 16 14:25:18 2017 +0200

    Updated log

 CHANGELOG.md | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)
```
Ran via `$ ./lynis audit system`:
```
  -[ Lynis 2.5.6 Results ]-

  Warnings (1):
  ----------------------------
  ! Couldn't find 2 responsive nameservers [NETW-2705] 
      https://cisofy.com/controls/NETW-2705/
```

Switching back to my branch things work as intended.

**Comment by mboelen** [comment]
What do you have in your /etc/resolv.conf? Then I can simulate it in our lab.

**Comment by majormoses** [comment]
```
$ cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.1.1
```

**Comment by mboelen** [comment]
I see, 127.0.1.1 was missing from the original test. So that is why it did not get picked up. I've made a change, can you test again?

**Comment by majormoses** [comment]
looks good now, thanks!

**Comment by majormoses** [comment]
The question is if we should implement the other situations around resolvconf as well. For example you could still run resolvconf without something like dnsmasq. As we are not checking if `/etc/resolv.conf` is a symlink we may not be evaluating files in `/etc/resolvconf/resolv.conf.d/` (base|head|tail) which people might insert more nameservers in.

**Comment by mboelen** [comment]
As no more input came to this issue, I will close it. The suggested changes can also be implemented if people have a need for it.
