### ISSUE TITLE
Umask settings not checked in test_shells

### ISSUE THREAD

**Issue by sklerder** [CISOfy/lynis#44]
Umask settings are not checked in SHLL-6240 and SHLL-6250.

- grep wasn't provided the name of the file to check in SHLL-6240 (FIND=`grep "^umask" | awk '{ print $2 }'` without any file to check)
- There was no code for SHLL-6250.

Code included for both in pull request #37

**Comment by mboelen** [comment]
Thanks for your feedback. Since we were shuffling some pieces, the pull request can't be used 1-on-1, but we will check out if we got everything from it.

**Comment by sklerder** [comment]
Hi !

Yes, and unfortunately, I did the mistake to merge two issues in one pull-request, which was not a good idea, sorry ...

**Comment by mboelen** [comment]
Several changes have been added to include these items. As it was one pull request, it couldn't be merged automatically with the other changes. Have a look at recent changes to see if everything is included, like you intended :)

Thanks!
