### ISSUE TITLE
Linux Mint 18.2 detected as Debian.

### ISSUE THREAD

**Issue by daniejstriata** [CISOfy/lynis#442]
Hi,

I've noticed that Lynis detects my Linux Mint 18.2 install as Debian Stretch.

---------------------------------------------------
  Program version:           2.5.3
  Operating system:          Linux
  Operating system name:     Debian
  Operating system version:  stretch/sid
  Kernel version:            4.10.0
  Hardware platform:         x86_64

Print from /etc/issue:

 $ cat /etc/issue
 Linux Mint 18.2 Sonya \n \l

**Comment by mboelen** [comment]
Hi, in commit https://github.com/CISOfy/lynis/commit/06491a5b4fb4121123f36fd1e81089285abd2833 a initial detection routine has been added for Linux Mint. Can you test the GitHub version and see if it shows your OS name and version properly?

**Comment by mboelen** [comment]
Hi @daniejstriata - was this fixed for you?

**Comment by daniejstriata** [comment]
Hi,

I'm sorry I could only test this now. I did a git -pull to the latest version but don't see it correctly detected yet. Am I missing the update?
$ cat /etc/issue
`Linux Mint 18.2 Sonya \n \l`

$ head -n 12 /tmp/lynis-report.dat
```
# Lynis Report
report_version_major=1
report_version_minor=0
report_datetime_start=2017-08-31 15:19:31
auditor=[Not Specified]
lynis_version=2.5.4
os=Linux
os_name=Debian
os_fullname=Debian stretch/sid
os_version=stretch/sid
linux_version=Debian
os_kernel_version=4.10.0
os_kernel_version_full=4.10.0-32-generic
```

**Comment by daniejstriata** [comment]
I can confirm that I cannot get to the branch that you added the change. 
I ran
`git reset --hard 06491a5 `
followed with
`git pull`
Not sure what version I'm on then.

**Comment by mboelen** [comment]
One option is to delete the 'lynis' directory where you checked out, then do a fresh clone. We only use master, so it should be the right one then.

**Comment by daniejstriata** [comment]
I've tried deleting the directory and cloned in again but it did not change it for me. I'm sorry. I'm not too familiar when I have to do any git commands that is not a git pull or git clone. My friend Google ended up confusing me more.

**Comment by mboelen** [comment]
No worries, the first patch was causing it. The detection did not pick up the OS correctly. Just checked and it does now work on Linux Mint 18.2. Case closed :)
