### ISSUE TITLE
Please undo #413, support debsums on Ubuntu and derivatives

### ISSUE THREAD

**Issue by tomreyn** [CISOfy/lynis#446]
Hi,

In #413 I stated that debsums does not work on Ubuntu and derivatives. This statement was erroneous and is factually false. I have to apologize for this mistake, and suggest to support debsums on Ubuntu and derivatives again, since it does work.

What does not work on Ubuntu (and most likely its derivatives as well) is debsecan, due to lack of a compatible data feed. You may want to remove support for this on Ubuntu and derivatives (only).

Sorry again,

Tom

**Comment by mboelen** [comment]
Hmm, I see. Want to help out and undo the change in the form of a pull request? :)

**Comment by tomreyn** [comment]
Sure, and sorry again.

**Comment by mboelen** [comment]
Close with pull request #457
