### ISSUE TITLE
[AUTH-9262] Suggested when libpam-cracklib is installed

### ISSUE THREAD

**Issue by d4t4king** [CISOfy/lynis#453]
[AUTH-9262] Suggested when libpam-cracklib is already installed on raspberry pi (raspian 8.0)

**Comment by mboelen** [comment]
Not sure if I understand. I read: you get the suggestion, while it is there. Or in other words, detection fails?

**Comment by d4t4king** [comment]
Correct: detection fails.  It looks like `pam_cracklib.so` is located in `/lib/arm-linux-gnueabihf/security/`.  I haven't looked at the check yet, so I'm not sure what would be required to include that path.

**Comment by d4t4king** [comment]
Pull request merged.  Closing.
