### ISSUE TITLE
CRYP-7902 Test is Marking Valid SSL PEM Certificate files as expired due to wrong redirect

### ISSUE THREAD

**Issue by elatov** [CISOfy/lynis#456]
I noticed that some of the SSL certs were getting marked as expired. In the *report-data*, I saw the following:

    certificate[]=/var/www/sign.crt |notAfter=Nov 30 06:00:00 2017 GMT
    Certificate will not expire

but in the log/report I saw this:

    2017-09-03 11:36:20 Test: checking certificate /var/www/sign.crt
    2017-09-03 11:36:20 Result: certificate /var/www/sign.crt has been expired

Looking over the test, I saw this:

    EXIT_CODE=$(${OPENSSLBINARY} x509 -noout -checkend 0 -in ${FILE} -enddate 2> /dev/null ; echo $?)
    ...
    if [ "${EXIT_CODE}" = "0" ]; then
      LogText "Result: certificate ${FILE} seems to be correct and still valid"
    else
      FOUNDPROBLEM=1
      LogText "Result: certificate ${FILE} has been expired"
    fi

Running that command manually I see that the output is more than just the exit code:

    ~# openssl x509 -noout -checkend 0 -in /var/www/sign.crt -enddate 2> /dev/null ; echo $?
    notAfter=Nov 26 08:39:10 2017 GMT
    Certificate will not expire
    0

Changing the first line to look like this, ensures it only gets the status code:

    EXIT_CODE=$(${OPENSSLBINARY} x509 -noout -checkend 0 -in ${FILE} -enddate >/dev/null 2>&1; echo $?)

And valid certs don't get marked as expired, but I wasn't sure if you guys want that output for something else.

**Comment by mboelen** [comment]
Did you test this on the latest master, or with version 2.5.3?

**Comment by elatov** [comment]
This was with the latest version of **lynis** (not from master):

    <> lynis --version
    2.5.3

**Comment by mboelen** [comment]
Thanks for the quick reply. Please check out the master version, as it should already be fixed.

**Comment by elatov** [comment]
yep, I do see the changes in **master**, thank you. Would you happen to know in which release (2.5.4?) will this added?

**Comment by mboelen** [comment]
Yes, upcoming release. If time allows, tomorrow. Will close this issue as a "wontfix", as it was already solved.
