### ISSUE TITLE
/bin/sh is normally not bash on Ubuntu

### ISSUE THREAD

**Issue by cdslashetc** [CISOfy/lynis#458]
lynis 2.5.4-1 uses -d bash extension to read, but specifies #!/bin/sh in the script resulting in errors like the following on Ubuntu:

\# /usr/sbin/lynis audit system --auditor automated --cronjob
/usr/sbin/lynis: 47: read: Illegal option -d
/usr/sbin/lynis: 47: read: Illegal option -d
/usr/sbin/lynis: 47: read: Illegal option -d
/usr/sbin/lynis: 47: read: Illegal option -d
/usr/sbin/lynis: 47: read: Illegal option -d

On Ubuntu, /bin/sh normally points to dash for a more lightweight and restricted shell for daemons as described in https://wiki.ubuntu.com/DashAsBinSh

\# ls -la /bin/sh
lrwxrwxrwx 1 root root 4 Feb 17  2016 /bin/sh -> dash

I have worked around this in my scripts by specifying bash explicitly, but the error is likely to confuse less experienced users.

/bin/bash /usr/sbin/lynis audit system --auditor automated --cronjob

**Comment by mboelen** [comment]
Thanks for sharing. Can you check if commit https://github.com/CISOfy/lynis/commit/c248ab6a1680de367692327f09a1e6ffd9d7949f has solved it for you as well?

**Comment by mboelen** [comment]
New release available, closing issue. Thanks again for reporting.
