### ISSUE TITLE
Executable (bin) search paths are predefined

### ISSUE THREAD

**Issue by BlessJah** [CISOfy/lynis#468]
Binary paths should not be predefined as a constant. Current way of searching binaries could be abandoned in favor of using `$PATH` environment variable.

`$PATH` variable and command search are well defined and should work on all modern unix-like systems:
 - http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_05_03
 - http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_01_01

https://github.com/CISOfy/lynis/blob/master/include/consts#L26
```sh
# Paths where system and program binaries are located
BIN_PATHS="/bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin \
          /usr/local/libexec /usr/libexec /usr/sfw/bin /usr/sfw/sbin \
          /usr/sfw/libexec /opt/sfw/bin /opt/sfw/sbin /opt/sfw/libexec \
          /usr/xpg4/bin /usr/css/bin /usr/ucb /usr/X11R6/bin /usr/X11R7/bin \
          /usr/pkg/bin /usr/pkg/sbin"
```

**Comment by ryneeverett** [comment]
As supporting evidence that the current situation is less than ideal, I present the patch I had to write to package lynis on nixos:

```console
perl -i -p0e 's/BIN_PATHS="[^"]*"/BIN_PATHS=\$\(echo \$PATH\ | sed "s\/:\/ \/g")/sm;' include/consts
```

https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/security/lynis/default.nix

**Comment by mboelen** [comment]
Commit https://github.com/CISOfy/lynis/commit/b4758e0b23944be61441ed594366cc943c798118 now uses PATH variable contents and only falls back to the predefined list if it is empty for some reason.
