### ISSUE TITLE
https://cisofy.com/controls/FILE-/###/ no exists

### ISSUE THREAD

**Issue by mudongliang** [CISOfy/lynis#48]
When I click the url in suggestion:
- Install 'ecryptfs-utils' and configure for each user. [FILE-####]
      http://cisofy.com/controls/FILE-####/
The content of this url does not exist!

**Comment by mboelen** [comment]
This seems to be a non-default test. From where did you install Lynis?

**Comment by mudongliang** [comment]
https://packages.debian.org/jessie/lynis
apt-get install lynis

**Comment by mboelen** [comment]
Will discuss this with Debian package maintainer.

**Comment by mboelen** [comment]
This item will be solved in upcoming Debian packages. Together with the maintainer we will remove the related tests from the Debian package, and move them upstream as much as possible. Since it is not a fix in the code here, this issue will be marked as a "wontfix". Thanks for reporting it!
