### ISSUE TITLE
Duplicate entries in /etc/hosts

### ISSUE THREAD

**Issue by Ackis** [CISOfy/lynis#480]
Hello, I've been getting the error that there are duplicate lines in my /etc/hosts file.

I'm using an automatic hosts file creator:
https://github.com/StevenBlack/hosts

Peeking through the test, it's using the following command to test:

`egrep -v '^(#|$)' /etc/hosts | awk '{ print $1, $2 }' | sort | uniq -d`

When I run that on my hosts file I get a single response:
`# and`

I did a search through my hosts file and found the following matches:
```
grep -i "# and" /etc/hosts

# and redirect all requests through their servers. You may need to use spyware
                                # and potentially other sites.
        # and some distribute adware and spyware
# and forms the basis of the bad referrers domain lists for
# and the Apache Ultimate Bad Bot Blocker at:
```

I wanted to run the egrep command on that limited input to see if it would give the same result - it did.
The command produced the same output as expected:
`grep -i "# and" /etc/hosts | egrep -v '^(#|$)' /etc/hosts | awk '{ print $1, $2 }' | sort | uniq -d`

Next I changed the egrep command to ignore lines that start with characters (which includes spaces) as well:

`grep -i "# and" /etc/hosts | egrep -v '^(#|$|/s)' /etc/hosts | awk '{ print $1, $2 }' | sort | uniq -d`

The output from that command was as expected - nothing.

I'm not sure if you want to change the egrep pattern or not, but I wanted to share.

**Comment by mboelen** [comment]
The egrep should actually already ignore each line starting with a comment character.

What does the following command return: `egrep -v '^(#|$)' /etc/hosts`

**Comment by Ackis** [comment]
The output of that command is quite a bit, due to the size of my hosts file (47k lines). I've uploaded my hosts file for you.

[hosts.txt](https://github.com/CISOfy/lynis/files/1414850/hosts.txt)

This may be more useful for you though:

```
egrep -v '^(#|$)' /etc/hosts | grep "#"
                                # mistyped URLs to search engines. They
                                # log all such errors.
                                        # URLs to their site.
                                        # May break iOS Game Center.
                                # video on sites such as cbc.ca
                                # and potentially other sites.
                                        # up CSS on livejournal
                                        # problems with NPR.org
  # ads and track users across
  # the com.com family of sites
        # and some distribute adware and spyware
        # message board spam and are unlikely to be real sites

```

**Comment by mboelen** [comment]
Resolved with https://github.com/CISOfy/lynis/commit/a7845b674814880c8f928d88d7888c8945197be0
