### ISSUE TITLE
Lynis:79  binary operator expected

### ISSUE THREAD

**Issue by sarlacpit** [CISOfy/lynis#486]
I have just cloned the letest release and get an error when trying to run Lynis:

```
./lynis audit system
./lynis: line 79: [: /home/user1/: binary operator expected
Fatal error: can't find include directory
Make sure to execute Lynis from untarred directory or check your installation.

```
Line 79 is the second if:

```
        for I in ${tINCLUDE_TARGETS}; do
            if [ "${I}" = "./include" ]; then
                if [ -d ${WORKDIR}/include ]; then INCLUDEDIR="${WORKDIR}/include"; fi
            elif [ -d ${I} -a -z "${INCLUDEDIR}" ]; then
                INCLUDEDIR=${I}
            fi
        done

```

Obviously it is struggling to see the includes directory as it drops out if our include directory can't be found but i am running an untarred version in the same directory.

`drwxr-xr-x 2 root root 4.0K Oct 30 13:23 include`

I'm really not sure where to go from here.

I am running as root on the following system:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

Any ideas?

Thanks

**Comment by mboelen** [comment]
I suggest switching to another directory. Then do the clone again and see if it then picks it up.

**Comment by sarlacpit** [comment]
I moved it from /home/user to /root and that works fine. All the files and directories appear to have the same permissions. Again I am running as root so would it matter?

**Comment by mboelen** [comment]
Ok, good to see it works good now. As you run Ubuntu, you can also use the repository at https://packages.cisofy.com
