### ISSUE TITLE
ARM Repository

### ISSUE THREAD

**Issue by Huskynarr** [CISOfy/lynis#488]
I want to Update with Repo on ARM/Stretch, but no ARM Repository exists.

Is there a way without Compile self.

**Comment by icasimpan** [comment]
Hi,

You don't actually need to compile anything.You could just do the following:

```
git clone https://github.com/CISOfy/lynis
cd lynis; ./lynis audit system
```

**Comment by mboelen** [comment]
No compilation is needed. You could try a different architecture or fetch it via Git, as suggested by @icasimpan
