### ISSUE TITLE
Plugin progress indicator looks odd

### ISSUE THREAD

**Issue by pyllyukko** [CISOfy/lynis#489]
When running Lynis (v2.5.7) in Debian (with the debian plugin), the progress indicator looks odd with only one square bracket:

![lynis](https://user-images.githubusercontent.com/1058704/32451227-00dc1fb0-c31f-11e7-90b5-17cfae6ff83d.png)

It apparently boils down to this piece of code:

```
                                    if [ ${PLUGIN_PHASE} -eq 1 ]; then Progress "    ["; fi
                                    . ${PLUGINFILE}
                                    if [ ${PLUGIN_PHASE} -eq 1 ]; then Progress "]"; Progress --finish; fi
```

I'm not entirely sure what's it supposed to look like. If I figure it out, I will make a PR.

This is what's happening (```set -x```):

```
  - Plugin: debian
+ '[' 1 -eq 1 ']'
+ Progress '    ['
+ '[' 0 -eq 0 ']'
+ '[' 0 -eq 0 ']'
+ '[' '    [' = --finish ']'
+ '[' '!' '' = '' ']'
+ echo -e -en '    ['
    [+ set +x

[+] Debian Tests
------------------------------------
  - Checking for system binaries that are required by Debian Tests...
-----8<-----
    - fail2ban                                                [ Not Installed ]
+ '[' 1 -eq 1 ']'
+ Progress ']'
+ '[' 0 -eq 0 ']'
+ '[' 0 -eq 0 ']'
+ '[' ']' = --finish ']'
+ '[' '!' '' = '' ']'
+ echo -e -en ']'
]+ Progress --finish
+ '[' 0 -eq 0 ']'
+ '[' 0 -eq 0 ']'
+ '[' --finish = --finish ']'
+ echo -e ''

+ set +x
```

So is the Debian plugin supposed to output dots or something?

**Comment by mboelen** [comment]
This plugin is not managed by the project team and it looks like they don't use the functions correctly (see plugins directory for examples).

I suggest reporting this to the maintainer or author of the plugin.
