### ISSUE TITLE
SSH root login with keys only

### ISSUE THREAD

**Issue by Bluewind** [CISOfy/lynis#49]
I'd consider this a secure setup and having root login enabled actually makes sense for a couple of reasons: 
- Root has reserved memory so if the box runs OOM you can still log in to kill whatever is creating the issue (oom killer doesn't always manage to do that)
- It's really cumbersome to copy files only accessible to root via scp if you can't log in as root
- root is the only one who can log in when /etc/nologin exists or when /home happens to be unaccessible

Could you check if key authentication is required and if it is omit the warning when root login is enabled?

**Comment by mboelen** [comment]
Thanks for the request. While you seem to have a secure setup, one thing might be missing: how did you configure accounting? In other words, how do you know which user logged in a root?

**Comment by Bluewind** [comment]
Openssh logs the public key and IP when logging in, but I guess that might not be enough for some since executed commands won't be logged. If you want to cater to those users that's fine by me.

**Comment by mboelen** [comment]
I'm actually thinking of grading the different options:
1) Direct root login allowed
2) Direct root login allowed, with key only
3) Direct root login allowed, with key only, with additional measures (e.g. only 1 root user)
4) No root login allowed

How many users do you have which are allowed to log in directly as root?

**Comment by Bluewind** [comment]
I have 3, but only I use it semi-regularly.

**Comment by mboelen** [comment]
Adding the fine-tailored options takes too long to implement, so we reclassified root logins with public key authentication. Related commit https://github.com/CISOfy/lynis/commit/3f9d1308bb62e53367e31c2d872edd9b962c8220
