### ISSUE TITLE
How to update v2.5.5

### ISSUE THREAD

**Issue by SimonFearby** [CISOfy/lynis#491]
./lynis --check-update
This option is deprecated
Use: lynis update info
root@feaerby:/linis/lynis# ./lynis update info

 == Lynis ==

  Version            : 2.5.5
  Status             : Outdated
  Installed version  : 255
  Latest version     : 257
  Release date       : 2017-09-07
  Update location    : https://cisofy.com/lynis/

2007-2017, CISOfy - https://cisofy.com/lynis/

./lynis update check
status=outdated
root@feaerby:/linis/lynis# lynis update check
The program 'lynis' is currently not installed. You can install it by typing:
apt install lynis

#:/linis/lynis# ./lynis update check
status=outdated

Do I run: sudo git clone https://www.github.com/CISOfy/lynis over the top of 2.5.5

**Comment by quantumpacket** [comment]
If you're using a Debian/Ubuntu system you should be using the package repository to get new updates opposed to doing manual updates. https://packages.cisofy.com/community/

**Comment by SimonFearby** [comment]
Thanks, I deleted the GIT synced folder and will update my guide here https://fearby.com/article/run-ubuntu-vm-system-audit-lynis/

**Comment by SimonFearby** [comment]
Thank I read https://packages.cisofy.com/community/#debian-ubuntu but apt-update fails
># apt update
>E: Malformed entry 1 in list file /etc/apt/sources.list.d/cisofy-lynis.list (Component)
>E: The list of sources could not be read.

Complete input/output:
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C80E383C3DE9F082E01391A0366C67DE91CA5D5F
Executing: /tmp/tmp.Dz9g9nKV6i/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv-keys
C80E383C3DE9F082E01391A0366C67DE91CA5D5F
gpg: requesting key 91CA5D5F from hkp server keyserver.ubuntu.com
gpg: key 91CA5D5F: public key "CISOfy Software (signed software packages) <software@cisofy.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

# apt install apt-transport-https
Reading package lists... Done
Building dependency tree
Reading state information... Done
apt-transport-https is already the newest version (1.2.24).
The following packages were automatically installed and are no longer required:
  gamin libfile-copy-recursive-perl libgamin0 libglade2-0 libpango1.0-0 libpangox-1.0-0 openbsd-inetd pure-ftpd-common update-inetd
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.

# echo 'Acquire::Languages "none";' > /etc/apt/apt.conf.d/99disable-translations

# echo "deb https://packages.cisofy.com/community/lynis/deb/xenial main" > /etc/apt/sources.list.d/cisofy-lynis.list

# apt update
E: Malformed entry 1 in list file /etc/apt/sources.list.d/cisofy-lynis.list (Component)
E: The list of sources could not be read.

**Comment by quantumpacket** [comment]
@SimonFearby there needs to be a space before "xenial". So:

> echo "deb https://packages.cisofy.com/community/lynis/deb/ xenial main" > /etc/apt/sources.list.d/cisofy-lynis.list

**Comment by SimonFearby** [comment]
Thanks

**Comment by mboelen** [comment]
Closing this one then :)
