### ISSUE TITLE
No support available yet for this OS or platform...

### ISSUE THREAD

**Issue by elpollino** [CISOfy/lynis#492]
hello good afternoon I have a problem to run lynis, it does not give me any results
 when starting stops, thank you very much for your help

`root@ETP1ERA67UPU:~# **lynis audit system**`
[ Lynis 2.4.0 ]
`################################################################################
  Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
  welcome to redistribute it under the terms of the GNU General Public License.
  See the LICENSE file for details about using this software.` `2007-2016, CISOfy - https://cisofy.com /lynis/ Enterprise support available (compliance, plugins, interface and tools)
################################################################################`

**[+]** Initializing program`

**[ WARNING ]**
Error: Unknown OS found. No support available yet for this OS or platform...
Please consult the README/documentation for more information.
root@ETP1ERA67UPU:~# 

`uname -a / Unknown ETP1ERA67UPU 999.999.999  x86_64 GNU/Linux`

**Comment by quantumpacket** [comment]
@elpollino  since `uname` is not providing the distro information can you please post it, and anything special you may have done to your system for uname to not provide the info.

**Comment by SimonFearby** [comment]
root@ETP1ERA67UPU Is not me? Wrong ticket?

**Comment by mboelen** [comment]
What is the OS?

I suggest also installing a newer version (from GitHub) or from the repository: https://packages.cisofy.com

**Comment by elpollino** [comment]
hi already update to its latest version . 
`
root@SKDSRDC3A1H0:~# lynis audit system
[ Lynis 2.5.7 ]
[+] Initializing program
[ WARNING ]
Error: Unknown OS found. No support available yet for this OS or platform...
Please consult the README/documentation for more information.
`
OS or platform : https://sourceforge.net/projects/sistemas-operativos/
thank you very much for your help

**Comment by quantumpacket** [comment]
It looks like it might be a fork of Kali with additional anonymity features. Maybe that's why the distro string is missing to prevent possible fingerprinting? Dunno yet as not much is in English. :\

**Comment by mboelen** [comment]
I see, everything in the OS is randomized, anonymized, scrubbed. Well, in that case it will reduce the detection capabilities.

As Lynis won't be able to retrieve basic details like the OS name, there is not much that we can do here. For now, we will have to accept that Lynis won't run and closing this issue as a 'wontfix'.

**Comment by quantumpacket** [comment]
@mboelen could we not have a config option which allows the user to force the OS type instead of relying on Lynis detecting it? This would allow for running these edge cases for the most part. So in this instance the user would force a "Debian" OS type via the config if they are indeed using a Kali fork. Similar option can be provided for other detected values that may be missing.

**Comment by mboelen** [comment]
Sure, that is definitely a possibility. But... this change would only satisfy it for a very very small number of users (maybe 1 at this moment?). Also, it would "complicate" the tool with another option or parameter to check for. This addition has to be created, explained, and documented.

With still enough issues open, this item is not of enough priority to do at this moment. So technically possible, yet not of enough value currently to invest time into.
