### ISSUE TITLE
doc issue: how to make automatic update on Fedora 27

### ISSUE THREAD

**Issue by hibouu** [CISOfy/lynis#493]
Hi, 
it's not really a problem for advanced user, but for rookies like me, it can take some time to find how to do. 
So on the doc page https://packages.cisofy.com/community/#centos-fedora-rhel
it's writed "yum update ca-certificates curl nss openssl", but Fedora use dnf, and not yum. so the exact command is "dnf etc". 
http://dnf.readthedocs.io/en/latest/conf_ref.html 

After, it's writted "Create /etc/yum.repos.d/cisofy-lynis.repo", but now the right formulation would be (at last on my config of Fedora 27): "[root@xxx]# nano /etc/dnf/dnf.conf" which contain the list of repositories.

Then (sorry, my system is in french) the result should be 

[root@xxx]# dnf update
CISOfy Software - Lynis package                 5.8 kB/s | 5.8 kB     00:01    
Dernière vérification de l’expiration des métadonnées effectuée il y a 0:00:00 le jeu 16 nov 2017 10:18:49 CET.
Dépendances résolues.
 Paquet           Architecture      Version              Dépôt            Taille

Mise à jour de:
 lynis            noarch            2.5.7-1              lynis            262 k

Résumé de la transaction
Mettre à jour  1 Paquet

Taille totale des téléchargements : 262 k
Voulez-vous continuer ? [o/N] :o
Téléchargement des paquets :
lynis-2.5.7-1.noarch.rpm                        110 kB/s | 262 kB     00:02    

Total                                           110 kB/s | 262 kB     00:02     
attention : /var/cache/dnf/lynis-ad29fbf09a6c8ef9/packages/lynis-2.5.7-1.noarch.rpm: Entête V3 RSA/SHA1 Signature, clé ID 0acf951b: NOKEY
Importing GPG key 0x0ACF951B:
 Userid     : "CISOfy Software RPMs (signed software packages) <software-rpms@cisofy.com>"
 Fingerprint: 9146 CE61 DD17 4FB3 02C9 90A9 8246 12E2 0ACF 951B
 From       : https://packages.cisofy.com/keys/cisofy-software-rpms-public.key
Voulez-vous continuer ? [o/N] :o
La clé a été importée avec succès
Test de la transaction en cours
La vérification de la transaction a réussi.
Lancement de la transaction de test
Transaction de test réussie.
Exécution de la transaction
  Préparation           :                                                   1/1 
  Mise à jour de        : lynis-2.5.7-1.noarch                              1/2 
  Nettoyage de          : lynis-2.5.5-1.fc27.noarch                         2/2 
  Exécution du scriptlet: lynis-2.5.5-1.fc27.noarch                         2/2 
  Vérification de       : lynis-2.5.7-1.noarch                              1/2 
  Vérification de       : lynis-2.5.5-1.fc27.noarch                         2/2 

Mis à niveau:
  lynis.noarch 2.5.7-1                                                          

Terminé !

 It's a little detail but exact (and existing) documentation make the life aesier for ppl like me. As your software of course. 
Thanks.

**Comment by mboelen** [comment]
Thanks for your suggestion. The [official docs](https://docs-old.fedoraproject.org/en-US/Fedora/26/html/System_Administrators_Guide/sec-Configuring_DNF_and_DNF_Repositories.html) suggest a slightly different way.

We updated the documentation. Can you have a look and see if this works for you as well?

**Comment by hibouu** [comment]
Hi, thank for your return. 
The actual documentation of Fedora is here
https://docs.fedoraproject.org/f27/system-administrators-guide/package-management/DNF.html#sec-Configuring_DNF_and_DNF_Repositories 
(but this point don't change from Fedora 26). 

So fare I understand, using the yum repo config (like your doc explained) allow to separate the main dnf config (like i do) and allow to desactive specifically one ore more repo if needed (fixing issue). For obvious practically reason, the first solution is preferable (and I change mine, sorry for the wasted time).

**Comment by mboelen** [comment]
You are welcome and don't feel sorry. You provided valuable feedback :)
