### ISSUE TITLE
Lynis Not Running My Profile?

### ISSUE THREAD

**Issue by Geyup** [CISOfy/lynis#496]
I'm using 2.5.7 and it's installed as a package in Slackware, so I am running this cmd as root;

lynis audit system --profile personal.prf

In /etc/lynis I copied default.prf;

cp default.prf personal.prf

I edited the personal.prf and then ran the above command and noticed this output in lynis;

```
Profiles:                  /etc/lynis/default.prf
Log file:                  /var/log/lynis.log
Report file:               /var/log/lynis-report.dat
Report version:            1.0
Plugin directory:          /usr/share/lynis/plugins
```

I brought this up over a year ago;

https://github.com/CISOfy/lynis/issues/264#issuecomment-255641170

If someone is going to run the cmd like above and using their own file, then this output of the ```Profiles:``` section should be showing the file being used, not default.prf as it's showing above, this makes me think it did not use personal.prf?

I also commented out ```pam``` and I noticed too in the ouput that pam was being checked;

```
- PAM password strength tools                               [ SUGGESTION ]
- PAM configuration file (pam.conf)                         [ NOT FOUND ]
- PAM configuration files (pam.d)                           [ NOT FOUND ]
- PAM modules                                               [ NOT FOUND ]
```
This seems to confirm that default.prf is being used...

Also the lynis.log seems to confirm that default.prf was used, at least it looks this way in that log.

Hmm

**Comment by quantumpacket** [comment]
What happens when you use an absolute path to the config profile?

**Comment by mboelen** [comment]
Run `lynis show profiles` to see what profiles are detected.

The suggested way is to create a custom.prf in /etc/lynis and only add the settings you need. So a copy of the full default.prf file is not needed.

**Comment by Geyup** [comment]
~ >lynis show profiles
/etc/lynis/default.prf

 ~ >cd /etc/lynis
~ >/etc/lynis >ls
default.prf  personal.prf

**Comment by mboelen** [comment]
Tip: do a diff between your default.prf and personal.prf. Then the settings you changed, put those in /etc//lynis/custom.prf. Remove personal.prf afterward.

Then look if things are properly picked up.

**Comment by Geyup** [comment]
What you just said sounds like I am only putting in the differences to a custom.prf, which doesn't make sense.

I did; ```cp default.prf personal.prf``` and then edite personal.prf to my liking and ran lynis, so what is wrong with this? That's suppose to be the way to do this...

**Comment by mboelen** [comment]
Yes, only put the differences in custom.prf. Lynis uses always uses default.prf, to give it its initial settings. Then you can use custom.prf to overrule them. in other words, Lynis will merge the settings, where the ones from custom.prf will override earlier defined values. So no need to copy all settings, just define the ones you need.

Below is the information on profiles and a training guide.

- https://cisofy.com/documentation/lynis/configuration/#lynis-profiles
- https://cisofy.com/files/public/lynis-enterprise-technical-training-product-and-deployment.pdf

Let us know if that worked for you.

**Comment by mboelen** [comment]
Closing issue, please reopen if with these instructions above things don't work as expected.

**Comment by Geyup** [comment]
Ok so I took just a few changes I wanted and created a custom.prf and added those in.

But when it comes to not wanting ```pam``` or ```systemd``` being scaned for, I don't see how this works, because in the default.prf these are not commented out, and then I'm going to add in both of these commented and I'm not seeing this working when I run lynis, I see it still checking for these plugins.

**Comment by mboelen** [comment]
Can you share the specific settings that you are referring to?

**Comment by Geyup** [comment]
plugin=pam
plugin=systemd

My understanding here is, we are saying, leave default.prf and make a custom.prf with the options you want, correct?

If that's true I don't see how this works when you want to make a custom.prf and ```#comment``` out some settings to not run, like the plugins I am trying to not have scanned, so I placed into custom.prf

```
#plugin=pam
#plugin=systemd
````
But the plugins are still being scanned for...

**Comment by mboelen** [comment]
Yes, correct.

And yes, correct again. Some settings can only be enabled (which they are by default). Plugins are one example that is always checked. If the plugin is not available, then it will be skipped. So delete the related plugin, if you rather not have them. Please note that only a few are included with the version from GitHub. If you install Lynis from package, then these plugins are not available. If you feel you like to use the plugins, only exclude a few plugin tests, then exclude them explicit via custom.prf (skip-test=PLGN-1234).

Does that make sense?

**Comment by Geyup** [comment]
From previous conversations, it is being mentioned that we do not want to touch default.prf Even inside the file itself it says not to touch it.

Now it appears I have to delete these options, then add in new options to a custom.prf that would exclude these.

Sorry it seems like this is defeating the purpose here.

Might as well just tell people to make a backup and just edit default.prf and run it...

This is what I'm doing now;

```cp default.prf default.prf.orig```

And I just edit default.prf and run lynis, which I think is simple enough...

I'm getting the feeling this is not only the plugins, because if someone doesn't want other options run, I don't see this working the same way...

Hmm
