### ISSUE TITLE
klogd should not be checked with systemd

### ISSUE THREAD

**Issue by BenjaminSchubert** [CISOfy/lynis#50]
Systemd has it own /dev/log implementation, making klogd useless and it seems even [harmful](http://lists.opensuse.org/opensuse-bugs/2011-03/msg04925.html)

However, when running lynis on a systemd system, I still get `klogd is not running, which could lead to missing kernel messages in log files [LOGG-2138]` which seems wrong.

Am I right ? Shouldn't this check be disabled if systemd is running ?

Thanks !

**Comment by mboelen** [comment]
Lynis actually tests for that and the test should NOT show up when using systemd journalling.
Does Lynis show in the screen output "- Checking systemd journal status" with the result "FOUND"?

**Comment by BenjaminSchubert** [comment]
You are right, this works. I had an outdated version apparently, now everything works perfectly, thanks !

**Comment by aurelien-git** [comment]
Hi,  It seems I get the same type of error:
Warnings (2):
----------------------------
! klogd is not running, which could lead to missing kernel messages in log files [LOGG-2138] 
https://cisofy.com/controls/LOGG-2138/

on a up to date RHEL 7 and last lynis git version
lynis$ sh lynis --version
2.4.1

Any idea?
