### ISSUE TITLE
Linux Kernel Setting: Accept TCP Timestamps with random offset also

### ISSUE THREAD

**Issue by CarstenGrohmann** [CISOfy/lynis#502]
I suggest to change `default.prf` to allow `0` and `1` for `net.ipv4.tcp_timestamps`.

- `0` disables TCP timestamps completely. This may cause issues on high speed networks as well as on networks with a high bandwidth delay product (long fat networks).

- `1` Enable timestamps as defined in RFC1323 and use random offset for each connection rather than only using the current time. The random offset increases the difficulty to guess the right uptime. This would also wrapping the TCP sequence number.

May you think about accept both values.

Documentation for tcp_timestamps: https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt

Regards,
Carsten

**Comment by mboelen** [comment]
Commit https://github.com/CISOfy/lynis/commit/1504370e416240d486e7aa1f88fbd7277c97e77d has been created to make multi-value possible. Both values are accepted now in the default profile.
