### ISSUE TITLE
SQD-3624 Incorrectly tagging port number that includes "22"

### ISSUE THREAD

**Issue by jamesmacwhite** [CISOfy/lynis#52]
For the Squid unsafe port check. An entry in my squid.conf is being tagged incorrectly by the grep statement and being interpreted as SSH 22.

**Line in my squid.conf:**

`acl Safe_ports port 2222        # DirectAdmin`

**The grep output is matching it as:**

`acl Safe_ports port 22`

**False positive warning given in audit:**

`Warning: Squid configuration possibly allows relaying traffic via configured Safe_port 22 [SQD-3624]`

Port 22 is not actually within Safe_ports at all.

**Comment by jamesmacwhite** [comment]
Perhaps adding the -w flag to the grep line would be a viable solution to prevent false positive matches:

`grep -w "^acl Safe_ports port ${I}" ${SQUID_DAEMON_CONFIG}`

**Comment by jamesmacwhite** [comment]
https://github.com/CISOfy/lynis/pull/53

**Comment by mboelen** [comment]
Closing after implementation of pull request #53
