### ISSUE TITLE
Lynis does not detect SPYRUS ToughBoot

### ISSUE THREAD

**Issue by thedrow** [CISOfy/lynis#521]
[SPYRUS ToughBoot](https://www.spyrus.com/wp-content/downloads/400-540001-01Linux2go.pdf) disallows single user mode so AUTH-9308 is not relevant in those environments.
I'm not sure if it's possible to detect such environments easily as ToughBoot is a commercial product but I thought it might be worthwhile to mention this.

**Comment by mboelen** [comment]
Thanks for letting us know. Yes, as this is very specific, you might also accept the finding and masking it (skip-test=AUTH-9308) in your profile.

I will close this issue for now. If there is more interest, or a proper pull request comes in with detection capabilities, then I will reopen.
