### ISSUE TITLE
Various command line options not working

### ISSUE THREAD

**Issue by dbsanfte** [CISOfy/lynis#522]
Using 2.6.2

> ./lynis audit dockerfile ../Dockerfile --log-file ./lynis.log

This doesn't output to ./lynis.log as would be expected.

> ./lynis audit system --no-colors

This doesn't work at all.

> ./lynis audit dockerfile ../Dockerfile --log-file ./lynis.log --no-colors

This throws an error.

**Comment by mboelen** [comment]
Thanks for reporting.

With the 'audit dockerfile', additional parameters might be ignored. You can add the log file option directly after lynis (lynis --log-file ./lynis.log audit dockerfile <file>).

The second one works for me. What do you get to see?

Third: see remark of the first.

**Comment by mboelen** [comment]
@dbsanfte - can you test the suggestions and share what you get with the second command?

**Comment by mboelen** [comment]
No feedback received, will close issue for now
