### ISSUE TITLE
Issue per file on folders

### ISSUE THREAD

**Issue by iranzo** [CISOfy/lynis#524]
Hi,
I was trying to get lynis somehow integrated in citellus ( https://github.com/zerodayz/citellus ) as we use a similar approach but for general system check (not security)

The thing is that for reporting it will be better to have each test separate/isolated .

Is this something that has been ever considered?
Thanks!
Pablo

**Comment by mboelen** [comment]
All tests are isolated, yet grouped by category. Only some tests need another one to be executed (e.g. testing for a prerequisite first).
