### ISSUE TITLE
Binaries not found on Manjaro

### ISSUE THREAD

**Issue by remcojansen** [CISOfy/lynis#526]
Lynis does not scan binaries in /usr/bin on Manjaro Linux. Empty variables for e.g. AWKBINARY then break the script.

Reason: Other paths under /usr/bin are scanned earlier and will match the regex so the script considers /usr/bin as already scanned.

Solution: Add condition to the regex that the SCANDIR must be followed by EOL or a comma.

Code change in "binaries", line 80-81:
```
                  # Add a space to make sure we discover a related directory if it was already scanned
-                FIND=$(echo ${BINARY_PATHS_FOUND} | grep ", ${SCANDIR}")
+                # Prevent matching sub-strings of paths by matching SCANDIR at EOL or followed by comma
+                FIND=$(echo ${BINARY_PATHS_FOUND} | grep ", ${SCANDIR}\(,\|$\)")
```

**Comment by mboelen** [comment]
Hi @remcojansen - What version of Lynis are you running?

**Comment by remcojansen** [comment]
This was in 261, noticed that you had fixed it in 262 using an additional `grep -v`.

**Comment by mboelen** [comment]
Yes, it did sound familiar and was solved last version. Thanks for your update.
