### ISSUE TITLE
Remove test for deprecated OpenSSH config option VerifyReverseMapping

### ISSUE THREAD

**Issue by artiommocrenco** [CISOfy/lynis#528]
`VerifyReverseMapping` OpenSSH config option is deprecated.

```
$ sshd -t
`/etc/ssh/sshd_config line x: Deprecated option VerifyReverseMapping`
```

I suggest removing it from OpenSSH configuration tests.

**Comment by mboelen** [comment]
Thanks for the suggestion. Although it may be deprecated, older OpenSSH versions might still be using it.

If you remove the particular line, do you get a warning or suggestion?

**Comment by mboelen** [comment]
@artiommocrenco ?

**Comment by mboelen** [comment]
Closing issue for now.

**Comment by kebertxela** [comment]
```shell=
user@host~ sudo grep Verify /etc/ssh/sshd_config 
VerifyReverseMapping yes
user@host~ sudo sshd -t
/etc/ssh/sshd_config line 31: Deprecated option VerifyReverseMapping
user@host~ sudo sed -i 's/Verify/\#Verify/' /etc/ssh/sshd_config 
user@host~ sudo sshd -t
user@host~ 
```

**Comment by NicolasCARPi** [comment]
I have submitted a PR to address this issue: https://github.com/CISOfy/lynis/pull/840
