### ISSUE TITLE
On Ubuntu 18.04 single user mode password false positive - AUTH-9308

### ISSUE THREAD

**Issue by rwky** [CISOfy/lynis#540]
`/lib/systemd/system/rescue.service` contains `ExecStart=-/lib/systemd/systemd-sulogin-shell rescue`

The test checks for `/sulogin` which doesn't match removing just the leading / will fix it, not sure if that's a suitable fix or not.

**Comment by mboelen** [comment]
Should be resolved with commit https://github.com/CISOfy/lynis/commit/105befb2e97d440fa6a0ebdc368edfdbc215b2e2

Thanks for reporting
