### ISSUE TITLE
PHP 7.x and Suhosin

### ISSUE THREAD

**Issue by thelounge-zz** [CISOfy/lynis#541]
please remove that - there is no suhosin for recent versions, it took ages even for PHP 5.4 (and the beta stuff broke roundcube sessions terrible), but on a machine with a with all hardening options self-compiled PHP 7.2.4 it's bad to give that false flags

 * Harden PHP by enabling suhosin extension [PHP-2379] 
      https://cisofy.com/controls/PHP-2379/

  * Harden PHP by deactivating suhosin simulation mode [PHP-2379]
      https://cisofy.com/controls/PHP-2379/

**Comment by mboelen** [comment]
We had this one under discussion as well. It has been disabled: https://github.com/CISOfy/lynis/commit/8077d244326e468c85ad73494cd97cd33c06cb95
