### ISSUE TITLE
FP Fedora 27: No password set for single mode [AUTH-9308]

### ISSUE THREAD

**Issue by thelounge-zz** [CISOfy/lynis#542]
! No password set for single mode [AUTH-9308] 
      https://cisofy.com/controls/AUTH-9308/

"Change your rescue.service file (/usr/lib/systemd/system/rescue.service) and define sulogin. ExecStart=-/usr/sbin/sulogin Note: ensure that it is linking to the right sulogin binary, which can change between distributions"

[root@testserver:~]$ cat /usr/lib/systemd/system/rescue.service
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Rescue Shell
Documentation=man:sulogin(8)
DefaultDependencies=no
Conflicts=shutdown.target
After=sysinit.target plymouth-start.service
Before=shutdown.target

[Service]
Environment=HOME=/root
WorkingDirectory=-/root
ExecStart=-/usr/lib/systemd/systemd-sulogin-shell rescue
Type=idle
StandardInput=tty-force
StandardOutput=inherit
StandardError=inherit
KillMode=process
IgnoreSIGPIPE=no
SendSIGHUP=yes

**Comment by mboelen** [comment]
Should now be recognized with commit https://github.com/CISOfy/lynis/commit/105befb2e97d440fa6a0ebdc368edfdbc215b2e2

If not, let it know. Will close issue in the meantime to reduce open items.
