### ISSUE TITLE
On FreeBSD suhosin detection (PHP-2379) fails

### ISSUE THREAD

**Issue by netfenceventu** [CISOfy/lynis#544]
This test will look for '^extension=.*?suhosin7?.so.*$' in ${PHPINI_ALLFILES}.
PHPINI_ALLFILES is quoted in the logs as:
"Result: using php.ini array  /usr/local/etc/php.ini for further tests"

However on FreeBSD there is an additional directory for php.ini extension include files: /usr/local/etc/php.
suhosin is thus enabled with "extension=suhosin.so" in /usr/local/etc/php/ext-30-suhosin.ini.

**Comment by mboelen** [comment]
Thanks for reporting.

The test will be disabled for now (next release), so the issue will be gone as well.

**Comment by netfenceventu** [comment]
On 05/01/18 21:02, Michael Boelen wrote:
> Thanks for reporting.
> 
> The test will be disabled for now (next release), so the issue will be 
> gone as well.

Fine.

One only note: the cited mechanism to enable PHP extensions is generic, 
not specific to Suhosin.
So it's possible other PHP tests are doing wrong (or will in the future) 
unless those files are parsed too.
