### ISSUE TITLE
[SSH-7408] No output for sshd config when using Match option

### ISSUE THREAD

**Issue by chr0mag** [CISOfy/lynis#548]
I'm running Lynis on an up to date Arch Linux KVM image.

_uname -r_
```
4.14.40-1-lts
```

_ssh -V_
```
OpenSSH_7.7p1, OpenSSL 1.1.0h  27 Mar 2018
```
However, Lynis is unable to retrieve my _sshd_ configuration because of a _Match_ statement in the config. If I run `sudo sshd -T` I get the following output, and no list of options:
```
'Match Group' in configuration but 'user' not in connection test specification.
```
This causes Lynis to return NOT_FOUND for all _sshd_ configuration options, essentially skipping the test.

My _sshd_ config contains the following section:
```
Match Group users
  ChrootDirectory %h
  ForceCommand internal-sftp -u 027
  AllowTcpForwarding no
  X11Forwarding no
```
If I run `sudo sshd -T -C user=someuser` I get the options list as expected. Is there a way to pass the -C option to the sshd -T command that lynis runs for this test?

**Comment by mboelen** [comment]
Thanks for reporting. Fixed it with commit https://github.com/CISOfy/lynis/commit/84faf57b30702f8e1ca1183ab216e26650be7a7c
