### ISSUE TITLE
Add command line option for skip-test

### ISSUE THREAD

**Issue by CarstenGrohmann** [CISOfy/lynis#549]
Hi Michael,

please add a command line option to choose tests to skip like the existing configuration file entry `skip-test=`. 

With this option you can skip tests w/o writing a configuration file.

Regards,
Carsten

**Comment by d4t4king** [comment]
I can see where it might be useful if the administrator wants to only skip 1 or 2 tests.  Anything more and IMHO it makes more sense to add them to the custom.prf.

**Comment by mboelen** [comment]
As not much feedback came on this possible enhancement proposal, let's park it for now. So that means that the profile should be still used to disable tests.

**Comment by fisher60** [comment]
Hello, sorry to necro this issue, but this seems like an essential feature that is missing. I am experiencing an issue where exactly one test hangs indefinitely so I am unable to complete tests. The docs seem to hint (in multiple places) that skipping a test should be possible ([Suggestion to skip tests that take too long](https://cisofy.com/faq/lynis-takes-a-long-time-to-run-what-can-i-do/), [Suggestion to use profile to disable tests](https://cisofy.com/documentation/lynis/#profiles)), but these solutions are only partially effective (and difficult to discover in my opinion).

I.e in my case, test `CRYP-7902` from `Cryptography` is hanging indefinitely. Commenting out the `crypto` plugin and disabling it in a custom profile and running a test with this profile results in the test still running and therefore the tool unable to execute. The docs seem to be insufficient at explaining how to skip a test. Using Vim, I can search the profile to find `skip-test` setting, which does work to skip the specific test ID, but is cumbersome for a task like this in my opinion.

A flag for `skip-test` and either a category or specific test ID would resolve this issue easily.

A current "example" of what disabling this test on the command line looks like is as follows:

`lynis audit system --tests-from-group "boot_services kernel memory_processes authentication kerberos shells filesystems usb storage storage_nfs nameservices dns ports_packages networking printers_spoolers mail_messaging firewalls webservers ssh snmp databases ldap php squid logging insecure_services banners scheduling accounting time virtualization containers mac_frameworks file_integrity tooling malware file_permissions homedirs kernel_hardening hardening"`

**Comment by mboelen** [comment]
Next time please create a new issue, as we are now responding to old and closed items.

I suggest using "skip-test=CRYP-7902" in your custom.prf file, that should disable the particular test and this way you don't have to disable a full group of tests.

If the issue remains, please create a new issue. Include the version, what you have in your custom.prf, and the command that you use to run.
