### ISSUE TITLE
BOOT-5122 (grub pw check) - reports false positive on grub2 check

### ISSUE THREAD

**Issue by sriegler** [CISOfy/lynis#552]
Check only greps for the default "grub.d/01_users" inclusion, which is not the password protection per se. Because grub2 (this check) checks for the existence of the "/boot/grub2/user.cfg", in which the actual password is stored. If there is no "user.cfg", no password is set and just grepping for stuff inside an if-clause which is never executed, it is issuing a false positive on a grub2 password check.

So for BOOT-5122/grub2 actually the "user.conf" file must be evaluated.

```
### BEGIN /etc/grub.d/01_users ###
if [ -f ${prefix}/user.cfg ]; then
  source ${prefix}/user.cfg
  if [ -n "${GRUB2_PASSWORD}" ]; then
    set superusers="root"
    export superusers
    password_pbkdf2 root ${GRUB2_PASSWORD}
  fi
fi
### END /etc/grub.d/01_users ###
```

**Comment by mboelen** [comment]
Thanks for reporting this. Do you have a suggested code submission?

**Comment by Capashenn** [comment]
To check if grub2 password is set, you could run
`grep "^GRUB2_PASSWORD" /boot/grub2/grub.cfg`

**Comment by xuiqzy** [comment]
On Arch Linux, the path to the `grub.cfg` normally is `/boot/grub/grub.cfg`.

**Comment by mboelen** [comment]
This test was recently changed. I will close this issue for now, with the assumption that it also resolved this issue. If not, feel free to add a remark.
