### ISSUE TITLE
Report print RKHunter=NOT

### ISSUE THREAD

**Issue by daniejstriata** [CISOfy/lynis#556]
In my Lynis 2.6.5 report I see the following that I don't understand:
_RKHunter=NOT_
But I know that RKHunter is installed from the same log:
_malware_scanner[]=rkhunter_

What does the NOT mean?

**Comment by mboelen** [comment]
Can you show the data (a few lines before and after this particular line)?

**Comment by daniejstriata** [comment]
Thank you for that. It seems it is my plugin that is broken. I'll look into it and get back to you.

SOFTWARE[]=/opt/lynis/plugins/plugin_striata-os_phase2:
UPGRADES="Loaded
FIREWALL=NOT
HOSTS_ALLOWED=0
HOSTS_DENIED=EMPTY
Sophos=FOUND
RKHunter=NOT
Zabbix=NOT
DLP=NOT
OCSBINARY=FOUND
OCSCONF=FOUND
OSSEC_INSTALLED=NO
OSSEC_CONF=NOT
OSSEC_SERVER=NOT
AUTHLOG=NOT

**Comment by mboelen** [comment]
Yup, seems like it is storing the wrong data points. Will close this issue, as the cause is in the custom plugin.
