### ISSUE TITLE
FAILLOG_ENAB apparently not available everywhere, PAM to rescue

### ISSUE THREAD

**Issue by FlorianHeigl** [CISOfy/lynis#564]
So, I found on SLES12 you can't use the suggested setting ```FAILLOG_ENAB``` in ```/etc/login.defs```. There's only the way via PAM's **pam_tally2** if you want a dedicated log _with_ counters.
It can be used to count / reset bad logins, and optionally also _lock_ the user account under attack.
I think I've got it configured to do the right thing using ```file=/var/log/faillog``` as a PAM parameter.

This generates the file which FALLOG_ENAB used to create. Probably it should probably also count for "Logging failed login attempts".

```
  - Logging failed login attempts                             [ DISABLED ]
```

**Comment by mboelen** [comment]
Hi @FlorianHeigl 

Thanks for reporting. Can you share your configuration? Then we can do a test in our lab and validate things.

**Comment by FlorianHeigl** [comment]
Hi,

so this is what I can see we configured. I hardly remember by now :-)

in ```/etc/pam.d/login``` we added the following over the SLES standard

```
#%PAM-1.0
auth     requisite      pam_nologin.so
auth     include        common-auth
account  include        common-account
password include        common-password
session  required       pam_loginuid.so
session  include        common-session
#session  optional       pam_lastlog.so nowtmp showfailed
session  optional       pam_mail.so standard
# this will only count, but not lock (for safety reasons. of course it would be more secure, but not neccesarily safer.
# add the following to this line for locking: onerr=fail deny=10 unlock_time=300
auth    required        pam_tally2.so file=/var/log/faillog 
account required        pam_tally2.so file=/var/log/faillog
```

**Comment by FlorianHeigl** [comment]
Ah, and as a followup, I think I remember searching a bit more into the login.defs man pages etc.
FAILLOG_ENAB must have been deprecated over time without much attention by auditors. (or anyone asking them)

**Comment by mboelen** [comment]
Hi @FlorianHeigl - A change has been applied to detect pam_tally2. As it has its own format, it looks like you better not use /var/log/faillog, as that can not be parsed by the faillog utility.

Related commit: https://github.com/CISOfy/lynis/commit/63043b536d7ed8f1c7a03be02e044d23c8382839
