### ISSUE TITLE
PHP option expose_php

### ISSUE THREAD

**Issue by cvieiraeduardo** [CISOfy/lynis#565]
**Describe the bug**
Expose_php already set Off, but on audit says this is enable.
i get all logs, for create a dashboard off all servers, and score of web servers is very down.

**Version**
 - Distribution: CentOS Linux 7 - Kernel 3.10 - PHP 7.1.20 - /etc/php.ini 
 - Lynis version: Lynis 2.6.6

**Comment by mboelen** [comment]
What does the lynis.log show regarding this specific control?

**Comment by cvieiraeduardo** [comment]
*this is a lynis.log:*

2018-07-26 15:15:43 __Performing test ID PHP-2372 (Check PHP expose_php option)__
2018-07-26 15:15:43 __Test: Checking expose_php option__
2018-07-26 15:15:43 __Warning: PHP option expose_php is possibly turned on, which can reveal useful information for attackers. [test:PHP-2372] [details:-] [solution:-]__
2018-07-26 15:15:43 __Suggestion: Change the expose_php line to: expose_php = Off [test:PHP-2372] [details:-] [solution:-]__

**Comment by gemal** [comment]
```
[+] PHP
------------------------------------
  - Checking PHP                                              [ FOUND ]
    - Checking PHP disabled functions                         [ FOUND ]
    - Checking expose_php option                              [ ON ]
    - Checking enable_dl option                               [ OFF ]
    - Checking allow_url_fopen option                         [ ON ]
    - Checking allow_url_include option                       [ OFF ]
```

```
[root@ip1 ec2-user]# php -i |grep expo
expose_php => Off => Off
```

**Comment by mboelen** [comment]
Thanks @cvieiraeduardo and @gemal - Commit https://github.com/CISOfy/lynis/commit/4df28ca6594fe21fd842e2a41303624834e21019 should improve detection, logging, and related details.

Feel free to open a new issue with logging details if this still returns for you.
