### ISSUE TITLE
Docker File false positive

### ISSUE THREAD

**Issue by superpoussin22** [CISOfy/lynis#567]
**Describe the bug**
when auditing a Dockerfile, Lynis report a Warning saying there's no MAINTAINER delcared in the Dockerfile

But MAINTAINER directive is deprecated and is replaced with  (for example) : 
```
LABEL maintainer="SvenDowideit@home.org.au"
```
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

tested on 2.6.6

**Comment by mboelen** [comment]
Thanks for reporting. Do you like to create a pull request to support the new style?

**Comment by superpoussin22** [comment]
will do :)

**Comment by superpoussin22** [comment]
@mboelen  Done in a simple way
