### ISSUE TITLE
Nginx logs bug

### ISSUE THREAD

**Issue by DocEmmetBrown** [CISOfy/lynis#57]
Hi,

I've come with a bug on parsing nginx logs : 

I get this error on every nginx log available : ```
./include/functions: line 781: [: /var/log/nginx/<my_log_file>: binary operator expected
```

in the `include/functions:781`, the ${VALUE} contains "<my_log_file> main" so the -f test cannot return true.

```++ '[' '!' -f /var/log/nginx/<my_log_file> main ']'
```

Thanx for your help

**Comment by d4t4king** [comment]
Is this from a fresh pull or clone?  I'm not able to reproduce the issue.

**Comment by DocEmmetBrown** [comment]
It's the 2.1.0 version, installed from the official tarball.

my access log line in the nginx conf looks like that : 

```
  access_log  /var/log/nginx/my_access.log main;
```

**Comment by mboelen** [comment]
@DocEmmetBrown Please clone latest version into a new directory, run Lynis and see if it still applies.

**Comment by DocEmmetBrown** [comment]
sorry, the latest version seems to fix that bug...  my mistake ;)
