### ISSUE TITLE
Shows Incorrect URLs in suggested fixes

### ISSUE THREAD

**Issue by changosmuertos** [CISOfy/lynis#573]
**Describe the bug**
Shows Incorrect URLs in suggested fixes

**Version**
 - Distribution Ubuntu 17.10
 - Lynis version 2.6.7

**Expected behavior**
URLs should be correct, however they show as follows, see below.

**Output**
If applicable, add output that you get from the tool or the related section of lynis.log
* Install libpam-tmpdir to set $TMP and $TMPDIR for PAM sessions [CUST-0280] 
      **https://your-domain.example.org/controls/CUST-0280/**

  * Install libpam-usb to enable multi-factor authentication for PAM sessions [CUST-0285] 
      **https://your-domain.example.org/controls/CUST-0285/**

  * Install apt-listbugs to display a list of critical bugs prior to each APT installation. [CUST-0810] 
      **https://your-domain.example.org/controls/CUST-0810/**

  * Install debian-goodies so that you can run checkrestart after upgrades to determine which services are using old versions of libraries and need restarting. [CUST-0830] 
      **https://your-domain.example.org/controls/CUST-0830/**

  * Install debsums for the verification of installed package files against MD5 checksums. [CUST-0875] 
      **https://your-domain.example.org/controls/CUST-0875/**

  * Set a password on GRUB bootloader to prevent altering boot configuration (e.g. boot in single user mode without password) [BOOT-5122] 
      **https://cisofy.com/controls/BOOT-5122/**

**Comment by mboelen** [comment]
Looks like you have some custom tests in there (CUST-xxxx). As we (=the project) don't know what to show for custom tests, Lynis replaces the URL with a placeholder. So this is expected behavior.

You can configure Lynis to change the URL to something of your own:
custom-url-protocol=https
custom-url-prepend=your-domain.example.org/control-info/
custom-url-append=/

**Comment by changosmuertos** [comment]
No custom anything, this is straight out of the box. Just running audit system.

**Comment by mboelen** [comment]
All tests starting with 'CUST-' are custom tests. In this case, you did not add them manually but got them by installing the Debian/Ubuntu package.

These custom tests are outside of the control of the Lynis project. This is something we rather avoid, as custom tests may contain issues that we can't resolve. We are talking with the package maintainer to see if all customizations can be dropped and integrated into the upstream project (that is, to the Lynis project directly).

You can resolve this issue (read: having non-official custom additions) by using the [official repository](https://packages.cisofy.com/). The alternative is to disable the tests using the `skip-test=` profile option.

Does that make sense?

**Comment by changosmuertos** [comment]
got you, tyvm.
