### ISSUE TITLE
PKGS-7388 (Check security repository in Debian/ubuntu apt sources.list file)

### ISSUE THREAD

**Issue by kairaven** [CISOfy/lynis#576]
Lynis doesn't find a security repository, because it doesn't check for sources informations in *.sources files with the DEB822-style format (see https://manpages.debian.org/sources.list) under Debian.

Debian Stretch (9.5)
Lynis 2.6.8

I have in /etc/apt/souces.list.d/debian.sources:

Types: deb
URIs: https://repositorydomain/debian-security
Suites: stretch/updates
Components: main contrib non-free
Architectures: amd64

So, Lynis should check *.sources files too and/or inside *.sources files the "debian-security" string.

lynis.log output:
2018-08-28 09:39:18 Performing test ID PKGS-7388 (Check security repository in Debian/ubuntu apt sources.list file)
2018-08-28 09:39:18 Searching for security.debian.org/security.ubuntu.com or security repositories in /etc/apt/sources.list file
2018-08-28 09:39:18 Searching for security.debian.org/security.ubuntu.com or security repositories in /etc/apt/sources.list.d directory
2018-08-28 09:39:18 Warning: Can't find any security repository in /etc/apt/sources.list or sources.list.d directory [test:PKGS-7388] [details:-] [solution:-]

**Comment by mboelen** [comment]
Thanks for reporting. Got the chance to make a pull request for this?

**Comment by JordiRoAl** [comment]
Hi,
how I can solve this Warning: [2C- Checking security repository in sources.list file or directory[0C [ [1;31mPELIGRO[0m ] ? what means this issue? 
Thanks.
Jordi.

**Comment by mboelen** [comment]
@JordiRoAl - please have a look in your lynis.log file for the details.

**Comment by JordiRoAl** [comment]
Sorry, but I don't see what's the solution in my lynis.log file. The solution text don't appear. Somebody can explain me this issue?
Thanks a lot.

**Comment by mboelen** [comment]
@kairaven - can you test with the latest version from GitHub to see if you still have this issue? I just checked and can't reproduce it. If you still have it, please provide the full file content so we can use that to reproduce.

**Comment by mboelen** [comment]
Closing for now, as part of cleanup and no response was received yet. Due to other related patches, this issue might be resolved already.

**Comment by Cyrille37** [comment]
Hi @mboelen 

I'm not sure the issue is resolved.

With Lynis 3.1.2 on debian 12.7 it still warning `Can't find any security repository in /etc/apt/sources.list or sources.list.d directory [PKGS-7388]`. 

Here is the content of `/etc/apt/sources.list.d/debian.sources ` :
```
Types: deb deb-src
URIs: mirror+file:///etc/apt/mirrors/debian.list
Suites: bookworm bookworm-updates bookworm-backports
Components: main

Types: deb deb-src
URIs: mirror+file:///etc/apt/mirrors/debian-security.list
Suites: bookworm-security
Components: main
```

Cheers :-)
