### ISSUE TITLE
how to use crontab audit result in my develop plugin?

### ISSUE THREAD

**Issue by nancheal** [CISOfy/lynis#577]
hi
what should i do if i want to use test like "lynis/include/tests_scheduling" in my develop plugin?
is it to change header like "PLUGIN_REQUIRED_TESTS=SCHD-7702,SCHD-7704,SCHD-7718,SCHD-7720,SCHD-7724"?

**Comment by nancheal** [comment]
@mboelen thank you for teach me the use of tests_custom file . after some try , i have some question, the first is what the difference between a plugin and a test in include/tests_* ? seconde is  if i want to write a custom test , all my code can only be type in tests_custom file , i can't custom the file name , is it right?

**Comment by mboelen** [comment]
Hi @nancheal - Yes, there is just tests_custom for that purpose. You can easily put 10-20 custom tests in there. If you have really more tests that you like to add, then consider to do some contributions to the project and get them into the main program :)

Plugins extend the data collection, tests perform some logic. So typically you just want to have a few check tests and it is better to place them in tests_custom.

Hope that helped. Will close this issue, but feel free to add more comments or contact me directly for further guidance.
