### ISSUE TITLE
PKGS-7322: Vulnerable packages found

### ISSUE THREAD

**Issue by PsiACE** [CISOfy/lynis#582]
>  ! Vulnerable packages found [PKGS-7322] 
    - Details  : arch-audit has output
    - Solution : Update packages with pacman -Suy
      https://cisofy.com/lynis/controls/PKGS-7322/

- [x]: Prompt to run `pacman -Suy`, but in fact everything is up to date.
- [x]: Lack of content on a web page, Oops, looks like this control is not listed yet in the database.

I suggest modifying the solution and providing the appropriate web content.

- Modify the solution to: "Run arch-audit for details, and update packages with pacman -Suy might be able to solve part of the problem."
- Provide a reliable description on the web page, at least pointing out the specifics of the problem and pointing out that there are still problems even in some of the latest versions of those packages. 

I think it will at least help people understand the problem correctly and make the right choice.

Thank you for your awesome work.

**Comment by mboelen** [comment]
Improved with change https://github.com/CISOfy/lynis/commit/b4e93d4fccf17f63da48e31aa863ccb74b2eaee2 and control has been added to website.

Thanks for your feedback and reporting this!
