### ISSUE TITLE
No package repository available for Ubuntu Bionic

### ISSUE THREAD

**Issue by rchekaluk** [CISOfy/lynis#584]
**Describe the bug**
Executing this command
```
sudo add-apt-repository "deb [arch=amd64] https://packages.cisofy.com/community/lynis/deb/ bionic main"
```
yields error:
```
Err:8 https://packages.cisofy.com/community/lynis/deb bionic Release                       
  404  Not Found [IP: 37.97.194.171 443]
Reading package lists... Done                                                              
E: The repository 'https://packages.cisofy.com/community/lynis/deb bionic Release' does not have a Release file.
```

**Version**
 - Ubuntu 18.04.1 LTS

**Expected behavior**
Respository installed successfully; able to install lynis package thereafter.

**Output**

**Additional context**

**Comment by mboelen** [comment]
The answer of @superpoussin22 is correct. Use the 'stable' branch on the repository and it will work also on Ubuntu 18.04.
