### ISSUE TITLE
'Warning' labeled mentions' count is non-correct

### ISSUE THREAD

**Issue by Ricky-Tigg** [CISOfy/lynis#591]
**Describe the bug** _Warning_ labeled **mentions'** count is non-correct

**Version**
 - Fedora 29
 - Lynis v.2.6.9

**Expected behavior** _Warning_ labeled **mentions'** count to be correct. Here **two** mentions.

**Output**
`$ LANG=C lynis audit system --pentest  --logfile ~/.pen-test0`

![lynis_v 2 6 9_pentest_warnigs_count1](https://user-images.githubusercontent.com/26058215/47012300-49be7500-d144-11e8-9f94-69a4e8e51578.png)

![lynis_v 2 6 9_pentest_warnigs_count2](https://user-images.githubusercontent.com/26058215/47012316-55aa3700-d144-11e8-980a-b9779c5fddc7.png)

![lynis_v 2 6 9_pentest_warnigs_count3](https://user-images.githubusercontent.com/26058215/47012330-5e9b0880-d144-11e8-8720-1732c85352a2.png)

**Additional context**
Test conducted under the system language on local system:
```
$ locale
LANG=fi_FI.UTF-8
```

**Comment by mboelen** [comment]
Thanks for reporting.

Some of the 'warning' labels are not always linked to a warning in the report. Sometimes they have a related suggestion. The status of the mentioned items have been replaced with commit https://github.com/CISOfy/lynis/commit/823ebd8268ea603a00b4c582b95eb43449948b3c
