### ISSUE TITLE
Checking for IDS/IPS tooling [ NONE ]

### ISSUE THREAD

**Issue by iohenkies** [CISOfy/lynis#592]
Hi, not really a bug I think but more a question: what is considered IDS or IPS tooling? Since we have OSSEC with or without active response and CSF with some of the same functionality, why would this not be considered as IDS/IPS?

This is on multiple Debian systems, but all unfortunately with the same outcome:
Checking for IDS/IPS tooling [ NONE ]

**Comment by mboelen** [comment]
Thanks for the suggestion. Can you share the OSSEC processes that you have active?

**Comment by iohenkies** [comment]
Sure and thanks!

```
# systemctl status ossec
● ossec.service - LSB: Start and stop OSSEC HIDS
   Loaded: loaded (/etc/init.d/ossec; generated; vendor preset: enabled)
   Active: active (running) since Fri 2018-10-19 11:18:39 CEST; 3h 50min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 17026 ExecStop=/etc/init.d/ossec stop (code=exited, status=0/SUCCESS)
  Process: 17089 ExecStart=/etc/init.d/ossec start (code=exited, status=0/SUCCESS)
    Tasks: 5 (limit: 4915)
   CGroup: /system.slice/ossec.service
           ├─17110 /var/ossec/bin/ossec-maild
           ├─17118 /var/ossec/bin/ossec-analysisd
           ├─17124 /var/ossec/bin/ossec-logcollector
           ├─17287 /var/ossec/bin/ossec-syscheckd
           └─17300 /var/ossec/bin/ossec-monitord
```

And:

```
# ps waux | grep ossec
ossecm   17110  0.0  0.0  34068  1984 ?        S    11:18   0:00 /var/ossec/bin/ossec-maild
ossec    17118  0.8  0.1  35932  4072 ?        S    11:18   1:53 /var/ossec/bin/ossec-analysisd
root     17124  0.0  0.0  25632  1924 ?        S    11:18   0:01 /var/ossec/bin/ossec-logcollector
root     17287  0.5  0.2  32164  8744 ?        S    11:18   1:11 /var/ossec/bin/ossec-syscheckd
ossec    17300  0.0  0.0  34188   496 ?        S    11:18   0:00 /var/ossec/bin/ossec-monitord
```

**Comment by mboelen** [comment]
Change has been made (commit https://github.com/CISOfy/lynis/commit/de7d64a8a0be0dcb7a8375e248525b01813563c4). Can you check if the Git version properly detects this on your system?

**Comment by iohenkies** [comment]
Hi, forgive my ignorance, how can I check? I've installed Lynis with the Cisofy repo, but apt update doesn't pick it up?

**Comment by mboelen** [comment]
If you have Git on your system:

1. apt remove lynis
2. git clone https://github.com/CISOfy/lynis
3. cd lynis
4. ./lynis audit system
5. [validate if it is detected]
6. remove 'lynis' subdirectory
7. apt install lynis

**Comment by iohenkies** [comment]
Thanks. These steps download Lynis 2.7.0 and then IDS/IPS tooling is properly detected ;-). Of course when apt installing it again, I have 2.6.9 again and it is not detected,

**Comment by mboelen** [comment]
Great, then it works like intended. The 2.7.0 version will be released very soon.

Thanks for the confirmation!

**Comment by ocafebabe** [comment]
@mboelen I'm currently evaluating Lynis for our SaaS environments and I've stumbled on the same problem! Is it possible to get a list of the tools that are evaluated during the scan? IMHO just reporting that none was found isn't really helpful... Is it more verbose with the commercial version?

**Comment by mboelen** [comment]
@ocafebabe This particular check tests for a set of known tools. So if it can't detect any of them, it will show "NONE". But that is where feedback from the community helps. If you have something running that is not detected yet, let us know what tooling you are running. Typically we can match on process name and add it to this particular test.

**Comment by ocafebabe** [comment]
@mboelen Is it possible to get the list of tools that are curently checked during this test?

**Comment by mboelen** [comment]
Hi @luis02lopez - please create a new issue and show the output of 'ps aux' with the related process(es). Then we can look into it.

**Comment by luis02lopez** [comment]
Sure, give me 20 minutes.

Luis E. López Andrade
AWS Certified and DevOps Engineer

________________________________
