### ISSUE TITLE
macOS Mojave "Unknown macOS Version"

### ISSUE THREAD

**Issue by jpartain89** [CISOfy/lynis#597]
**Describe the bug**
The initialization step outputs the error ```Unknown macOS version. Do you know what version it is? Create an issue at https://github.com/CISOfy/lynis```

**Version**
 - macOS Mojave 10.14.1
 - Lynis version 2.7.0

**Expected behavior**
Lynis should be able to identify the macOS Version

**Output**
```
[+] Initializing program
------------------------------------
Unknown macOS version. Do you know what version it is? Create an issue at https://github.com/CISOfy/lynis
  - Detecting OS...                                           [ DONE ]
  - Checking profiles...                                      [ DONE ]

  ---------------------------------------------------
  Program version:           2.7.0
  Operating system:          macOS
  Operating system name:     Mac OS X
  Operating system version:  10.14.1
  Kernel version:            18.2.0
  Hardware platform:         x86_64
  Hostname:                  JustinsMBA
```

**Comment by mboelen** [comment]
Thanks for reporting. Detection has been added with commit https://github.com/CISOfy/lynis/commit/28a2580a36e2454c04a074bfaa00bb1df26510eb

**Comment by kehao95** [comment]
This issue is not fixed yet.
https://github.com/CISOfy/lynis/commit/28a2580a36e2454c04a074bfaa00bb1df26510eb#r31359132
