### ISSUE TITLE
AUTH-9328 (Default umask values)

### ISSUE THREAD

**Issue by DocEmmetBrown** [CISOfy/lynis#60]
Hi,

when no umask is setted in /etc/profile, the result of the test is : 

```
[17:19:19] Result: found several umask values configured in /etc/profile
[17:19:19] Hardening: assigned 1 hardening points (max for this item: 2), current: 1, total: 2
[17:19:19] Hardening: assigned 2 hardening points (max for this item: 2), current: 3, total: 4
```
because the item : 
```
FIND2=`grep "umask" /etc/profile | sed 's/^[ \t]*//' | grep -v "^#" | awk '{ print $2 }' | wc -l`
```
returns 0, and the following test is 
```
if [ "${FIND2}" = "1" ]; then OK ; else "found several values"; fi
```
doesn't act differently if the result is 0 or a number greater than 1.

**Comment by mboelen** [comment]
Patch applied. Can you test if it properly works for your system as well?

**Comment by mboelen** [comment]
@DocEmmetBrown Patch applied, does it work correctly for you?

**Comment by mboelen** [comment]
Several improvements have been made to properly detect the umask values. Closing this issue, to keep the list clean. When something still needs attention, reopen the issue.

Thanks for reporting this issue!
