### ISSUE TITLE
SSH-7408 : Clarifications on few options 

### ISSUE THREAD

**Issue by sashank** [CISOfy/lynis#604]
**Describe the bug**
We are reviewing the SSH Related checks performed by Lynis ,  for below options we have questions. 

```  ## SSHOPTIONS scheme:
        ##      <OptionName>:<ExpectedValue>,<MediumScoreValue>,<WeakValue>:<TestType>
        ##
        ##      Test types:
        ##      (a) '='         -- equal to is better,
        ##      (b) '<'         -- less or equal is better,
        ##      (c) '>'         -- more or equal is better,
        ##      (d) '!'         -- not equal is better.
        ##
        ##      Example:
        ##      PermitRootLogin:NO,WITHOUT-PASSWORD,YES,:=
                Compression:NO,,YES:=\
                Port:,,22:!\
                AllowAgentForwarding:NO,,YES:=\"
                TCPKeepAlive:NO,,YES:=\
```

**Version**
 - Distribution Ubuntu 18.04
 - Lynis version latest

**Expected behavior**

- Is turning on Compression a Security Risk ? any further reference ? 
- Not sure why the rule `Port:,,22:!` ? Isn't the expected value 22 and the rule should be `Port:22,,:1`
- Why is AllowAgentForwarding expected value is No ? Isn't it safe to use it that way according to this [link](https://yakking.branchable.com/posts/ssh-A/)  ? 
- Why is prefered vaue of TCPKeepAlive NO)?  [Reference](https://security.stackexchange.com/questions/186655/openssh-server-are-there-any-security-implications-and-or-value-of-for-tcpkeep)

**Additional context**
Hope you could provide explanations for the above ?

**Comment by lpirl** [comment]
> Is turning on Compression a Security Risk ? any further reference ?

see #217

**Comment by mboelen** [comment]
Hi @sashank - Lynis provides suggestions to improve the security of your system. However, you have to do the evaluation, and make a risk estimation for your system or environment. Now the difficulty with best practices is that they aren't always the best.

Regarding port 22: it is fine to run it on port 22. But if you run it on another one and get it out of sight, it might be an additional layer (yes, security through obscurity, but still some level of cloaking).
