### ISSUE TITLE
Run lynis as user 

### ISSUE THREAD

**Issue by arthurlogilab** [CISOfy/lynis#606]
**Describe the bug**
lynis fails when launched as user and not as root

**Version**
 - Distribution: Ubuntu 18.04
 - Lynis version: 2.6.2-1

**Expected behavior**
For example when using the audit dockerfile is there a need to run lynis as root ? 

**Output**

```
$ lynis --help
/usr/sbin/lynis: 204: .: Can't open /usr/share/lynis/include/consts
$ lynis audit dockerfile local/gaia/docker/Dockerfile
/usr/sbin/lynis: 204: .: Can't open /usr/share/lynis/include/consts
```

**Comment by mboelen** [comment]
How did you install this package? Looks like an issue with file permissions. Is the 'consts' file actually there?

**Comment by njxjackson87** [comment]
$ lynis --help
/usr/sbin/lynis: 204: .: Can't open /usr/share/lynis/include/consts
$ lynis audit dockerfile local/gaia/docker/Dockerfile
/usr/sbin/lynis: 204: .: Can't open /usr/share/lynis/include/consts

**Comment by arthurlogilab** [comment]
@mboelen I've installed it using the apt package manager.

**Comment by mboelen** [comment]
Looks like we can't resolve that, as it is caused by the package itself. I could suggest running as root or changing the file permissions manually. I suggest sending in a [bug report](https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=lynis) in the Debian bug tracker.

**Comment by arthurlogilab** [comment]
OK. Thanks for taking a look at my bug report.

**Comment by Dmole** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939325
