### ISSUE TITLE
NETW-300X Find active network interfaces

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#607]
I think it would be a good idea during audits to be able to check for active network connections on a system in addition to checking the available connections.
This would ensure that the network is properly configured (e.g. no connection waiting for dhcp)

It could be done
with ifconfig : just doing ifconfig give the active network interfaces
or with ip : ip link show give the state of network interfaces "state UP/DOWN"

This could be added as a new test (e.g. NETW-300X)

**Comment by mboelen** [comment]
As part of a cleanup of old issues to prioritize on the upcoming major release, this issue will be closed. Feel free to submit a pull request with initial work.
