### ISSUE TITLE
[STRG-1842] Error when authorize(_default) files don't exists

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#610]
**Describe the bug**
When files authorized and authorized_default don't exists in /sys/bus/usb/devices/usb*, the test report that "None USB devices are authorized by default (or temporary) to connect to the system" but actually you can.

**Version**
 - Distribution : Centos/RHEL 5 and before
 - Lynis version : 2.7.1

**Expected behavior**
If these files don't exists, it would be better not to do this test

**Comment by mboelen** [comment]
Closing after pull request https://github.com/CISOfy/lynis/pull/680 was merged
