### ISSUE TITLE
[BOOT-5177] add more consistency to this test

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#613]
**Is your feature request related to a problem? Please describe.**
The test [BOOT-5177] log : 
`LogText "Note: Run systemctl list-unit-files --type=service to see all services"` for systemd
`LogText "Hint: Run chkconfig --list to see all services and disable unneeded services"` for chkconfig

**Describe the solution you'd like**
I think it shoud log the same : Note or Hint (easier to search in the log file)
Moreover this note/hint should be displayed by Lynis output with warnings and suggestions

**Required changes**
Change code for test [BOOT-5177]

**Comment by mboelen** [comment]
Thanks for the suggestion.

In this case, it is just a suggested command to help people if they want to know how to find more details. This is different than most tests, in the way that the output from this test is always informational (e.g. not a warning or suggestion), stating how many services are discovered.

The Note:/Hint: line has been adjusted.
