### ISSUE TITLE
[BOOT-5184] check systemd startup scripts

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#614]
**Is your feature request related to a problem? Please describe.**
Test [BOOT-5180] only check for SysVinit startup script.
With new systemd, this test should check for systemd startup scripts also.

**Describe the solution you'd like**
Check systemd startup script in /lib/systemd/system and /etc/systemd/system

**Required changes**
Change code in [BOOT-5180] or add a new test.

**Comment by mboelen** [comment]
Updated original question to reflect correct test ID.

BOOT-5177 is already taking care of services that are enabled during boot. So no change is needed.
