### ISSUE TITLE
[CRYPT] or [FILE] check for encrypted partitions

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#615]
**Is your feature request related to a problem? Please describe.**
It should be nice if lynis could check for encrypted partitions (LUKS)

**Describe the solution you'd like**
Check for encrypted (LUKS) partitions

**Required changes**
Add a new test in [CRYPT] or [FILE] to check for encrypted (LUKS) partitions
```
$ blkid /dev/sdb1
/dev/sdb1: UUID="xxxxxxxxxxxx" TYPE="crypto_LUKS"   #encrypted
```

**Comment by pyllyukko** [comment]
I think a better test would be:

```
cryptsetup isLuks /dev/sdb1
```

It returns `0` if it's LUKS and `1` when it's not.

**Comment by mboelen** [comment]
Test CRYP-7930 was already implemented to check this. Closing this issue.
