### ISSUE TITLE
[DBS] PostgreSQL client authentication

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#616]
**Is your feature request related to a problem? Please describe.**
It should be nice if lynis could check for client authentication in postgresql.

**Describe the solution you'd like**
Check authentication and authorization to databases in pg_hba.conf,
Check who can access to databases and how.

```
$ cat pg_hba.conf
local      database  user  auth-method  [auth-options]
host       database  user  address  auth-method  [auth-options]
hostssl    database  user  address  auth-method  [auth-options]
hostnossl  database  user  address  auth-method  [auth-options]
host       database  user  IP-address  IP-mask  auth-method  [auth-options]
hostssl    database  user  IP-address  IP-mask  auth-method  [auth-options]
hostnossl  database  user  IP-address  IP-mask  auth-method  [auth-options]
```

**Required changes**
Add a new test DBS-XXXX

**Additional context**
pg_hba.conf : Each record specifies a connection type, a client IP address range (if relevant for the connection type), a database name, a user name, and the authentication method to be used for connections matching these parameters. The first record with a matching connection type, client address, requested database, and user name is used to perform authentication. There is no "fall-through" or "backup": if one record is chosen and the authentication fails, subsequent records are not considered. If no record matches, access is denied.

**Comment by mboelen** [comment]
Thanks for the suggestion. I see the value of parsing a file, but only if one would know a particular client, and/or user, and/or database combination. On the average system it is hard to know that.

What specifically would you like to have checked that could result in a GOOD/BAD outcome?

**Comment by Capashenn** [comment]
From [OWASP Backend Security Project PostgreSQL Hardening](https://www.owasp.org/index.php/OWASP_Backend_Security_Project_PostgreSQL_Hardening#pg_hba.conf_-_Client_Authentication), lynis should check : 

- Disable all trust connections
`# grep trust pg_hba.conf`
`Suggestion : Disable all trust connections`
- Use strong authentication (md5/kerberos etc)
`# egrep 'crypt|password' pg_hba.conf`
`Suggestion : Use md5 or stronger authentication`
- Limit connections only from allowed IP
`# grep 0.0.0.0 pg_hba.conf | grep -v reject`
`Suggestion : Limit connections only from allowed IP`
*Perhaps, we could also check the ip addresses of the audited system ?
- Use SSL connection
`# egrep '^host|^hostnossl' pg_hba.conf` | egrep -v 'localhost|127.0.0.1|::1'
`Suggestion : use hostssl instead of host or hostnossl`

**Comment by mboelen** [comment]
Any taker that like to create some pull requests (tested preferably on a few different Linux distributions to cover all paths)?

**Comment by mboelen** [comment]
Closing this issue as part of cleaning older issues and it was not picked up by the community yet.
