### ISSUE TITLE
[FINT]  AIDE - Ensure filesystem integrity is regularly checked

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#619]
**Is your feature request related to a problem? Please describe.**
Lynis should ensure filesystem integrity is regularly checked

**Describe the solution you'd like**
lynis should check that crond is running and that there is an aide job
```
# crontab -u root -l | grep aide
# grep -r aide /etc/cron.* /etc/crontab
```

**Required changes**
Add a new tests FINT-XXXX to lynis

**Additional context**
This test could also be added for other integrity softwares but i don't know them as well as AIDE

**Comment by mboelen** [comment]
Thanks for the suggestion. While it is a good suggestion, it is hard to properly implement it at this moment. Besides a variety of tools, also cron tasks can be at several places. Even the mentioning of aide itself in such files would not guarantee that the tool is properly executed. It might be better to implement such test in a monitoring tool or SIEM solution that collects the data from AIDE.
