### ISSUE TITLE
How to run the compliance tests?

### ISSUE THREAD

**Issue by YanFird** [CISOfy/lynis#62]
I'm trying to run an hardening compliance tests with Lynis. after the test is done I see: 
- **Compliance Test [X]** <br>
Is the Compliance tests only available in the Lynis enterprise suite or I'm missing something?

**Comment by quantumpacket** [comment]
@YanFird see https://cisofy.com/lynis-enterprise/why-upgrade/ only the online Auditor or Premium offer compliance testing.

**Comment by mboelen** [comment]
The compliance section is marked with a "[V]" when related tests are performed. Right now, some compliance tests are only available in the full suite, as they collect data and get processed on a central node. Later on, more tests will be created which are also available in the Lynis-only version.
