### ISSUE TITLE
[FINT] AIDE - Ensure database exists

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#620]
**Is your feature request related to a problem? Please describe.**
Lynis should ensure that the database exists

**Describe the solution you'd like**
lynis should check that the database file exists because if it doesn't, aide always fail

```
# aide --check
Couldn't open file /var/lib/aide/aide.db.gz for reading
```

A piece of code to help (works with CentOS/Debian): 
```
DBDIR=$(grep ^database= ${AIDECONFIG} | sed "s/.*://")
if case ${DBDIR} in @@*) ;; *) false;; esac; then
    DBDIR=$(echo ${DBDIR} | sed "s#.*}#$(grep  "@@define.*DBDIR" {AIDECONFIG} | awk '{print $3}')#")
fi
if [ -s ${DBFILE} ]; then
    LogText "Result: found aide database ${DBDIR}"
fi
```

**Required changes**
Add a new tests FINT-XXXX to lynis

**Additional context**
This test could also be added for other integrity softwares but i don't know them as well as AIDE

**Comment by mboelen** [comment]
Sounds like a good suggestion and can be easily checked. Can you turn this into a pull request?

Suggested test ID: FINT-4316

**Comment by Capashenn** [comment]
Of course, I can do that.
As soon as I have a moment to spare I will code this new test.

**Comment by mboelen** [comment]
Implemented by @Capashenn with commit https://github.com/CISOfy/lynis/pull/623

**Comment by mboelen** [comment]
This was already implemented, but not closed yet. So closing issue now.
