### ISSUE TITLE
[SSH-7402] SSH_DEAMON_OPTIONS_FILE empty

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#621]
**Describe the bug**
I know I'm a little late but in OpenSSH releases before 5.1 the "-T" option didn't exist, so the file SSH_DEAMON_OPTIONS_FILE is always empty and SSH-7408 test never works

**Version**
 - Distribution RHEL 5
 - Lynis version 2.7.1

**Expected behavior**
Lynis should parse /etc/ssh/sshd_config if -T option doesn't exist in OpenSSH

**Output**
```
[root@localhost ~]# sshd -T
sshd: illegal option -- T
OpenSSH_4.3p2, OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008
```

**Additional context**
related to #159

**Comment by mboelen** [comment]
Thanks for reporting.

As this is a really old version, it is not worth the effort of changing the test at this point. Even RHEL 5 itself is no longer supported by the vendor and ended in [2015](https://access.redhat.com/support/policy/updates/errata).

**Comment by Capashenn** [comment]
Although there are still many redhat 5 in some industries, I agree with you.
So, it would make more sense to add a prerequisite on the OpenSSH version for this test, if the version is lower than 5.1, we don't do this test.
