### ISSUE TITLE
Inconsistent recording of some suggestions

### ISSUE THREAD

**Issue by d4t4king** [CISOfy/lynis#622]
**Describe the bug**
Not all suggestions are recorded in /var/log/lynis-report.dat in a consistent format.
* ```suggestion[]=KRNL-6000|One or more sysctl values differ from the scan profile and could be tweaked||Change sysctl value or disable test (skip-test=KRNL-6000:<sysctl-key>)|```
* ```suggestion[]=PHP-2372|Turn off PHP information exposure|expose_php = Off|-|```
/Should Be:/
* ```suggestion[]=KRNL-6000|One or more sysctl values differ from the scan profile and could be tweaked; Change sysctl value or disable test (skip-test=KRNL-6000:<sysctl-key>)|-|```
* ```suggestion[]=PHP-2372|Turn off PHP information exposure; expose_php = Off|-|```

**Version**
 - Distribution [e.g. Ubuntu 18.04]
Debian 8.11
 - Lynis version [e.g. 22]
2.7.1 (from github)

**Expected behavior**
Fields should map to expected format of id|description|severity|other.  

**Output**
NA

**Additional context**
NA

**Comment by mboelen** [comment]
Output values have two different formats (old and new). The goal is to migrate them all to the new one that includes all fields. You are welcome to send in pull requests for any test that you encounter with the old format.

**Comment by pavlychs** [comment]
Hi,
Please run the next code from lynis home directory. The output will help you to unify  ReportSuggestion calls and find messages strings which need to be combined into one.
`grep -nE "ReportSuggestion \"?\\$\{TEST_NO\}" * | while read -r INLINE; do
	if [ $(echo ${INLINE} | grep -o '"' | wc -l) -gt "2" ]; then
		echo ${INLINE};
	fi;
done`

**Comment by d4t4king** [comment]
> grep -nE "ReportSuggestion \"?\\$\{TEST_NO\}" * | while read -r INLINE; do if [ $(echo ${INLINE} | grep -o '"' | wc -l) -gt "2" ]; then echo ${INLINE}; fi; done

This just throws errors for me that it's trying to grep a directory.

**Comment by pavlychs** [comment]
tests_accounting:306: ReportSuggestion "${TEST_NO}" "Check status of audit daemon"
tests_accounting:374: ReportSuggestion "${TEST_NO}" "Check if the Solaris audit directory is available"
tests_accounting:379: ReportSuggestion "${TEST_NO}" "Check if the Solaris audit directory is properly configured"
tests_authentication:843: ReportSuggestion "${TEST_NO}" "Delete accounts which are no longer used"
tests_boot_services:818: ReportSuggestion "${TEST_NO}" "Protect rescue.service by using sulogin"
tests_containers:120: ReportSuggestion "${TEST_NO}" "Run 'docker info' to see warnings applicable to Docker daemon"
tests_containers:151: ReportSuggestion "${TEST_NO}" "Test output of both 'docker ps -a' and 'docker info', to determine why they report a different amount of containers"
tests_containers:181: ReportSuggestion "${TEST_NO}" "More than 10 unused containers found on the system. Clean up old containers by using output of 'docker ps -a' command"
tests_custom.template:98: ReportSuggestion "${TEST_NO}" "Check if this process is running" "apache" "url:https://cisofy.com/support/"
tests_databases:329: ReportSuggestion "${TEST_NO}" "Configure the 'requirepass' setting for Redis" "${FILE}" "text:configure 'requirepass' setting in ${FILE}"
tests_databases:355: ReportSuggestion "${TEST_NO}" "Use the 'rename-command CONFIG' setting for Redis" "${FILE}" "text:configure 'rename-command CONFIG' in ${FILE}"
tests_databases:381: ReportSuggestion "${TEST_NO}" "Use 'bind' setting to listen on localhost for Redis instance" "${FILE}" "text:configure 'bind localhost' in ${FILE}"
tests_dns:57:# #ReportSuggestion "${TEST_NO}" "Altered DNS queries are accepted, configure DNSSEC valdating name servers"
tests_file_integrity:95: ReportSuggestion "${TEST_NO}" "Check the AIDE configuration file as it may contain errors"
tests_filesystems:47: ReportSuggestion ${TEST_NO} "Symlinked mount point needs to be checked manually" "${I}" ""
tests_filesystems:345: # TODO ReportSuggestion "${TEST_NO}" "Consider mounting /proc via /etc/fstab with mount option hidepid=2" "/proc" "-"
tests_filesystems:394: ReportSuggestion ${TEST_NO} "Set the sticky bit on ${ROOTDIR}tmp, to prevent users deleting (by other owned) files in the /tmp directory." "/tmp" "text:Set sticky bit"
tests_filesystems:417: ReportSuggestion ${TEST_NO} "Set the sticky bit on ${ROOTDIR}var/tmp, to prevent users deleting (by other owned) files in the /var/tmp directory." "/var/tmp" "text:Set sticky bit"
tests_hardening:102: ReportSuggestion ${TEST_NO} "Harden the system by installing at least one malware scanner, to perform periodic file system scans" "-" "Install a tool like rkhunter, chkrootkit, OSSEC"
tests_insecure_services:105: ReportSuggestion "${TEST_NO}" "Disable telnet in inetd configuration and use SSH instead"
tests_kernel:390: ReportSuggestion ${TEST_NO} "Determine why ${ROOTDIR}vmlinuz is missing on this Debian/Ubuntu system." "/vmlinuz"
tests_kernel:441: ReportSuggestion "${TEST_NO}" "Check if core dumps need to be enabled on this system"
tests_kernel:465: ReportSuggestion "${TEST_NO}" "Determine if all binaries need to be able to core dump"
tests_kernel_hardening:109: ReportSuggestion ${TEST_NO} "One or more sysctl values differ from the scan profile and could be tweaked" "" "Change sysctl value or disable test (skip-test=${TEST_NO}:<sysctl-key>)"
tests_mac_frameworks:103: ReportSuggestion "${TEST_NO}" "Check output of aa-status" "${FILE}" "text:Run aa-status"
tests_mail_messaging:217: ReportSuggestion ${TEST_NO} "Found a configuration error in Postfix" "${POSTFIX_CONFIGFILE}" "text:run postconf > /dev/null"
tests_mail_messaging:273: ReportSuggestion "${TEST_NO}:disable_vrfy_command" "Disable the 'VRFY' command" "disable_vrfy_command=no" "text:run postconf -e disable_vrfy_command=yes to change the value"
tests_nameservices:584: ReportSuggestion "${TEST_NO}" "Remove duplicate lines in ${ROOTDIR}etc/hosts"
tests_nameservices:661: ReportSuggestion ${TEST_NO} "Split resolving between localhost and the hostname of the system" "/etc/hosts" "text:Check your localhost line"
tests_networking:105: ReportSuggestion "${TEST_NO}" "Check your MTU configuration of IPv6 interfaces"
tests_networking:564: ReportSuggestion "${TEST_NO}" "Determine why system has many connections in WAIT state (${FIND})"
tests_php:245: ReportSuggestion ${TEST_NO} "Turn off PHP information exposure" "expose_php = Off" "-"
tests_ports_packages:175: ReportSuggestion "${TEST_NO}" "Check RPM database as RPM binary available but does not reveal any packages"
tests_ports_packages:239: ReportSuggestion "${TEST_NO}" "Perform update of system updates as this system uses rolling updates"
tests_ports_packages:305: ReportSuggestion "${TEST_NO}" "Consider installing arch-audit to determine vulnerable packages" "arch-audit" "text:Install arch-audit"
tests_ports_packages:587: ReportSuggestion "${TEST_NO}" "Check output of: dnf repoquery --duplicated"
tests_ports_packages:592: ReportSuggestion "${TEST_NO}" "Check output of: dnf repoquery --unsatisfied"
tests_ports_packages:653: ReportSuggestion "${TEST_NO}" "Check debsums configuration and enable checking regurlarly via a cron job."
tests_ports_packages:716: ReportSuggestion "${TEST_NO}" "Fetch the package database with pkg_admin fetch-pkg-vulnerabilities"
tests_ports_packages:1258: ReportSuggestion "${TEST_NO}" "Remove any unneeded kernel packages with package-cleanup utility (--old-kernels)"
tests_ssh:266: ReportSuggestion ${TEST_NO} "Consider hardening SSH configuration" "${OPTIONNAME} (${FOUNDVALUE} --> ${EXPECTEDVALUE})" "-"
tests_ssh:272: ReportSuggestion ${TEST_NO} "Consider hardening SSH configuration" "${OPTIONNAME} (${FOUNDVALUE} --> ${EXPECTEDVALUE})" "-"
tests_time:229: ReportSuggestion "${TEST_NO}" "Check timedatectl output. Sychronization via NTP is enabled, but status reflects it is not synchronized"
tests_tooling:281: # ReportSuggestion "${TEST_NO}" "Some Fail2ban jails are configured with non-notified actions. Consider changing these to emailed alerts."
tests_tooling:288: # ReportSuggestion "${TEST_NO}" "None of the Fail2ban jails are configured to send email notifications. Consider changing these to emailed alerts."
tests_tooling:310: # ReportSuggestion "${TEST_NO}" "Check config to see why iptables does not have a fail2ban chain" "${FAIL2BAN_CONFIG}"
tests_tooling:314: # ReportSuggestion "${TEST_NO}" "iptables doesn't seem to be installed; Fail2ban will not work. Remove Fail2ban or install iptables" "${FAIL2BAN_CONFIG}"
tests_usb:160: # ReportSuggestion ${TEST_NO} "Consider hardening USBGuard configuration" "RestoreControllerDeviceState (${USBGUARD_RESTORE_POLICY} --> false)"
tests_usb:171: # ReportSuggestion ${TEST_NO} "Fix USBGuard configuration" "RestoreControllerDeviceState invalid \"${USBGUARD_RESTORE_POLICY}\""
tests_usb:191: # ReportSuggestion ${TEST_NO} "Consider hardening USBGuard configuration" "PresentControllerPolicy (${USBGUARD_CONTROLLER_POLICY} --> (apply-policy|block|reject)"
tests_usb:202: # ReportSuggestion ${TEST_NO} "Fix USBGuard configuration" "PresentControllerPolicy invalid \"${USBGUARD_CONTROLLER_POLICY}\""
tests_usb:221: # ReportSuggestion ${TEST_NO} "Consider hardening USBGuard configuration" "PresentDevicePolicy (${USBGUARD_DEVICE_POLICY} --> (apply-policy|block|reject)"
tests_usb:232: # ReportSuggestion ${TEST_NO} "Fix USBGuard configuration" "PresentDevicePolicy invalid \"${USBGUARD_DEVICE_POLICY}\""
tests_usb:251: # ReportSuggestion ${TEST_NO} "Consider hardening USBGuard configuration" "InsertedDevicePolicy (${USBGUARD_INSERTED_POLICY} --> (apply-policy|block|reject)"
tests_usb:262: # ReportSuggestion ${TEST_NO} "Fix USBGuard configuration" "InsertedDevicePolicy invalid \"${USBGUARD_INSERTED_POLICY}\""
tests_usb:281: # ReportSuggestion ${TEST_NO} "Consider hardening USBGuard configuration" "ImplicitPolicyTarget (${USBGUARD_DEFAULT_POLICY} --> (block|reject)"
tests_usb:292: # ReportSuggestion ${TEST_NO} "Fix USBGuard configuration" "ImplicitPolicyTarget invalid \"${USBGUARD_DEFAULT_POLICY}\""
tests_usb:319: #ReportSuggestion ${TEST_NO} "Install USBGuard RuleFile" "\"man usbguard\" for instructions to install initial policies"
tests_webservers:477: ReportSuggestion "${TEST_NO}" "Disable weak protocol in nginx configuration"
tests_webservers:491: ReportSuggestion "${TEST_NO}" "Change the HTTPS and SSL settings for enhanced protection of sensitive data and privacy"

**Comment by d4t4king** [comment]
That seems like a lot.  lol

**Comment by mboelen** [comment]
Going to close this issue. As shared, there is an old and new format (with an actual suggestion/solution text). In time they will be all migrated. We are adding all controls to the website, including those tests that don't trigger a warning/suggestion. Also, with some upcoming code revisions, we will come across these items.

As usual, feel free to send in a pull request if you come across one or more before we got to change them.
