### ISSUE TITLE
[DBS] Check PostgreSQL config file

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#624]
**Is your feature request related to a problem? Please describe.**
It should be nice if lynis could check the postgresql config file for hardening options.

**Describe the solution you'd like**
Check the postgresql config file /var/lib/pgsql/data/postgresql.conf for : 
- Listening addresses (postgresql should not listen on all addresses '*')
`# grep ^listen_addesses /var/lib/pgsql/data/postgresql.conf`
`listen_addresses = '*'          # what IP address(es) to listen on;`

- And ssl (should be on)
`# grep '^ssl = on' /var/lib/pgsql/data/postgresql.conf`

**Required changes**
Add a new test DBS-XXXX to tests_databases

**Comment by mboelen** [comment]
Hi @Capashenn - I agree that it could be a nice option to test more details regarding PostgreSQL and its configuration file. However, the config file can be at several locations. Ubuntu has a different location and so will others like the BSDs. Maybe we can add a check first to discover where the configuration file is?

Do you want to create a pull request with an initial test?

**Comment by mboelen** [comment]
As part of a cleanup, I'm closing old issues including this one. Please create a pull request if you like to have initial support for this.
