### ISSUE TITLE
fs.suid_dumpable impossible to get right

### ISSUE THREAD

**Issue by TheFlipside** [CISOfy/lynis#625]
**Describe the bug**
_include/tests_kernel_ checks **fs.suid_dumpable** and gets only green when it is set to 2
but _include/tests_kernel_hardening_ checks **fs.suid_dumpable** as well and expects it to be 0 and will result red if it is something else

**System**
Debian 9.6
 Lynis 2.7.1

**Expected behavior**
a possibility for a green result in both tests

**Comment by mboelen** [comment]
The related test in tests_kernel was changed and no longer shows yellow color.

Related: https://github.com/CISOfy/lynis/issues/655
