### ISSUE TITLE
php 7.2 on ubuntu 18.04 only finding cli ini file.

### ISSUE THREAD

**Issue by kiwichrish** [CISOfy/lynis#628]
**Describe the bug**
Trying out Lynis against Ubuntu 18.04 server and found that it finds the cli php .ini but not the apache2 one in /etc/php/7.2/apache2/php.ini

**Version**
 - Distribution Ubuntu 18.04
 - Lynis version 2.7.0

**Expected behavior**
Would expect /etc/php/7.2/apache2/php.ini to be included as it arguably more important than the CLI one.

**Additional context**
New to this tool / project.  I added the file to my local test_php, should I just do a pull request for the change to test_php.  :-)

**Comment by mboelen** [comment]
Hi @kiwichrish - Thanks for reporting.

Yes, a pull request with the change would be great. Then we merge it and can properly attribute the change to you :)

**Comment by NicolasCARPi** [comment]
> Yes, a pull request with the change would be great.

Done! :)

**Comment by kiwichrish** [comment]
:-)  I got completely sidetracked onto another project, thanks for updating it.
