### ISSUE TITLE
Exit code should be non-zero when problems are found

### ISSUE THREAD

**Issue by thedrow** [CISOfy/lynis#63]
That way I'll be able to use lynis in CI while building docker containers or full blown images.
I plan to add lynis as one of my serverspec tests and for that it is required that lynis will exit with the correct status code.

**Comment by mboelen** [comment]
When fatal errors are found, it exits with exit code 1. When you say "problems", do you include the discovery of warnings/suggestions?

**Comment by thedrow** [comment]
At the very least, warnings.
You could introduce a --strict mode that treats warnings as errors.

**Comment by mboelen** [comment]
Initial set of exit codes have been implemented. Updated man page with the details (exit codes). It will trigger on warnings, configuration issues, parameter issues. No additional strict mode has been added, to prevent the list of options becoming too long.

Can you test if this is in line for your automation? Would love to see your build process script, as this might be a great addition to the documentation for others.

**Comment by mboelen** [comment]
Closing issue, as this is considered to be finished work. If not, let me know by reopening.
Thanks for reporting the improvement.
