### ISSUE TITLE
Allow automatically detecting if the audit didn't pass

### ISSUE THREAD

**Issue by maurofaccenda** [CISOfy/lynis#630]
As a user want to automatically run Lynis on my VM image creation pipeline to detect compliance violations in a reliable way.

For now, Lynis exit codes are only for failure on the application execution.

For now, I can search for `[ WARNING ]` and if found, decide that the audit failed, however there are some other results that could mean the audit failed, such as `[ NOT FOUND ]` (not having a malware installed) or `[ DIFFERENT ]` (routing being enabled on a server)

I could try searching for all of them, but sometimes `[ NOT FOUND ]` isn't a problem (when trying to audit a service that is not installed), so I don't think doing this is really reliable.

Suggestion  1:

Would be good to have 2 extra exit codes:

1. for audit errors (something is surelly wrong and some action needs to be taken).
1. for audit warnings (something that  is possibly wrong or is only suggested, not necessarily an error)

Suggestion 2:

Another option is to have one extra exit code (let's call it `AUDIT_FAIL`) which the tool would exit with in same circunstances described in case number 1 (from Suggestion 1).
And one new parameter (`--strict-audit`) that would make the tool exit with `AUDIT_FAIL` if an error or warning occour (any of the 2 cases from Suggestion 1 happen).

**Comment by maurofaccenda** [comment]
It seems it should exit with code 78, however, it is not happening. Maybe it is related to: #632

**Comment by mboelen** [comment]
Did you configure `error-on-warnings=yes` in your custom profile?

**Comment by maurofaccenda** [comment]
@mboelen I'll give it a try.

**Comment by maurofaccenda** [comment]
that seems to do the job. closing the issue.
