### ISSUE TITLE
--warnings-only don't print context information

### ISSUE THREAD

**Issue by maurofaccenda** [CISOfy/lynis#631]
When running lynis with `--warnings-only` it prints only the line with the warning, so the context is missing.

Example:
```
# lynis audit system --warnings-only
    - Checking for password protection                        [ WARNING ]

  [TIP]: Enhance Lynis audits by adding your settings to custom.prf (see /etc/lynis/default.prf for all settings)

```
There is no way to know what password it is talking about.

On an execution without the parameter it is shown, that it is the GRUB password. I'd expect the output would be something like:

```
[+] Boot and services
------------------------------------
  - Checking presence GRUB2                                   [ FOUND ]
    - Checking for password protection                        [ WARNING ]

  Suggestions (1):
  ----------------------------
  * Set a password on GRUB bootloader to prevent altering boot configuration (e.g. boot in single user mode without password) [BOOT-5122] 
      https://cisofy.com/lynis/controls/BOOT-5122/
```

Also without the TIP in the botton.

**Comment by mboelen** [comment]
The flag is typically used to do a quick scan to find issues (e.g. via cron or in build pipeline). Sometimes these items are part of multiple lines. At this moment we can't change this behavior, as the project goal is to keep output (e.g. line length) as small as possible).

My suggestion is to follow up in the lynis.log when a warning is displayed, or run the tool once more with full output.

**Comment by maurofaccenda** [comment]
Unfortunatelly that would make it really hard to report the appropriate error on automated triggered scans.

**Comment by mboelen** [comment]
@maurofaccenda you could use the return code as a trigger to retrieve the warnings from the lynis-report.dat?

**Comment by maurofaccenda** [comment]
@mboelen I could give it a try and report back here
