### ISSUE TITLE
Add Dropbear SSH server checks

### ISSUE THREAD

**Issue by kisst** [CISOfy/lynis#635]
**Is your feature request related to a problem? Please describe.**
Lynis provide a false negative result as it does not detect SSH server.
```
[+] SSH Support
------------------------------------
  - Checking running SSH daemon                               [ NOT FOUND ] 
```
*Dropbear* is a lightweight alternative SSH server https://matt.ucc.asn.au/dropbear/dropbear.html which is often used SBC's and other small systems.
There should be a check for it, and maybe for other alternatives as well like *tinysshd* or *lsh-server* ( at least the ones which are available from the default repos )  

**Describe the solution you'd like**
Extend the include/tests_ssh to check and parse `/etc/init.d/dropbear` which is the default location for dropbear ssh server.

**Required changes**
Only `include/tests_ssh`

**Additional context**
I discovered this with the context of DietPi which use by default dropbear, with root allowed by default, with default port, and with password auth ...all you don't want on a secure setup, but this is not marked by lynis.

**Comment by mboelen** [comment]
Hi @kisst - Thanks for reporting. Instead of checking for startup scripts, it would be better to look for a running process.

**Comment by mboelen** [comment]
Made the first set of changes to detect at least that SSH is running. See commit https://github.com/CISOfy/lynis/commit/ae474c72c6566f86d738897cfdd78c979377eb14

If you like a deeper set of checks against the dropbear configuration, please send in a pull request or reach out. As part of work on the new major 3.x release, will close this issue.
