### ISSUE TITLE
missing files and permission issue on git pull

### ISSUE THREAD

**Issue by imthenachoman** [CISOfy/lynis#639]
**Describe the bug**
On a fresh install of Debian 9, after I run `git clone https://github.com/CISOfy/lynis`, when I run ` /usr/local/lynis/lynis update info` I get a lot of errors for missing files/folders.

The output errors are below. The issue is that it's looking for `/usr/local/include/consts` and `/usr/local/include/functions`. I assume it **should** be looking for them in the Lynis install directory?

**Version**
 - Debian 9
 - Lynis 2.7.1

**Expected behavior**
Lynis to update

**Output**

    # /usr/local/lynis/lynis update info
    ls: cannot access '/usr/local/include/consts': No such file or directory
    ls: cannot access '/usr/local/include/consts': No such file or directory
    ls: cannot access '/usr/local/include/consts': No such file or directory
    ls: cannot access '/usr/local/include/consts': No such file or directory
    ls: cannot access '/usr/local/include/consts': No such file or directory
    ls: cannot access '/usr/local/include/functions': No such file or directory
    ls: cannot access '/usr/local/include/functions': No such file or directory
    ls: cannot access '/usr/local/include/functions': No such file or directory
    ls: cannot access '/usr/local/include/functions': No such file or directory
    ls: cannot access '/usr/local/include/functions': No such file or directory

    [!] Change ownership of /usr/local/include/functions to 'root' or similar (found:  with UID ).

        Command:
          # chown 0:0 /usr/local/include/functions

    [X] Security check failed

        Why do I see this error?
        -------------------------------
        This is a protection mechanism to prevent the root user from executing user created files. The files may be altered, or including malicious pieces of script.

        What can I do?
        ---------------------
        Option 1) Check if a trusted user created the files (e.g. due to using Git, Homebrew or similar).
                  If you trust these files, you can decide to continue this run by pressing ENTER.

        Option 2) Change ownership of the related files (or full directory).

           Commands (full directory):
             # cd ..
             # chown -R 0:0 lynis
             # cd lynis
             # ./lynis audit system

    [ Press ENTER to continue, or CTRL+C to cancel ]q^C
    - 

**Additional context**
n/a

**Comment by mboelen** [comment]
Do you have by any chance both a package installed and the Git version cloned?

**Comment by imthenachoman** [comment]
Nope. This is a fresh install with nothing else done to it. I just tested again in a new VM. 

    $ sudo -s
    # cd /usr/local
    # git clone https://github.com/CISOfy/lynis
    # # /usr/local/lynis/lynis update info
    ls: cannot access '/usr/local/include/consts': No such file or directory
    ls: cannot access '/usr/local/include/consts': No such file or directory
    ls: cannot access '/usr/local/include/consts': No such file or directory
    ls: cannot access '/usr/local/include/consts': No such file or directory
    ls: cannot access '/usr/local/include/consts': No such file or directory
    ls: cannot access '/usr/local/include/functions': No such file or directory
    ls: cannot access '/usr/local/include/functions': No such file or directory
    ls: cannot access '/usr/local/include/functions': No such file or directory
    ls: cannot access '/usr/local/include/functions': No such file or directory
    ls: cannot access '/usr/local/include/functions': No such file or directory


    [!] Change ownership of /usr/local/include/functions to 'root' or similar (found:  with UID ).

        Command:
          # chown 0:0 /usr/local/include/functions

    [X] Security check failed

        Why do I see this error?
        -------------------------------
        This is a protection mechanism to prevent the root user from executing user created files. The files may be altered, or including malicious pieces of script.

        What can I do?
        ---------------------
        Option 1) Check if a trusted user created the files (e.g. due to using Git, Homebrew or similar).
                  If you trust these files, you can decide to continue this run by pressing ENTER.

        Option 2) Change ownership of the related files (or full directory).

           Commands (full directory):
             # cd ..
             # chown -R 0:0 lynis
             # cd lynis
             # ./lynis audit system

    [ Press ENTER to continue, or CTRL+C to cancel ]

**Comment by imthenachoman** [comment]
I think I figured it out. I had to chmod +x the executable and set root:root ownership for the folder.

**Comment by mboelen** [comment]
Thanks for reporting and good that you resolved it.

Background information: Lynis checks for the permissions, to prevent a normal user pulling in the scripts and then later execute them with root privileges. Normally if you are both controlling the non-privileged user and the root user, then the risk is low. Yet for other systems where you have no root access, this might be used in privilege escalation attacks, etc.
