### ISSUE TITLE
Provide debian packages in a PPA

### ISSUE THREAD

**Issue by thedrow** [CISOfy/lynis#64]
The project has a PPA but it does not provide any packages.
It could be nice to be able to install this through apt-get.

See PPA here: https://launchpad.net/~cisofy/+archive/ubuntu/lynis

**Comment by mboelen** [comment]
We tried building them, but the process failed. If someone from the community likes to step in to get this working, we will reconsider building the PPA and maintaining it.

**Comment by thedrow** [comment]
You could as an alternative provide Debian and RPM packages on bintray which is free for open source projects.
Packaging can be done with FPM.

**Comment by mboelen** [comment]
Marking this item as a wontfix for now. Instead it will moved to our roadmap, as we want to cover all package types, including building several types of the same package. We will determine if bintray is a good alternative for this. Thanks for the suggestion!

**Comment by socrat3000** [comment]
You can use this repository: https://packages.cisofy.com/#debian-ubuntu instead.

**Comment by adrian-vg** [comment]
Has there been any progress on this repo recently?

Getting this:
W: The repository 'http://ppa.launchpad.net/cisofy/lynis/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/cisofy/lynis/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by mboelen** [comment]
@adrian-vg - Please see the note from @ahmadsocrat pointing to the actual repository.

**Comment by adrian-vg** [comment]
Will give it a try. Thank you.
