### ISSUE TITLE
Unsupported FreeBSD installations are not reported

### ISSUE THREAD

**Issue by daniejstriata** [CISOfy/lynis#644]
Noticed that on a FreeBSD 9.3 server Lynis does not report that the OS is no longer supported.

```
# Lynis Report
report_version_major=1
report_version_minor=0
report_datetime_start=2019-02-13 12:06:44
auditor=
lynis_version=2.7.1
os=FreeBSD
os_name=FreeBSD
os_fullname=FreeBSD 9.3-RELEASE-p49
os_version=9.3-RELEASE-p49
os_kernel_version=GENERIC
```
Only warnings I got:

```
warning[] | AUTH-9204 | Multiple users with UID 0 found in passwd file
-- | -- | --
warning[] | AUTH-9208 | Multiple accounts found with same UID
warning[] | AUTH-9218 | Possible harmful shell found (for passwordless account!)
warning[] | SHLL-6202 | Found unprotected console in /etc/ttys
warning[] | PKGS-7381 | Found vulnerable packages
```
Here is the list of supported or end-of-life versions:
https://www.freebsd.org/releases/

**Comment by mboelen** [comment]
Hi @daniejstriata - You are correct. Lynis does not check for EOL configurations.

A first change (https://github.com/CISOfy/lynis/commit/34a2742cdb14c11f965498621d36df78cdbc3303) has been made to introduce this functionality.

Can you `git clone` to your system and see if it is picked up? You should see it in the OS overview near the top and as a warning in the report at bottom of screen.

**Comment by daniejstriata** [comment]
Thanks. I run 2.7.2 on FreeBSD 9.3-RELEASE-p10 and could see "EOL check: 255" checked but looking at the warnings I did not see any mention of the OS being EOL.
[test.zip](https://github.com/CISOfy/lynis/files/2924485/test.zip)

**Comment by mboelen** [comment]
Thanks for sharing. Another set of changes has been made. Can you test again? Also, try 'lynis show eol' :)

**Comment by daniejstriata** [comment]
Thanks. I see this now but not sure about the date. I have the EOL for 9.3 as December 31, 2016:

```
This version 9.3-RELEASE-p49 is marked end-of-life as of 1404165600 [GEN-0010] 
      https://cisofy.com/lynis/controls/GEN-0010/
```
https://endoflife.software/operating-systems/unix-like-bsd/freebsd

**Comment by mboelen** [comment]
Thanks, a new commit has been made. I changed FreeBSD items and added CentOS and OpenBSD as well.

Closing this issue. Thanks for bringing up this idea :+1:

**Comment by daniejstriata** [comment]
Can you calculate the hardening points based on this? Say deduct 25 points for every year the OS is EOL?
