### ISSUE TITLE
[FILE-6332] blkid binary not found

### ISSUE THREAD

**Issue by schlumpfuk** [CISOfy/lynis#645]
**Describe the bug**
Performing file system tests (specifically FILE-6332 -Checking swap partitions) results in "blkid binary not found". However binary exists (installed) on systems.

**Version**
 - Distribution Ubuntu 18.04
 - Lynis version 2.7.1

**Expected behavior**
Since the `blkid` binary exists, the filesystems test should report correctly.

**Output**
From lynis.log we see:
```
Directory /sbin exists. Starting directory scanning...
 Found known binary: blkid (information about block devices) - /sbin/blkid
```
and further in the same lynis.log, we see:
```
 Result: blkid binary not found, trying by checking device listing
```

**Additional context**
In the `<installdir>/include/binaries` line 100, we have the following in the case statement::
```
blkid)                  BLKDBINARY="${BINARY}";
```

However, in `<installdir>/include/test_fielsystems` lines 255-262, suggests:
```
if [ ! -z "${BLKIDBINARY}" ]; then
    FIND2=$(${BLKIDBINARY} | ${AWKBINARY} '{ if ($2=="UUID=\"${UUID}\"") print $1 }' | ${SEDBINARY} 's/:$//')
    if [ ! -z "${FIND2}" ]; then
        REAL="${FIND2}"
    fi  
else
    LogText "Result: blkid binary not found, trying by checking device listing"
```

The mismatch seems to be a simple syntax error between the variable names _BLKDBINARY_ and _BLKIDBINARY_.

Simply changing _BLKDBINARY_ to _BLKIDBINARY_ in the `include/binaries` file resolves the issue.

**Comment by mboelen** [comment]
Thanks for reporting. Good find!

Do you have the chance to create a pull request? Then we can merge your finding and give you the right attribution as well :)

**Comment by mboelen** [comment]
Hi @schlumpfuk - Do you have the time for a pull request?

**Comment by mboelen** [comment]
Fixed with https://github.com/CISOfy/lynis/commit/703a856e82ed0678d33ca089cc1566dd6979b127
