### ISSUE TITLE
incorrect grep command in testlogging::LOGG-2154

### ISSUE THREAD

**Issue by ioxxoi** [CISOfy/lynis#646]
**Describe the bug**
they are a error in the grep expression in lynis 2.7.1 at testlogging::LOGG-2154
the grep  expression:
FIND2=$(${GREPBINARY} "log"  | ${GREPBINARY} "source" | ${EGREPBINARY} "destination\(${DESTINATION}\)")
never terminates because the target file is bnot included in the first grep, the correct expresion is:
FIND2=$(${GREPBINARY} "log" ${SYSLOGD_CONF} | ${GREPBINARY} "source" | ${EGREPBINARY} "destination\(${DESTINATION}\)")

**Version**
 - Distribution test in SLES 9 but is affected all systems with syslog-ng an remote logging configured.
 - Lynis version 2.7.1 and previous 

**Expected behavior**
this command return a list of all syslog-ng destination included in the syslog-.ng config file, wirthout the config file target the command never ends 

**Output**
null, script never ends 

**Additional context**
this is the patch file with the changes:

[patch_lynis_LOGG-2154_2019-02-25.zip](https://github.com/CISOfy/lynis/files/2900090/patch_lynis_LOGG-2154_2019-02-25.zip)
cat patch_lynis_LOGG-2154_2019-02-25.patch 
diff -Naur lynis.orig/include/tests_logging lynis/include/tests_logging
--- lynis.orig/include/tests_logging    2019-01-31 01:00:00.000000000 +0100
+++ lynis/include/tests_logging 2019-02-25 11:17:50.579495928 +0100
@@ -363,7 +363,7 @@
                 # Search for configured destinations with an IP address or hostname, then determine which ones are used as a log destination
                 DESTINATIONS=$(${GREPBINARY} "^destination" ${SYSLOGD_CONF} | ${EGREPBINARY} "(udp|tcp)" | ${GREPBINARY} "port" | ${AWKBINARY} '{print $2}')
                 for DESTINATION in ${DESTINATIONS}; do
\-                    FIND2=$(${GREPBINARY} "log" | ${GREPBINARY} "source" | ${EGREPBINARY} "destination\(${DESTINATION}\)")
\+                    FIND2=$(${GREPBINARY} "log" ${SYSLOGD_CONF} | ${GREPBINARY} "source" | ${EGREPBINARY} "destination\(${DESTINATION}\)")
                     if [ ! -z "${FIND2}" = "" ]; then
                         LogText "Result: found destination ${DESTINATION} configured for remote logging"
                         REMOTE_LOGGING_ENABLED=1

**Comment by mboelen** [comment]
Thanks for reporting. Do you have the chance to create a pull request? Then we can easily merge it and gives you the right attribution at the same time :)

**Comment by mboelen** [comment]
Fixed with https://github.com/CISOfy/lynis/commit/303050dda3ffa97c0139db07dfa41f94f2f217f8
