### ISSUE TITLE
File permissions + ownership

### ISSUE THREAD

**Issue by perfecto25** [CISOfy/lynis#647]
**Is your feature request related to a problem? Please describe.**
Currently no way to check for file permission and ownership of core OS files, and home directory files

Lynis File permission check seems to check only /root dir

```

[+] File Permissions
------------------------------------
  - Starting file permissions check
    /root/.ssh                                                [ OK ]

```

**Describe the solution you'd like**
lynis should scan for proper permissions, ie

/home/<user> = 700  user:user
/home/<user>/.ssh/id_rsa  = 600 user:user
/etc/passwd = 644 root:root
etc

**Required changes**
adding file ownership + permission check

**Additional context**

**Comment by mboelen** [comment]
There is definitely a way to check both files and directories. It is done using the permfile and permdir settings and with a few defined in default.prf (as example).

https://github.com/CISOfy/lynis/blob/master/default.prf#L322

If you are up for it, add the entries you want to check to your custom.prf file and test if it works. Then if you are happy with it, feel free to contribute your changes (in that case to default.prf, so we can include it as default).
