### ISSUE TITLE
[PKGS-7388] False positive warning on missing security archive

### ISSUE THREAD

**Issue by silentcreek** [CISOfy/lynis#648]
Currently the check for the security archive in Debian/Ubuntu fails, if the archive is not hosted on security.{debian,ubuntu}.org and the URL does have trailing slash, such as this:
`deb http://deb.debian.org/debian-security/ stretch/updates main`

I'm attaching a patch that fixes this by allowing a trailing slash in the regular expression when filtering the sources files.
[PKGS-7388-Fix-false-positive-warning-on-missing-security-archive.txt](https://github.com/CISOfy/lynis/files/2922145/PKGS-7388-Fix-false-positive-warning-on-missing-security-archive.txt)

**Comment by mboelen** [comment]
Thanks @silentcreek - the patch looks good. Can you turn it into a pull request? Then we can merge it and give right attribution.

**Comment by silentcreek** [comment]
Hi Michael, I already referenced the pull request above, but here you go:
https://github.com/CISOfy/lynis/pull/651
