### ISSUE TITLE
[KRNL-5788] False positive warning on missing /vmlinuz

### ISSUE THREAD

**Issue by silentcreek** [CISOfy/lynis#649]
The current code in test KRNL-5788 assumes all Debian systems have a symlink /vmlinuz. This assumption is wrong, however, expecially for architectures that use different bootloaders such as armhf and U-Boot. Such systems (set up with the official Debian installer) may not have /vmlinuz but only /boot/vmlinuz.

I'm attaching a patch that fixes this by falling back to checking /boot/vmlinuz if /vmlinuz is not found.
[KRNL-5788-Fix-false-positive-warning-on-missing-vmlinuz.txt](https://github.com/CISOfy/lynis/files/2922156/KRNL-5788-Fix-false-positive-warning-on-missing-vmlinuz.txt)

**Comment by mboelen** [comment]
Hi Timo, thanks for reporting this and the patch. It looks good to me. Can you turn your patch into a pull request? Then we can merge it with proper attribution.

**Comment by silentcreek** [comment]
Hi Michael, in case you didn't get a notification about my pull request, here it is:
https://github.com/CISOfy/lynis/pull/650
