### ISSUE TITLE
[SSH-7408] SSH option: MaxAuthTries 

### ISSUE THREAD

**Issue by iohenkies** [CISOfy/lynis#654]
Hi,

Not a bug and not a feature request I think, more a question and with low priority.

Although we agree that the default MaxAuthTries of 10 is too much, the suggested MaxAuthTries of 2 is too low for us (because we're working with multiple SSH keys). Is it possible to alter the default threshold?

If not we will disable the check.

**Comment by mboelen** [comment]
That is not possible. So you could disable the check, but only for that key: `skip-test=SSH-7408:maxauthtries` (add to custom.prf)

**Comment by d4t4king** [comment]
> That is not possible. So you could disable the check, but only for that key: `skip-test=SSH-7408:maxauthtries` (add to custom.prf)

It should be possible (philosophically) to add a line in custom.prf that will allow desired configuration modifications such as this.  This works for some (if not all) sysctl options.  It should scale to other configuration items as well.  

I, too, have seen issues with this setting at 2 when authenticating with SSH keys.  Bumping it to just 3 works for me.  YMMV.

**Comment by mboelen** [comment]
Based on the feedback of @d4t4king - The values have been increased to 3 (or less) as good value.
