### ISSUE TITLE
[KRNL-6000] Conflicting tests?

### ISSUE THREAD

**Issue by iohenkies** [CISOfy/lynis#655]
**Describe the bug**
When setting fs.suid_dumpable=0 the [KRNL-6000] test gives an OK but at the kernel section we get a yellow warning 'Checking setuid core dumps configuration [ DEFAULT ]'

When setting fs.suid_dumpable=2 the [KRNL-6000] test gives a red DIFFERENT and at the kernel section we get a green 'Checking setuid core dumps configuration [ PROTECTED ]'

**Version**
Distribution Debian 9.
Lynis version 2.7.2

**Expected behavior**
These two seem conflicting, they can't be green and OK at the same time.

**Output**
Output is:
    - Checking setuid core dumps configuration                [ PROTECTED ]
    - fs.suid_dumpable (exp: 0)                               [ DIFFERENT ]

Or:
    - Checking setuid core dumps configuration                [ DEFAULT ]
    - fs.suid_dumpable (exp: 0)                               [ OK ]

**Additional context**
None.

**Comment by mboelen** [comment]
Thanks for reporting. I can imagine the confusion, therefore changed color to white instead of yellow.
