### ISSUE TITLE
[STRG] Add samba checks

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#658]
**Is your feature request related to a problem? Please describe.**
It should be nice if lynis could check for samba server and shares like NFS

**Describe the solution you'd like**
Check if samba server is active
Check if there are samba shares on the machine (smbclient -L localhost -N)
Check if anyone is connected to samba shares (smbstatus)

**Required changes**
Add some STRG-XXXX tests

**Comment by mboelen** [comment]
Thanks for the suggestion. As it does not directly perform a security check, I will skip this one and close it as an issue due to work on the major 3.x release.

If you have time, feel free to submit a pull request with initial work on this.
