### ISSUE TITLE
FILE-6410:  /var/lib/locate/locatedb Should be valid (and isn't)

### ISSUE THREAD

**Issue by d4t4king** [CISOfy/lynis#66]
Checked locations:
`/var/lib/mlocate/mlocate.db
/var/lib/locatedb
/var/lib/slocate/slocate.db
/var/cache/locate/locatedb
/var/db/locate.database`

Linux From Scratch (LFS) and/or some derivations of LFS (smoothwall) store the DB for `updatedb` in the subject path.  It should be checked as a valid path for check FILE-6410

**Comment by mboelen** [comment]
Changed via pull request, thanks!
