### ISSUE TITLE
[PRNT] Check SAMBA Printers

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#660]
**Is your feature request related to a problem? Please describe.**
It would be nice if lynis could check for samba printers in addition to cups printers

**Describe the solution you'd like**
Check for samba printers in /etc/samba/smb.conf or with smbclient -L localhost -N 

**Required changes**
Add a new test in [PRNT]

**Comment by mboelen** [comment]
Sounds like a good idea. Can you create an initial test for this?

Will close this issue for now, as part of an ongoing clean up related to the upcoming 3.x release.
