### ISSUE TITLE
[INSE] Add support for xinetd

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#661]
**Is your feature request related to a problem? Please describe.**
Lynis should handle xinetd as well as inetd because it's the daemon used by RHEL like distributions 

**Required changes**
Add some tests for handling xinetd
- Check for enabled xinet daemon
- Check for xinetd configuration file
- Check for xinetd configuration file contents if xinetd is NOT active
- Check for telnet enabled via xinetd

**Comment by mboelen** [comment]
This was implemented with pull requests by @Capashenn so can be closed.
