### ISSUE TITLE
[INSE] Check for rsh enabled via inetd and xinetd

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#662]
**Is your feature request related to a problem? Please describe.**
Lynis should check for rsh enabled via inetd and xinetd as well as telnet

**Describe the solution you'd like**
Check if rsh is enabled via inetd and xinetd

**Required changes**
Add a new test in [INSE]

**Comment by mboelen** [comment]
Merged with pull request, closing issue
