### ISSUE TITLE
[INSE] Check for tftp enabled via inetd and xinetd

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#663]
Is your feature request related to a problem? Please describe.
Lynis should check for tftp enabled via inetd and xinetd as well as telnet

Describe the solution you'd like
Check if tftp is enabled via inetd and xinetd

Required changes
Add a new test in [INSE]

**Comment by mboelen** [comment]
Implemented with pull requests by @Capashenn so can be closed.
