### ISSUE TITLE
[SCHD-7702] Max points if crond is not running

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#664]
**Describe the bug**
Regarding multiples security sources (openscap, RHEL security guide, CIS etc.) : "**Due to its usage for maintenance and security-supporting tasks, enabling the cron daemon is essential.**"
So giving max points if cron is not running is not relevent.

**Version**
 - Distribution All
 - Lynis version 2.7.1

**Expected behavior**
If cron is not enabled, test SCHD-7702 should give no point.

**Output**
`Performing test ID SCHD-7702 (Check status of cron daemon)`
`Result: no cron daemon found`
`Hardening: assigned maximum number of hardening points for this item (3). Currently having 137 points (out of 175)`

**Comment by mboelen** [comment]
Agree. Adjusted with commit https://github.com/CISOfy/lynis/commit/dbc6f9bc4cff8ea958e7bad923533a7f6db5a3bc
