### ISSUE TITLE
[HOME] Ensure users' home directories permissions are 750 or more restrictive

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#666]
**Is your feature request related to a problem? Please describe.**
Group or world-writable user home directories may enable malicious users to steal or
modify other users' data or to gain another user's system privileges.

**Describe the solution you'd like**
Check users home directories permissions

**Required changes**
Add new test HOME-XXXX

**Comment by mboelen** [comment]
Closing with your pull request merged
