### ISSUE TITLE
Found promiscuous interface [NETW-3015] - But promiscuous mode is not enable.

### ISSUE THREAD

**Issue by arafatx** [CISOfy/lynis#668]
**Describe the bug**

Got a warning message like below about promiscuous interface when running the audit:

 ! Found promiscuous interface [NETW-3015]
    - Details  : eth0
    - Solution : Determine if this mode is required or whitelist interface in profile
      https://cisofy.com/lynis/controls/NETW-3015/

When check, with the command sudo ip link show eth0 found out that
 the current interface, the promiscuous is not enabled.

Output:
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000

**Version**
 - Distribution : Centos 7.6.1810
 - Lynis version: 2.7.3

**Expected behavior**
The message should not be shown if the promiscuous mode is not enabled.

**Output**
 Warnings (1):
  ----------------------------
  ! Found promiscuous interface [NETW-3015]
    - Details  : eth0
    - Solution : Determine if this mode is required or whitelist interface in profile
      https://cisofy.com/lynis/controls/NETW-3015/

**Additional context**
No

**Comment by arafatx** [comment]
How do I verify the promiscuous status is completely disabled in Centos 7 or is this bug in Lynis check ?

**Comment by Capashenn** [comment]
What's the result of `ip -o -d link show eth0` ?

**Comment by arafatx** [comment]
The result is:

     2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000\    link/ether f2:3c:91:05:6c:b1 brd ff:ff:ff:ff:ff:ff promiscuity 1 addrgenmode none numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535

**Comment by mboelen** [comment]
promiscuity is set to 1, so looks like something actually put it into promiscuous mode.

**Comment by Capashenn** [comment]
Look at this for more info : 
[https://kmroz.wordpress.com/2016/04/21/determine-interface-promiscuity/](https://kmroz.wordpress.com/2016/04/21/determine-interface-promiscuity/)

To disable promiscious mode with ip : `ip link set ethX promisc off`

Or if you want to happen on boot you can use `systemd` service `rc-local`.

**Comment by arafatx** [comment]
Ok I guess something is turning on the promiscious mode and I thought it was completely off before auditing with Lynis. I tried this command multiple times:

    ip link set eth0 promisc off 

and the promiscious mode 1 still not turning off. I also use both rc-local and systemd service to disable the mode on boot but it still showing the promiscious mode 1.

**Comment by arafatx** [comment]
Ok, I think the promiscuous mode is set by the linux kernel through dev_set_promiscuity() in my distribution . I have to figure out which kernel because there are dozens kernels that can be selected.

**Comment by mboelen** [comment]
If this is a test system, you can try to disable multicast as well.

ip link set DEVICE-NAME multicast off promisc off
