### ISSUE TITLE
Bootloader not detected for Gentoo VM

### ISSUE THREAD

**Issue by d4t4king** [CISOfy/lynis#7]
Grub is installed.

**Comment by d4t4king** [comment]
@mboelen I'm seeing a similar issue on a different Gentoo VM.  Similar build, just a (slightly) different package set.  

Test BOOT-5122 is skipped via /etc/lynis/custom.prf, but BOOT-5121 is not.  Do you want to reopen this issue or should I file a new one?

**Comment by mboelen** [comment]
A new one please. Thanks :)
