### ISSUE TITLE
[LOGG-2154] Add support for rsyslog

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#700]
**Is your feature request related to a problem? Please describe.**
While rsyslog is the new syslog daemon for many Linux distros, it's not handle by the test LOGG-2154 : Check to see if remote logging is enabled

**Describe the solution you'd like**
Look for remote logging in /etc/rsyslog.conf and /etc/rsyslog.d files

**Required changes**
Change test LOGG-2154 to handle rsyslog

**Comment by mboelen** [comment]
The requested feature has been implemented. If you have the chance, please test it on your systems as well.

Related commit: https://github.com/CISOfy/lynis/commit/429ad46649f181af32c3d5ead61f79f02a3ef144
