### ISSUE TITLE
Direct root Logins Not Allowed

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#701]
**Is your feature request related to a problem? Please describe.**
Disabling direct root logins ensures proper accountability and multifactor authentication to privileged accounts. Users will first login, then escalate to privileged (root) access via su / sudo. This is required for FISMA Low and FISMA Moderate systems.

**Describe the solution you'd like**
Check if /etc/securetty is empty

**Required changes**
Add a new test

**Comment by pyllyukko** [comment]
>  Check if /etc/securetty is empty

To make sure, it would be also required to check whether [pam_securetty](http://www.linux-pam.org/Linux-PAM-html/sag-pam_securetty.html) (which is in charge of enforcing `/etc/securetty`) is used by services utilizing PAM.
