### ISSUE TITLE
NETW Check for Uncommon Network Protocols

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#702]
**Is your feature request related to a problem? Please describe.**
Linux include support for several network protocols which are not commonly used. Although security vulnerabilities in kernel networking code are not frequently discovered, the consequences can be dramatic. Ensuring uncommon network protocols are disabled reduces the system's risk to attacks targeted at its implementation of those protocols.

**Describe the solution you'd like**
Check for 
```
install dccp /bin/true
install sctp /bin/true
install rds /bin/true
install tipc /bin/true
```
in /etc/modprobe.conf and /etc/modprobe.d/* files 

**Required changes**
Add a new test NETW-XXXX

**Comment by mboelen** [comment]
Thanks for the suggestion. Implemented NETW-3200 with commit https://github.com/CISOfy/lynis/commit/d2deb63ebb416b957ba973a014ea6588103f3cfc
