### ISSUE TITLE
Ensure prelink is disabled

### ISSUE THREAD

**Issue by Capashenn** [CISOfy/lynis#704]
**Is your feature request related to a problem? Please describe.**
The prelinking feature can interfere with the operation of AIDE, because it changes
binaries. Prelinking can also increase the vulnerability of the system if a malicious user is
able to compromise a common library such as libc

**Describe the solution you'd like**
Check if prelink is installed
`PackageIsInstalled prelink`

**Required changes**
Add a new test

**Comment by mboelen** [comment]
Implemented using commit https://github.com/CISOfy/lynis/commit/afba58e7433140e76736bc9dc539e8b7cb7e6756
