### ISSUE TITLE
No docs for PKGS-7420

### ISSUE THREAD

**Issue by d4t4king** [CISOfy/lynis#706]
**Describe the bug**
_There is no online documentation for check PKGS-7420.  A link exists, but no correlating guidance._

**Version**
 - Distribution [e.g. Ubuntu 18.04]
_CentOS Linux release 7.6.1810 (Core)_
 - Lynis version [e.g. 2.7.0]
_2.7.4_

**Expected behavior**
_If online documentation is referred to by the tool, the documentation should exist, even if only in bare bones_

**Comment by mboelen** [comment]
Version 2.7.4. is a development version. With new tests being added to the development version, the documentation might be a little bit behind. Basic text for this control has been added in the meantime.
