### ISSUE TITLE
Conflicting Warnings/Suggestions

### ISSUE THREAD

**Issue by d4t4king** [CISOfy/lynis#707]
**Describe the bug**
_Lynis suggests running an arp monitoring software [SUGGESTION].  Doing so puts the active network interface in promiscuous mode.   Lynis then warns that a network interface is in promiscuous mode._

**Version**
 - Distribution [e.g. Ubuntu 18.04] _Probably any_
 - Lynis version [e.g. 2.7.0] _2.7.4_

**Expected behavior**
_Lynis should know if an arp monitor is running (NETW-3032), and if it is (running), suppress or downgrade the interface promiscuity warning._

**Comment by mboelen** [comment]
Some of the items might conflict, which is actually fine. As system owner you have to make an informed decision about what security measures are needed for your environment and which ones are not needed. Most systems will not need ARP monitoring software, as typically one system within the network to do the monitoring is enough. I suggest disabling one of the tests in the profile (skip-test=ABCD-1234).
