### ISSUE TITLE
More User Friendly Report

### ISSUE THREAD

**Issue by zero77** [CISOfy/lynis#708]
lynis shows lots of useful info but, it can some times be a bit hard to analyze when the reports big and there's lots of info their.

Perhaps, having an option to create an html report with hyperlinks and cullers as well as minimizing or expanding sections, this may make it easier to analyze.
Thanks

**Comment by mboelen** [comment]
Thanks for your suggestion.

Lynis is a command line (CLI) tool and therefore sends it output primarily to the screen and log/report file.

At this moment there is no action planned to create an HTML report, as the tool output already contains hyperlinks to the website, where additional information can be found. Another reason is to reduce the complexity of the code and the goal to keep Lynis as fast as possible.

**Comment by d4t4king** [comment]
>>> Shameless Plug <<<

My lynis-report-converter does exactly this.  It converts the default lynis report into more human-friendly formats, including HTML, PDF, Excel, JSON, and XML.

https://github.com/d4t4king/lynis-report-converter
