### ISSUE TITLE
False positive since test INSE-8300 as been added

### ISSUE THREAD

**Issue by jodumont** [CISOfy/lynis#709]
**Describe the bug**

False positive since test INSE-8300 as been added

**Version**

 - Debian 9.8
 - Lynis version 2.7.4

**Expected behavior**

**Output**

  * Remove rsh client when it is not in use or replace with the more secure SSH package [INSE-8300]
      https://cisofy.com/lynis/controls/INSE-8300/

**Additional context**

No rsh or xinetd on my machine

![image](https://user-images.githubusercontent.com/5204724/55718180-6e145380-59fb-11e9-8f35-f59f515333b9.png)
![image](https://user-images.githubusercontent.com/5204724/55718248-97cd7a80-59fb-11e9-917e-67cda4d618a3.png)

**Comment by mboelen** [comment]
Thanks for reporting. Several improvements have been made to reduce the chance on a false positive.

Related commit: https://github.com/CISOfy/lynis/commit/fd8b1e790d3eb7e3d98b89fc66edd392862f8430
