### ISSUE TITLE
NETW-3015|Found promiscuous interface

### ISSUE THREAD

**Issue by aram535** [CISOfy/lynis#710]
**Describe the bug**
App is reporting that the interface is in promiscuous mode, when it's only allowed to be in promiscuous mode, not actually on.

**Version**
 - CentOS 7
 - Lynis 2.7.4

**Expected behavior**
Checking should be at via 'netstat' or 'ss'

**Output**
```
# cat /var/log/lynis-report.dat | grep warning | sed -e 's/warning\[\]=//g'
NETW-3015|Found promiscuous interface|eno167|text:Determine if this mode is required or whitelist interface in profile|

# netstat -i | grep eno167
eno167      1500 390596597      0      0 0      333593474      0      0      0 BRU

# ip -o -d link show eno167  
2: eno167: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000\    link/ether 00:xx:xx:89:4c:ca brd ff:ff:ff:ff:ff:ff promiscuity 1 numtxqueues 4 numrxqueues 4 gso_max_size 65536 gso_max_segs 65535 
```

**Additional context**
AFAIK "the BRU" from netstat is showing the active profiles applied.   Where the ip output list is showing all capable option for that interface.
To show the difference: 
```
# ip link set eno167 promisc on    
# netstat -i | grep eno167
eno167      1500 390603302      0      0 0      333598622      0      0      0 BPRU
# ip -o -d link show eno167 
2: eno167: <BROADCAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000\    link/ether 00:xx:xx:89:4c:ca brd ff:ff:ff:ff:ff:ff promiscuity 2 numtxqueues 4 numrxqueues 4 gso_max_size 65536 gso_max_segs 65535 
```

**Comment by mboelen** [comment]
Thanks for reporting.

We recently researched this and concluded that using 'ip' is the best option for Linux systems. From what we can see is any value [higher than 0](https://github.com/shemminger/iproute2/blob/6754e1d9783458550dce8d309efb4091ec8089a5/include/uapi/linux/if_link.h#L146) for the promiscuity value an indication that it is turned on.

There are a few different reasons why it is in promiscuous mode besides the "I turned it on purpose or running something like tcpdump". I just checked a fresh CentOS system again, and it is set to '0' for me. Maybe you are running something like Docker on it? Do you have some other systems to compare as well?

**Comment by d4t4king** [comment]
Hello @aram535 , it may be possible that you have followed another suggestion from Lynis and installed/enabled arpwatch or a similar tool?  These tools enable promiscuous mode for active interfaces and are in direct conflict with the promiscuous mode detection test (IMHO).

The guidance I received, in this case, was that the administrator must decide whether to enable aprwatch (or similar tools) or allow promisc mode for your interfaces.

This may not apply and is only one possibility.  YYMV.

**Comment by aram535** [comment]
Hello @d4t4king, @mboelen .. I do see the module loaded but again I believe (as you can see above) it's simply the capability that has been enabled, but the interface is not actually in promisc mode.  And yes you're correct that on a fresh install since the kernel module is not loaded it would be set to 0 in the "ip" command.  That said you maybe 100% correct in this assume and I'm wrong but my current understanding is that unless the interface itself is in PROMISC mode then it isn't "active", and that that "1" in "ip" output is showing the kernel's module has been loaded and/or enabled.
I guess the best way to test this and not guess or go by our understanding is to setup a couple of VMs with a virtual wire connection and see if they see each other's packets.

**Comment by arafatx** [comment]
especially if we use tool like arpwatch, if we can identify by script how "the interface is not actually in promisc mode", then we can actually put this skip check on lynis  

A little bit confused how lynis suggest to solve one security issue in order to appear another security issue.

**Comment by mboelen** [comment]
As this topic (choose between X or Y) shows up more often, the suggestion on tooling like arpwatch has now been disabled. In the end, it is you (the administrator) that have to decide what makes sense for your environment. Sometimes that may be enabling a tool that puts your interface in promiscuous mode. That it is in this mode is not bad, but it is good to know. If you do know and accept that, then you can simply add 'skip-test' to your custom.prf and disable a particular test.

For now closing this issue. If someone has the time to do an extensive test besides what we did, please reach out.
