### ISSUE TITLE
How to keep updated via CentOS yum?

### ISSUE THREAD

**Issue by morespinach99** [CISOfy/lynis#712]
Hello. Using `yum install lynis` on CentOS 7.6.181 I only got version 2.7.1, which is Outdated. Yet, when I do `yum update lynis` I get a message that there's no update. Does this need some special repo?

**Comment by mboelen** [comment]
Most likely your Lynis version comes from a default repository or from EPEL. If you want to stay up-to-date with the latest versions, then you can consider using the [Lynis community repository](https://packages.cisofy.com/community/) that we maintain.
