### ISSUE TITLE
auditd not detected on OSX 10.14.4 with Lynis 2.7.4

### ISSUE THREAD

**Issue by micheas** [CISOfy/lynis#715]
**Describe the bug**
`auditd` is not detected on OSX . 10.14.4 (Mojave) even though it is running.

**Version**
 - Distribution OS X 10.14.4
 - Lynis version 2.7.4

**Expected behavior**
Lynis should detect auditd if it is running, even if you can't tell with ps.

**Output**
Nothing in the logs,

auditd can be verified working with the following command:
```
 sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.auditd.plist
Password:
/System/Library/LaunchDaemons/com.apple.auditd.plist: service already loaded
```

**Additional context**
This is especially annoying as it is one of the checks built into the standard HIPAA policy..

**Comment by dolmen** [comment]
What about first checking if `/System/Library/LaunchDaemons/com.apple.auditd.plist` exists? This would work for non-root users.
Then check `launchctl list com.apple.auditd`. If status code is not 0, the service is not running.
