### ISSUE TITLE
Exclude /etc/letsencrypt/archive/ from cert check

### ISSUE THREAD

**Issue by pyllyukko** [CISOfy/lynis#724]
**Describe the bug**

`tests_crypto` goes through all the cert dirs with `find` checking all the certs for expiration. Let's encrypt places old certs in `/etc/letsencrypt/archive/` so it's bound to have expired certs, but that's perfectly fine.

**Version**
 - Lynis 2.7.4

**Expected behavior**

Report meaningful stuff. Maybe best option would be to skip the whole `/etc/letsencrypt/archive/` dir.

**Output**

```
2019-06-11 23:13:43 Result: found 48 certificates in /etc/letsencrypt
```

**Comment by mboelen** [comment]
A new option has been added to Lynis to achieve this.

Commits:
- https://github.com/CISOfy/lynis/commit/2c17c14c3b8235c906e3435369b278e95f09b1ad
- https://github.com/CISOfy/lynis/commit/16146aabc0023a10e3f83c8d27860323080297c3

Can you test and see if it works for you?
Note: upcoming release is a major release, so have a look at the changelog for details.

**Comment by pyllyukko** [comment]
> Can you test and see if it works for you?

<https://github.com/CISOfy/lynis/commit/2c17c14c3b8235c906e3435369b278e95f09b1ad#r34221139>

**Comment by mboelen** [comment]
Thanks. New changes applied. Does this work better?

**Comment by pyllyukko** [comment]
> Does this work better?

Now it works. Although you need to specify the full path (e.g. `/etc/letsencrypt/archive/cisofy.com`) as there are hostname specific subdirectories there and it would be better that it would disregard `/etc/letsencrypt/archive/` and everything from there. But I think this is still sufficient :+1: 

Thanks.

**Comment by damnms** [comment]
I installed the current master of lynis and the scan reports all /etc/letsencrypt/archives certificates as expired. Did i miss something? Or is this a regression?

**Comment by mboelen** [comment]
@damnms - please open a new issue with the requested details (e.g. relevant logging), so we can investigate it.
