### ISSUE TITLE
Problem with "Minimal of 2 responsive nameservers" in AWS an maybe other cloud environments

### ISSUE THREAD

**Issue by Reiner030** [CISOfy/lynis#725]
Similar to #545 AWS offers by DHCP only one DNS server 172.31.0.2 in default VPC by DHCP (or adopted DNS in different network mask).
AWS offered DNS server is (hopely) setup with failover and by default the only one.

So it would be nice to have a parameter setting to override this check in custom.prf.

* There is also a DNS server reachable within 169.254.169.253 but not announced by DHCP
* From documentation it is also possible to enhance the DNS server within DHCP client configuration but thats default not active:
    https://aws.amazon.com/premiumsupport/knowledge-center/ec2-static-dns-ubuntu-debian/

**Comment by mboelen** [comment]
Thanks for sharing this. If you could override, what specifically is it?

**Comment by Reiner030** [comment]
It would be nice to allow 1 DNS server only as "good" result of this check.
Maybe like
```
# Ignore some stratum 16 hosts (for example when running as time source itself)
#ntp-ignore-stratum-16-peer=127.0.0.1
```
it would be nice to have something like
```
# ns-ignore-single-server=yes
```
or maybe direct setup like for dnsmasq with acceptable individual IP setup as single resolv entry:
```
# ns-allow-single-server=127.0.0.1
# ns-allow-single-server=127.0.0.1,172.168.31.2
```

**Comment by mboelen** [comment]
The current test already 'knows' that if you are using 127.x.x.x that it should skip further testing, as most likely you configured a local daemon to handle things.

If you feel that it is fine to have just a single nameserver configured on that system, then instead of a new option, you can leverage the existing 'skip-test' option. It tells Lynis that you don't want this particular test to run.

**Comment by Reiner030** [comment]
Ah, thanks for the hint.
Sadly there is no mini howto for setup so it was not clear by finding this snippet beginning with:

https://github.com/CISOfy/lynis/blob/cc0987a00f14f8e91c10f7319e4d14239316a304/include/tests_networking#L164-L168

while searching for `Minimal of 2 responsive nameservers`
because all checks have the same `if [ ${SKIPTEST} -eq 0 ]; then` condition which looks not really functional because there is in programming languages no variable which works with multiple content/lines and especially not bash... 
Just searched for `Register` and couldn't find a definition which matches the used functionality, even not in https://wiki.bash-hackers.org/howto/calculate-dc?s[]=register#registers.
=> Do you have a nice reference for it? Thanks.

While now searching for `skip` I found:
https://github.com/CISOfy/lynis/blob/841509465b03e7a538649cb5fe94c9def7c40075/default.prf#L85-L90

so if I am right in the local configuration part I could setup:
```
skip-test=NETW-2705
```
ant the test is ignored ?

Thanks for clarification and maybe some improved small documentation e.g. in the Readme (maybe that tests can be skipped and all possible behavior changes are documented in the configuration file ...) 😄

**Comment by mboelen** [comment]
The Register call is a function defined in include/functions. It determines if the test should be skipped or not (SKIP).

Yes, that is the right way to use the 'skip-test' option. Add it to your custom.prf file.

There is documentation (see the reference in the README on the first line and a bit later). Agree, the option to skip can be clarified a bit better in the documentation. Will work on that. In the meantime, will close this issue, as there is a way to ignore the test.
