### ISSUE TITLE
Release file is missing for Ubuntu bionic (18.04 LTS) distribution

### ISSUE THREAD

**Issue by shpokas** [CISOfy/lynis#737]
After upgrade from xenial to bionic, Cisofy repository cannot be enabled on Ubuntu bionic as apt command does not find Release file.

# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

# cat cisofy-lynis.list 
deb https://packages.cisofy.com/community/lynis/deb/ bionic main

# apt update
....
Ign:5 https://packages.cisofy.com/community/lynis/deb bionic InRelease                                                                                                                                         
Err:6 https://packages.cisofy.com/community/lynis/deb bionic Release     
  404  Not Found [IP: 2a01:7c8:aac2:37b::1 443]
Reading package lists... Done                      
E: The repository 'https://packages.cisofy.com/community/lynis/deb bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by mboelen** [comment]
Thanks for reporting.

There is actually no need to specify the distribution name as we use 'stable' for releases. So change 'bionic' into 'stable' to resolve this.

Background: Before, xenial and other distribution were used on the repository. Since Lynis can run on all (and is not compiled), we merged them all into 'stable'.
