### ISSUE TITLE
minilogd incorrectly detected as running.

### ISSUE THREAD

**Issue by leogx9r** [CISOfy/lynis#738]
Since the test for detecting minilogd was added, it incorrectly labels "not found" as found due to flipped if/else.

Relevant code is here: https://github.com/CISOfy/lynis/blob/fb33112555b41cab32fd550b3ca276ea843c8205/include/tests_logging#L209-L217

**Version**
 - Arch Linux
 - fb33112555b41cab32fd550b3ca276ea843c8205

**Expected behavior**
Minilogd usage should not be detected when it's not actually running.

**Comment by mboelen** [comment]
Thanks for reporting. Fixed with commit https://github.com/CISOfy/lynis/commit/4b77e27495c9447e09f348d191b14b4b72694b33
