### ISSUE TITLE
On upload error: "{EXITCODE}"

### ISSUE THREAD

**Issue by wagner-certat** [CISOfy/lynis#741]
**Describe the bug**
Calling "lynis audit upload-only", getting an curl error (that's not the bug I am reporting here), output contains at the end:
```
...
Upload Error: cURL could not upload data. See /var/log/lynis.log for details.
Suggested command: tail -n 20 /var/log/lynis.log

Related exit code: {EXITCODE}. See man page of cURL for the meaning of this code.
```
`{EXITCODE}` looks like it should have been replaced

**Version**
 - Distribution openSUSE Tumbleweed
 - Lynis version 2.7.5

**Expected behavior**
An actual error code

**Comment by mboelen** [comment]
Fixed with commit https://github.com/CISOfy/lynis/commit/c86e24fced57e0e11916e318fc015f70d18ba84f

Thanks for reporting!
