### ISSUE TITLE
Unknown OS found in /etc/os-release  - Centos 7

### ISSUE THREAD

**Issue by daniejstriata** [CISOfy/lynis#746]
**Describe the bug**
I was asked to report this when I ran Lynis v3 in debug mode:
```

+] Initializing program
------------------------------------
[DEBUG] Already discovered default.prf - skipping this file (./default.prf)
[DEBUG] Found profile defined with --profile
[DEBUG] **Unknown OS found** in /etc/os-release. Do you know what it is? Create an issue at https://github.com/CISOfy/lynis
  - Detecting OS...                                           [ DONE ]
[DEBUG] Profile option set: colors (with value yes)
[DEBUG] Colors set to 1
[DEBUG] Profile option set: compressed-uploads (with value yes)
[DEBUG] Profile option set: error-on-warnings (with value no)

```
**Version**
 - Centos 7.6
 - Lynis version 3.0.0

# Output:

# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

# cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core) 

# lsb_release -a
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core) 
Release:	7.6.1810
Codename:	Core

**Comment by mboelen** [comment]
Thanks for reporting. Added CentOS to that detection function among some other improvements.

Related commit: https://github.com/CISOfy/lynis/commit/2c4e7711db0ab965ac78f3c3bba91162bb143e50
