### ISSUE TITLE
CONT-8106: Number of containers is not detected properly

### ISSUE THREAD

**Issue by mrplug** [CISOfy/lynis#749]
**Describe the bug**
Error happens in file `tests_containers` line 140. When fetching the actual number of containers a command like this in generated: `docker info | grep "^Containers: " | awk '{ print $2 }'`. After running the command no number is printed out. The regular expression fails, because there is a white space right before the word `Containers`. 

**Version**
 - Distribution Ubuntu 18.04
 - Lynis version 2.7.5

**Expected behavior**
`<JustTheNumberOfContainers>`

**Output**
Nothing

**Additional context**
-

**Possible Solution**
Change regular expression from `"^Containers: "` to `"Containers: "`.
Just remove the `^`.

**Comment by mboelen** [comment]
Can you show your 'docker info' output?

This is what I see on a Ubuntu 18.04 test system:

> root@ubuntu:~/lynis# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-58-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.947GiB
Name: ubuntu
ID: DOID:FN7F:KDHC:VIXR:VE53:ABQ3:BIFU:FZGC:D43P:SXEC:5YGY:5A3J
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Comment by mrplug** [comment]
Of course, i can! 

<img width="524" alt="docker_info_output" src="https://user-images.githubusercontent.com/29592445/63711337-7ac70600-c83b-11e9-9508-e485cc0584e2.PNG">

Maybe there is an issue with a new version?

**Comment by mboelen** [comment]
Yes, I think so. Added commit https://github.com/CISOfy/lynis/commit/7469b4aa7229bfe96e0620bfd0268d5e9dc71843 to catch the optional extra spacing.

Can you check if it works for you as well now?

**Comment by mrplug** [comment]
Works totally fine! Thank you!

**Comment by Creamers158** [comment]
@mboelen @mrplug Working with version 2.7.5, and it seems that it is not recognizing the total number of containers
![totaldocker](https://user-images.githubusercontent.com/6506666/73614322-2f8cfc80-45fe-11ea-9806-ec9ba8040350.png)

**Comment by mboelen** [comment]
@Creamers158 - please open a new issue, as this might not be directly related to this issue. Please share all available details that you have (OS, Docker version, etc).
