### ISSUE TITLE
OSSEC agent not detected as IDS/IPS tooling

### ISSUE THREAD

**Issue by luis02lopez** [CISOfy/lynis#750]
**Describe the bug**
When OSSEC is installed as an agent and a Lynis audit is performed, the later detect OSSEC but does not detect it as an IPS/IDS tool, even though IDS/IPS actions are executed. This is due that Lynis on the `test_tooling` in the `TOOL-5160` and `TOOL-5190` depends on the `ossec-analysisd` process which only runs on the OSSEC master server. The following represent the situation:

Abstract of Lynis report `(lynis audit system)`:

      . . .

      - Checking file integrity tools
        - OSSEC (syscheck)                                              [ FOUND ]
      - Checking presence integrity tool                                [ FOUND ]

    [+] Software: System tooling
    ------------------------------------
      - Checking automation tooling
      - Automation tooling                                              [ NOT FOUND ]
      - Checking for IDS/IPS tooling                                    [ NONE ]

      . . .

Abstract of /include/test_tooling (Which depends on `ossec-analysisd`):

    . . .

    # Test        : TOOL-5160
    # Description : Check for OSSEC
    Register --test-no TOOL-5126 --weight L --network NO --category security --description "Check for active OSSEC analysis daemon"
    if [ ${SKIPTEST} -eq 0 ]; then

        if IsRunning "ossec-analysisd"; then
            IDS_IPS_TOOL_FOUND=1
            LogText "Result: OSSEC analysis daemon is active"
            Report "ids_ips_tooling[]=ossec"
            Display --indent 2 --text "- Checking presence of OSSEC" --result "${STATUS_FOUND}" --color GREEN
        else
            LogText "Result: OSSEC analysis daemon not active"
        fi
    fi

    # Test        : TOOL-5190
    # Description : Check for an IDS/IPS tool
    Register --test-no TOOL-5190 --weight L --network NO --category security --description "Check presence of IDS/IPS tool"
    if [ ${SKIPTEST} -eq 0 ]; then

        if [ ${IDS_IPS_TOOL_FOUND} -eq 1 ]; then
            Display --indent 2 --text "- Checking for IDS/IPS tooling" --result "${STATUS_FOUND}" --color GREEN
            AddHP 2 2
        else
            Display --indent 2 --text "- Checking for IDS/IPS tooling" --result "${STATUS_NONE}" --color YELLOW
            #ReportSuggestion ${TEST_NO} "Install and configure automated intrusion detection/prevention tools"
            AddHP 0 2
        fi
    fi
    
    . . .

Proccess running on an OSSEC Agent installation (`ps -aux | grep ossec`):

    ubuntu     885  0.0  0.0  12944   972 pts/0    S+   14:28   0:00 grep --color=auto ossec
    root     31468  0.0  0.0  12888   160 ?        S    12:10   0:00 /var/ossec/bin/ossec-execd
    ossec    31472  0.0  0.1  13196  2128 ?        S    12:10   0:00 /var/ossec/bin/ossec-agentd
    root     31476  0.0  0.0   4592  1580 ?        S    12:10   0:00 /var/ossec/bin/ossec-logcollector
    root     31480  0.0  0.1   5684  2924 ?        S    12:10   0:06 /var/ossec/bin/ossec-syscheckd

**Version**
 - Distribution: Ubuntu 16.04
 - Lynis version 2.7.5

**Expected behavior**
Detect OSSEC IDS/IPS installation.

**Output**
      - Checking for IDS/IPS tooling                                    [ NONE ]

**Additional context**
Reference of what is `ossec-analysisd`:
https://www.ossec.net/docs/programs/ossec-analysisd.html#ossec-analysisd
https://www.ossec.net/docs/faq/ossec.html#the-rules-aren-t-on-my-agents-they-re-only-on-the-server

**Comment by mboelen** [comment]
Added support for agent daemon with commit https://github.com/CISOfy/lynis/commit/61404c1bf335c5a1f3a82267346346446589868f

If you have the chance, please test it on your system(s).
