### ISSUE TITLE
Entropy check

### ISSUE THREAD

**Issue by Schwingg** [CISOfy/lynis#751]
**Is your feature request related to a problem? Please describe.**
It could be interesting to check the available entropy on systems. In in some case a lack of entropy could generate weird issues using SSL connections.

**Describe the solution you'd like**
On Linux systems which I am familiar with you could do a check like:
  `cat /proc/sys/kernel/random/entropy_avail`

**Required changes**
 Add a check to verify if the number given by the command above is more than 200.

**Additional context**
This problem is a real thing when you are using a small virtual machines.

**Comment by mboelen** [comment]
Thanks for the suggestion. Implemented with commit https://github.com/CISOfy/lynis/commit/a87c2b10f9ce15d51344c8531e143bbc52a106e7
