### ISSUE TITLE
lsblk does not have a PATH column

### ISSUE THREAD

**Issue by konstruktoid** [CISOfy/lynis#752]
**Describe the bug**
`lsblk` does not have a `PATH` column.

**Version**
 - Ubuntu 18.04.3 LTS
 - Git master a87c2b10f9ce15d51344c8531e143bbc52a106e7

**Output**
```
[+] Cryptography
------------------------------------
  - Checking for expired SSL certificates [0/2]               [ NONE ]
lsblk: unknown column: PATH
  - Kernel entropy is sufficient                              [ YES ]
```

**Additional context**
#731
https://github.com/CISOfy/lynis/blob/master/include/tests_crypto#L142

```
$ lsblk --help | grep -E 'PATH|MOUNTPOINT' && lsblk -V
  MOUNTPOINT  where the device is mounted
lsblk from util-linux 2.31.1
```

**Comment by mboelen** [comment]
Thanks for reporting. It did not trigger on my system as this test works for both root and non-privileged users.

Applied change with commit https://github.com/CISOfy/lynis/commit/0d58ee77a05d15675bc011244c600293a6ec3cbc
