### ISSUE TITLE
Syntax error: Unterminated quoted string while running lynis audit system

### ISSUE THREAD

**Issue by Yashwantbokadia** [CISOfy/lynis#760]
- Permissions of home directories                           [ WARNING ]
./lynis: 178: /home/ubuntu/lynis/include/tests_homedirs: Syntax error: Unterminated quoted string

**Comment by mboelen** [comment]
Thanks for reporting.

Resolved with commit https://github.com/CISOfy/lynis/commit/6cf0b28f2ccd7b4c04f41e985735bbe68ec2a023

(use git pull to refresh)
