### ISSUE TITLE
[FIRE-4512] warning when ruleset isn't empty

### ISSUE THREAD

**Issue by Nono-m0le** [CISOfy/lynis#767]
**Describe the bug**
When running a audit system with root priviledge, I'm having [FIRE-4512] as a warning
(could it be related to https://github.com/CISOfy/lynis/issues/579 ?)
However, I guess it's a kind of a bug because iptables is running and the ruleset aren't empty.

**Version**
 - Distribution: Ubuntu 18.04
 - Lynis version: 2.7.5

**Expected behavior**
I shouldn't have this warning at all ?

**Output**
```
[+] Software: firewalls
------------------------------------
- Checking iptables kernel module                           [ FOUND ]
- Checking iptables policies of chains                    [ FOUND ]
- Checking for empty ruleset                              [ WARNING ]
- Checking for unused rules                               [ FOUND ]
- Checking host based firewall                              [ ACTIVE ]

[...]

  Warnings (1):
  ----------------------------
  ! iptables module(s) loaded, but no rules active [FIRE-4512]
      https://cisofy.com/lynis/controls/FIRE-4512/
```

**Additional context**
I first though that it was because I've loaded the module nf_log_ipv4 to use the debug/trace method on iptables
I used this for set it up: 
`sudo modprobe nf_log_ipv4; sudo sysctl net.netfilter.nf_log.2=nf_log_ipv4`
And this to revert it back: 
`sudo modprobe -r nf_log_ipv4; sudo sysctl net.netfilter.nf_log.2=nfnetlink_log`

**Comment by mboelen** [comment]
Thanks for reporting. Can you show your firewall rules?

**Comment by Nono-m0le** [comment]
Here is an anonymized (port / hostname have been changed) example: 

```
user@srv:~$ sudo iptables -L -t nat
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
RETURN     all  --  anywhere            !srv
REDIRECT   tcp  --  anywhere            !srv             tcp flags:FIN,SYN,RST,ACK/SYN redir ports 2222
REDIRECT   udp  --  anywhere            !srv             udp dpt:domain redir ports 1111

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
DNAT       udp  --  anywhere             anywhere             owner UID match user udp dpt:domain to:1.1.1.1:1111
DNAT       tcp  --  anywhere             anywhere             multiport dports https,555 owner UID match user tcp to:1.1.1.1:2222

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
MASQUERADE  all  --  anywhere             anywhere
```

**Comment by Nono-m0le** [comment]
Any updates on this?

**Comment by Nono-m0le** [comment]
@mboelen any news?

**Comment by konstruktoid** [comment]
Hi @Nono-m0le, can you reproduce this in a later version?

```
~$ lsb_release -a && grep -iE 'lynis_version|^firewall' ./lynis-report.dat 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu Focal Fossa (development branch)
Release:        20.04
Codename:       focal
lynis_version=3.0.0
firewall_software[]=iptables
firewall_active=1
firewall_empty_ruleset=0
firewall_installed=1
~$ sudo iptables -t filter --numeric --list | grep -E -z -o -w  '[A-Z]+' | tr -d '\0'
INPUTDROPFORWARDDROPOUTPUTACCEPTADDRTYPEBROADCASTLOGLOGUFWBLOCKLOGLOGUFWBLOCKACCEPTRELATEDESTABLISHEDACCEPTACCEPTACCEPTACCEPTACCEPTACCEPTRELATEDESTABLISHEDINVALIDDROPINVALIDACCEPTACCEPTACCEPTACCEPTACCEPTACCEPTACCEPTACCEPTACCEPTRELATEDESTABLISHEDLOGLOGUFWALLOWRETURNINVALIDLOGLOGUFWBLOCKRETURNADDRTYPELOCALRETURNADDRTYPEMULTICASTRETURNADDRTYPEBROADCASTDROPDROPDROPACCEPTACCEPTNEWACCEPTNEWACCEPTLOGLOGUFWLIMITBLOCKREJECTACCEPT
```

**Comment by mboelen** [comment]
@Nono-m0le are you still having the issue. The related part of the log file might be useful.

Apologies for the delay in answering. From different directions we got a lot of requests and this one was missed. That is also why we have the GitHub bot now active to keep an eye on issues.

**Comment by mboelen** [comment]
@Nono-m0le - Is this still an active issue for you?

**Comment by Nono-m0le** [comment]
I didn't find the package version 3.0.0 so :
```
# lsb_release -a && grep -iE 'lynis_version|^firewall' /var/log/lynis-report.dat
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
lynis_version=2.7.5
firewall_software[]=iptables
firewall_no_logging[]=iptables
firewall_active=1
firewall_empty_ruleset=1
firewall_installed=1
# iptables --list --numeric 2>  /dev/null | grep -E -v '^(Chain|target|$)' | wc -l | tr -d ' '
5
```
and still: 
```

  Warnings (1):
  ----------------------------
  ! iptables module(s) loaded, but no rules active [FIRE-4512]
      https://cisofy.com/lynis/controls/FIRE-4512/
```

**Comment by konstruktoid** [comment]
`3.0.0` is the current code in the master branch, so you need to download it (eg `git clone`) and run it.

**Comment by Me-Codifier** [comment]
I'm running lynis 3.0.0 in my desktop and getting the same warning.
When I check the log file, I get these...
----------------------------------------------
Performing test ID FIRE-4512 (Check iptables for empty ruleset)
Result: iptables ruleset seems to be empty (found 3 rules)
Warning: iptables module(s) loaded, but no rules active
----------------------------------------------
there is no unused rule sets.
is there any minimum rules to be present to pass this test.

**Comment by mboelen** [comment]
@Me-Codifier Yes, 5 or more.

**Comment by mboelen** [comment]
@Nono-m0le Do you still have this issue?

**Comment by Nono-m0le** [comment]
Using:
```
# lsb_release -a && grep -iE 'lynis_version|^firewall' /var/log/lynis-report.dat
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
lynis_version=3.0.1
firewall_software[]=iptables
firewall_no_logging[]=iptables
firewall_active=1
firewall_empty_ruleset=1
firewall_installed=1
```
got : 

```
  ! iptables module(s) loaded, but no rules active [FIRE-4512]
      https://cisofy.com/lynis/controls/FIRE-4512/
```

even though:

```
# iptables --list --numeric 2>  /dev/null | grep -E -v '^(Chain|target|$)' | wc -l | tr -d ' '
1
# iptables --list --numeric -t nat 2>  /dev/null | grep -E -v '^(Chain|target|$)' | wc -l | tr -d ' '
9
```

So, I understand there is a minimum of 5 rules (even though, I don't understand why ?!) but why: 
1) It's not mentionned somewhere ?
2) Why its says "no rules" when it's in fact "only 1 on the expected minimum of 5" ?

**Comment by Nono-m0le** [comment]
No explanations @mbolen?

**Comment by stnert** [comment]
@mboelen  Também estou tentando esse problema no Fedora Silverblue...
