### ISSUE TITLE
Incorrect report of relative path in PATH for paths with spaces

### ISSUE THREAD

**Issue by nh2** [CISOfy/lynis#768]
**Describe the bug**

I get `Found relative path in PATH` when there is no relative path in it. Having a path with spaces, like `/home/niklas/opt/sublime/Sublime Text 2`, in `PATH`, creates this false positive.

**Version**
 - Ubuntu 16.04
 - Lynis version: 3.0.0 (commit 0088593506138b54f6edcabf995fdaac5cbeee9a)

**Expected behavior**

No warning.

**Output**

```
  Warnings (1):
  ----------------------------
  ! Possible riskful location in PATH discovered [CORE-1000] 
    - Details  : text:Found relative path in PATH
      https://cisofy.com/lynis/controls/CORE-1000/
```

**Additional context**

My colleague @neilmayhew pointed out:

> I ran shellcheck on the Lynis source. It came up with a LOT of Double quote to prevent globbing and word splitting warnings. Interestingly, there was an issue (now closed) to use shellcheck and fix as many issues as possible (https://github.com/CISOfy/lynis/issues/189).
> The author didn't fix this one, though:
> `PATH_REVERSED=$(echo ${PATH} | awk -F: '{ for (i=NF; i>1; i--) printf("%s ",$i); print $1; }')`

**Comment by neilmayhew** [comment]
It would be better to use `'\n'` as the separator rather than `' '`:

```shell
BIN_PATHS=$(echo "$PATH" | tr : '\n' | tac)

echo "$BIN_PATHS" | while read SCANDIR; do
```

It would also be helpful to add a test before that to check that `PATH` doesn't contain any control characters:

```shell
[ "$(echo -n "$PATH" | tr -d '[[:print:]]' | wc -c)" -eq 0 ]
```

**Comment by neilmayhew** [comment]
Just realized `tac` isn't present on macOS. However, as shown by this [StackOverflow answer][1], its equivalent is `tail -r` so you could define an alias (shell function) conditionally.

[1]: https://unix.stackexchange.com/a/114043

**Comment by neilmayhew** [comment]
Unfortunately, `tr` doesn't seem to be Unicode-aware, so `[[:print:]]` doesn't include anything outside the ASCII range and this test would produce a false positive for any dir that has non-ASCII characters in it. Maybe just check that there are no newlines:

```shell
[ "$(echo -n "$PATH" | tr -cd '\n' | wc -c)" -eq 0 ]
```

**Comment by Schmuuu** [comment]
Hello @nh2, @dolmen and @neilmayhew (not sure if you were affected as well Neil),

Could you please test the potential fix: #800 ?
I chose a quite simplistic approach, however there was more to edit than expected and I would like to make sure, there are no other false-reports or weird output to the console when running the script.
I tried to test of course, but real world scenarios are always a bit different.

I appreciate it. Thanks

**Comment by neilmayhew** [comment]
@Schmuuu I wasn't affected directly, but I tested it anyway, using:

```shell
PATH="/bin:/opt/Sublime Text 2:$PATH" ./lynis audit system --tests CORE-1000
```

and didn't get any warnings. Then when I changed `/bin` to `bin`, I did get a warning, as required.

**Comment by Schmuuu** [comment]
Hi @nh2 

Any chance to test my potential fix? If you confirm the fix we could probably merge it into master.

Thanks in advance :)

**Comment by nh2** [comment]
@Schmuuu Sorry for the delay, I've tested it just now, it works for me as well.
