### ISSUE TITLE
LOGG-2190 also throws a warning with MySQL 5.7

### ISSUE THREAD

**Issue by cueedee** [CISOfy/lynis#769]
I know about issue #209 which is about versions `<5.6` of MySQL leaving deleted open files in `/tmp`; an exception for these version was implemented for `LOGG-2190`.

I have a fresh Ubuntu`@18.04.x` install with an `apt-get install mysql-server` resulting in a `mysqld@5.7.27`.

I find `LOGG-2190` (of `lynis@2.7.5`) still reports deleted open files for `mysqld`.  

Now, I don't know (yet) if this is a regression of the bug supposedly fixed for `mysqld@5.6`, a new bug or simply expected behaviour of `mysqld`.

I suspect it's the latter.

If so, it would be nice if certain processes could be exempted by name from getting warned for. 
I'm thinking along the lines of:

```
skip-test=LOGG-2190:mysqld
```

This would remove the need for implementing explicit exceptions such as the one that #209 was the cause for, allow for end-users customizing specific exceptions themselves without having to resort to completely disabling the test.

**Comment by mboelen** [comment]
Hi @cueedee - Thanks for reporting this and your patience. Last few months were more busy than usual, so we had no time yet to research this one yet.

Yes, it would be great to allow exclusions. For now, we have excluded mysqld altogether, so we can fix this for the upcoming major release (3.0.0).

Related commit: https://github.com/CISOfy/lynis/commit/4432f9304485c0c1615b8772d19065c5fc7e7e4c
