### ISSUE TITLE
debian / false positive for some users on  HOME-9306

### ISSUE THREAD

**Issue by damnms** [CISOfy/lynis#773]
**Describe the bug**
Some users are reported having a homedirectory which is not owned by them. This is wrong.

**Version**
 - Debian 10.1
 - Lynis version master (downloaded from github as zip)

**Expected behavior**
Get no error on such users

**Output**
If applicable, add output that you get from the tool or the related section of lynis.log

**Additional context**
for example, my amavis user looks like: 
`amavis:x:114:120:AMaViS system user,,,:/var/lib/amavis:/bin/sh
`
The report says: 
`2019-10-06 21:26:11 Result: The home directory  of user amavis is owned by root. Change with: chown amavis`

But when i check the folder /var/lib/amavis, it says:
`drwxr-x---  7 amavis         amavis        4,0K Okt  6 21:17 amavis`

**Comment by church1e** [comment]
I took a deeper look into this and it seems the AWK statement in line 92 of `includes/tests_homedirs` is malforming the output when spaces are in place :-(

A possible workaround is to simple colon delimit the output for the desired fields $1 and $6 rather than the entire line from `/etc/passwd`

Can I suggest the following as a replacement... simply modify lines 92 and 94!

```
diff --git include/tests_homedirs include/tests_homedirs
index 9b8c9c6..1647a47 100644
--- include/tests_homedirs
+++ include/tests_homedirs
@@ -89,9 +89,9 @@
     if [ ${SKIPTEST} -eq 0 ]; then
         # Check if users own their home directories
         FOUND=0
-        for LINE in $(${EGREPBINARY} -v '^(daemon|git|halt|root|shutdown|sync)' ${ROOTDIR}etc/passwd | ${AWKBINARY} -F: '($7 !~ "/(false|nologin)$") { print }'); do
+        for LINE in $(${EGREPBINARY} -v '^(daemon|git|halt|root|shutdown|sync)' ${ROOTDIR}etc/passwd | ${AWKBINARY} -F: '($7 !~ "/(false|nologin)$") { print $1 ":" $6}'); do
             USER=$(echo ${LINE} | ${CUTBINARY} -d: -f1)
-            DIR=$(echo ${LINE} | ${CUTBINARY} -d: -f6)
+            DIR=$(echo ${LINE} | ${CUTBINARY} -d: -f2)
             if [ -d ${DIR} ]; then
                 OWNER=$(ls -ld ${DIR} | awk -F" " '{ print $3 }')
                 if [ ! "${OWNER}" = "${USER}" ]; then
```

**Comment by neilmayhew** [comment]
@church1e Any chance you could create a PR for this? It might get fixed sooner that way.

**Comment by neilmayhew** [comment]
BTW, this affects all systems, not just Debian.

**Comment by mboelen** [comment]
Implemented change with pull request
