### ISSUE TITLE
FILE-6374 wrong test description in tests.db

### ISSUE THREAD

**Issue by liedekef** [CISOfy/lynis#775]
The output for "lynis show tests" for test FILE-6374 (that probably comes from db/tests.db) is:
"Checking /boot mount options (security)"
However, the test itself registers as "Check mount options for Linux" (and includes tests for several fs's).
Maybe the db/tests.db should be regenerated based on the real tests included, to avoid mismatches ... or let "lynis show tests" get its info directly from the real tests, to avoid double/missing information.

**Comment by mboelen** [comment]
Thanks for reporting. This has been corrected with commit https://github.com/CISOfy/lynis/commit/f188bac7e8b92a4d1d933e5ed961c0417d4e1aeb

We have an improvement planned to sync tests and their descriptions in a future release and make it also part of the Software Development Kit (SDK).
