### ISSUE TITLE
Add a new malware scanner - CrowdStrike's Falcon

### ISSUE THREAD

**Issue by daniejstriata** [CISOfy/lynis#776]
**Feature request**
We have a client that is using CrowdStrike's FALCON-SENSOR service on Centos/RHEL.

Current v3 of Lynis does not recognise Falcon as an AV on Linux. Not using this myself I don't know if it does perform periodic scans or not. From what I read scans are essentially continuous rather than periodic.

**Log Entry**
suggestion[]=HRDN-7230|Harden the system by installing at least one malware scanner, to perform periodic file system scans|-|Install a tool like rkhunter, chkrootkit, OSSEC|

**service running**
running_service[]=falcon-sensor

**Describe the solution you'd like**
Review and possibly add Falcon as an acknowledged AV/Malware solution for Linux.

**Required changes**
Expand list of known AV on Linux.

**Resources**
https://www.crowdstrike.com/endpoint-security-products/
https://www.crowdstrike.com/wp-content/brochures/IDC_Vendor_Profile-CrowdStrike.pdf

**Comment by mboelen** [comment]
Hi @daniejstriata - what is the process name on the system?

**Comment by daniejstriata** [comment]
Here you go:
```
# ps fauwx | grep falcon
root       693  0.0  0.0   8588  2536 ?        Ss   Aug29   0:00 /opt/CrowdStrike/falcond
root       694  0.1  3.4 1203916 125136 ?      Sl   Aug29  86:26  \_ falcon-sensor
```
```
drwxr-x--- 2 root root        6 Oct  9 07:11 Downloads
lrwxrwxrwx 1 root root       30 Oct  4 15:11 falconctl -> /opt/CrowdStrike/falconctl8201
-rwxr-x--- 1 root root    60200 Oct  4 15:11 falconctl8201
lrwxrwxrwx 1 root root       28 Oct  4 15:11 falcond -> /opt/CrowdStrike/falcond8201
-rwxr-x--- 1 root root    10824 Oct  4 15:11 falcond8201
lrwxrwxrwx 1 root root       40 Aug 27 04:37 falcon-kernel-check -> /opt/CrowdStrike/falcon-kernel-check7603
-rwxr-x--- 1 root root    48905 Jul  9 21:16 falcon-kernel-check7603
lrwxrwxrwx 1 root root       34 Oct  4 15:11 falcon-sensor -> /opt/CrowdStrike/falcon-sensor8201
-rwxr-x--- 1 root root  1458184 Oct  4 15:11 falcon-sensor8201
-rw-r----- 1 root root     8192 Oct 10 09:39 falconstore
lrwxrwxrwx 1 root root       40 Oct  4 15:11 KernelModuleArchive -> /opt/CrowdStrike/KernelModuleArchive8201
-rw-r----- 1 root root 25029992 Oct  4 15:11 KernelModuleArchive8201
-rw-r----- 1 root root    13887 Oct  9 07:11 Registry.bin
```

**Comment by mboelen** [comment]
Thanks. Implemented using commit https://github.com/CISOfy/lynis/commit/cb59e924417fb1b18a8c2af5200c7359550ae92c
