### ISSUE TITLE
RHEL 6 - /bin/lsblk: unrecognized option '--paths' doing Cryptography checks

### ISSUE THREAD

**Issue by daniejstriata** [CISOfy/lynis#781]
**Describe the bug**
Running Lynis on RHEL 6.10 I see under "[+] Cryptography" the following:

```
[+] Cryptography
------------------------------------
- Checking for expired SSL certificates [0/23] [ NONE ]
/bin/lsblk: unrecognized option '--paths'

Usage:
 lsblk [options] [<device> ...]

Options:
 -a, --all            print all devices
 -b, --bytes          print SIZE in bytes rather than in human readable format
 -d, --nodeps         don't print slaves or holders
 -D, --discard        print discard capabilities
 -e, --exclude <list> exclude devices by major number (default: RAM disks)
 -I, --include <list> show only devices with specified major numbers
 -f, --fs             output info about filesystems
 -h, --help           usage information (this)
 -i, --ascii          use ascii characters only
 -m, --perms          output info about permissions
 -l, --list           use list format ouput
 -n, --noheadings     don't print headings
 -o, --output <list>  output columns
 -P, --pairs          use key="value" output format
 -r, --raw            use raw output format
 -s, --inverse        inverse dependencies
 -t, --topology       output info about topology
 -V, --version        output version information and exit

Available columns (for --output):
        NAME  device name
       KNAME  internal kernel device name
     MAJ:MIN  major:minor device number
      FSTYPE  filesystem type
  MOUNTPOINT  where the device is mounted
       LABEL  filesystem LABEL
        UUID  filesystem UUID
          RA  read-ahead of the device
          RO  read-only device
          RM  removable device
       MODEL  device identifier
        SIZE  size of the device
       STATE  state of the device
       OWNER  user name
       GROUP  group name
        MODE  device node permissions
   ALIGNMENT  alignment offset
      MIN-IO  minimum I/O size
      OPT-IO  optimal I/O size
     PHY-SEC  physical sector size
     LOG-SEC  logical sector size
        ROTA  rotational device
       SCHED  I/O scheduler name
     RQ-SIZE  request queue size
        TYPE  device type
    DISC-ALN  discard alignment offset
   DISC-GRAN  discard granularity
    DISC-MAX  discard max bytes
   DISC-ZERO  discard zeroes data

For more details see lsblk(8).
- Kernel entropy is sufficient [ NO ]
```
![image](https://user-images.githubusercontent.com/13314239/66564433-4647a900-eb60-11e9-9edb-44d90e77592c.png)

**Version**
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.10 (Santiago)
Release:	6.10
Codename:	Santiago
Lynis: 3.0.0

**Expected behavior**
I'm not sure what the Cryptography check is using lsblk for as I'm not seeing this in the logs. The RHEL 6 version is probably too old.

**Comment by Schmuuu** [comment]
Hi,

I have an idea how to fix this issue:
File:  lynis/include/tests_crypto - line 142 and 143:
```
for BLOCK_DEV in $(${LSBLKBINARY} --noheadings --list -o NAME 2> /dev/null | cut -d' ' -f1); do
                if ${CRYPTSETUPBINARY} isLuks $(${FINDBINARY} /dev/ -name ${BLOCK_DEV} 2> /dev/null) 2> /dev/null; then
```

@daniejstriata Would you like to test this code changes?

At all: Any thoughts about this? Could this be sufficiant solution? If yes, I could create a pull request later.

**Comment by Schmuuu** [comment]
Hi, 

I just created a pull request already. I'm very positive this will work on all older systems without the --paths option in lsblk.
Feel free to test @daniejstriata  :)

**Comment by daniejstriata** [comment]
@Schmuuu I ran a new report on the server with latest pulled version and got the same on RHEL 6.10:

```
DEBUG] Performing test ID CRYP-7930 (Determine if system uses LUKS block device encryption)
/bin/lsblk: unrecognized option '--paths'

Usage:
 lsblk [options] [<device> ...]

Options:
 -a, --all            print all devices
 -b, --bytes          print SIZE in bytes rather than in human readable format
 -d, --nodeps         don't print slaves or holders
 -D, --discard        print discard capabilities
 -e, --exclude <list> exclude devices by major number (default: RAM disks)
 -I, --include <list> show only devices with specified major numbers
 -f, --fs             output info about filesystems
 -h, --help           usage information (this)
 -i, --ascii          use ascii characters only
 -m, --perms          output info about permissions
 -l, --list           use list format ouput
 -n, --noheadings     don't print headings
 -o, --output <list>  output columns
 -P, --pairs          use key="value" output format
 -r, --raw            use raw output format
 -s, --inverse        inverse dependencies
 -t, --topology       output info about topology
 -V, --version        output version information and exit

Available columns (for --output):
        NAME  device name
       KNAME  internal kernel device name
     MAJ:MIN  major:minor device number
      FSTYPE  filesystem type
  MOUNTPOINT  where the device is mounted
       LABEL  filesystem LABEL
        UUID  filesystem UUID
          RA  read-ahead of the device
          RO  read-only device
          RM  removable device
       MODEL  device identifier
        SIZE  size of the device
       STATE  state of the device
       OWNER  user name
       GROUP  group name
        MODE  device node permissions
   ALIGNMENT  alignment offset
      MIN-IO  minimum I/O size
      OPT-IO  optimal I/O size
     PHY-SEC  physical sector size
     LOG-SEC  logical sector size
        ROTA  rotational device
       SCHED  I/O scheduler name
     RQ-SIZE  request queue size
        TYPE  device type
    DISC-ALN  discard alignment offset
   DISC-GRAN  discard granularity
    DISC-MAX  discard max bytes
   DISC-ZERO  discard zeroes data

For more details see lsblk(8).

```

**Comment by Schmuuu** [comment]
Hi @daniejstriata 

My code changes have not been pulled yet, To test, you could either make a backup and edit the file includes/tests_crypto with this content:
https://github.com/CISOfy/lynis/blob/62419033f5049a39e177953a54e180bfe0123211/include/tests_crypto
or you could download my repo into a new folder folder testing:
https://github.com/Schmuuu/lynis/tree/crypto/fix-lsblk-check

If you clone the repo, please make sure you run 
`git checkout crypto/fix-lsblk-check`
to switch to the correct branch.

**Comment by daniejstriata** [comment]
Hi, seems to work:


[+] Cryptography
------------------------------------
[DEBUG] Performing test ID CRYP-7902 (Check expire date of SSL certificates)
  - Checking for expired SSL certificates [0/12]              [ NONE ]
[DEBUG] Performing test ID CRYP-7930 (Determine if system uses LUKS block device encryption)
[DEBUG] Performing test ID CRYP-8002 (Gather available kernel entropy)
  - Kernel entropy is sufficient

**Comment by Schmuuu** [comment]
Thanks a lot for testing and I'm glad to see there are no more error messages so far.

Could you run:
`./lynis show details CRYP-7930`

and post the output here as well? It should show the log content for the test in question.

**Comment by daniejstriata** [comment]
# ./lynis show details CRYP-7930

2019-10-23 11:48:45 Performing test ID CRYP-7930 (Determine if system uses
LUKS block device encryption)
2019-10-23 11:48:45 Result: block device sr0 is not LUKS encrypted
2019-10-23 11:48:45 Result: block device sda is not LUKS encrypted
2019-10-23 11:48:45 Result: block device sda1 is not LUKS encrypted
2019-10-23 11:48:45 Result: block device sdb is not LUKS encrypted
2019-10-23 11:48:45 Result: block device sdc is not LUKS encrypted
2019-10-23 11:48:45 Result: block device sdd is not LUKS encrypted
2019-10-23 11:48:45 Result: block device sdd1 is not LUKS encrypted
2019-10-23 11:48:45 Result: block device vgroup1-LVmysql is not LUKS
encrypted
2019-10-23 11:48:45 Result: block device vgroup1-LVvarStriata is not LUKS
encrypted
2019-10-23 11:48:45 Result: block device vgroup1-LVusrlocal is not LUKS
encrypted
2019-10-23 11:48:45 Result: block device vgroup1-LVvarlocal is not LUKS
encrypted
2019-10-23 11:48:45 Result: block device sde is not LUKS encrypted
2019-10-23 11:48:45 Result: block device sde1 is not LUKS encrypted
2019-10-23 11:48:45 Result: block device vgroup1-LVmysql is not LUKS
encrypted
2019-10-23 11:48:45 Result: block device vgroup1-LVvarStriata is not LUKS
encrypted
2019-10-23 11:48:45 Result: block device vgroup1-LVvarlocal is not LUKS
encrypted
2019-10-23 11:48:45 Result: block device sdf is not LUKS encrypted
2019-10-23 11:48:45 Result: block device sdf1 is not LUKS encrypted
2019-10-23 11:48:45 Result: block device vgroup1-LVmysql is not LUKS
encrypted
2019-10-23 11:48:45
===---------------------------------------------------------------===

**Comment by Schmuuu** [comment]
Awesome! Thanks a lot for testing! 

So in my opinion this issue is fixed and we only need to wait until the code changes are pulled into the master.
