### ISSUE TITLE
[DBS-1828] POSTGRESQL_RUNNING: parameter not set

### ISSUE THREAD

**Issue by church1e** [CISOfy/lynis#782]
**Describe the bug**
Running `lynis audit system --profile developer.prf` returns `POSTGRESQL_RUNNING: parameter not set` and aborts the remainder of the audit.

**Version**
 - Distribution Ubuntu 18.10, 19.04 and 19.10 (dev branch)
 - Lynis version 3.0.0 (git pull)

**Expected behavior**
Test DBS-1828 to complete without errors.

**Output**
From output, we see:
```
[DEBUG] Performing test ID DBS-1826 (Checking active PostgreSQL processes)
  - PostgreSQL processes status                               [ NOT FOUND ] [DEBUG]                                                                               
./lynis: 194: /data/src/lynis/include/tests_databases: POSTGRESQL_RUNNING: parameter not set
```

**Additional context**
In file `<installdir>/include/tests_databases` line 172 [DBS-1826] sets the variable `POSTGRESQL_RUNNING=1` if postgres is running. But this variable is not set anywhere else within the Lyis codebase.

In file `<installdir>/include/tests_databases` line 194 [DBS-1828] checks if the variable `POSTGRESQL_RUNNING` -eq 1. Here is where Lynis falls over as the variable has not been previously set.

In `<installdir>include/consts` line 227 we see the variable `POSTGRES_RUNNING` but this variable is not references anywhere else in the Lynis codebase.

If we change the variable name to `POSTGRESQL_RUNNING` then rerun the audit, test DBS-1828 completes successfully.

**Comment by mboelen** [comment]
Solved by pull request of @katkad  https://github.com/CISOfy/lynis/pull/787
