### ISSUE TITLE
incorrect text related to INSE-8314 / NIS Check

### ISSUE THREAD

**Issue by daniejstriata** [CISOfy/lynis#786]
The check INSE-8314 is finding an installed NIS client. It is suggesting that NIS has been replaced "with the more secure SSH package"? I fail to see the link between SSH and NIS/YP as they are a directory service and SSH is a network protocol. Binding Linux and BSD to a domain uses some directory service like LDAP.

INSE-8314 | Suggestion | NIS client should be removed as it contains numerous security exposures and have been replaced with the more secure SSH package
-- | -- | --

**Version**
 - Distribution - Centos 7.7
 - Lynis version - 3.0.0

**Comment by mboelen** [comment]
Thanks for reporting. Resolved with commit https://github.com/CISOfy/lynis/commit/c4b24c48a97acd98bb94fccbd4691a777553c350
