### ISSUE TITLE
RHEL 6 - ImportError: No module named yum

### ISSUE THREAD

**Issue by daniejstriata** [CISOfy/lynis#789]
**Describe the bug**
Somewhere doing the yum checks on RHEL 6.10 I see the following:
```
- Checking missing security packages [ OK ]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named yum

```
![image](https://user-images.githubusercontent.com/13314239/66840407-47197a00-ef68-11e9-9595-a249436fc91a.png)

I do not find any reference to this looking in the Lynis logs though so I'm not exactly sure what is failing. This does not happen on Centos 7.7.

**Version**
 - Distribution [RHEL 6.10]
 - Lynis version [3.0.0]

I have installed:
```
yum-utils-1.1.30-42.el6_10.noarch
yum-3.2.29-81.el6.noarch
yum-metadata-parser-1.1.2-16.el6.x86_64
yum-rhn-plugin-0.9.1-60.2.el6_8.noarch
yum-plugin-security-1.1.30-42.el6_10.noarch
```

**Comment by mboelen** [comment]
Run Lynis with --verbose and --debug to see which test is the one causing it. Most likely it is a yum thing, as that is executed.

Also, you could compare the yum components on your CentOS 7 system, to see if that has any differences?

**Comment by Schmuuu** [comment]
Hi,

This issue seems to be cause by this line:
https://github.com/CISOfy/lynis/blob/c16133b25545078e166ba05c10b2f53cfd88bbd4/include/tests_ports_packages#L948

Executing `python -c 'import yum'` to double check shows a similar output. 
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'yum'
```
Unfortunately I know nothing about Python, so I don't have an idea what this import is about and how to fix that. Hopefully my finding helps :)

**Comment by daniejstriata** [comment]
Thanks for that. It could be that the check is Python 2.7 specific. RHEL 6
only has Python 2.6. I will check on Monday.
*Danie de Jager* * • * *Security Analyst* * • * *Striata*
*T.* *+27 011 5309600* * | * *www.striata.com
<https://www.striata.com/?utm_source=email&utm_medium=striataEmailFooter&utm_campaign=daniede+jager>*

**Comment by daniejstriata** [comment]
I pulled the latest version and ran with debug and verbose:

```
DEBUG] Performing test ID PKGS-7386 (Check for YUM security package)
  - Checking missing security packages                        [ OK ]

  [WARNING]: Test PKGS-7386 had a long execution: 10.390923 seconds

[DEBUG] Performing test ID PKGS-7387 (Check for GPG signing in YUM security package)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named yum
  - Checking GPG checks (yum.conf)                            [ OK ]
[DEBUG] Performing test ID PKGS-7398 (Check for package audit tool)
  - Checking package audit tool                               [ INSTALLED ]
    Found: yum-security
[DEBUG] Performing test ID PKGS-7410 (Count installed kernel packages)
[DEBUG] Performing test ID PKGS-7420 (Detect toolkit to automatically download and apply upgrades)

```

**Comment by Schmuuu** [comment]
So you tested with the other Python version now and the result is, that there is no difference between Python 2.6 and 2.7?

**Comment by daniejstriata** [comment]
Hi,

I have Python 2.7 running from
/usr/local/bin/python2

and Python 2.6 from:
/usr/bin/python2

I'm not exactly sure how Python is used in this test. So from any other
"default RHEL 6" installation you won't have Python 2.7 as it is not
available unless your compile it. Therefore on RHEL 6 the test will always
fail.

**Comment by mboelen** [comment]
I had a look at this issue, but can't reproduce it. What happens is that we import yum and check the repositories. For each enabled repo we look at its settings, and GPG signing in particular.

Might be specific to this system and its configuration. As we can't reproduce it currently, I will close this issue. If it is reported more often, we can reopen it.
