### ISSUE TITLE
Debian Bullseye: "unexpected operator" in Checking core dumps configuration

### ISSUE THREAD

**Issue by SantosSi** [CISOfy/lynis#791]
Running the newest code from Github, version 3.0.0, in the step 

> Checking core dumps configuration

before 

>    - configuration in systemd conf files

the command line interface puts out:

> ./lynis: 476: [: -ge: unexpected operator
> ./lynis: 477: [: -ge: unexpected operator
> ./lynis: 478: [: -ge: unexpected operator

My humble comment:
Having a quick look at the code lines listed above the syntax in includes/tests_kernel seems to be OK overall with one exception: if the variables, e.g. ${SYSD_CORED_BASE_PROCSIZEMAX_NR_ENABLED} are empty, the syntax is broken. A pair of "" would resolve at least that syntax issue.
But supposedly the problem is a logical one somewhere else by erroneously not having filled the variables.

**Comment by Schmuuu** [comment]
Hello,

Yes, that was my mistake. I forgot a commit when creating the pull request :see_no_evil: 
I created another pull request for that which should fix it:
https://github.com/CISOfy/lynis/pull/790

Sorry!

**Comment by SantosSi** [comment]
Resolved, thanks.
