### ISSUE TITLE
Crypto: Check for TRNG and rngd

### ISSUE THREAD

**Issue by pyllyukko** [CISOfy/lynis#793]
**Is your feature request related to a problem? Please describe.**
Lynis could check for existence of TRNG and whether `rngd` is running.

**Describe the solution you'd like**
* Check that `/sys/class/misc/hw_random/rng_current` value is not "none"
* Check that `rngd` is running and utilizing the TRNG

**Required changes**
* [x] Assign `CRYP` ID (CRYP-8004)
* [ ] Assign potential hardening points
* [ ] Implement a test for this

**Additional context**
Somewhat relates to #751

**Comment by mboelen** [comment]
Sounds like a good change. Want to submit an initial pull request for this?

Suggested CRYP id = CRYP-8004

**Comment by pyllyukko** [comment]
> Sounds like a good change. Want to submit an initial pull request for this?

Sure.

**Comment by mboelen** [comment]
Implemented with pull request #821
