### ISSUE TITLE
NTP_CONFIG_FOUND is never set

### ISSUE THREAD

**Issue by liedekef** [CISOfy/lynis#794]
In the file include//tests_time the parameter NTP_CONFIG_FOUND gets initialized at 0 and later on reported (ntp_config_found). But it never gets set, so this always stays at 0, even if /etc/ntp.conf is indeed found. I believe the check TIME-3170 should set this if appropriate.

**Comment by mboelen** [comment]
Merged related pull request by @Schmuuu
