### ISSUE TITLE
HTTP-6640 and HTTP-6641 do not find modules

### ISSUE THREAD

**Issue by SchwarzerA** [CISOfy/lynis#807]
Function "CheckItem" searches in ${REPORTFILE} whereas HTTP-6632 puts its findings into ${LOGFILE}. Hence the message that mod_evasive24.so and mod_sewcurity2 could not be found.

openSUSE Tumbleween, Leap 15.1
Lynis 3.0.0

Modules are active and should be found.

  Suggestions (3):
  ----------------------------
  * Install Apache mod_evasive to guard webserver against DoS/brute force attempts [HTTP-6640]
      https://cisofy.com/lynis/controls/HTTP-6640/

  * Install Apache mod_reqtimeout or mod_qos to guard webserver against Slowloris attacks [HTTP-6641]
      https://cisofy.com/lynis/controls/HTTP-6641/

  * Install Apache modsecurity to guard webserver against web application attacks [HTTP-6643]
      https://cisofy.com/lynis/controls/HTTP-6643/

**Comment by mboelen** [comment]
Hi @SchwarzerA - I had a look and see that HTTP-6632 does collect the information and stores them in the report (Report "apache_module[]=${ITEM}").

Can you show me the `apache_module[]` lines from your lynis-report.dat file?

**Comment by SchwarzerA** [comment]
I remember that Michael and me had a conversation about the topic and it was solved at that time. So there is no need to keep it active anymore.
