### ISSUE TITLE
[2.7.5] Lynis version check error Centos 8

### ISSUE THREAD

**Issue by arafatx** [CISOfy/lynis#808]
**Describe the bug**
The latest version is 2.7.5 and the current version also 2.7.5 but lynis still ask to upgrade.

**Version**
  Program version:           2.7.5
  Operating system:          Linux
  Operating system name:     CentOS
  Operating system version:  CentOS Linux release 8.0.1905 (Core)
  Kernel version:            5.1.17

**Output**
` Current version is more than 4 months old

        Current version : 275   Latest version : 275

        Please update to the latest version.
        New releases include additional features, bug fixes, tests, and baselines.
`

![image](https://user-images.githubusercontent.com/4420157/67778608-6226d680-fa9e-11e9-9b4c-7b6cae3e7f04.png)

**Comment by daniejstriata** [comment]
The same version check issue pops up with version 3.

```
      ===============================================================================
        Lynis update available
      ===============================================================================

        Current version is more than 4 months old

        Current version : 300   Latest version : 275

```

**Comment by mboelen** [comment]
Related commit that fixes this for the upcoming release (and version on GitHub): https://github.com/CISOfy/lynis/commit/61b78c1cf3d9d5fa4f5bf968063e3931be336572
