### ISSUE TITLE
Empty iptables ruleset not detected when fail2ban is installed

### ISSUE THREAD

**Issue by rhyven** [CISOfy/lynis#81]
The detection method in include/tests_firewall will not detect an empty ruleset when fail2ban is installed.  This is caused by fail2ban inserting an extra chain, which makes FIRE-4513 return a "1":

Here's my iptables list, with fail2ban installed:  

    root@FFF-BASE:~/lynis# iptables --list --numeric
    Chain INPUT (policy ACCEPT)
    target     prot opt source               destination         
    
    Chain FORWARD (policy ACCEPT)
    target     prot opt source               destination         
    
    Chain OUTPUT (policy ACCEPT)
    target     prot opt source               destination         
    
    Chain fail2ban-ssh (0 references)
    target     prot opt source               destination         
    RETURN     all  --  0.0.0.0/0            0.0.0.0/0

**Comment by mboelen** [comment]
Patch have been applied to show the warning if a rule set contains 10 rules or less. This should catch more configurations which have some rules, but are clearly not configured.

Closing issue. Feel free to reopen if not working as expected. Thanks for sharing!
