### ISSUE TITLE
Question: TCP/IP Stack OS Fingerprint - sysctl hardending possible?

### ISSUE THREAD

**Issue by 0pLuS0** [CISOfy/lynis#814]
Hello,

Since Lynis offers sysctl information to help improve kernel hardening through sysctl.conf options, I wanted to know if it's possible also through sysctl to spoof the TCP/IP Stack OS Fingerprint?

From information I read online; ```net.ipv4.ip_default_ttl=``` has, or had the ability to do this, I'm not sure, maybe this was with older kernels.

It was my understanding that by changing the TTL to a different number it would spoof the OS 128 or 64 as example I read would make the system show up as Windows instead of Linux.

Is it possible to spoof the TCP/IP Stack with a different OS reply through sysctl?

If this is possible it would be nice to see options like this in a future release of Lynis.

THANKS

**Comment by TheFlipside** [comment]
If I understand your request correctly you would like to see lynis suggest for the mentioned sysctl value something set which might spoof the OS fingerprint.

In my opinion something like this does not offer real system hardening/security, it's more a case of security through obscurity which I never felt the lynis project was aiming for. From my feeling lynis aims to provide information about real measurements to make a system more secure.

It's still open for anyone to set that sysctl if it makes them feel their system gets more secure from it but a suggestion from an audit tool like lynis would be out of place imho.

Btw I think this is more a feature request than a bug report.

**Comment by 0pLuS0** [comment]
I'm certainly not into security through obscurity... LOL

I'm into real security, and I actually thought that ```net.ipv4.ip_default_ttl=``` was a real solution?

THANKS

**Comment by mboelen** [comment]
Nothing wrong with spoofing things, as long as you are familiar with the downsides. I agree with @TheFlipside (hardening aspect and feature request).

At this moment we are working on the 3.x release and this specific request would get low priority as it is more a feature request than an actual issue. For that reason, I will close this issue.
