### ISSUE TITLE
Please update to the latest version when using the latest version

### ISSUE THREAD

**Issue by crylium** [CISOfy/lynis#816]
**Describe the bug**
Please update to the latest version advice given when using the latest version.

**Version**
 - Distribution [Debian 9.11]
 - Lynis version [2.7.5]

**Expected behavior**
There should be no update required when using the latest version.

**Output**
        Lynis update available
        Current version is more than 4 months old
        Current version : 275   Latest version : 275
        Please update to the latest version.

**Comment by mboelen** [comment]
Known issue (see https://github.com/CISOfy/lynis/issues/808), will be fixed soon with a new release.
