### ISSUE TITLE
i need little help about installation...

### ISSUE THREAD

**Issue by azamet90** [CISOfy/lynis#817]
im using kali linux and this was preinstalled on my distro... 
how to update it so that i can run this tool direct from terminal anywhere i want same like the preinstalled version?

**Comment by quantumpacket** [comment]
You can use the package repository to get new updates instead of waiting on the distro.. https://packages.cisofy.com/community/ Add the repo to APT and then upgrade.

**Comment by mboelen** [comment]
Closing issue as I agree with @quantumpacket :)
