### ISSUE TITLE
 [KRNL-5830:4]  Could not find the kernel version

### ISSUE THREAD

**Issue by roelandjansen** [CISOfy/lynis#818]
**Describe the bug**

  Exception found!
  Function/test:  [KRNL-5830:4]
  Message:        Could not find the kernel version

**Version**
opensuse 15.1 64 bit
lynis: at commit 09740e0debb410e2b8de55fcc30add6cdbc32ad8

**Expected behavior**
it should find kernel version

**Output**
  Exception found!

  Function/test:  [KRNL-5830:4]
  Message:        Could not find the kernel version

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (./lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

  let me know what part of the logs you need.

**Comment by roelandjansen** [comment]
Linux taplop 4.12.14-lp151.28.36-default #1 SMP Fri Dec 6 13:50:27 UTC 2019 (8f4a495) x86_64 x86_64 x86_64 GNU/Linux

**Comment by roelandjansen** [comment]
with ./lynis audit system -q --wait

/home/roeland/src/lynis/include/tests_kernel: line 668: [: argument expected

is shown

**Comment by Schmuuu** [comment]
Hi,

Can you please also show the output of
```
ls -l /boot/
```

**Comment by roelandjansen** [comment]
roeland@taplop:~/src/lynis> ls -l /boot/
total 75519
-rw-r--r-- 1 root root     1725 Jul 13 18:12 boot.readme
-rw-r--r-- 1 root root   200048 Nov 13 09:03 config-4.12.14-lp151.28.32-default
-rw-r--r-- 1 root root   200048 Dec  6 17:35 config-4.12.14-lp151.28.36-default
drwxr-xr-x 6 root root     1024 Dec 12 18:05 grub2
lrwxrwxrwx 1 root root       34 Dec 12 18:00 initrd -> initrd-4.12.14-lp151.28.36-default
-rw------- 1 root root 17187960 Dec  4 22:12 initrd-4.12.14-lp151.28.32-default
-rw------- 1 root root 17189904 Dec 12 18:01 initrd-4.12.14-lp151.28.36-default
drwx------ 2 root root    12288 May 25  2018 lost+found
-rw-r--r-- 1 root root   422912 May 24  2019 message
-rw-r--r-- 1 root root  1180761 Nov 13 11:20 symtypes-4.12.14-lp151.28.32-default.gz
-rw-r--r-- 1 root root  1180915 Dec  6 18:08 symtypes-4.12.14-lp151.28.36-default.gz
-rw-r--r-- 1 root root   407318 Nov 13 11:09 symvers-4.12.14-lp151.28.32-default.gz
-rw-r--r-- 1 root root   407424 Dec  6 18:08 symvers-4.12.14-lp151.28.36-default.gz
-rw-r--r-- 1 root root      484 Nov 13 11:09 sysctl.conf-4.12.14-lp151.28.32-default
-rw-r--r-- 1 root root      484 Dec  6 18:08 sysctl.conf-4.12.14-lp151.28.36-default
-rw-r--r-- 1 root root  3640821 Nov 13 10:41 System.map-4.12.14-lp151.28.32-default
-rw-r--r-- 1 root root  3641765 Dec  6 18:04 System.map-4.12.14-lp151.28.36-default
-rw-r--r-- 1 root root  8340236 Nov 13 11:42 vmlinux-4.12.14-lp151.28.32-default.gz
-rw-r--r-- 1 root root  8343364 Dec  6 18:12 vmlinux-4.12.14-lp151.28.36-default.gz
lrwxrwxrwx 1 root root       35 Dec 12 18:00 vmlinuz -> vmlinuz-4.12.14-lp151.28.36-default
-rw-r--r-- 1 root root  7319664 Nov 13 12:58 vmlinuz-4.12.14-lp151.28.32-default
-rw-r--r-- 1 root root  7323760 Dec  6 18:46 vmlinuz-4.12.14-lp151.28.36-default

**Comment by XVicarious** [comment]
The problem is from 11f8ce236165bd650515f3141f3dea1ed1fb8baa, where on line 668 an extra `-o` was added to the test command like there was supposed to be another check there.

**Comment by cfeedback** [comment]
Just wanted to confirm same problem running Arch 5.4.6 and yes removing the "-o" fixed the issue.

**Comment by mboelen** [comment]
Made several changes, including fixing that "-o" error. Tested on Tumbleweed and looks to be working now.
