### ISSUE TITLE
[KRNL-5820] Page does not exist

### ISSUE THREAD

**Issue by robo2bobo** [CISOfy/lynis#819]
**Describe the bug**

The suggestion for NRNL-5820 points to a URL that does not exist:

```
  * If not required, consider explicit disabling of core dump in /etc/security/limits.conf file [KRNL-5820] 
      https://cisofy.com/lynis/controls/KRNL-5820/
```

The URL comes up with:

```
A new discovery!

Oops, looks like this control is not listed yet in the database.
```

**Version**
 - CentOS 8
 - git

**Expected behavior**

The page to give more details about the suggestion KRNL-5820.

**Additional context**

This lead me to issue #801

**Comment by mboelen** [comment]
Thanks for reporting. An initial placeholder has been added.
