### ISSUE TITLE
[FIRE-4512] support for firewalld

### ISSUE THREAD

**Issue by robo2bobo** [CISOfy/lynis#820]
**Describe the bug**
lynis reports the following warning under CentOS 8:

```
  ! iptables module(s) loaded, but no rules active [FIRE-4512] 
      https://cisofy.com/lynis/controls/FIRE-4512/
```

CentOS 8 uses a different firewall structure, the primary "frontend" is now firewalld via the firewall-cmd tool and iptables has been kept as an alternative "frontend" for more complex rules.

**Version**
 - CentOS 8
 - git

**Expected behavior**
Understand the specifics of firewalld and the various XML zone rules under /etc/firewalld/zones/

lynix should be able to read those rules first and the iptables rules second. Then decide if there are really no firewall rules at all.

**Comment by jaydenrussell** [comment]
Same issue with Centos 8.1.1911, FirewallD uses nftables as the backend now.

**Comment by robo2bobo** [comment]
no interest, closing.
