### ISSUE TITLE
[NETW-3015] Incorrectly reports promiscuity with multiple promiscuous processes

### ISSUE THREAD

**Issue by TopherIsSwell** [CISOfy/lynis#825]
**Describe the bug**
Test NETW-3015 (interface promiscuity testing on Linux) looks specifically for the string ```promiscuity 1``` in the output of ```ip -d link```.
Shown here. 
```
include/tests_networking:533:                    FIND=$(${IPBINARY} -o -d link show ${I} 2> /dev/null | ${GREPBINARY} 'promiscuity 1')
```
however the promiscuity property is not a binary flag, it's a count of promiscuous processes. Evidenced in the iproute2 source here:
https://github.com/shemminger/iproute2/blob/master/include/uapi/linux/if_link.h
line 146 as of this writing:
```c
#Define IFLA_PROMISCUITY	/* Promiscuity count: > 0 means acts PROMISC */
```

**Version**
 - Confirmed on Fedora 31 and Centos 7 (but likely all distros that use iproute2 / ip)
 - Lynis version 2.7.5

**To reproduce**
Set the interface manually to promiscuous, and then run tcpdump in the background, this will set promiscuity to 2 and lynis will not flag the interface as promiscuous.
```bash
iface=eth0
ip link set dev $iface promisc on
tcpdump -i $iface > /dev/null &
lynis audit system --tests NETW-3015
kill %1
```

**Expected behavior**
With two promiscuous processes, Lynis would flag the interface as promiscuous.

**Output**
None, the interface is not flagged as promiscuous. 

**Additional context**
I will attempt to make a pull request to fix this soon.

**Comment by mboelen** [comment]
Thanks for reporting! I applied a change to the code that should catch it. Does this work correctly on your system?

https://github.com/CISOfy/lynis/commit/a7b48e40b0ef500b4e0213d2fd23194b1efd3f83

**Comment by TopherIsSwell** [comment]
Tested and works as expected. Promiscuity 2 is detected as promiscuous and reported correctly.

**Comment by mboelen** [comment]
Thanks for confirmation, closing issue.
