### ISSUE TITLE
[TIME-3104] Wrong directory listing is used

### ISSUE THREAD

**Issue by patti2** [CISOfy/lynis#826]
**Describe the bug**
Upon trying to find NTP cronjobs in /etc/cron.hourly, the directory listing of the pwd is used instead of the correct directory listing.

**Version**
 - Distribution: Debian buster
 - Lynis version: 2.7.5

**Expected behavior**
check for ntpdate or rdate in /etc/cron.hourly and not in pwd

**Output**
(each x represents a different file that is not present in /etc/cron.hourly, but rather in the pwd)

> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x
> 2020-01-12 02:29:38 Test: checking for ntpdate or rdate in /etc/cron.hourly/x

**Additional context**
the test works fine in /etc/cron.d, but fails upon entering the /etc/cron.hourly stage.

**Comment by Varbin** [comment]
The code in question is at [line 144 of tests_time](https://github.com/CISOfy/lynis/blob/2.7.5/include/tests_time#L144):
```
        # Check cron jobs
        for I in ${CRON_DIRS}; do
            if [ -d ${I} ]; then
                if FileIsReadable ${I}; then
                    FIND=$(${LSBINARY} ${I} | ${GREPBINARY} -v FIFO)
                    if [ ! -z "${FIND}" ]; then
                        for J in ${FIND}; do
                            LogText "Test: checking for ntpdate or rdate in ${I}/${J}"
                            FIND2=$(${EGREPBINARY} "rdate|ntpdate" ${I}/${J} | ${GREPBINARY} -v "^#")
                            if [ ! -z "${FIND2}" ]; then
                                LogText "Positive match found: ${FIND2}"
                                FOUND=1; FOUND_IN_CRON=1; NTP_CONFIG_TYPE_SCHEDULED=1
                            fi
                        done
                    else
                        LogText "Result: ${I} is empty, skipping search in directory"
                    fi
                else
                    LogText "Result: could not search in directory due to permissions"
                fi
            fi
        done
```

Parsing of `ls` seems do be a general bad idea, as it does not properly escape special characters, as '*' (asterisk), spaces or newlines.
Additionally the file FIFO is not skipped properly as ls returns (at least on Linux) every file in one line.

The reported issue can be reproduced by creating a file '*' in a scanned folder (e.g. `sudo touch '/etc/cron.hourly/*').

**Comment by mboelen** [comment]
Thanks for reporting this. The test has been altered to use find and strip potential unexpected control characters with commit https://github.com/CISOfy/lynis/commit/7e3c9448df1bea8344597bcc4a1732c51430bf1a

@patti2 - Can you confirm this works better?
@Varbin - Can you double-check it does work as expected with unexpected file names?

**Comment by Varbin** [comment]
Will check in the next few days.

**Comment by Varbin** [comment]
@mboelen 

I wrote this script to test your change:

<details>
```bash
#!/bin/sh
export FINDBINARY=find
export SEDBINARY=sed
export TRBINARY=tr
export LSBINARY=ls
export AWKBINARY=awk
export CUTBINARY=cut

export LOGFILE=/dev/stderr
export LOGTEXT=0

. ./functions

mkdir test 2> /dev/null
cd test
touch 'a b' 'a  b' a$'\xe2\x80\x82'b a$'\xe2\x80\x83'b a$'\t'b a$'\n'b
touch '*' a$'\n*'
cd ..

alias LogText="echo"

FIND=$(${FINDBINARY} test/ -type f -a ! -name ".placeholder" -print 2> /dev/null | ${SEDBINARY} 's/ /__space__/g' | ${TRBINARY} '\n' '\0' | ${TRBINARY} -cd '[:print:]\0' | ${TRBINARY} '\0' ' ')

for J in ${FIND}; do
        J=$(echo ${J} | ${SEDBINARY} 's/__space__/ /g')
        if FileIsReadable ${J}; then
                echo "running egrep"
                egrep "rdate|ntpdate" "${J}"
        else
                echo "Result: could not test in file '${J}' as it is not readable"
        fi
done
```
</details>

`functions` is the file from Lynis.
Everything after FIND should be as in 7e3c944, besides discarding 

When I run my script I see following output, what I think should not happen:

<details>
```
Result: could not test in file 'test/a  b' as it is not readable
Result: could not test in file 'test/a b' as it is not readable
Result: could not test in file 'test/a$
b' as it is not readable
Result: could not test in file 'test/a$
* test/a$
b' as it is not readable
Result: could not test in file 'test/a$
b' as it is not readable
Result: could not test in file 'test/a$ b' as it is not readable
running egrep "test/a$\xe2\x80\x82b"
running egrep "test/a$\xe2\x80\x83b"
Result: could not test in file 'test/* test/a  b test/a b test/a$
* test/a$
b test/a$       b test/a$\xe2\x80\x82b test/a$\xe2\x80\x83b' as it is not readable
Result: could not test in file 'test/a b' as it is not readable
Result: could not test in file 'test/a b' as it is not readable
Result: could not test in file 'test/a$
* test/a$
b' as it is not readable
Result: could not test in file 'test/a$
b' as it is not readable
Result: could not test in file 'test/a$ b' as it is not readable
running egrep "test/a$\xe2\x80\x82b"
running egrep "test/a$\xe2\x80\x83b"
```
</details>

On a positive side, the original behaviour is does not occur.

Out of curiosity, what does speak against iterating over '*' in the cron folder, like this:

```
for J in "${FOLDER}"/*; do
        if [ -r "${J}" ]; then
                echo "running egrep \"${J}\""
                egrep "rdate|ntpdate" "${J}"
        else
                echo "Result: could not test in file '${J}' as it is not readable"
        fi
done
```

It is obviously not recursive (the previous `ls` was also not recursive) and works in dash, ksh93 and busybox ash, but would skip parsing `find` or `ls` completely.

**Comment by patti2** [comment]
@mboelen I'm getting this error (besides many "deprecated function" errors from the debian plugin), but the original behaviour has improved, even with the * file.

> grep: /etc/cron.monthly/* /etc/cron.monthly/acct /etc/cron.monthly/debsums /etc/cron.monthly/readahead-monthly: No such file or directory

However, using @Varbin's script I get the same output as him.
