### ISSUE TITLE
Check WIFI connection with autoconnect to unencrypted network

### ISSUE THREAD

**Issue by kisst** [CISOfy/lynis#831]
**Is your feature request related to a problem? Please describe.**
Lynis is more and more often used at endpoints as well, not only server side. 
As a clients ( for convenient ) frequently choose wireless connections over wired, it's worth add a check for saved, network connections which do not use any encryption, and set to automatically connect.
Hence the network across DHCP and routeing makes a large effect on the security of the device, fakeap and other similar type of attacks still have large success rate.

**Describe the solution you'd like**
Create a check for the edge cases as described above.

**Required changes**
Presuming NetworkManager to be in use, a simple parsing in the `/etc/NetworkManager/system-connections` folder with either some magical grep regex awk etc, or `augtool` ( which would be an extra dependency ) 

**Additional context**
Here is a sample with augtool just to showcase :
```
$ sudo augtool print /files/etc/NetworkManager/system-connections/demo-network/connection/type
/files/etc/NetworkManager/system-connections/demo-network/connection/type = "wifi"
$ sudo augtool print /files/etc/NetworkManager/system-connections/demo-network/wifi-security/key-mgmt
/files/etc/NetworkManager/system-connections/demo-network/wifi-security/key-mgmt = "wpa-psk"
```

**Comment by mboelen** [comment]
I like the idea of this request, but also wonder about its complexity (and future maintenance). It should detect a wide range of network managers or preferably a generic method. Is there really no generic option to query WiFi connections?

**Comment by kisst** [comment]
I'm not aware any generic solution,  but can count on one hand the options which cover at least 90% of the users.
 

- NetworkManager
- systemd-networkd
- ConnMan
- netctl
- wicd

I think even the first two should be covering a large enough user-base to worth the effort, and however I'm a bit fun of `sed` `cut` `grep` etc, I'm sure that augeas would be a massive help in both detection and remediation, have a look at the [default lenses](http://augeas.net/stock_lenses.html) they cover a massive section of the config files currently parsed in a less elegant way.

In terms of estimated effort, I would say it should be trivial, let me try to showcase it at least for nm.

**Comment by mboelen** [comment]
Sure, go ahead in that case and which ones you can cover already.
