### ISSUE TITLE
consider a new (ant maybe more frequent) release

### ISSUE THREAD

**Issue by anthraxx** [CISOfy/lynis#832]
Hi,
since the last version 2.7.5 there were 372 commits pushed to master. Would it be possible to get a new release and maybe to more frequent release cycles again like in the past? :cat: 

cheers,
Levente

**Comment by mboelen** [comment]
Hi Levente,

A new release will be planned soon. As this is a major upgrade, there is a lot of time between last and this release. More regular releases are planned after 3.0.0 became available.
