### ISSUE TITLE
NETW-3032 and NETW-3015 are mutually exclusive on Linux

### ISSUE THREAD

**Issue by TopherIsSwell** [CISOfy/lynis#834]
**Describe the bug**
This was briefly discussed in NETW-3032 and NETW-3015 are mutually exclusive on Linux. NETW-3032 recommends having an ARP monitoring software such as arpwatch (which puts an interface into promiscuous mode). NETW-3015 docks you for having promiscuous interfaces. 
This has been discussed briefly in https://github.com/CISOfy/lynis/issues/710 and I can accept that security is not a sliding scale, but a set of tradeoffs, but hear me out. 

**Version**
 - Distribution RHEL 7.7
 - Lynis version 2.7.5

**Expected behavior**
The NETW-3015 test would check to see if arpon or arpwatch were the only promiscuous processes on the interface, and not count as a test failure if they are. However, I don't know of a reliable way to determine this other than to check if /usr/sbin/arpwatch or arpon is running and the interface promiscuity counter is only 1 (the kernel logs an ANOM_PROMISCUOUS message to the audit log that provides the uid/gid of the process, however, the uid/gid is root when Arpwatch turns the interface into promiscuous mode, so the only thing that can be detected here is when arpwatch turns off and the audit message is logged as it's own uid).

I realize this is an opinion, so I'm open to discussion. I feel that promiscuity checking is important, but I've seen folks that SKIP-TEST on NETW-3015 or whitelist the interface in question because they've installed arpwatch and want a configuration with no warnings on the baseline. But then they're blind to any new processes listening promiscuously. 

**Output**
#### Option 1:
warning[]=NETW-3015|Found promiscuous interface|eth0|text:Determine if this mode is required or whitelist interface in profile|
arpwatch_running=1
#### Option 2:
suggestion[]=NETW-3032|Consider running ARP monitoring software (arpwatch,arpon)|-|-|
arpwatch_running=0

**Additional context**
If you're amiable to passing NETW-3015 if Promiscuity = 1 and a process named /usr/sbin/arpwatch or arpon is running, I can make a pull request.

**Comment by TopherIsSwell** [comment]
Forgive me, this appears to be fixed in 3.0.0

**Comment by mboelen** [comment]
Closing issue due to the previous remark of @TopherIsSwell that it is already fixed.
