### ISSUE TITLE
auditor-Flag ignored

### ISSUE THREAD

**Issue by SoftCreatR** [CISOfy/lynis#836]
**Describe the bug**

The `--auditor` flag seems to be ignored.

**Version**
 - Debian 10
 - 3.0.0

**Expected behavior**

```
$ lynis audit system --quick --auditor "Foo"

[...]

  ---------------------------------------------------
  Auditor:                   Foo

[...]
```

**Output**

```
# Lynis Report
report_version_major=1
report_version_minor=0
report_datetime_start=2020-02-06 16:44:34
auditor=[Not Specified]
lynis_version=3.0.0
os=Linux
os_name=Debian
os_fullname=Debian 10.2
os_version=10.2
linux_version=Debian
os_kernel_version=4.19.0
....
```

**Comment by mboelen** [comment]
Using the latest version I can't reproduce this. When using your command, I see "Foo" (without quotes) both in the screen output and in the report file.

When did you git clone or pull the latest version? Is it possible that you have Lynis also installed from a package AND have a git cloned version?

**Comment by SoftCreatR** [comment]
> When did you git clone or pull the latest version?

Yesterday.

> Is it possible that you have Lynis also installed from a package

After noticing this issue, i've removed the Clone (v.3.0.0) and installed it from the Customer Repository (v.2.7.5).

The older version doesn't seem to ignore that flag.

**Comment by Schmuuu** [comment]
I don't have a Debian and could only test the latest lynis version on Raspbian, but it is working here. The auditor is shown in the direct output of lynis on stdout and also in the log and report.dat

```
./lynis audit system --auditor "Peter Maier"
...
  ---------------------------------------------------
  Program version:           3.0.0
  Operating system:          Linux
  Operating system name:     Raspbian
  Operating system version:  10.2
  Kernel version:            4.19.75
  Hardware platform:         armv7l
  Hostname:                  raspberrypi
  ---------------------------------------------------
  Profiles:                  /home/pi/Development/lynis_CISOfy/default.prf
  Log file:                  /tmp/lynis.log
  Report file:               /tmp/lynis-report.dat
  Report version:            1.0
  Plugin directory:          ./plugins
  ---------------------------------------------------
  Auditor:                   Peter Maier
  Language:                  en
  Test category:             all
```

``` 
grep -i auditor /tmp/lynis*
/tmp/lynis.log:2020-02-06 19:37:05 Auditor:                   Peter Maier
/tmp/lynis-report.dat:auditor=Peter Maier
```

I ran the script as unprivileged and as root user. 

@SoftCreatR are there any error messages in the lynis.log?

**Comment by SoftCreatR** [comment]
2.7.5:

```
grep -i auditor /var/log/lynis*
grep: /var/log/lynis: Is a directory
/var/log/lynis.log:2020-02-06 20:13:59 Auditor:                   Peter Maier
/var/log/lynis-report.dat:auditor=Peter Maier
```

3.0.0:

```
grep: /var/log/lynis: Is a directory
/var/log/lynis.log:2020-02-06 20:14:13 Auditor:                   [Not Specified]
/var/log/lynis-report.dat:auditor=[Not Specified]
```

No errors so far. But i'll perform a cleanup, check it out and try again.

**Comment by SoftCreatR** [comment]
Just a quick heads up: It seems to work now. No idea, why it didn't before, but now it definitely does. Sorry for the false alarm then :)
