### ISSUE TITLE
PackageIsInstalled() With no package manager.

### ISSUE THREAD

**Issue by jsrc27** [CISOfy/lynis#841]
Hi I mostly work on embedded devices specifically running embedded Linux distributions. 

I am interested in using lynis as the centerpiece for a simple security type tooling. Fortunately the lynis scan for the most part just works on the specific embedded Linux distro I'm using.

However one of the biggest parts that doesn't work is the `PackageIsInstalled()` function. This is due to most embedded Linux distributions being fairly lightweight meaning no real package manager which this function relies on. This of course causes several exceptions in the end report whenever this function is invoked.

Has there been any thoughts/discussion on making this function work on a distro with no package manager?

**Comment by mboelen** [comment]
Thanks for pointing this out. Looks something we should discuss :)

Can you share a bit more about what OS you are using? Maybe we can add proper detection and disable particular tests if there is no package manager available.

**Comment by jsrc27** [comment]
Sure thing, thanks for considering this.

The OS I'm using is a custom embedded OS built using the Yocto project. It's rather minimal feature wise. Other than basic Linux utilities it has a container runtime in the form of Docker and an OTA update client with OSTree.

While the idea is that people would keep most things within a container similar to Fedora CoreOS. There are still of course some configurations that would need to be done on the base system itself, which leaves things open for people to make somewhat questionable security decisions.

As for possible solutions, one that comes to mind and would work for most Yocto built OSes would be the ability to read a build manifest. To clarify all Yocto builds produce a manifest text file of all packages included in the final binary image. This would probably be the most generic solution.

Though of course I'm open to other suggestions/ideas.

I've accepted I might need to create a fork to support things more specific to my OS, but I would like to try to at least upstream all/most changes if possible. 😄

**Comment by bginsbach** [comment]
The `IsPackageInstalled` function for the most part assumes a Linux system with a package manager. It does not work with the various BSD systems that don't use package management for base OS components. As an example NetBSD installs `inetd` as part of the base OS so it is not a tracked package. The `IsPackageInstalled` function needs a lot of work to properly function on BSD systems.

**Comment by mboelen** [comment]
Hi @jsrc27 and @bginsbach - I've applied a change to the `Register` function to optional check if a package manager is needed. If so, and a package manager was not detected, then the test will be skipped. For example in the "insecure services" this is used.

Can you check if errors that were shown due to a missing package manager is resolved for you now?

**Comment by mboelen** [comment]
Related commit = https://github.com/CISOfy/lynis/commit/c368846a08d12901e7de43b525d3e055c7f67508

**Comment by jsrc27** [comment]
For me there is still one "PackageIsInstalled error as shown here:
`PackageIsInstalled:01 (test=PROC-3802)`

**Comment by mboelen** [comment]
> For me there is still one "PackageIsInstalled error as shown here:
> `PackageIsInstalled:01 (test=PROC-3802)`

Thanks @jsrc27 - That one should be fixed now as well.

**Comment by mboelen** [comment]
> The change hides the problem on BSD systems which include services in the base system that are not tracked by a package manager. The "insecure services" tests could still be used on a BSD system with core "insecure services" not tracked by a package manager. An alternative method is needed to determine if a service is present.
> 
> PR #890 fixed issues on NetBSD that were caused by a _missing_ package manager.

Hi @bginsbach - Yes, I know it does not check for "base" components of the operating system. Currently, most of the checks that test for insecure services focus on testing for packages. So it only makes sense to run those tests if there is a package manager. Even although that does not cover all ground (that is all operating systems), it is a start. The next step is to check if we can find inetd and others on the disk (e.g. in search path or as running process). This way we can get everything covered. As you are having in-depth experience on NetBSD and others, I welcome you to look together at the next steps to cover the BSDs even more. Lynis was originally developed on FreeBSD, so I'm the first person that wants to see good coverage for the BSDs.

**Comment by mboelen** [comment]
Closing this issue with the recently applied changes.
