### ISSUE TITLE
[SSH-7408] OpenSSH server version check

### ISSUE THREAD

**Issue by maczniak** [CISOfy/lynis#844]
**Describe the bug**

The intention is to check whether OpenSSH server version >= 5.1, but it tests whether both the major version >= 5 and the minor version >= 1 actually. Then it skips 8.0 version because the minor version (0) < 1.

**Version**
 - Distribution RHEL/CentOS 8 (with OpenSSH 8.0 version)
 - Lynis version 2.7.5

**Expected behavior**

SSH option checks should not skip OpenSSH server versions such as 7.0 and 8.0.

**Output**

**Additional context**

related issue #621

**Comment by mboelen** [comment]
Was closed with pull request.
