### ISSUE TITLE
MAIL-8804 bug

### ISSUE THREAD

**Issue by xianlin** [CISOfy/lynis#848]
In https://github.com/CISOfy/lynis/blob/master/include/tests_mail_messaging#L64 the test ID to be registered should be **MAIL-8804**, not **MAIL-8803**.

 - Redhat 7.4
 - Lynis version 2.7.5

**Comment by mboelen** [comment]
Thanks for reporting, it has been corrected with commit https://github.com/CISOfy/lynis/commit/c0158da38ea4b95c4789b072447a820f288ee2f3
