### ISSUE TITLE
expose_php on but it is off

### ISSUE THREAD

**Issue by damnms** [CISOfy/lynis#849]
**Describe the bug**
When i run lynis master it reports that php_expose is On, which is correct for cli but not for the web version (which is actually used).
It is on in the php.ini in /etc/php/7.3/cli/php.ini, but its Off in /etc/php/7.3/apache2/php.ini and /etc/php/7.3/fpm/php.ini

**Version**
 - Debian 10
 - Lynis version master

**Expected behavior**
no error reported 

**Output**

**Additional context**

**Comment by NicolasCARPi** [comment]
I submitted a PR to fix this issue: https://github.com/CISOfy/lynis/pull/853

**Comment by mboelen** [comment]
Fixed with commit https://github.com/CISOfy/lynis/pull/853
