### ISSUE TITLE
Leaking error messages & warnings

### ISSUE THREAD

**Issue by FlorianHeigl** [CISOfy/lynis#88]
In quiet mode there's a few spurious errors that should not happen.
The warning is by lynis itself, the other message from dnf on fedora.
The dnf one cannot even be suppressed with 2>&1 > /dev/null

```
[demo@fc11 lynis]$ sudo ./lynis -q
    - Checking for password protection                        [ WARNING ]
  - Checking Linux single user mode authentication            [ WARNING ]

Yum-utils package has been deprecated, use dnf instead.
See 'man yum2dnf' for more information.



Yum-utils package has been deprecated, use dnf instead.
See 'man yum2dnf' for more information.


Yum command has been deprecated, redirecting to '/usr/bin/dnf list-sec security'.
See 'man dnf' and 'man yum2dnf' for more information.
To transfer transaction metadata from yum to DNF, run:
'dnf install python-dnf-plugins-extras-migrate && dnf-2 migrate'

No such command: list-sec. Please use /usr/bin/dnf --help
```

I'm aware this also shows a bug in fedora. But I'm trying to build a monitoring & compliance check based on lynis and for that i need to be able to really rely on suppressing output.
(I'm writing to a file and then report the % of hardening_index and lynis_tests_done.

**Comment by kboratynski** [comment]
This test is associated with c68b70ff2e305335d5bf8252141e6f7599f49491 and previous commits containing `yum list-sec`. Fedora is the only OS that uses `dnf` by default. RHEL7 and RHEL6, Centos7 and so on use `yum` by default.
This is a Fedora only bug, I think.

Why don't you use `logfile` Lynis feature?

**Comment by FlorianHeigl** [comment]
Yes it's a Fedora only bug. Actually it's two bugs since the password module also leaks output in -q.
The output also leaks with the logfile feature.

In summary, -q doesn't work as it should.

**Comment by mboelen** [comment]
This behavior was as originally intended: be quiet, but display warnings. We try to fetch as much possible stdout and stderr output, to keep it quiet. Will internally discuss this option and if we should make it ReallyQuiet(tm).

**Comment by FlorianHeigl** [comment]
Ah ok, wasn't obvious it was intended like this :-)

**Comment by mboelen** [comment]
We had a talk about it. Right now Quiet means: it is pretty quiet and only shows you the warnings, as stated in the man page.

If you feel you don't want to see anything at all, then you can upgrade to "really quiet" by redirecting all stderr/stdout to the /dev/null. For your purposes that seems to be a fitting solution as well.

Thanks for asking the question. I will close this issue as a wontfix, as no changes will be applied.
