### ISSUE TITLE
stderr output when systemd-resolved is disabled

### ISSUE THREAD

**Issue by Schmuuu** [CISOfy/lynis#897]
**Describe the bug**
With disabled systemd-resolved lynis displays the error message (stderr) from resolvectl in its output:
![DeepinScreenshot_select-area_20200403004503](https://user-images.githubusercontent.com/26191454/78307209-b4848b80-7545-11ea-903d-de827c51d164.png)

I could open a pull-request just to exclude the error message and add some additional information to the log. However, I wanted to ask here first, if somebody has an idea how to handle that issue even better and probably check dnssec when pihole is active instead.

**Version**
 - Distribution: Arch-Linux LTS kernel
 - Lynis version: 3.0 latest master

**Expected behavior**
Don't show stderr messages in lynis output. The state "Warning" is good enough to check the details. As a bonus some information in the test details for the user to check the output of resolvectl would be nice.

**Output**
./lynis show details NETW-2706:
2020-04-03 00:32:54 Performing test ID NETW-2706 (Check systemd-resolved and upstream DNSSEC status)
2020-04-03 00:32:55 Result: DNSSEC not supported by systemd-resolved or upstream DNS servers
2020-04-03 00:32:55 ====

**Additional context**
I have Pi-Hole running on that system and Pi-Hole brings dnsmasq. Therefore I had to disable/ stop systemd-resolved. In return resolvectl returns the error message on stderr, that the service dbus-org.freedesktop.resolve1 can't be found.

**Comment by mboelen** [comment]
Applied change to redirect errors to /dev/null. Is the message gone now on your system?

**Comment by Schmuuu** [comment]
Yes, the message is gone now. 
I just saw "include/tests_dns". This will cover my other question then later, right? So there is an alternative test for dnssec already, right?

Could you add a log entry for the user to manually run resolvectl in case there was an error from this command? So keep the line in case there was no error:
`LogText "Result: DNSSEC not supported by systemd-resolved or upstream DNS servers"`

and use something like this, in case there was an error:
`LogText "Result: command '$(${RESOLVECTLBINARY} statistics' returned an error. Please run command manually to check for details."`

**Comment by mboelen** [comment]
New changes applied and extended test. Is it working correctly for you now (including the right message)?

**Comment by Schmuuu** [comment]
Perfect! Thank you very much for the very quick solution! 
When will include/tests_dns be activated?

**Comment by mboelen** [comment]
Great, closing this one then.

As there are not much DNS specific tests yet, it is fine that things are now under networking. The idea is to enable DNS when we have more tests for Bind, PowerDNS, etc. Then it might also make sense to move a few from networking to the more specific DNS group.

If you have ideas to improve in this area, feel free to reach out by email. Happy to discuss the options!
