### ISSUE TITLE
Running kernel not found on disk [KRNL-5830]

### ISSUE THREAD

**Issue by d4t4king** [CISOfy/Lynis#9]
Gentoo contains a utility to simplify kernel building and installation, called genkernel.  Genkernel names the kernel files kernel-genkernel-{*arch*}-{*version*}-gentoo(-r_n_), instead of _vmlinuz_.

Example:  current running kernel is `/boot/kernel-genkernel-x86-3.14.16-gentoo`.

**Comment by mboelen** [comment]
Closing issue, latest testing did not show this issue. Please let me know if it is still the case.
