### ISSUE TITLE
[CRYP-7902] Checks for SSL_CERTIFICATE_PATHS_TO_IGNORE fails to ignore sub-directories

### ISSUE THREAD

**Issue by church1e** [CISOfy/lynis#902]
**Describe the bug**
When `ssl-certificate-paths-to-ignore` is set CRYP-7902 fails to ignore subdirectories...

**Version**
 - Distribution Ubuntu 19.04, 19.10 and 20.04
 - Lynis version 3.0.0

**Expected behavior**
Checks for SSL_CERTIFICATE_PATHS_TO_IGNORE should also ignore sub-directories.

**Output**
current output
```  - Checking for expired SSL certificates [4/60]              [ FOUND ]```
expected output with sub-directories ignored
```  - Checking for expired SSL certificates [0/48]              [ NONE ]```

**Additional context**
In `default.prf` we see that ssl-certificate-paths-to-ignore is set as:
```ssl-certificate-paths-to-ignore=/etc/letsencrypt/archive:```

This is also confirmed in the `lynis.log` file:
```
Performing test ID CRYP-7902 (Check expire date of SSL certificates)
Paths to scan: /etc/apache2 /etc/dovecot /etc/httpd /etc/letsencrypt /etc/pki /etc/postfix /etc/ssl /opt/psa/var/certificates /usr/local/psa/var/certificates /usr/local/share/ca-certificates /var/www /srv/www
Paths to ignore: /etc/letsencrypt/archive
```

However when and audit is run, sub directories are still being queried. From `lynis.log` we see:
```
Result: file /etc/letsencrypt/archive/mydomain/cert7.pem is readable (or directory accessible).
Result: file /etc/letsencrypt/archive/mydomain/cert8.pem is readable (or directory accessible).
Result: file /etc/letsencrypt/archive/mydomain/cert9.pem is readable (or directory accessible).
Result: file /etc/letsencrypt/archive/mydomain/chain7.pem is readable (or directory accessible).
Result: file /etc/letsencrypt/archive/mydomain/chain8.pem is readable (or directory accessible).
Result: file /etc/letsencrypt/archive/mydomain/chain9.pem is readable (or directory accessible).
Result: file /etc/letsencrypt/archive/mydomain/fullchain7.pem is readable (or directory accessible).
Result: file /etc/letsencrypt/archive/mydomain/fullchain8.pem is readable (or directory accessible).
Result: file /etc/letsencrypt/archive/mydomain/fullchain9.pem is readable (or directory accessible).
Result: file /etc/letsencrypt/archive/mydomain/privkey7.pem is readable (or directory accessible).
Result: file /etc/letsencrypt/archive/mydomain/privkey8.pem is readable (or directory accessible).
Result: file /etc/letsencrypt/archive/mydomain/privkey9.pem is readable (or directory accessible).
```

**Resolution**
In `include/tests_crypto` change line 66, from:
```if Equals "${D}" "${SUBDIR}"; then```
to:
```if ContainsString "${D}" "${SUBDIR}"; then```

**Comment by mboelen** [comment]
Hi @church1e - Thanks for reporting this.

Sounds like you got the right fix. Do you have the chance to create a pull request for this? This way we can properly attribute it to you :)

Thanks

**Comment by mboelen** [comment]
Closing after pull request was merged.
