### ISSUE TITLE
PKGS-7388: Lynis complains for Debian unstable

### ISSUE THREAD

**Issue by hpreusse** [CISOfy/lynis#906]
**Is your feature request related to a problem? Please describe.**
I've recently installed Lynis from Debian repository. It is the latest released 2.7.5. I run an "audit system" and it complains "Can't find any security repository in /etc/apt/sources.list or sources.list.d directory [PKGS-7388]". I run Debian unstable, hence there can't be sources list entries for security.

**Describe the solution you'd like**
Lynis should be aware that there can't security entries for machines running Debian unstable or testing, hence it should stop complaining.

**Required changes**
The check for security sources should be disabled for people running Debian unstable or testing. It may print out a message: "system runs Debian unstable / testing, check for security entries in sources.list skipped".

**Additional context**
<N/A>

**Comment by Schmuuu** [comment]
Hi,

Lynis 2.7.5 is quite old and a lot of changes have been committed to master since then. 
There is this commit, which should address this issue I believe:
https://github.com/CISOfy/lynis/commit/6e3e93d5854960dee1e7516922647c303e4094b8

Could you maybe test the latest master instead of the Debian package for lynis?
```
git clone https://github.com/CISOfy/lynis.git && cd lynis
./lynis audit system
```

**Comment by hpreusse** [comment]
> Could you maybe test the latest master instead of the Debian package for lynis?
> 
As said elsewhere I checked the "git log" already to see if the git solves the issue. Just now I re-checked with git checkout: issue not solved.

[+] Ports and packages
------------------------------------
  - Searching package managers
    - Searching dpkg package manager                          [ FOUND ]
      - Querying package manager
    - Query unpurged packages                                 [ NONE ]
  - Checking security repository in sources.list file or directory  [ WARNING ]
  - Checking vulnerable packages (apt-get only)               [ DONE ]

  [WARNING]: Test PKGS-7392 had a long execution: 29.759054 seconds

  - Checking package audit tool                               [ INSTALLED ]
    Found: apt-get
  - Toolkit for automatic upgrades                            [ NOT FOUND ]

**Comment by Schmuuu** [comment]
Sorry, I misread the code and indeed the mentioned commit doesn't handle this issue.

There is a way to provide lynis a profile which configures the test execution. With option "debian-skip-security-repository" skipping that test can be configured.

I might be able to provide the necessary code changes to skip Debian unstable and testing automatically, but unfortunately I never used Debian and don't know yet how to check if unstable or testing is currently running. So I would need this information at least.

**Comment by mboelen** [comment]
Should not be that hard to add. What output do you get when running `lynis show os`?

**Comment by hpreusse** [comment]
> Should not be that hard to add. What output do you get when running `lynis show os`?
> 
root@debian-amd64-sid:~/lynis# ./lynis show os
OS=Linux
OS_NAME=Debian
OS_FULLNAME=Debian bullseye/sid
OS_VERSION=bullseye/sid

I would not rely on that string "bullseye" as that will change after next Debian release.

**Comment by Varbin** [comment]
Even though it is now incorrectly closed, I'd like to add the following: *testing release code*/is present on both testing and unstable (and sometimes even Ubuntu), and Debian testing does have security repositories (unstable has not).
