### ISSUE TITLE
Do not show encryption warnings for snapd loop devices

### ISSUE THREAD

**Issue by alexhaydock** [CISOfy/lynis#910]
**Describe the bug**
As part of `snapd`'s function, each installed Snap package on a user's system is mounted as a read-only squashfs filesystem image. The Snap daemon does nothing to obfuscate these mounts from the system so many commands, like `mount`, will list all of them.

Lynis lists all of these mounts too, as part of the "DM-Crypt, Cryptsetup & Cryptmount" checks. This leads to a lot of output spam when the user is an active Snap user.

**Version**
 - Ubuntu 20.04 RC
 - Lynis 2.7.5

**Expected behavior**
Lynis should ignore the Snap mounts as they are not expected to be encrypted anyway.

**Output**
![image](https://user-images.githubusercontent.com/13152214/79633843-fb39ce80-815e-11ea-8f8d-84bbffa183fd.png)

**Additional context**
N/A

**Comment by Varbin** [comment]
@alexhaydock This warning is generated by the debian plugin. The maintainer of Lynis on Debian is [Francisco Manuel Garcia Claramonte](https://qa.debian.org/developer.php?login=francisco%40debian.org) (francisco@debian.org).
