### ISSUE TITLE
Chronyd's default port (UDP 323) is marked suspicious

### ISSUE THREAD

**Issue by mrplow87** [CISOfy/lynis#928]
**Describe the bug**
The Lynis Web interface shows NTP daemon Chronyd's used default port as "suspicious".

**Version**
 - CentOS Linux release 8.1.1911 (Core)
 - Lynis version 2.7.5 from Cisofy Repository

**Expected behavior**
Chronyd's default port (UDP 323) is not reported "suspicious".

**Output**
[::1]:323 | all interfaces | udp | udp | chronyd | Chrony daemon (time synchronization) - Suspicious (Service is running on an unusual port)

**Additional context**
Chronyd is configured to only listen on localhost and it's default port (UDP 323). This is not suspicious and intended behaviour. Yes, NTP normally listens on UDP 123, but some context (which daemon is used and what are it's default settings) should be added to the service test to avoid unnecessary questions/remarks by auditors because they see a big red banner "SUSPICIOUS" in the web interface.

**Comment by mboelen** [comment]
Thanks for reporting. This issue has been resolved with the latest update of the web interface.
