### ISSUE TITLE
Lynis weird error message. How to get rid of it

### ISSUE THREAD

**Issue by arafatx** [CISOfy/lynis#930]
Sorry if this issue sounds dumb to post here. I'm pretty new to CentOS 8. I use lynis to check my system using the following script:

    #!/bin/sh
    #lynis.sh
    
    #Global Variables
    REPORT_FILE_FINAL="/tmp/lynis-report-final.log"
    MYHOSTNAME=`/bin/hostname`
    LYNIS_BIN="/usr/local/lynis/./lynis"
    MAIL_BIN="/usr/local/bin/mail"
    MYEMAIL="webmaster@jfc.com"

    cat /dev/null > $REPORT_FILE_FINAL
   
    $LYNIS_BIN --cronjob >> $REPORT_FILE_FINAL
    $MAIL_BIN -s "Lynis System Audit Scan Report @ $MYHOSTNAME" $MYEMAIL < $REPORT_FILE_FINAL

and I got the following weird message:

    2020-05-12 06:00:03 cwd=/root 2 args: /usr/sbin/exim -bV
    # Warning: iptables-legacy tables present, use iptables-legacy to see them
    # Warning: iptables-legacy tables present, use iptables-legacy to see them
    # Warning: iptables-legacy tables present, use iptables-legacy-save to see them

In the first line, I understand that this has nothing to do with Lynis but I would like to understand where does this message generated from. Why does it point on the exim installation path ?

    cwd=/root 2 args: /usr/sbin/exim -bV 

In the last 3 lines of that weird message, it also mention about iptables warning and I guess this has something to do with the latest iptables on Centos 8 (because I didn't have this message on Centos 7). What does the warning mean and how to get rid of it or exclude it from the scan ?

I know Lynis can't do anything because it just reported what it's seen. But how do I get rid of the warning message in Lynis? because I don't see any TEST_ID to view more details about this error and with this TEST_ID I can exclude it from the list like we usually did in the default.prf 

Thank you

**Comment by mboelen** [comment]
Try `lynis audit system --verbose --debug` in the terminal to see which test is producing the additional output. Then you can exclude that, or let us know so we can redirect or filter that.

**Comment by mboelen** [comment]
@arafatx - Did you learn the related test with the command above?

**Comment by mboelen** [comment]
Closing for now due to no response.

**Comment by arafatx** [comment]
Sorry for the late response on this. I have resolved this issue.
