### ISSUE TITLE
CRYP-8005: rngd.service provides jitterentropy-rngd.service functionality

### ISSUE THREAD

**Issue by gittyhups** [CISOfy/lynis#931]
rng-tools which provides rngd.service and is used in CRYP-8004 uses jitterentropy-library to provide jitterentropy-rngd functionality since version 6.3 (dated July 5 2018).

https://github.com/nhorman/rng-tools/releases/tag/v6.3

Some distributions have removed the separate package jitterentropy-rngd because of that.

The maintainer or jitterentropy-rngd and jitterentropy-library has confirmed that an updated rngd doesn't need jitterentropy-rngd:
https://bugzilla.redhat.com/show_bug.cgi?id=1634788

**Version**
 - Lynis 3.0.0

**Expected behavior**
CRYP-8005 passing if rngd.service is running from rng-tools version equal or greater than 6.3.

**Comment by konstruktoid** [comment]
I believe `rngd` gets caught in test CRYP-8004, https://github.com/CISOfy/lynis/blob/master/include/tests_crypto#L251-L254, and because of that CRYP-8005 is ignored.
