### ISSUE TITLE
Strange warning about an “available update”

### ISSUE THREAD

**Issue by gergelypolonkai** [CISOfy/lynis#934]
Lynis warns about an update wher there is none.

**Version**
 - Arch Linux
 - Lynis 2.7.5 (installed from the Arch repos)

**Expected behavior**
It seems fine to warn users about an outdated version (“Current version is more than 4 months old), but notifying the user about an available update is strange when there are actually no updates.

**Output**
```
  - Program update status...                                  [ NO UPDATE ]

      ===============================================================================
        Lynis update available
      ===============================================================================

        Current version is more than 4 months old

        Current version : 275   Latest version : 275
```

**Comment by Jaimie85** [comment]
Yes it is a known issue and will be resolved with upcoming release. See #892.

**Comment by mboelen** [comment]
New release is coming soon(tm).
