### ISSUE TITLE
Unknown OS found in /etc/os-release

### ISSUE THREAD

**Issue by PaulGWebster** [CISOfy/lynis#938]
**Describe the bug**
It seems to not like gentoo for os-detection

**Version**
 - Gentoo
 - Latest (github clone today)

**Expected behavior**
It should not raise Unknown OS

**Output**
 cat /etc/os-release
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"

**Additional context**
  Exception found!

  Function/test:  [OS Detection]
  Message:        Unknown OS found in /etc/os-release

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (./lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

  Thanks!

=================================================================

  - Detecting OS...                                           [ DONE ]
  - Checking profiles...                                      [ DONE ]

  ---------------------------------------------------
  Program version:           3.0.0
  Operating system:          Linux
  Operating system name:     Gentoo
  Operating system version:  4.19.86-gentoo
  Kernel version:            4.19.86
  Hardware platform:         x86_64
  Hostname:                  dev-11
  ---------------------------------------------------
  Profiles:                  /home/paul.webster/Work/SecurityScan-Lynis/default.prf
  Log file:                  /var/log/lynis.log
  Report file:               /var/log/lynis-report.dat
  Report version:            1.0
  Plugin directory:          ./plugins
  ---------------------------------------------------
  Auditor:                   [Not Specified]
  Language:                  en
  Test category:             all
  Test group:                all
  ---------------------------------------------------
  - Program update status...                                  [ SKIPPED ]

**Comment by mboelen** [comment]
Thanks for sharing. Gentoo has been added with commit https://github.com/CISOfy/lynis/commit/9fdfc062dd17820114c2721f211f2c0f36bf5494
