### ISSUE TITLE
AUTH-9282/9286 are obsolete

### ISSUE THREAD

**Issue by damnms** [CISOfy/lynis#943]
https://www.heise.de/security/meldung/Passwoerter-BSI-verabschiedet-sich-vom-praeventiven-Passwort-Wechsel-4652481.html
https://www.extremetech.com/computing/292534-microsoft-says-forced-password-resets-dont-improve-security
https://www.sans.org/security-awareness-training/blog/time-password-expiration-die

Maybe it is time to get rid of those checks.

**Comment by Varbin** [comment]
I would suggest leaving them in Lynis, but to make them disabled by default. In case such policy still exists in a company (e.g. in a concept for ISO certification), administrators might want to check if password expiration is present.

**Comment by mboelen** [comment]
Although password rotation is nowadays no longer considered a best practice, you can still use it for good. For example, provide temporary access to systems. We will look into this so that people keep using it for the reason (and well-informed) reasons.
