### ISSUE TITLE
Add "Fedora release 31 (Thirty One)'" to software-eol.db

### ISSUE THREAD

**Issue by medined** [CISOfy/lynis#944]
**Is your feature request related to a problem? Please describe.**

I am running lynis on Fedora CoreOS v31 which is not represented in the software end-of-life list.

**Describe the solution you'd like**

Unfortunately, I don't know the end-of-life dates that I would like added. I have emailed the Fedora support team. If I hear back, I will add a comment to this request.

CoreOS Container Linux will reach its end of life on May 26, 2020,
Fedora 25 officially enters End Of Life (EOL) status on December 12th, 2017.

**Required changes**

The software-eol.db file needs to updated.

**Comment by medined** [comment]
I just found https://en.wikipedia.org/wiki/Fedora_version_history which lists end of life for Fedora versions.

**Comment by konstruktoid** [comment]
Hi @medined, according to https://fedoraproject.org/wiki/End_of_life Fedora release 31 doesn't yet have a EOL date.

**Comment by medined** [comment]
Yes. Thanks for adding the previous releases to the end-of-life file. I'll take that as a win for the weekend.
