### ISSUE TITLE
openSUSE splits /etc and /usr/etc

### ISSUE THREAD

**Issue by SchwarzerA** [CISOfy/lynis#947]
According to 

https://en.opensuse.org/openSUSE:Packaging_UsrEtc
https://kubic.opensuse.org/blog/2019-12-05-usr-etc/

configuration files may be in both directories with a different scope. Is this already considered?

**Comment by mboelen** [comment]
It definitely needs attention in those tests that specifically check for a configuration file. Want to help to identify them?

**Comment by SchwarzerA** [comment]
--    -shw.mobile-Hello Michael,Yes I wouild like to help. Can you please let me know what you need? -------- Ursprüngliche Nachricht --------Betreff: Re: [CISOfy/lynis] openSUSE splits /etc and /usr/etc (#947)Von: Michael Boelen An: CISOfy/lynis Cc: Axel Schwarzer ,Author 
It definitely needs attention in those tests that specifically check for a configuration file. Want to help to identify them?

**Comment by mboelen** [comment]
You could point out tests that already should check for the presence of both (including the overrule principle it uses). So you could go through the tests which you think are relevant.

Will mark this issue as 'no-change' for now and closing it. Feel free to open an issue(s) for tests that need to be updated.
