### ISSUE TITLE
/bin/sed: -e expression #1, char 27: unterminated `s' command

### ISSUE THREAD

**Issue by brentclark** [CISOfy/lynis#949]
Good day

I got the follow message:
/bin/sed: -e expression #1, char 27: unterminated `s' command

**Version**
 - Ubuntu 18.04
 - Lynis 3.0.0

**Output**
[+] Software: file integrity
------------------------------------
  - Checking file integrity tools
  - AIDE                                                    [ FOUND ]
  - AIDE config file                                    [ FOUND ]
/bin/sed: -e expression #1, char 27: unterminated `s' command
  - AIDE database                                    [ NOT FOUND ]
  - AIDE config (Checksum)                     [ Suggestion ]
  - Checking presence integrity tool         [ FOUND ]

**Comment by mboelen** [comment]
Hi @brentclark - I can't reproduce that on a similar system. Can you share the output of `grep database /etc/aide/aide.conf` on your system?

**Comment by brentclark** [comment]
root@REMOVED:~# grep database /etc/aide/aide.conf
database=file:@@{DBDIR}
database_out=file:@@{DBDIR_TEMP}
database_new=file:@@{DBDIR_TEMP}
# gzip output to the database?

**Comment by mboelen** [comment]
Can you run this and share the output?
`grep "@@define.*DBDIR" /etc/aide/aide.conf | awk '{print $3}'`

**Comment by brentclark** [comment]
root@REMOVED:~# grep "@@define.*DBDIR" /etc/aide/aide.conf | awk '{print $3}'
/var/lib/aide/aide.db
/var/lib/aide/aide.db.new
