### ISSUE TITLE
Language detection does not work in 3.0

### ISSUE THREAD

**Issue by al-lac** [CISOfy/lynis#950]
**Describe the bug**
As it stands now the language detection does not seem to be working in Version 3.0. It always falls back to the default language (en). This is probably because of the following line which unsets the LANG variable: https://github.com/CISOfy/lynis/blob/3.0.0/include/consts#L38

I do not know exactly why the LANG variable is unset in consts, maybe it is just some old code. In previous versions like 2.7.5 the language selection was done prior to including the consts file and that is why it worked: https://github.com/CISOfy/lynis/blob/2.7.5/lynis#L112

It is not possible to move the language selection part to before the import of the consts file because it now relies on some of the functions that are defined in consts (SafeFile, ExitFatal).

**Version**
 - Distribution: MacOS 10.15 and Raspberry Pi 4 with Raspbian
 - Lynis version: 3.0

**Expected behavior**
Lynis runs with the system language, **de** for example.

**Comment by mboelen** [comment]
Thanks @al-lac for sharing.

Just made a change to this with commit https://github.com/CISOfy/lynis/commit/75738ceeab380e852739a9b78e0d907f3e611478. Can you check if it works correctly now?

**Comment by al-lac** [comment]
On my raspberry it is looking good now:
```bash
---------------------------------------------------
  Auditor:                   [Not Specified]
  Language:                  de
  Test category:             all
  Test group:                all
  ---------------------------------------------------
```

However, for it to work on macOS you would need to remove the quotes because the output of the `locale` command looks like this:
```bash
LANG="de_AT.UTF-8"
```

A simple `sed` should do the trick:
```bash
LANGUAGE=$(locale | egrep "^LANG=" | cut -d= -f2 | cut -d_ -f1 | sed 's/\"//g' | egrep "^[a-z]{2}$")
```

**Comment by mboelen** [comment]
Thanks for the confirmation. Applied the suggestion to delete the quotes (using tr -d).
