### ISSUE TITLE
systemd-timesync test shows a warning if dbus is not installed

### ISSUE THREAD

**Issue by Varbin** [CISOfy/lynis#953]
**Describe the bug**
It is possible to use systemd-timesyncd without dbus, and Debian allows its users to remove it. Without dbus, timedatectl does not work but prints and error.

**Version**
 - Raspberry Pi OS Buster (formerly raspbian)
 - 3.0.1, bd29a3e4e790d9825521ae9e9a04ffb3c01721d0

**Expected behavior**
I'm not sure. Show something like "systemd-timesyncd running, but it is not possible to theck the status"?

At least the presence should be detected (systemd-timesyncd is installed) and if the service runs. Lynis should note that there is a problem querying it. 

**Output**

```
[+] Time and Synchronization
------------------------------------
Failed to create bus connection: Connection refused
  - Checking for a running NTP daemon or client               [ WARNING ]
```

```
  * Use NTP daemon or NTP client to prevent time issues. [TIME-3104] 
      https://cisofy.com/lynis/controls/TIME-3104/
```

**Comment by mboelen** [comment]
Thanks for reporting!

Lynis just queries systemd-timesyncd. While we can implement some checks, like checking the dbus status, is it worth the overhead?

Is your time synchronization working at all? In other words, how would you check it currently?

**Comment by Varbin** [comment]
I have no idea, I don't check if time synchronization actually works. Systemd reports the daemon as running.
If at all, I would manually test if it is working (running a single ntp query and compare the result).
I stumbled accross this issue on a system I removed dbus for minimization purposes, luckily not a very important one.

Maybe the correct (and without much overhead) behaviour of Lynis could be to:
- Supress the error message of timedatectl
- Check if systemd-timesyncd is running (`systemctl status systemd-timesyncd ` instead of directly using timedatectl)
- Test if systemd-timesyncd is actually working. If timedatectl is not working (but the service is running) report it as error.

If I find time in the next few days, I may implement this approach and send you a PR.

**Comment by Varbin** [comment]
Unstale

**Comment by Varbin** [comment]
timesyncd apparently creates the file /run/systemd/timesync/synchronized and /var/lib/systemd/timesync/clock. I guess this can be checked instead of timedatectl.

 [timesyncd(8)](https://dyn.manpages.debian.org/buster/systemd/systemd-timesyncd.8.en.html).

**Comment by Varbin** [comment]
@mboelen I've created #980 with a potential fix. Do you mind looking at it?
