### ISSUE TITLE
INSE-8304 and INSE-8322 are not documented

### ISSUE THREAD

**Issue by Varbin** [CISOfy/lynis#954]
**Describe the bug**
When rsh-server is installed, lynis correctly complains about it by emitting INSE-8304 (replace rsh-server) and INSE-8322 (replace _amount_ packages).

**Version**
 - Raspbian OS Buster
 - 3.0.1, bd29a3e4e790d9825521ae9e9a04ffb3c01721d0

**Expected behavior**
Documentation.

**Comment by mboelen** [comment]
Text about missing controls on website will be added soon (will be done in a batch). Bulk closing issues related to missing documentation.
