### ISSUE TITLE
[INSE-8322] Not all insecure services are counted

### ISSUE THREAD

**Issue by Varbin** [CISOfy/lynis#956]
**Describe the bug**
On a test system I have installed telnet and rsh. In the end, I get the hint to replace rsh and 1 service, although two insecure services were found.

**Version**
 - Raspberry Pi OS Buster (formerly Raspbian)
 - Lynis 3.0.1, bd29a3e4e790d9825521ae9e9a04ffb3c01721d0

**Expected behavior**
Correctly count or at least display all services individually.

**Output**
```
  * Remove the rsh-server package and replace with a more secure alternative like SSH [INSE-8304] 
      https://cisofy.com/lynis/controls/INSE-8304/

  * Removing the 1 package and replace with SSH when possible [INSE-8322] 
      https://cisofy.com/lynis/controls/INSE-8322/
```

```
suggestion[]=INSE-8304|Remove the rsh-server package and replace with a more secure alternative like S$
insecure_service[]=rsh-server
suggestion[]=INSE-8322|Removing the 1 package and replace with SSH when possible|-|-|
insecure_service[]=telnet-server
```

**Comment by mboelen** [comment]
Actually it was an incorrect variable used, giving the impression that it was a counter. Text has been adjusted: https://github.com/CISOfy/lynis/commit/610f70d5aa5a8e5930b7b0329e1e7c8347367f43
