### ISSUE TITLE
Install one copy of default.prf

### ISSUE THREAD

**Issue by medined** [CISOfy/lynis#959]
**Is your feature request related to a problem? Please describe.**

I installed v3.0.0 from the yum repository. I have two identical copies of `default.prf`.

```
/usr/etc/lynis/default.prf
/etc/lynis/default.prf
```

**Describe the solution you'd like**

I'd like one copy of `default.prf`.

**Required changes**

Remove one copy of the file.

** Extra Information **

This is a Fedora CoreOS v32 server on AWS. 

Runing `lynis show profiles` only shows the `/etc/lynis/default.prf` file.

**Comment by mboelen** [comment]
The /usr/etc/lynis/default.prf is not something we use (yet). What specific package did you use and what repository?

**Comment by medined** [comment]
- name: Create Lynis Yum repository file.
copy:
dest: /etc/yum.repos.d/lynis.repo
content: |
[lynis]
name=CISOfy Software - Lynis package
baseurl=https://packages.cisofy.com/community/lynis/rpm/
enabled=1
gpgkey=https://packages.cisofy.com/keys/cisofy-software-rpms-public.key
gpgcheck=1
priority=2
mode: 644

- name: Install lynis.
shell: rpm-ostree install lynis
register: output
changed_when: "'start a reboot' in output.stdout"
failed_when: "'start a reboot' not in output.stdout and 'already requested'
not in output.stderr"
args:
warn: false


*After learning a bit more, I looked at the files loaded by the lynis
package:*

$ rpm -ql lynis | grep prf
/etc/lynis/default.prf

*Information about the package is*

$ rpm -qi lynis
Name        : lynis
Version     : 3.0.0
Release     : 100
Architecture: noarch
Install Date: Sun 21 Jun 2020 09:11:13 PM UTC
Group       : Applications/System
Size        : 1598742
License     : GPL
Signature   : RSA/SHA1, Thu 18 Jun 2020 10:57:37 AM UTC, Key ID
824612e20acf951b
Source RPM  : lynis-3.0.0-100.src.rpm
Build Date  : Thu 18 Jun 2020 10:57:07 AM UTC
Build Host  : build01.cisofy.local
Packager    : CISOfy <software@cisofy.com>
Vendor      : CISOfy
URL         : https://cisofy.com/


*I don't understand where the /usr/etc/lynis/default.prf file comes from.*

*Having two files does not seem to be affecting anything. I just don't know
not knowing.*

**Comment by mboelen** [comment]
Might be coming from another package.
