### ISSUE TITLE
/usr/bin/find: `/etc/grub.d': No such file or directory

### ISSUE THREAD

**Issue by gemal** [CISOfy/lynis#960]
I run Lynis as a cronjob with the following parameters:
`/usr/bin/lynis audit system --cronjob --warnings-only`

using version 3.0.0

I get the following output from the cronjob which I only got after the update to version 3.0.0:
```
/bin/find: `/etc/grub.d': No such file or directory
```

I think some code is missing for checking that the folder exists before using it

Running it from command line produces:
```
  - Checking presence GRUB                                    [ OK ]
/bin/find: `/etc/grub.d': No such file or directory
    - Checking for password protection                        [ NONE ]
```

**Comment by mboelen** [comment]
Thanks for reporting!

The check has been added: https://github.com/CISOfy/lynis/commit/a2f8bdc5f8b4c67338f7cf9995f74df06d572b27
