### ISSUE TITLE
ls: cannot access /etc/nginx//usr/share/nginx/modules/*.conf: No such file or directory

### ISSUE THREAD

**Issue by gemal** [CISOfy/lynis#961]
I run Lynis as a cronjob with the following parameters:
`/usr/bin/lynis audit system --cronjob --warnings-only`

using version 3.0.0

I get the following output from the cronjob which I only got after the update to version 3.0.0:

`ls: cannot access /etc/nginx//usr/share/nginx/modules/*.conf: No such file or directory`

I think some code is missing for checking that the folder exists before using it

Running it from command line produces:

```
  - Checking nginx                                            [ FOUND ]
    - Searching nginx configuration file                      [ FOUND ]
      - Found nginx includes                                  [ 16 FOUND ]
    - Parsing configuration options
        - /etc/nginx/nginx.conf
ls: cannot access /etc/nginx//usr/share/nginx/modules/*.conf: No such file or directory

```

**Comment by FBurner** [comment]
Hi having the same problem 
- Parsing configuration options
- /etc/nginx/nginx.conf
ls: cannot access '/etc/nginx//etc/nginx/conf.d/*.conf': No such file or directory

Includes are now read always with the directory attached infront of absolute paths

**Comment by BOPOHA** [comment]
up

**Comment by mboelen** [comment]
@gemal @FBurner @BOPOHA Do you still have those with 3.0.3?

**Comment by BOPOHA** [comment]
> @gemal @FBurner @BOPOHA Do you still have those with 3.0.3?

lynis-3.0.1-1.el8.noarch works good, w/o this issue

**Comment by FBurner** [comment]
Our scan doesn't show any problems.

BOPOHA ***@***.***> schrieb am Mo., 22. März 2021, 00:07:
