### ISSUE TITLE
Add Bitdefender for Mac to the set of acceptable commercial anti-virus software

### ISSUE THREAD

**Issue by johnpraill** [CISOfy/lynis#963]
Please would you consider adding Bitdefender for Mac to the test for running commercial anti-virus software

The product page is https://www.bitdefender.com/solutions/antivirus-for-mac.html 

I have watched the processes running when Bitfender is active and the following see to be running at all times:

BDCoreIssues 
bdagentd
BDUpdDaemon
BDLDaemon

I am not very knowledgeable about these things so if there is any other information I can provide please let me know.

Thank you

**Comment by mboelen** [comment]
Hi @johnpraill - Thanks for sharing.

BitDefender was already recognized, but with other processes. I added `bdagentd` as an additional way of detecting it: https://github.com/CISOfy/lynis/commit/c707b7d100dd902e7f183812504bc24428420c64

Next release it should be detected.
