### ISSUE TITLE
Unknown OS SLES15

### ISSUE THREAD

**Issue by tsia** [CISOfy/lynis#965]
**Describe the bug**
 When running lynis on SLES15, I get the following message included in the output:
 Exception found!

  Function/test:  [OS Detection]
  Message:        Unknown OS found in /etc/os-release

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (./lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

here is my /etc/os-release:

NAME="SLES"
VERSION="15-SP1"
VERSION_ID="15.1"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP1"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp1"

**Version**
 - Distribution SLES15
 - Lynis version 3.0.0

**Expected behavior**
Lynis should recognize SLES15

**Comment by mboelen** [comment]
Issue automatic closed after implementing pull request by @konstruktoid
