### ISSUE TITLE
permfile and permdir settings not working

### ISSUE THREAD

**Issue by Steve8291** [CISOfy/lynis#967]
**Describe the bug**
Changing permfile or permdir settings in `custom.prf` does not override those set in `default.prf`
For example, if this is set in `custom.prf`
Note: these are the actual permissions that are currently on the file.
`permfile=/etc/at.deny:rw-r-----:root:daemon:WARN:`
The warning is still triggered based on the setting in `default.prf` of
`permfile=/etc/at.deny:rw-------:root:-:WARN:`

**Version**
 - Distribution Ubuntu 18.04.4 LTS (bionic)
 - Lynis 3.0.0

**Expected behavior**
Settings in custom.prf should override those in default.prf

**Output**
2020-06-25 11:20:53 Test: checking file/directory /etc/at.deny
2020-06-25 11:20:53 Test: checking if file /etc/at.deny has the permissions set to 600 or more restrictive
2020-06-25 11:20:53 Outcome: permissions of file /etc/at.deny are not matching expected value (640 != rw-------)

**Additional context**

**Comment by mboelen** [comment]
Hi @Steve8291 - Thanks for reporting. At this moment permdir/permfile are combined, not overwritten.

Do you really need the 640 or is it just an example of how you discovered it?

**Comment by Steve8291** [comment]
Thanks @mboelen I didn't know that combining those files was intentional.
That was just an example of how I discovered it wasn't working as I expected. Wouldn't it make more sense to have any settings in the custom.prf files overwrite those that were set as default values. I'm thinking about a scenario somewhat like is done in mysql/mariadb where the order the preference files are loaded causes later files to overwrite previous ones. I would think that most people would assume that is how it works. 

If my custom.prf doesn't overwrite the ones from the default.prf then there is no point in me maintaining my own custom.prf file and I should just edit the default.prf. However, when lynis updates, all my settings in the default.prf will be wiped out.

**Comment by pyllyukko** [comment]
> Do you really need the 640 or is it just an example of how you discovered it?

Actually `/etc/{at,cron}.{allow,deny}` should be 640 in Debian because that's how it works.

`crontab` is SGID for group `crontab` which should be able to read `/etc/cron.{allow,deny}`:

```
-rwxr-sr-x 1 root crontab 30452 Feb 23  2021 /usr/bin/crontab
```

And `at` is SGID `daemon`.

So the `.{deny,allow}` files need to be readable for those groups.
