### ISSUE TITLE
False positive with kernel logger check (LOGG-2138)

### ISSUE THREAD

**Issue by chusopr** [CISOfy/lynis#975]
**Describe the bug**
The kernel logger check (`LOGG-2138`) seems to be limited to checking that either `rsyslogd` or `journald` is running, but other options are available for kernel logging.
I'm using [syslog-ng](https://syslog-ng.com/open-source-log-management) and the default in Gentoo Linux is [https://github.com/hvisage/metalog](metalog). Both would make this test fail while a logger is actually running.
Or am I missing something and there is something that `rsyslog` and `journald` log that `syslog-ng` and `metalog` don't?

Also, the check message seems misleading as it states it searches for `klogd` process when that's not the case.

**Version**
 - Distribution Gentoo 17.1
 - Lynis version 3.0.0

**Expected behavior**
Passing LOGG-2138 check when any other logger than rsyslogd and journald is running.

**Output**
```
Performing test ID LOGG-2138 (Checking kernel logger daemon on Linux)
Test: Searching kernel logger daemon (klogd)
Performing pgrep scan without uid
IsRunning: process 'klogd' not found
Result: No klogd found
Warning: klogd is not running, which could lead to missing kernel messages in log files [test:LOGG-2138] [details:-] [solution:-]
```

**Additional context**
I don't really know how this can be improved. Maybe just listing all the other known loggers than `rsyslogd`? Checking for processes reading `/dev/log`?

**Comment by chusopr** [comment]
Why is this closed? This is still not fixed.

**Comment by jhe2** [comment]
This is still an issue with lynis 3.0.3. Perhaps one could check which processes are accessing ``/dev/log`` as chusopr suggested, something like:
```
for i in $(fuser /dev/log 2> /dev/null); do cat "/proc/$i/cmdline"; echo; done
```
...and then check the result against a list of known logging daemons?

**Comment by pyllyukko** [comment]
This is also a problem (FP) with [sysklogd](https://github.com/troglobit/sysklogd) where `klogd` was removed in [v2.1](https://github.com/troglobit/sysklogd/releases/tag/v2.1).
