### ISSUE TITLE
HostID generation is not working properly

### ISSUE THREAD

**Issue by Firesphere** [CISOfy/lynis#976]
**Describe the bug**
Since version 3.0, we are getting an error about the HostID or HostID2 being incorrect length.

**Version**
 - Ubuntu 18.04
 - Lynis 3.0.0

**Expected behavior**
The HostID generated should match

**Additional context**
HostIDs are key to the portal or self-hosted Enterprise environment, we are missing out on certain devices due to this.

**Comment by GSam** [comment]
It looks like it's related to the following line:
https://github.com/CISOfy/lynis/blob/master/include/helper_generate#L54

The hexdump printf string does not appear to produce a consistent output length (sometimes at worst being a whole byte short, or two hex chars). The previous xxd version worked without issue.

**Comment by mboelen** [comment]
You only have this problem when using the 'lynis generate hostids' command, right?

**Comment by mboelen** [comment]
Applied a change to deal with too short IDs: https://github.com/CISOfy/lynis/commit/6eae35e564fba2183a1d6a2cddaa656d841756f9

This will be part of the upcoming release. Thanks @Firesphere and @GSam for reporting and the discovery.

**Comment by Firesphere** [comment]
Cheers for the incredibly quick fix @mboelen !

**Comment by Firesphere** [comment]
Any indication on when this will be released?

**Comment by mboelen** [comment]
Hopefully in upcoming days, depending on some review work.
