### ISSUE TITLE
"Device sda3 not found" email with cron

### ISSUE THREAD

**Issue by stephen-d-hill** [CISOfy/lynis#978]
**Describe the bug**
I am getting an email from Lynis when run from cron

**Version**
 - Ubuntu 18.04.4
 - Lynis version 3.0.0

**Expected behavior**
No email, as there are no Lynis warnings, apart from this device not found

**Output**
Subject:
```
Cron <root@hill> test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
```
Body:
```
/etc/cron.daily/lynis:
Device sda3 not found
```

**Additional context**
I was not getting this email on Ubuntu's version of Lynis. Has only been happening since using cisofy repo and getting latest Lynis (deb https://packages.cisofy.com/community/lynis/deb/ stable main).
The amount of partitions has changed recently...I don't know if is relevant or not.
```
~$ sudo fdisk -l /dev/sda
[sudo] password for stephen: 
Disk /dev/sda: 931.5 GiB, 1000204886016 bytes, 1953525168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot    Start        End    Sectors  Size Id Type
/dev/sda1           4096     528383     524288  256M  b W95 FAT32
/dev/sda2  *      528384    2625535    2097152    1G 83 Linux
/dev/sda3        2625536   68161535   65536000 31.3G 82 Linux swap / Solaris
/dev/sda4       68161536 1953523711 1885362176  899G 83 Linux
```
```
~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            9.6G     0  9.6G   0% /dev
tmpfs           2.0G  3.5M  2.0G   1% /run
/dev/sda4       2.8T  550G  644G  47% /
tmpfs           9.6G  164K  9.6G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           9.6G     0  9.6G   0% /sys/fs/cgroup
/dev/loop0      9.2M  9.2M     0 100% /snap/canonical-livepatch/95
/dev/loop1       97M   97M     0 100% /snap/core/9436
tmpfs           9.6G     0  9.6G   0% /run/shm
/dev/sda2       976M  178M  732M  20% /boot
/dev/sdd        3.7T  835G  2.9T  23% /shared_data
/dev/sde        5.5T  3.2T  2.3T  59% /shared_data2
tmpfs           100K     0  100K   0% /var/lib/lxd/shmounts
tmpfs           100K     0  100K   0% /var/lib/lxd/devlxd
/dev/loop2       55M   55M     0 100% /snap/core18/1754
/dev/loop3       96M   96M     0 100% /snap/get-iplayer/250
tmpfs           2.0G     0  2.0G   0% /run/user/1000

```

**Comment by stephen-d-hill** [comment]
/etc/cron.daily/lynis
```
#!/bin/sh

set -u
DATE=$(date +%Y%m%d)
HOST=$(hostname)
LOG_DIR="/var/log/lynis"
REPORT="$LOG_DIR/report-${HOST}.${DATE}"
DATA="$LOG_DIR/report-data-${HOST}.${DATE}.txt"

# Run Lynis
lynis audit system --cronjob --quiet > ${REPORT}

# Optional step: Move report file if it exists
if [ -f /var/log/lynis-report.dat ]; then
    mv /var/log/lynis-report.dat ${DATA}
fi

#The End
```

**Comment by mboelen** [comment]
Thanks for reporting. Please determine what test this is by running: `lynis audit system --debug --verbose`. This should show you which test triggered the specific message, so we can filter it out (when possible).

**Comment by stephen-d-hill** [comment]
```sudo lynis audit system --debug --verbose &> lynis_log.txt```
[lynis_log.txt](https://github.com/CISOfy/lynis/files/4884126/lynis_log.txt)

```
Performing test ID CRYP-7931 (Determine if system uses encrypted swap)
Device sda3 not found
```

**Comment by stephen-d-hill** [comment]
As a workaround I have added the following into /etc/lynis/custom.prf:
```
# Complains about device not found otherwise in v3.0.0
skip-test=CRYP-7931
```

**Comment by mboelen** [comment]
If you run `swapon --show=NAME --noheadings`, do you then get to see the same error?

**Comment by stephen-d-hill** [comment]
```
~$ sudo swapon --show=NAME --noheadings
/dev/sda3
```

**Comment by mboelen** [comment]
Does `cryptsetup isLuks /dev/sda3` or `cryptsetup status /dev/sda3` give you the error (not found)?

**Comment by stephen-d-hill** [comment]
```
~$ cryptsetup isLuks /dev/sda3
Device /dev/sda3 doesn't exist or access denied.
~$ sudo cryptsetup isLuks /dev/sda3
~$ 
```

**Comment by stephen-d-hill** [comment]
```
~$ cryptsetup status /dev/sda3
Cannot initialize device-mapper, running as non-root user.
~$ sudo cryptsetup status /dev/sda3
Device sda3 not found
```

**Comment by mboelen** [comment]
Regarding the reason why this happens, I'm not sure. Apparently sda3 exists. But as you already said, the total number changed. So maybe, somewhere, things are out of order. As errors are already being redirected and specific text is being grepped, there is not much we can change to this test at this moment.

Will close this test for now, as you already discovered the option to disable this particular test for that system. Let's monitor it in the future. If others share the same error, then we can do new research.
