### ISSUE TITLE
Amazon Linux 2 is end-of-life (GEN-0010) ?

### ISSUE THREAD

**Issue by jmahler** [CISOfy/lynis#979]
**Describe the bug**

Running a system audit on Amazon Linux 2 incorrectly reports that it is end-of-life.

```
AL2 ~$ sudo lynis --report-file report.out --no-colors audit system | tee lynis.out
[...]
AL2 ~$ grep -B 4 -A 2 end-of-life lynis.out
  -[ Lynis 3.0.0 Results ]-

  Warnings (5):
  ----------------------------
  ! This version 2 is marked end-of-life as of 2020-06-30 [GEN-0010] 
      https://cisofy.com/lynis/controls/GEN-0010/
```

Looking at `software-eol.db` it appears that it is incorrectly picking the date for `Amazon Linux`
and using it for `Amazon Linux 2`.

```
AL2 ~$ cat /usr/share/lynis/db/software-eol.db
[...]
# Amazon Linux
#
os:Amazon Linux:2020-06-30:1593468000:
os:Amazon Linux 2:2023-06-26:1687730400:
[...]
```

**Version**
 - Distribution: Amazon Linux 2

```
AL2 ~$ cat /etc/system-release
Amazon Linux release 2 (Karoo)
```

 - Lynis version: 3.0.0

**Comment by mboelen** [comment]
Thanks for reporting. Commit https://github.com/CISOfy/lynis/commit/1da058d6defcbfa4729b99526fdafcd1ae5295ce was applied recently to resolve this issue. So in 3.0.1 this is resolved.
