### ISSUE TITLE
SSHd on OS X not detected

### ISSUE THREAD

**Issue by tas50** [CISOfy/lynis#98]
I have "remote sharing" enabled on OS X and I can ssh to my host without issues, but the SSH daemon is not detected during the scan.

**Comment by mboelen** [comment]
Thanks, that shouldn't be a hard one to detect. Can you share your ps aux output?
Where is the sshd_config located on your system?

**Comment by kboratynski** [comment]
@mboelen Fixed with #142 .

**Comment by kboratynski** [comment]
@mboelen: You can close this, hence #142 is merged.
