### ISSUE TITLE
Fedora: generic-release - [OS Detection] - Exception found

### ISSUE THREAD

**Issue by thelounge-zz** [CISOfy/lynis#984]
Unknown OS found in /etc/os-release

in fact that's Fedora with a non.default release package
------------------------

[root@asterisk:~]$ rpm -qa | grep release
generic-release-31-2.noarch
generic-release-common-31-2.noarch

[root@asterisk:~]$ cat /etc/os-release
NAME=Generic
VERSION="31 (Generic)"
ID=generic
ID_LIKE=fedora
VERSION_ID=31
PRETTY_NAME="Generic 31 (Generic)"
ANSI_COLOR="0;34"
LOGO=generic-logo-icon
CPE_NAME="cpe:/o:generic:generic:31"
HOME_URL="http://www.zombo.com/"
SUPPORT_URL="https://en.wikipedia.org/wiki/Help!_(album)"
BUG_REPORT_URL="https://youtu.be/CSemARaqGqE"
REDHAT_BUGZILLA_PRODUCT="Generic"
REDHAT_BUGZILLA_PRODUCT_VERSION=%{bug_version}
REDHAT_SUPPORT_PRODUCT="Generic"
REDHAT_SUPPORT_PRODUCT_VERSION=%{bug_version}
PRIVACY_POLICY_URL="http://nsa.gov"  
------------------------

Exception found!

  Function/test:  [OS Detection]
  Message:        Unknown OS found in /etc/os-release

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (/usr/bin/lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

**Comment by thelounge-zz** [comment]
WTF

**Comment by konstruktoid** [comment]
@thelounge-zz can you give an example where you downloaded this distro? The `*_URL` information isn't particularity informational too say the least.

**Comment by mboelen** [comment]
We typically add all distributions, but I'm going to disqualify this one. All information in this distribution release file seems to be misleading, a joke, or incorrect. I doubt that the CPE is valid, the privacy policy is not serious, and other URLs are not helpful nor serious.

I suggest creating a bug report with the official project and have them fix their identifiers, URLs, and other supporting fields (such as CPE).

**Comment by thelounge-zz** [comment]
don't you get that this is *an ordianry fedora* with a non.default *release package* installed by intention and the only thing i ask for is to just detect it as Fedora as "fedora-release" would be installed instead of "generic-release"?

the whole point of generic-release is that it's what it is

Description :
Generic release files such as yum configs and various /etc/ files that
define the release. This package explicitly is a replacement for the
trademarked release package, if you are unable for any reason to abide by the
trademark restrictions on that release package.

**Comment by thelounge-zz** [comment]
ID=generic
ID_LIKE=fedora
VERSION_ID=31

all you need to konw is there

**Comment by konstruktoid** [comment]
Just for verfication @thelounge-zz, but I agree with what @mboelen said.

"Generic release files such as yum configs and various /etc/ files that define the release. This package explicitly is a replacement for the trademarked release package, if you are unable for any reason to abide by the trademark restrictions on that release package."

```
$ cat /etc/os-release 
NAME=Fedora
VERSION="31 (Thirty One)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Thirty One)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
$ sudo dnf install generic-release --allowerasing
$ cat /etc/os-release 
NAME=Generic
VERSION="31 (Generic)"
ID=generic
ID_LIKE=fedora
VERSION_ID=31
PRETTY_NAME="Generic 31 (Generic)"
ANSI_COLOR="0;34"
LOGO=generic-logo-icon
CPE_NAME="cpe:/o:generic:generic:31"
HOME_URL="http://www.zombo.com/"
SUPPORT_URL="https://en.wikipedia.org/wiki/Help!_(album)"
BUG_REPORT_URL="https://youtu.be/CSemARaqGqE"
REDHAT_BUGZILLA_PRODUCT="Generic"
REDHAT_BUGZILLA_PRODUCT_VERSION=%{bug_version}
REDHAT_SUPPORT_PRODUCT="Generic"
REDHAT_SUPPORT_PRODUCT_VERSION=%{bug_version}
PRIVACY_POLICY_URL="http://nsa.gov"
```

**Comment by thelounge-zz** [comment]
> but I agree with what @mboelen said

i don't understand such discussions at all, the bits to detect it as Fedora are there, it's that easy

**Comment by mboelen** [comment]
Discussions are always welcome, so are decisions. At this moment the decision is not to implement the detection of a Linux distro called "Generic". If more people report this issue, then we can reconsider this and implement a new routine that parses "ID_LIKE". Just implementing it for a single edge case does not warrant the time and added code currently. Each bit of code also needs to be maintained in the end.

**Comment by thelounge-zz** [comment]
>  the decision is not to implement the detection of a Linux distro called "Generic"

nobody is asking for that - detect it as what it is - ordinary Fedora

**Comment by mboelen** [comment]
The os-release file identifies it as "generic", so that is what it is. We can't say from the ID field alone that it is Fedora. Maybe this package is also used on CentOS systems or other RHEL clones. Currently, the usage of the `ID_LIKE` field is not implemented. As explained, this has no priority now as it is an edge case. If more people report this issue, then we will reconsider it.
