### ISSUE TITLE
ACCT-9627 CentOS 8/Sysstat/SystemD support

### ISSUE THREAD

**Issue by trelane** [CISOfy/lynis#986]
**Describe the bug**
Lynis fails to detect a properly installed sysstat on CentOS 8 with systemd.

**Version**
 - Distribution [e.g. CentOS 8]
 - Lynis version [e.g. 3.0.0]

**Expected behavior**
Lynis should check sysstat.service and sysstat-collect.timer to see if they are enabled on systemd based systems.  Lynis only checks /etc/default/sysstat (non existent on centos-8), and /etc/cron.d/sysstat (this is now the .timer file referenced above)

**Comment by yakhatape** [comment]
+1 @trelane

**Comment by Varbin** [comment]
@yakhatape @trelane Do you mind checking #1011?

**Comment by trelane** [comment]
I just got this message.  I'll try to check out the test branch this weekend.

**Comment by Varbin** [comment]
@trelane Did you have time to look at PR?
