### ISSUE TITLE
support for ufw/firewalld/nftables 

### ISSUE THREAD

**Issue by trelane** [CISOfy/lynis#987]
**Is your feature request related to a problem? Please describe.**
More modern versions of Linux have firewalls that have configurations which should be audited.  Additionally we are new moving from iptables to nftables.
The output from at least FIRE-4512 isn't super useful on a more modern (last 5 years or so) Linux distro.

**Describe the solution you'd like**
I would like to see a more comprehensive set of firewall checks as the Linux firewall world seems to be moving on from manually created firewall rules via iptables to firewall "Suites" which should be enabled on their distro eg:
Ubuntu should always have ufw enabled
Centos/FC/RHEL should always have firewalld enabled
(or these should at least be suggested)

A systemd and cli check can confirm they are enabled and at least doing something.

**Comment by Varbin** [comment]
@trelane I have a question:
- Should the platform specific firewall solution even be recommended if a different frontend, "regular" iptables or even nftables is already set up (e.g. firewalld on Ubuntu)? Administrators might prefer one over another.

In any case, the firewall modules and frontends should at least be detected properly and ideally there should be the same tests for all of them (e.g. empty rulesets).

**Comment by trelane** [comment]
I think at this point, unless there is an argument otherwise, we should push people towards the OS Supported/supplied firewall.  Rolling your own firewall is kind of like rolling your own crypto at this point.  It's likely to be a bad idea.

**Comment by Varbin** [comment]
Reasons to use a different firewall may be:
 - The administrator is more proficient with *x* than platform preferred *y*. He chooses *x* as he is less likely to make mistakes in it. 
 - A large number of machines already uses firewall *x*. Thus it is used on all machines when possible, even if a platform preferred alternative is available. Especially when different distributions are used, this is a common decision.

The cryptography seems a bit far fetched for me: All of them are proven firewall solutions, and the difference between the individual Linux distributions is small enough for all solutions to work on all distributions equally well (and all are present the respective package managers). Using one over another does not affect the security much.

- - 

I think we can agree in that lynis needs at least some kind of improvement for the firewall rules.

By the way, nftables is already detected at least partially (FIRE-4536, FIRE-4538, FIRE-4540).

**Comment by trelane** [comment]
In the case of 
point 1 (more experience): that administrator is also capable of disabling the test
point 2:  I would suggest that disabling the test, and perhaps having some text explaining that this test should be disabled if you use something other than the stock firewall is the solution here.

I do think I was unclear on my final point.  I wasn't comparing firewall tools, I was comparing rolling your own firewall from scratch to using firewall tools, and suggesting that the second is much more secure. I think checking the firewall builder tool (firewalld, ufw, etc) is more useful than checking iptables/nftables itself.  Lynis should, in the end, recommend either using a tool, or disabling that specific check if you know what you're doing, and are building your own firewall from scratch.
