### ISSUE TITLE
Ultimate Edition Linux

### ISSUE THREAD

**Issue by TheeMahn** [CISOfy/lynis#989]
Exception found!

  Function/test:  [OS Detection]
  Message:        Unknown OS found in /etc/os-release - Please create issue on GitHub project page: https://github.com/CISOfy/lynis

root@JackHammer:/home/theemahn/Downloads/lynis# cat /etc/os-release
NAME="Ultimate_Edition_Server"
VERSION=6.6
ID="ultimate edition"
ID_LIKE=ubuntu
PRETTY_NAME="Ultimate Edition Server (6.6) LTS"
VERSION_ID="6.6"
VERSION_CODENAME="focal"
VARIANT="Server"
HOME_URL="http://ultimateedition.info/"
DOCUMENTATION_URL="https://forumubuntusoftware.info/viewforum.php?f=10"
BUG_REPORT_URL="https://launchpad.net/ubuntu.ultimate/+filebug"
root@JackHammer:/home/theemahn/Downloads/lynis#

You asked me to submit a bug...

Before you blow me off (millions of downloads & these are not small files):
https://sourceforge.net/projects/ultimateedition/files/

With 879,553 files installed I got:
Hardening index : 65 [#############       ]
  Tests performed : 284
  Plugins enabled : 2

Bash is my favorite language.  I wrote an OS-Builder solidly in BASH: http://os-builder.com/ Builds 11,115 of them when desktop environments are also calculated.

**Comment by quantumpacket** [comment]
Hi, are you the developer? I've never heard of this distro before and checked out your site. The only reason I'm even replying is that this post is borderline spammy, and this section on your FAQ really concerns me.

> Safety
> 
> ...
> But with Ultimate Edition, anti-virus software is a thing of the past! **Since there are virtually no security threats in the wild for the Linux kernel, your PC is safe and sound with just the pre-installed firewall. No extra security software is needed.**

That doesn't sound like a system that a security oriented user would want to use. Where is the defense in depth? A firewall is just one layer, telling your users no extra security software is needed is harmful.

**Comment by mboelen** [comment]
@TheeMahn Can you create a pull request? As you are familiar with bash, extend the include/osdetection routine.

**Comment by TheeMahn** [comment]
The FAQ was written by one of my admin back in 2006 - 2008 I believe a fairly accurate statement at the time.  I try and do as little Webmastering as possible it eats into my programming time, I also work a regular job.  If I have the time I will pull request.  I have already worked17 Hours today.  12 Hours at my regular Job, yes a Sunday & Saturday as well Friday.  I work a 2-2-3, come home and write software.  I do not sleep much.
