### ISSUE TITLE
PHP not detected on OS X

### ISSUE THREAD

**Issue by tas50** [CISOfy/lynis#99]
MBP_tsmith:~ php --version
PHP 5.5.29 (cli) (built: Sep  9 2015 00:26:40)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
MBP_tsmith:~ which php
/usr/bin/php

**Comment by kboratynski** [comment]
@mboelen: fixed with #140.

**Comment by kboratynski** [comment]
@mboelen You can close this, hence #140 is done.
