### ISSUE TITLE
Denial of service by user creating symlink to /

### ISSUE THREAD

**Issue by duck-rh** [CISOfy/lynis#991]
**Describe the bug**
A user can cause a filesystem full by creating a simple symlink from his home to / due to very verbose `find` errors.

**Version**
 - Distribution Debian
 - Lynis version 3.0.0, maybe before

**Expected behavior**
Do not log errors from find. I wondered if asking find to not follow symlink would make sense, but I'm not sure yet what it' trying to find so it might not be appropriate. Surely skipping /proc would avoid doing the whole loop.

**Output**
See Debian BR below.

**Additional context**
It was reported on the Debian BTS: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=965359

**Comment by mboelen** [comment]
It is not Lynis that is logging that, but simply the `find` command that outputs them. If I see the bug report, it looks like syslog/journal was filled, not the lynis.log file. Or at least, I don't see evidence of a huge lynis.log file.

We can look into the option to redirect errors from find to stderr. Do you know what specific test caused this or have the reporter share that? (using --debug --verbose, press CTRL+C when the errors start showing up)

**Comment by baryluk** [comment]
Yes, it looks the message spam is coming from the `find`.

No special options, `/usr/sbin/lynis audit system --cronjob` as started by systemd timer job.

I am not sure which parts do trigger the issue, but on my system doing `find -L` in /lib, will easily trigger cycles and the spam:

```
root@debian:~# find -L /lib > /dev/null
find: File system loop detected; ‘/lib/live/mount/rootfs/filesystem.squashfs/bin/X11’ is part of the same file system loop as ‘/lib/live/mount/rootfs/filesystem.squashfs/bin’.
find: ‘/lib/live/mount/rootfs/filesystem.squashfs/dev/fd/4’: No such file or directory
find: File system loop detected; ‘/lib/live/mount/rootfs/filesystem.squashfs/lib/llvm-9/build/Debug+Asserts’ is part of the same file system loop as ‘/lib/live/mount/rootfs/filesystem.squashfs/lib/llvm-9’.
find: File system loop detected; ‘/lib/live/mount/rootfs/filesystem.squashfs/lib/llvm-9/build/Release’ is part of the same file system loop as ‘/lib/live/mount/rootfs/filesystem.squashfs/lib/llvm-9’.
find: File system loop detected; ‘/lib/live/mount/rootfs/filesystem.squashfs/usr/bin/X11’ is part of the same file system loop as ‘/lib/live/mount/rootfs/filesystem.squashfs/usr/bin’.
find: File system loop detected; ‘/lib/live/mount/rootfs/filesystem.squashfs/usr/lib/llvm-9/build/Debug+Asserts’ is part of the same file system loop as ‘/lib/live/mount/rootfs/filesystem.squashfs/usr/lib/llvm-9’.
find: File system loop detected; ‘/lib/live/mount/rootfs/filesystem.squashfs/usr/lib/llvm-9/build/Release’ is part of the same file system loop as ‘/lib/live/mount/rootfs/filesystem.squashfs/usr/lib/llvm-9’.
^C

```

I guess, filtering out `find: File system loop detected;` (yeah, semicolon) from stderr output would be the best solution probably.

It can probably by done by creating a shell function, that wraps the `find`, i.e.

```shell
function lynis_find () {
  return "${FINDBINARY}" "$*" 2>&1 | grep -v '^find: File system loop detected'
}
```

There are tricks to redirect just the stderr, instead of stdout and stderr, easier in bash, but also possibly in POSIX shell. You can check for hints here: https://stackoverflow.com/questions/3618078/pipe-only-stderr-through-a-filter

**Comment by duck-rh** [comment]
Thanks @baryluk for replying directly (he is the original reporter), that should ease things a lot.

**Comment by baryluk** [comment]
FYI. I identified the `find` that is problematic, or is the first to trigger the issue:

```
# ps aux  | egrep 'find|lynis'
root      152159  0.0  0.0   3812  3124 ?        SNs  00:19   0:04 /bin/sh /usr/sbin/lynis audit system --cronjob
root      182179 99.9  0.0   6716  4016 ?        RN   00:19 1000:41 find -L /lib -name pam_tmpdir.so
```

this is a part of `/etc/lynis/plugins/plugin_debian_phase1` plugin, which at line 99 does perform this find:
```shell
FIND=`find -L /lib -name pam_tmpdir.so`
```

BTW. I don't have this installed:

```
# ls -lh /lib/x86_64-linux-gnu/security/pam_tmpdir.so
ls: cannot access '/lib/x86_64-linux-gnu/security/pam_tmpdir.so': No such file or directory
#
```

but of course there is a number of other PAM modules there:

```
# ls -lh /lib/x86_64-linux-gnu/security/  | wc -l
48
```


I tried using `ldconfig` to search for the pam modules, but it looks like the main PAM library do set own library paths dynamically, so the pam module shared object files are not a part of normal linker paths / caches.

**Comment by duck-rh** [comment]
Thanks @baryluk . So this means this is not an upstream bug and I should be able to fix this on my own. I need to look how Lynis does this kind of search. These extra Debian checks probably need some refresh but I did not have time to look deeper into it yet.

**Comment by mboelen** [comment]
Thanks @baryluk - That is very helpful. As @duck-rh already said, it is in a customization on the Debian package. We would suggest to remove all customizations (in steps) and move the useful tests upstream.

Will close this issue here, as no specific code change can be applied to upstream code.

**Comment by baryluk** [comment]
Yes, and no. lynis still uses plenty of `find` in its own source and standard plugins, but I could't really find any use of `find -L` which is problematic (and could produce the cycle detection warning).

But yes, easiest to fix it in Debian specific part, and move some of these tests upstream. The tmpdir for example would fit into upstream, as do some other tests
