### ISSUE TITLE
Malware scanner - MDATP

### ISSUE THREAD

**Issue by Vilican** [CISOfy/lynis#992]
**Describe the bug**
Lynis does not recognize Microsoft Defender ATP as malware scanner and therefore the test fails.

MDATP docs: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually
Binary is installed to /usr/bin/mdatp

**Version**
 - Ubuntu 20.04
 - Lynis 3.0.0

**Output**
    - Installed malware scanner                               [ NOT FOUND ]

**Comment by mboelen** [comment]
Thanks for reporting. Is there also an active running process?

**Comment by mboelen** [comment]
Closing issue, as initial detection was added by @konstruktoid
