### ISSUE TITLE
PHP 7.4 is not recognized

### ISSUE THREAD

**Issue by TheFlipside** [CISOfy/lynis#996]
**Describe the bug**
On a system with PHP 7.4 installed the check result is

**[+] PHP**
**------------------------------------**
  **- Checking PHP                                              [ NOT FOUND ]**

**Version**
 - Distribution: Ubuntu 20.04
 - Lynis version: 3.0.1

**Expected behavior**
The PHP installation should be found and be able to be analyzed by lynis.

**Output**
**[+] PHP**
**------------------------------------**
  **- Checking PHP                                              [ NOT FOUND ]**

**Additional context**
Output of **php --version**
_PHP 7.4.3 (cli) (built: May 26 2020 12:24:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies_

**Comment by quantumpacket** [comment]
@mboelen Since the filepaths are relatively consistent with just one character in most cases changing between versions, could we possibly use a wildcard match to reduce the ever growing list of paths down and help prevent new versions from not being detected?

**Comment by rm-td** [comment]
Hello,
Can I add some substance to this and state that PHP 7.4 is correctly detected on a CentOS 7.8 install. I have not checked a CentOS 8 install also don't know what version is stock.

For info, the PHP install on CentOS v7.8 is from the REMI repo providing later PHP installs where the native distro does not provide.

`# rpm -qa | grep php
php-xml-7.4.8-2.el7.remi.x86_64
php-snmp-7.4.8-2.el7.remi.x86_64
php-pspell-7.4.8-2.el7.remi.x86_64
php-xmlrpc-7.4.8-2.el7.remi.x86_64
php-gd-7.4.8-2.el7.remi.x86_64
php-pdo-7.4.8-2.el7.remi.x86_64
php-odbc-7.4.8-2.el7.remi.x86_64
php-bcmath-7.4.8-2.el7.remi.x86_64
php-common-7.4.8-2.el7.remi.x86_64
php-sodium-7.4.8-2.el7.remi.x86_64
php-pdo-dblib-7.4.8-2.el7.remi.x86_64
php-soap-7.4.8-2.el7.remi.x86_64
php-opcache-7.4.8-2.el7.remi.x86_64
php-intl-7.4.8-2.el7.remi.x86_64
php-pecl-mcrypt-1.0.3-1.el7.remi.7.4.x86_64
php-json-7.4.8-2.el7.remi.x86_64
php-devel-7.4.8-2.el7.remi.x86_64
php-mbstring-7.4.8-2.el7.remi.x86_64
php-pear-1.10.12-1.el7.remi.noarch
php-cli-7.4.8-2.el7.remi.x86_64
php-mysqlnd-7.4.8-2.el7.remi.x86_64
php-fpm-7.4.8-2.el7.remi.x86_64
php-fedora-autoloader-1.0.1-2.el7.noarch
php-7.4.8-2.el7.remi.x86_64
php-process-7.4.8-2.el7.remi.x86_64
php-ldap-7.4.8-2.el7.remi.x86_64
oniguruma5php-6.9.5+rev1-2.el7.remi.x86_64`

visual results from lynis audit system

`[+] PHP
------------------------------------
  - Checking PHP                                              [ FOUND ]
    - Checking PHP disabled functions                         [ FOUND ]
    - Checking expose_php option                              [ OFF ]
    - Checking enable_dl option                               [ OFF ]
    - Checking allow_url_include option                       [ OFF ]
    - Checking listen option                                  [ OK ]
`

output of php --version

`# php --version
PHP 7.4.8 (cli) (built: Jul  9 2020 08:57:23) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.8, Copyright (c), by Zend Technologies
`

**Comment by TheFlipside** [comment]
> Hello,
> Can I add some substance to this and state that PHP 7.4 is correctly detected on a CentOS 7.8 install. I have not checked a CentOS 8 install also don't know what version is stock.
> 

This is probably because on CentOS like systems the php installation always uses the path /etc/php.ini which makes it easy for tools like lynis to detect.
On debian based systems the path is always a construct including the version which needs to be searched for explicitly unless, as proposed, a wildcard could be used.
