### ISSUE TITLE
Add a flag to define custom root path

### ISSUE THREAD

**Issue by kaosmaja** [CISOfy/lynis#998]
**Is your feature request related to a problem? Please describe.**
I want to be able to run Lynis in a container to monitor a host (microservice-like architecture), but there is no way to tell Lynis to change the root path.

**Describe the solution you'd like**
Add a flag to define root path to the host file system.

**Required changes**
Lynis already has a root path variable defined in include/consts, but not all tests make use of this variable. This would require checking that all tests that need this use $ROOTDIR. 

**Additional context**
I'm not as naïve enough to think running it from a container on the host would not break something else, but that's why this is a feature request so more capable people can offer their view.

**Comment by mboelen** [comment]
A flag will be added later when all tests are migrated and tests to use ROOTDIR. At this moment adding it will only give bad results. Some tests need also to be changed to only perform the test if the execution is done and directed to the host itself (e.g. process checking).

**Comment by mboelen** [comment]
For now I will close this issue. Thoughts and ideas remain welcome.
